"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-admin-audit-logs",
  title: "Design an Admin Audit Logs & Activity Tracking UI",
  description:
    "Architecture for an admin audit log and activity tracking system: immutable append-only event log, structured event schema with actor/action/resource/diff, real-time activity feed via SSE, search and filter across millions of events, compliance export (SOC 2, GDPR), tamper-evident log integrity via hash chaining, alerting on suspicious activity patterns, retention policies with archival, per-resource activity history, and admin impersonation tracking.",
  category: "high-level-design",
  subcategory: "enterprise-saas-systems",
  slug: "admin-audit-logs",
  wordCount: 5000,
  readingTime: 31,
  lastUpdated: "2026-05-11",
  tags: ["hld", "audit-logs", "compliance", "soc2", "gdpr", "activity-tracking", "immutable", "security"],
  relatedTopics: ["rbac-dashboard", "reporting-analytics-dashboard"],
};

export default function AdminAuditLogsArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <p>An audit log is a chronological record of every significant action performed within a system: who did what, to which resource, when, and from where. Unlike application logs (which are primarily for debugging and may be noisy or ephemeral), audit logs serve compliance, security, and accountability requirements — they must be accurate, complete, tamper-evident, and retained for defined periods (often 1–7 years for regulated industries). An enterprise SaaS product without audit logs cannot pass SOC 2 Type II certification or GDPR compliance audits, making the audit log system a business-critical feature for selling to enterprise customers.</p>
        <p>The activity tracking UI surfaces these audit logs to administrators in a searchable, filterable interface. The challenges are: volume (a large enterprise tenant may generate millions of audit events per month, making naive SQL queries prohibitively slow), completeness (every security-relevant action must be logged — a missed event is a compliance gap), and tamper-evidence (the audit log must prove that no events were deleted or modified after the fact, which is especially important for forensic investigations after a security incident). Additionally, the system must distinguish between user-initiated actions and system-initiated actions, and between direct actions and actions taken through admin impersonation (an admin acting as another user).</p>
        <p><strong>Explicit scope:</strong> Immutable audit event pipeline, structured event schema, admin activity feed UI, search and filter, compliance export, tamper-evident hash chaining, and retention policy enforcement. Not in scope: SIEM (Security Information and Event Management) integration, real-time intrusion detection, or machine learning anomaly detection on the audit stream.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <li><strong>Event capture:</strong> All security-relevant actions are logged: user login/logout, password changes, role changes, record create/update/delete, data export, billing changes, API key generation/revocation, admin impersonation start/end, and permission changes. Each event includes: event ID, timestamp, actor (user ID, name, email), action type, target resource (type + ID + name), IP address, user agent, session ID, and a before/after diff for mutation events.</li>
          <li><strong>Immutability:</strong> Audit log entries can never be modified or deleted through the application layer. The write path is append-only; the read path is read-only. Retention policy enforcement (deleting events older than the retention window) is the only deletion, and it is an automated system action that is itself logged.</li>
          <li><strong>Tamper evidence:</strong> Each audit log entry includes a hash of its own content plus the hash of the previous entry (forming a hash chain). Any modification or deletion of a log entry breaks the chain, enabling tamper detection during compliance audits. The chain integrity can be verified on demand by the compliance export endpoint.</li>
          <li><strong>Activity feed UI:</strong> Admin view showing recent events across the organization: event type icon, actor avatar, description ("Alice updated Deal #4521: closed date changed from 2026-06-01 to 2026-05-15"), timestamp, and resource link. Filterable by actor, action type, date range, and resource type. Searchable by actor name, resource name, or IP address.</li>
          <li><strong>Compliance export:</strong> Export audit log entries for a given date range as a signed JSON Lines file (.jsonl) with a cryptographic signature for integrity verification. Support for SOC 2 evidence packages (formatted for auditor review) and GDPR subject access requests (all events involving a specific user).</li>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <li><strong>Write latency:</strong> Audit log writes must not add latency to the application action being logged. Events are written asynchronously via a fire-and-forget message to a Kafka topic after the action completes.</li>
          <li><strong>Query performance:</strong> The activity feed loads within 2 seconds for queries over the last 90 days. Historical queries (over 1 year of data) are served from an archived store (S3 + Athena) with higher latency (up to 30 seconds).</li>
          <li><strong>Retention:</strong> Events are retained for a configurable period per tenant (default: 1 year, enterprise: up to 7 years). Events beyond the retention window are soft-archived to S3 Glacier and purged from the hot store.</li>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <p>The audit log system uses an event-driven write path that is completely decoupled from the application's main request path. Application services publish audit events to a Kafka topic (audit-events) after completing each action. The Audit Log Consumer reads from this topic, computes the hash chain entry (previous entry's hash + current event content), and writes to two stores: a hot PostgreSQL table (audit_events, partitioned by month, with Elasticsearch sync for search) for queries over the recent retention window, and an S3 data lake (Parquet files, partitioned by tenant and month) for long-term archival and Athena queries. The Admin Activity UI reads from Elasticsearch for the search/filter interface (fast, flexible queries) and from S3/Athena for historical compliance exports.</p>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/enterprise-saas-systems/admin-audit-logs.svg"
          alt="Admin audit logs architecture showing event capture (application services: after action complete publish to Kafka audit-events topic; fire-and-forget no latency on main request; event schema: {eventId tenantId timestamp actor:{id name email} action:{type category} resource:{type id name} metadata:{ipAddress userAgent sessionId} diff:{before after} prevHash hash}; categories: auth data-access admin-action billing api-key), hash chain consumer (Kafka consumer: read event; SELECT hash FROM audit_events WHERE tenantId=X ORDER BY id DESC LIMIT 1 → prevHash; compute SHA256(prevHash + JSON.stringify(event)); set event.prevHash=prevHash event.hash=computed; INSERT audit_events; forward to Elasticsearch index; async S3 Parquet write), hot store PostgreSQL (audit_events table: id eventId tenantId timestamp actorId actionType resourceType resourceId ipAddress prevHash hash; range partition by month; index on tenantId+timestamp; index on tenantId+actorId; index on tenantId+resourceId; 90-day hot retention), search layer Elasticsearch (index audit-events-{tenantId}; mappings: timestamp keyword actionType actorName resourceName ipAddress; search query: {bool must:[{range:timestamp},{term:actionType}] should:[{match:actorName:'alice'}]}; 90-day index lifecycle: rollover at 50GB; older → read-only), activity feed UI (GET /api/audit-events?tenantId&filters&cursor; Elasticsearch query; result: events list with pagination cursor; each event: icon actor description timestamp resource link; SSE /api/audit-events/stream for real-time events: new events pushed to top of feed; filter panel: actor date-range action-type resource-type; search input: freetext → Elasticsearch match), per-resource history (GET /api/audit-events?resourceType=deal&resourceId=4521; Elasticsearch term query; shows chronological history of all changes to Deal 4521: created by updated by field changes; diff display: before/after values highlighted), compliance export (POST /api/audit-export {tenantId dateRange format}; async job; query: Elasticsearch for recent range OR Athena S3 query for historical; stream events → jsonl file; HMAC-SHA256 signature with audit-signing-key; S3 upload; presigned download URL; SOC2 package: formatted PDF with event counts by category; GDPR SAR: filter by actorId=userId), tamper verification (GET /api/audit-events/verify {tenantId start end}; load events in sequence; recompute each hash: SHA256(prevHash+content); compare to stored hash; report: {verified:true chainLength:24801} or {broken:true atEventId:'evt_xyz' expectedHash:... actualHash:...}), retention archival (nightly job: SELECT events WHERE timestamp < now-retentionDays; write to S3 Parquet tenant={id}/year={y}/month={m}/part-{n}.parquet; DELETE from PostgreSQL after S3 confirm; update Elasticsearch ILM policy; very old: S3 Glacier tier after 2 years)."
          caption="Fire-and-forget Kafka publish (no request latency), SHA256 hash chain consumer (prevHash → INSERT → Elasticsearch → S3 Parquet), monthly-partitioned PostgreSQL hot store (90-day), Elasticsearch activity feed (cursor pagination, real-time SSE push), per-resource diff history, async HMAC-signed JSONL compliance export (Athena for historical), chain integrity verifier, and nightly S3 archival with ILM Glacier tiering"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Event Schema and Capture</h3>
        <p>Every audit event follows a consistent schema: eventId (UUID), tenantId, timestamp (UTC ISO 8601, nanosecond precision), actor (userId, name, email, impersonatedBy if the action was taken through admin impersonation), action (type e.g. "deal.updated", category e.g. "data-mutation"), resource (type, id, name), metadata (ipAddress, userAgent, sessionId, requestId for correlation with application logs), diff (before and after values for mutation events), prevHash, and hash. The diff is computed by the application service before publishing the event: for a deal update, the diff would be {`{ before: { closedDate: "2026-06-01" }, after: { closedDate: "2026-05-15" } }`}. Only changed fields are included in the diff, not the entire record — this keeps event payloads manageable even for records with 50+ fields.</p>
        <p>Event categories define the security relevance: auth events (login, logout, password change, MFA enable/disable), data-access events (record read for sensitive entities like billing data), data-mutation events (record create/update/delete), admin-action events (role assignments, permission changes, user suspension), api events (API key create/revoke/use), and billing events (subscription change, payment method update). Each category has a defined set of action types that are exhaustively enumerated in a registry, preventing ad-hoc event type strings that make analysis difficult. New event types are added via a code review process to ensure completeness before the feature ships.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Tamper-Evident Hash Chain</h3>
        <p>The hash chain makes modifications detectable: each event's hash is computed from the SHA256 of (prevHash + eventId + tenantId + timestamp + actorId + actionType + resourceId + diff serialized). The prevHash is the hash of the immediately preceding event for the same tenant. The first event for a tenant uses a genesis hash (a fixed public constant: "GENESIS"). If any event is modified after insertion, its hash would no longer match the stored hash, and the chain of hashes from that event forward would all be invalid. If an event is deleted from the middle of the sequence, the next event's prevHash would no longer match its predecessor's hash.</p>
        <p>The hash computation happens in the Audit Consumer before the INSERT: it reads the most recent event's hash for the tenant (SELECT hash FROM audit_events WHERE tenantId=X ORDER BY id DESC LIMIT 1 FOR UPDATE), computes the new hash, and inserts both the event and the hash atomically. The FOR UPDATE lock prevents concurrent events from computing hashes against the same prevHash (which would create two events with the same prevHash, breaking the chain). The chain integrity verifier endpoint (GET /api/audit-events/verify) loads all events in sequence for a tenant and date range, recomputes each hash, and compares to the stored value. The verifier reports the first broken link (if any) with the eventId and the computed vs. stored hash mismatch. This verification can be run by the tenant's own security team or by external auditors as part of a compliance assessment.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Activity Feed UI with Search</h3>
        <p>The admin activity feed is an infinite scroll list of recent audit events, newest first. Each event renders as a timeline entry: the event type icon (color-coded by category: red for auth, orange for admin actions, blue for data mutations), the actor's avatar and name, a human-readable description ("Alice updated Deal 'Acme Corp Q3 Renewal': closed date changed from June 1 to May 15"), the timestamp (relative: "3 minutes ago"), and a link to the affected resource. For impersonated actions, the description includes "as Bob" (the impersonated user): "Admin Alice (acting as Bob) deleted Contact 'John Smith'."</p>
        <p>The filter panel allows narrowing by actor (user search dropdown), action type (multi-select from the category/action type registry), date range (presets: last hour, last 24 hours, last 7 days, last 30 days, or custom range), and resource type (dropdown: Deal, Contact, User, API Key, etc.). Text search (a single input field) runs a multi-field Elasticsearch match query across actorName, resourceName, and IP address. The search is debounced (300ms). Cursor-based pagination loads the next page on scroll (infinite scroll) using the last event's timestamp as the cursor. The feed also shows real-time events via SSE: new events for the current filter context are pushed to the top of the feed using an SSE stream (POST /api/audit-events/stream with the current filter parameters), highlighted with a brief animation to distinguish them from historical entries.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Per-Resource Activity History</h3>
        <p>Every resource in the system (deals, contacts, invoices, users) has a dedicated audit history tab showing all events that involved that resource as the target. This is fetched via GET /api/audit-events?resourceType=deal&amp;resourceId=&#123;id&#125;&amp;tenantId=&#123;tenantId&#125;, which queries Elasticsearch for events matching the resource. The per-resource history is displayed in chronological order (oldest first), formatted as a change timeline: "Created by Alice on March 1, 2026," "Stage changed from Prospect to Qualified by Bob on March 15," "Closed date updated by Alice on April 2," "Deleted by Admin Carol on May 10." Each entry expands to show the full before/after diff. This history answers the operational question "who changed this record and when?" without requiring the admin to know the actor in advance.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Compliance Export and Retention</h3>
        <p>Compliance exports are generated asynchronously. The admin requests an export for a date range and format via POST /api/audit-export. A background job queries Elasticsearch for events in the range (for dates within the hot store window) or runs an Athena SQL query over S3 Parquet files (for archived data). Events are streamed to a JSON Lines (.jsonl) file, which is then signed using HMAC-SHA256 with the audit signing key (stored in AWS KMS, rotated annually). The signature and the audit signing key's public certificate are included in the export package, allowing an external auditor to verify the file was not tampered with after export. The export file and signature are uploaded to S3, and a presigned download URL is sent to the requesting admin via email and in-app notification.</p>
        <p>Retention enforcement: a nightly job queries for events older than the tenant&apos;s retention window (tenants.retention_days, default 365). These events are written to S3 Parquet (as an archival copy, if not already there) and then deleted from PostgreSQL and removed from the Elasticsearch index. The retention deletion itself generates an audit event ("Retention archival: N events for tenant X deleted from hot store, archived to S3 s3://audit-archive/&#123;tenantId&#125;/..."), ensuring there is a record of the deletion. Events in S3 are transitioned to Glacier after 2 years (for enterprise customers with 7-year retention requirements, Glacier retrieval within 12 hours is acceptable for compliance evidence requests).</p>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <p>Synchronous versus asynchronous audit log writes: synchronous audit writes (writing to the audit log within the same database transaction as the action being logged) guarantee that every action has a corresponding audit event — if the transaction commits, the audit event is committed. However, this increases the latency of every action by the audit write cost and creates a coupling between the application database and the audit log store. Asynchronous writes (publishing to Kafka after the action commits) introduce a small window where the action is committed but the audit event has not yet been written — if the application process crashes between the DB commit and the Kafka publish, the event is lost. The asynchronous approach is preferred for performance, with the risk of occasional missed events mitigated by comprehensive application-layer event emission (every code path that performs a security-relevant action explicitly publishes an event) and monitoring for audit consumer lag.</p>
        <p>Hash chain correctness under high concurrency: the hash chain requires sequential processing of events per tenant (each event depends on the previous event's hash). Under high-volume tenants (many concurrent actions), the FOR UPDATE lock on the previous hash creates a write serialization bottleneck. Two approaches: (1) maintain separate hash chains per action category per tenant (auth chain, data-mutation chain, etc.), reducing contention while maintaining per-category integrity; (2) compute hashes in an offline batch process (the consumer inserts events without hashes initially, and a separate hash chain process processes events in order and computes hashes). Approach (2) introduces latency before events are "sealed" in the chain, but decouples write throughput from hash computation throughput.</p>
      </section>

      <section>
        <h2>Summary</h2>
        <p>An admin audit log and activity tracking system uses a fire-and-forget event pipeline (application → Kafka → Audit Consumer) to decouple audit writes from application request latency. The Audit Consumer computes SHA256 hash chains (each event hashes itself plus its predecessor, creating tamper-evident linkage) and writes to a monthly-partitioned PostgreSQL hot store (90-day retention), syncs to Elasticsearch for fast search/filter queries, and archives to S3 Parquet for long-term compliance storage. The admin activity feed uses Elasticsearch for real-time filtered search with SSE push for live events. Per-resource history (GET /api/audit-events?resourceType=&resourceId=) answers "who changed this record?" on any resource page. Compliance exports are HMAC-signed JSONL files with KMS-backed signing keys; Athena queries S3 Parquet for historical ranges. Retention enforcement archives to S3 then deletes from hot store, with the deletion itself logged. The chain integrity verifier allows on-demand tamper detection by external auditors. The core design principle: audit logs exist to answer questions after something goes wrong — completeness (every security-relevant action is logged) and tamper evidence (hash chain) are more important than performance, because a missing or modified log entry is worse than a slow one.</p>
      </section>
    </ArticleLayout>
  );
}
