"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-workflow-automation-system",
  title: "Design a Workflow Automation System (Zapier-like)",
  description:
    "Architecture for a workflow automation system: visual workflow builder with trigger and action nodes, condition branching and loops, connector integrations (webhooks, OAuth, REST APIs), execution engine with retry and backoff, real-time execution logs, workflow versioning and rollback, rate limiting per connector, error handling with dead letter queues, and multi-step data transformation with a mapping UI.",
  category: "high-level-design",
  subcategory: "enterprise-saas-systems",
  slug: "workflow-automation-system",
  wordCount: 5000,
  readingTime: 31,
  lastUpdated: "2026-05-11",
  tags: ["hld", "workflow", "automation", "zapier", "triggers", "execution-engine", "connectors", "retry"],
  relatedTopics: ["crm-dashboard", "form-builder-system"],
};

export default function WorkflowAutomationSystemArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <p>A workflow automation system allows non-technical users to connect different SaaS products and automate repetitive tasks without writing code. The defining abstraction is a workflow: a sequence of steps beginning with a trigger (an event that initiates the workflow — "new row added to Google Sheet", "form submitted", "webhook received") followed by one or more actions (operations performed in response — "send Slack message", "create Salesforce contact", "send HTTP request"). The product is simultaneously a UI builder (the visual canvas for constructing workflows), an integration platform (hundreds of connectors to third-party APIs), and an execution engine (the reliable, scalable infrastructure that executes workflows when triggers fire).</p>
        <p>The reliability challenge is central: when a workflow fires, it must execute exactly once. If the Slack API is temporarily down during action execution, the system must retry the action with exponential backoff — without re-running actions that already succeeded. This requires durable execution state, where the system knows exactly which steps have completed so it can resume from the failure point rather than restarting from scratch. The scale challenge is also significant: a popular workflow ("notify Slack when any row is added to any Google Sheet") may fire thousands of times per minute across thousands of users.</p>
        <p><strong>Explicit scope:</strong> Visual workflow builder, trigger and action nodes, execution engine with retry, real-time execution logs, connector OAuth management, and data transformation mapping. Not in scope: custom code execution (lambda functions within workflows), or connector SDK for third-party developers.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <li><strong>Workflow builder:</strong> Visual canvas where users add trigger and action nodes. Drag nodes from a panel, connect them with edges to define execution order. Condition branches (if/else) and loops (for-each) supported as special nodes. Workflows have a name, description, enabled/disabled toggle, and are saved as JSON.</li>
          <li><strong>Connectors:</strong> Library of 200+ connectors (Slack, Salesforce, Google Sheets, HubSpot, HTTP). Each connector has a set of triggers and actions. Triggers require a connection (OAuth token or API key) and a configuration (which sheet, which channel). Actions require a connection and input data (message text, contact fields) which can reference outputs from previous steps using a {`{{step.output.field}}`} template syntax.</li>
          <li><strong>Execution engine:</strong> When a trigger fires, the workflow executes all subsequent action nodes in sequence. Each step has a timeout (30s default), retry policy (3 retries with exponential backoff), and output that downstream steps can reference. Parallel branches execute concurrently. Failed steps after all retries send the execution to an error state.</li>
          <li><strong>Execution history:</strong> Every workflow execution is logged: trigger time, each step's status (success/failure/skipped), duration, input data, output data, and error messages. Execution logs are searchable and paginated. Re-run failed executions from the point of failure.</li>
          <li><strong>Data transformation:</strong> Field mapping UI between step outputs and action inputs. Support for simple transformations: string formatting, date conversion, number arithmetic, array filtering. Mapping expressions use a Jinja-like template syntax.</li>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <li><strong>Trigger latency:</strong> Webhook triggers execute the workflow within 2 seconds of the webhook being received. Polling triggers (checking for new rows every 5 minutes) are eventually consistent with the 5-minute polling interval.</li>
          <li><strong>Execution reliability:</strong> Each workflow step executes at-least-once (retry on failure) with idempotency keys to ensure external API calls are not duplicated on retry. Aim for exactly-once semantics at the action level.</li>
          <li><strong>Concurrency:</strong> Support 10,000 concurrent workflow executions across all tenants. Per-tenant throttling to prevent a single tenant from consuming all execution capacity.</li>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <p>The system has three layers. The Builder Layer is a React canvas application (using React Flow or a custom DAG renderer) where users design workflow graphs. The workflow is serialized as a JSON document (nodes array, edges array, each node has a type, connector, and configuration) and saved to the Workflow Service. The Trigger Layer monitors configured trigger sources: a Webhook Service receives inbound HTTP webhooks, a Polling Scheduler runs cron jobs at the trigger's configured interval to check for new data, and an Event Bus receives internal system events. When a trigger fires, the Trigger Layer publishes an ExecutionRequest to a Kafka queue. The Execution Layer consumes ExecutionRequests from Kafka, loads the workflow definition, and executes steps sequentially using a Step Runner that calls the appropriate connector. Execution state is durably stored in PostgreSQL (one row per step execution, with status, input, output, attempt count). Redis tracks in-flight executions for per-tenant concurrency limits.</p>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/enterprise-saas-systems/workflow-automation-system.svg"
          alt="Workflow automation system architecture showing workflow builder UI (React Flow canvas: trigger node + action nodes + condition nodes + loop nodes; drag from left panel; connect edges; node config panel: connector OAuth field mapping; save → POST /api/workflows {nodes edges config}; workflow JSON stored in PostgreSQL), trigger layer (webhook trigger: POST /webhooks/{workflowId}/{secret} → validate HMAC signature → publish Kafka execution-requests; polling trigger: cron scheduler SCAN trigger:{id} configs → connector.pollForNewData → diff against last_seen cursor; event trigger: internal Kafka events subscriptions), execution engine (consume Kafka execution-requests; load workflow definition; create execution record {execId workflowId status:running startedAt}; step runner loop: for each node in topological order: load step state; if COMPLETED skip; call connector.execute(input); store step_executions {stepId status output attempt}; on error: retry with exponential backoff 1s 2s 4s up to 3 retries; dead letter queue after max retries), connector integration (OAuth connection store: connections table {userId connectorId accessToken refreshToken expiresAt}; auto-refresh on expiry; API rate limit tracking per connection; connector SDK: each connector implements trigger.poll() trigger.registerWebhook() action.execute(); idempotency: action called with idempotencyKey={execId}:{stepId}:{attempt}), data transformation (field mapping UI: left panel step.output fields; right panel action.input fields; drag to map; transformation expressions: {{step1.output.email | lowercase}} {{step2.output.createdAt | date:'YYYY-MM-DD'}}; evaluated at runtime with step output data injected), execution logs UI (GET /api/executions?workflowId&cursor; real-time SSE /api/executions/{id}/stream for in-progress; step timeline: accordion rows showing input output duration; re-run from step: POST /api/executions/{id}/retry {fromStepId}; filter by status date range search), per-tenant throttling (Redis INCR concurrent:{tenantId} TTL 30s; reject if > quota 100 concurrent; burst allowance: 2x quota for 60s; execution time billing: track step_executions.duration_ms sum per month)."
          caption="Workflow builder (React Flow canvas, connector OAuth, field mapping), webhook/polling/event trigger layer (Kafka ExecutionRequests), step runner (topological order, per-step durable state, exponential backoff retries, dead letter queue), connector SDK (idempotency key per attempt), data transformation templates, SSE execution logs, and per-tenant concurrency throttling via Redis"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Visual Workflow Builder</h3>
        <p>The workflow builder is a directed acyclic graph (DAG) editor. Each node represents a step: a trigger (exactly one per workflow, always the root) or an action. Condition nodes have two outgoing edges (true branch, false branch); loop nodes have a body edge (the steps inside the loop) and an exit edge. The canvas uses a library like React Flow for node rendering and drag-and-drop edge connection. Each node renders as a card showing the connector icon, step name, and a status indicator (configured/incomplete). Clicking a node opens a side panel with the step's configuration form: the connector to use (with a dropdown of configured connections), the trigger or action to perform, and the input field mapping.</p>
        <p>The workflow is serialized as a JSON document with two top-level keys: nodes (array of &#123;id, type, connectorId, actionId, config, position&#125;) and edges (array of &#123;source, target, label&#125;). This JSON is validated on save: the server checks that the graph is a valid DAG (no cycles), that all referenced connectors and actions exist, and that required input fields are either mapped or have defaults. Validation errors are returned as a list of &#123;nodeId, field, message&#125; tuples and highlighted in the canvas. Workflow changes are auto-saved every 30 seconds (PATCH /api/workflows/&#123;id&#125;) but do not take effect until the workflow is explicitly published (PUT /api/workflows/&#123;id&#125;/publish), which increments the version number and starts using the new definition for subsequent trigger executions.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Execution Engine with Durable State</h3>
        <p>When a trigger fires, the Execution Service creates an Execution record (execId, workflowId, workflowVersion, status=RUNNING, triggeredAt, triggerData) and a StepExecution record for each step in the workflow (stepId, execId, status=PENDING, attempt=0). The step runner processes steps in topological order (respecting the DAG edges). For each step: it loads the step's StepExecution record, skips if status=COMPLETED (idempotent replay), otherwise calls the connector's action.execute() method with the resolved input (step output values from previous steps substituted into the mapping template). If the call succeeds, the StepExecution is updated to status=COMPLETED, output=responseData. If it fails with a transient error (network timeout, 5xx), the attempt counter is incremented and the step is retried after a backoff delay (1s, 2s, 4s for attempts 1, 2, 3). After 3 failed attempts, the step is moved to status=FAILED and the execution halts.</p>
        <p>This durable state approach enables crash recovery: if the execution worker crashes mid-execution, a heartbeat mechanism detects the stale execution (no heartbeat update for 60 seconds) and re-queues the execution. The step runner picks it up and resumes from the last COMPLETED step — PENDING and FAILED steps are re-attempted, but COMPLETED steps are skipped. This provides at-least-once execution semantics at the step level. For external API calls (Slack, Salesforce), the idempotency key (execId:stepId:attempt) is passed as an idempotency header or request parameter where the API supports it, providing exactly-once semantics for idempotent APIs.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Connector OAuth and Connection Management</h3>
        <p>Most connectors (Google, Slack, Salesforce, HubSpot) use OAuth 2.0 for authentication. The connection setup flow: user clicks "Connect Slack" in the connector configuration panel → redirect to Slack&apos;s OAuth authorization URL with the platform&apos;s client_id and a CSRF state parameter → user authorizes → Slack redirects back to the platform&apos;s callback URL with an authorization code → the platform exchanges the code for access_token and refresh_token → stored in the connections table (userId, connectorId, accessToken, refreshToken, expiresAt, scopes). The access token is encrypted at rest using AES-256 with a per-tenant encryption key. When an action requires an API call, the Step Runner fetches the connection credentials, checks expiry, and proactively refreshes the access token if it expires within 5 minutes (using the refresh_token). Rate limiting per connection is tracked in Redis (INCR rate:&#123;connectorId&#125;:&#123;connectionId&#125;:&#123;minute&#125;, compared against the connector&apos;s documented rate limit). If a rate limit is reached, the step is delayed (not failed) until the rate limit window resets.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Data Transformation and Field Mapping</h3>
        <p>The field mapping UI allows users to wire step outputs to action inputs without writing code. The left panel shows the output schema of preceding steps (derived from the connector&apos;s documented response schema and enriched with sample data from the most recent execution). The right panel shows the input schema of the current action (required and optional fields). The user drags from an output field to an input field to create a mapping. For transformations, the user can type a template expression in the input field: &#123;&#123;step1.output.email | lowercase&#125;&#125; or &#123;&#123;step1.output.amount | multiply:100&#125;&#125;. Supported filters: lowercase, uppercase, trim, date:&apos;format&apos;, number, multiply:N, divide:N, add:N, if:condition:value:fallback.</p>
        <p>At execution time, the template engine resolves the expressions: it substitutes step output data into the template, applies filters, and produces the final value. The engine handles missing data gracefully: if step1.output.email is null, &#123;&#123;step1.output.email | lowercase | default:&apos;unknown&apos;&#125;&#125; returns &apos;unknown&apos;. Template compilation happens at workflow save time (the expressions are parsed and validated for syntax errors) and template execution happens at step run time. A live preview panel in the mapping UI shows the resolved value using the most recent execution&apos;s data, letting the user verify their expression before publishing.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Real-Time Execution Logs</h3>
        <p>The execution history page shows all past executions for a workflow: trigger time, duration, status, and the triggering data (truncated to 200 characters). Clicking an execution opens the detail view: a timeline of steps with expandable rows showing input data (what was sent to the connector API), output data (what the connector API returned), duration, and error message if failed. For in-progress executions, the step timeline updates in real time via SSE: GET /api/executions/&#123;id&#125;/stream returns an SSE stream that pushes StepExecution update events (&#123; stepId, status, output, duration &#125;). The client appends events to the timeline as they arrive, turning the execution detail into a live progress view. When the execution completes (or fails), the SSE connection closes and the final status is displayed.</p>
        <p>Re-running a failed execution: the user clicks "Retry from step X" on a failed execution. This clones the original execution record, preserves the trigger data, marks all steps before X as COMPLETED (copying their outputs), and marks step X and subsequent steps as PENDING. The re-run is queued to the execution engine, which picks up from step X without re-firing the trigger or re-running preceding steps. This pattern is essential for failures caused by transient external issues — if the Slack API was down for 10 minutes, the user can retry just the Slack step without re-running the Google Sheets read step that already succeeded.</p>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <p>Sequential versus parallel execution for independent branches: most user-created workflows are sequential (trigger → action A → action B → action C), where each action depends on the previous step's output. However, when a workflow has a condition node with two branches that don't depend on each other, parallel execution could reduce total execution time. The complexity of parallel execution (managing concurrent step states, tracking branch completion, merging results) is significant. For a first version, sequential execution with an optional explicit "parallel" node type is simpler to implement and covers the majority of use cases. Parallel execution can be introduced as a feature once the execution engine is stable.</p>
        <p>Polling triggers versus webhook triggers for connector coverage: webhook triggers (the connector pushes events to the platform) provide low latency and are efficient but require the connector's API to support webhooks — many APIs do not. Polling triggers (the platform periodically pulls for new data) work with any REST API that supports cursor-based pagination but introduce polling latency (typically 1–15 minutes). The system must support both, with the connector SDK defining which trigger type each connector supports. For connectors that support webhooks, the platform registers the webhook URL with the connector's API when the trigger is configured and de-registers it when the workflow is disabled. Webhook registration state (URL, secret, connectorWebhookId) is stored per trigger configuration and managed by the Connector Service.</p>
      </section>

      <section>
        <h2>Summary</h2>
        <p>A workflow automation system (Zapier-like) is built around three layers. The Builder Layer is a React Flow DAG canvas where triggers and action nodes are connected, configured with field mapping templates (&#123;&#123;step.output.field | filter&#125;&#125;), and published as versioned JSON workflow definitions. The Trigger Layer routes inbound webhooks (HMAC-validated) and polling scheduler results to Kafka ExecutionRequests. The Execution Engine consumes ExecutionRequests, processes steps in topological order with durable per-step state (PostgreSQL StepExecution rows), exponential backoff retry (3 attempts), and dead letter queue for final failures. Crash recovery resumes from the last completed step using heartbeat detection. Connector OAuth tokens are stored encrypted with proactive refresh; rate limits are tracked per connection in Redis. Execution logs stream in real time via SSE; failed executions support partial re-run from any step. Per-tenant concurrency throttling (Redis INCR concurrent:&#123;tenantId&#125;) prevents single-tenant resource monopolization. The key design insight: durable step-level execution state (not just workflow-level) is the foundation of reliable automation — it enables idempotent replay, crash recovery, partial re-run, and observability all from the same persistence model.</p>
      </section>
    </ArticleLayout>
  );
}
