"use client";
import { useEffect, useState } from "react";
type QueryState = { rawQuery: string; normalizedQuery: string; tokens: string[]; filters: string[]; lastMessage: string };
export default function Page() {
  const [state, setState] = useState<QueryState | null>(null);
  const [rawQuery, setRawQuery] = useState('Distributed Systems Search content-type:article');
  async function refresh() { const response = await fetch('/api/query/state'); setState((await response.json()) as QueryState); }
  async function processQuery() { const response = await fetch('/api/query/process', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rawQuery }) }); setState((await response.json()) as QueryState); }
  useEffect(() => { void refresh(); }, []);
  return <main className="mx-auto max-w-6xl px-6 py-10"><h1 className="text-3xl font-bold">Query Processing</h1><p className="mt-2 text-slate-300">Normalize the user query, split free-text terms from structured filters, and expose the parsed representation to downstream search systems.</p><section className="mt-8 grid gap-6 lg:grid-cols-[320px,1fr]"><article className="rounded-xl border border-slate-800 bg-slate-900/60 p-5"><label className="block text-sm text-slate-300">Raw query</label><input value={rawQuery} onChange={(event) => setRawQuery(event.target.value)} className="mt-2 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2" /><button onClick={processQuery} className="mt-4 rounded bg-sky-600 px-4 py-2 text-sm font-semibold hover:bg-sky-500">Process query</button></article><article className="rounded-xl border border-slate-800 bg-slate-900/60 p-5 text-sm text-slate-300"><div>Normalized: <span className="font-semibold text-slate-100">{state?.normalizedQuery}</span></div><div className="mt-4 grid gap-4 md:grid-cols-2"><div><div className="text-xs uppercase tracking-wide text-slate-400">Tokens</div><ul className="mt-2 space-y-2">{state?.tokens.map((token) => <li key={token} className="rounded border border-slate-800 px-3 py-2">{token}</li>)}</ul></div><div><div className="text-xs uppercase tracking-wide text-slate-400">Filters</div><ul className="mt-2 space-y-2">{state?.filters.map((filter) => <li key={filter} className="rounded border border-slate-800 px-3 py-2">{filter}</li>)}</ul></div></div><p className="mt-5">{state?.lastMessage}</p></article></section></main>;
}
