"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-location-based-recommendation-system",
  title: "Design a Location-Based Recommendation System",
  description:
    "Architecture for a location-based recommendation system: Redis GEORADIUS fetching up to 200 candidate places within 5km in under 5ms, S2 cell level-14 spatial index sharded by city geohash prefix, multi-signal ranking (proximity 40%, rating 30%, personal affinity 20%, popularity 10%), user affinity profile built from visit history and cuisine preferences cached in Redis 10-minute TTL, real-time feedback loop via Kafka visit events updating affinity scores near-real-time, open-now filtering using RRULE-based business hours, and session-aware deduplication to exclude recently visited places.",
  category: "high-level-design",
  subcategory: "maps-location-intelligence",
  slug: "location-based-recommendation-system",
  wordCount: 4800,
  readingTime: 27,
  lastUpdated: "2026-05-14",
  tags: ["hld", "recommendation", "geospatial", "redis", "postgis", "s2-geometry", "location", "ranking"],
  relatedTopics: ["maps-exploration-ui", "route-optimization-ui"],
};

export default function LocationBasedRecommendationSystemArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A location-based recommendation system answers the question: "given where I am right now, what should I visit next?" The system must consider the user's current location (proximity), their personal preferences (inferred from past behavior), the quality of nearby places (ratings, reviews, popularity), and contextual signals (time of day, day of week, weather, occasion). Unlike a pure collaborative filtering recommendation system (which works on item-item or user-user similarity without a location dimension), a geo recommendation system has a strict constraint: only places within a reasonable travel radius are candidates.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The core architecture challenge is the two-stage retrieve-then-rank pipeline: (1) candidate retrieval — efficiently find all places within the user's radius from a database of millions of POIs without scanning every row; (2) ranking — score each candidate on multiple dimensions and return the top N. Both stages must complete in under 100ms end-to-end for a responsive user experience.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Geo candidate retrieval, user affinity modeling, multi-signal ranking, real-time feedback loop, and open-now filtering. Not in scope: map tile rendering (separate article), route optimization (separate article), or content recommendation (non-location-based).</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Geo candidate retrieval:</strong> The first stage retrieves all places within the user's search radius that match the requested category. The primary geo index is Redis GEORADIUS — a Redis Sorted Set where each member is a placeId and the score is the geohash of the place's coordinates. Redis stores all places indexed by their geohash and supports O(log N + M) radius queries returning M results. Query: GEORADIUS places:restaurant &#123;lng&#125; &#123;lat&#125; 5 km ASC COUNT 200 WITHCOORD WITHDIST. This returns up to 200 candidate placeIds with distances in under 5ms even with millions of entries. The 200-candidate ceiling is the retrieve-then-rank tradeoff: fetching more candidates improves recall but increases ranking latency. For categories with sparse coverage (e.g., "axe throwing"), the radius is expanded progressively (5km → 10km → 25km) until at least 10 candidates are found.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>User affinity profile:</strong> The affinity profile captures the user's long-term preferences inferred from their behavior. Profile fields: visitedPlaceIds (set of places the user has been to, used for deduplication), cuisineAffinity (map of cuisine type → affinity score 0–1, e.g., &#123;italian: 0.8, thai: 0.6, fast_food: 0.2&#125;), priceRangePreference (preferred price tier 1–4), distanceComfort (how far the user typically travels — drives 20km vs. walks 500m), visitTimeDistribution (morning/afternoon/evening preference), and savedPlaces (user-starred places). The affinity scores are computed by a batch ML job that runs nightly, using implicit feedback signals: visits (strongest signal), dwell time &gt;30 minutes at a place, photos taken, reviews written, and saves. The affinity profile is stored in Redis (as a JSON hash per userId) with a 10-minute cache TTL and in PostgreSQL as the source of truth.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Multi-signal ranking:</strong> Each candidate is scored using a linear combination of signals: score = α × proximityScore + β × ratingScore + γ × affinityScore + δ × popularityScore. Default weights: α = 0.40 (proximity), β = 0.30 (rating), γ = 0.20 (personal affinity), δ = 0.10 (popularity). The weights are configurable and can be personalized — users who frequently travel far for food get a lower proximity weight and higher affinity weight. proximityScore = 1 - (distance / maxRadius) — closer places score higher. ratingScore = rating / 5.0, weighted by review count confidence (a place with 5,000 reviews at 4.2 stars scores higher than a place with 3 reviews at 5.0 stars, using a Bayesian confidence interval). affinityScore = cuisineAffinity[place.cuisine] × priceMatch(place.priceRange, userPricePreference). popularityScore = log10(visitCount in last 30 days) / normalizedMax — log-scaled to avoid viral places dominating. After scoring, filters are applied: exclude places that are currently closed (using RRULE-based hours + current time + timezone), exclude places in the user's visitedPlaceIds (for "new discovery" mode), and apply minimum rating threshold (configurable, default 3.5 stars).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Open-now filtering:</strong> Business hours are stored as a structured weekly schedule (RRULE format per day, specifying open and close times, including special closures and holiday overrides). The open-now check: given the place's IANA timezone and the current UTC timestamp, compute local time and check if it falls within the current day's open interval. This check is performed for all 200 candidates in-memory (no additional DB query required) using the hours data fetched in the candidate enrichment step. Places that are closed are excluded from results unless the user explicitly requests "include closed" (useful for planning ahead). For places with inconsistent or missing hours, a "hours unknown" label is shown but the place is not excluded.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Real-time feedback loop:</strong> Every user interaction with a recommendation is a learning signal. Events are logged to Kafka: impression (recommendation shown), tap (user opened place detail), navigation_start (user navigated to place), visit (user arrived at and stayed 5+ minutes), dismiss (user swiped away the recommendation). The Kafka topic is consumed by two services: (1) the affinity update service — near-real-time (within 30 seconds of a visit event), the service increments the cuisine affinity score for the visited place's cuisine and decrements it for dismissed cuisines, using an exponential moving average with a decay factor so recent visits have higher weight than older ones; (2) the training pipeline — events are accumulated and used in the nightly batch ML job to re-train the full affinity model. The near-real-time update ensures that if a user visits an Italian restaurant and immediately asks for more recommendations, the affinity model has already been updated to surface more Italian options.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>S2 cell-based sharding:</strong> For massive scale (hundreds of millions of places globally), a single Redis GEORADIUS instance cannot hold all places in memory. Places are sharded across Redis instances by S2 cell at level 5 (each level-5 cell covers approximately 250km × 250km — roughly a metropolitan region). The recommendation API determines which S2 cells cover the user's search radius (typically 1–4 cells for a 5km radius) and issues parallel GEORADIUS queries to the corresponding Redis shards. Results are merged and deduplicated before ranking. S2 cells at level 14 (approximately 600m × 600m) are used as the indexing key for the places within each shard — this provides a hierarchical structure that enables efficient drill-down from city-level to neighborhood-level. New places are indexed into Redis when they are created or when their coordinates change (a separate place update event triggers a Redis GEOADD).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Context signals:</strong> Beyond the user's static affinity profile, contextual signals improve recommendation quality. Time-of-day context: at 7am, breakfast spots are boosted; at 8pm, dinner restaurants and bars are boosted. Day-of-week context: weekday recommendations lean toward quick service; weekend recommendations lean toward leisurely dining and attractions. Occasion context: if the user's calendar shows a "anniversary dinner" event in 2 hours (with calendar permission), the system boosts fine dining and flowers. Weather context: on rainy days, indoor venues are boosted; on sunny days, parks and outdoor dining are boosted. Weather data is fetched from a weather API at the user's current location and cached per S2 cell at level 10 (city-level) with a 30-minute TTL. Context signals adjust the α/β/γ/δ weights dynamically — weather context is applied as a multiplier on the base scores rather than a separate ranking dimension.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Cold start for new users:</strong> A new user with no visit history has no affinity profile. Cold start strategy: (1) onboarding survey — ask the user to select 3–5 cuisine preferences and a price range during sign-up; these seed the affinity profile; (2) collaborative filtering bootstrap — find the N users who are geographically nearest (same home geohash at S2 level 10) and whose onboarding preferences are most similar; use their aggregated visit history as the new user's initial affinity profile (item-based collaborative filtering); (3) popularity fallback — rank candidates by popularity score alone (highest rated + most visited in the area) until the user has at least 5 visit events, at which point the personal affinity model takes over. The transition from collaborative filtering to personal model is gradual: the personal affinity weight starts at 0 and increases linearly to its target weight (0.20) as the user accumulates visits.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The recommendation system has three planes: the retrieval plane (Redis GEORADIUS sharded by S2 cell, returning geo candidates in &lt;5ms), the ranking plane (user profile fetch from Redis, candidate enrichment from place DB, multi-signal scoring, open-now filter, top-N selection), and the feedback plane (Kafka event stream, near-real-time affinity update service, nightly batch ML training). The retrieval and ranking planes complete in under 100ms end-to-end (retrieval: &lt;5ms, profile fetch: &lt;5ms parallel, enrichment: &lt;30ms batch DB query for 200 candidates, scoring: &lt;10ms in-memory, serialization: &lt;10ms). The feedback plane is fully asynchronous and does not block the recommendation response.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/maps-location-intelligence/location-based-recommendation-system.svg"
          alt="Location-based recommendation system: user sends lat/lng; Redis GEORADIUS returns 200 candidates within 5km in under 5ms; parallel fetch user affinity profile from Redis 10min cache; ranking engine scores each candidate (dist 40%, rating 30%, affinity 20%, popularity 10%); filter closed; return top 20; user tap triggers Kafka visit event that updates affinity scores near-real-time."
          caption="Redis GEORADIUS &lt;5ms; S2 cell sharding by metro region; parallel profile fetch Redis 10min TTL; score = dist×0.4 + rating×0.3 + affinity×0.2 + pop×0.1; open-now filter via RRULE; Kafka visit → affinity update &lt;30s"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Redis Geo Index Design</h3>
        <HighlightBlock as="p" tier="crucial">Redis GEORADIUS uses a sorted set where scores are 52-bit geohashes (the Mercator projection is approximated by a 52-bit integer representing the position in a space-filling Hilbert curve — this is the same mapping used by S2). Each category gets a separate Redis key per S2 shard: places:&#123;s2cell&#125;:&#123;category&#125;. This structure allows GEORADIUS to scan only the relevant category within the relevant shard. The trade-off is memory: with 100 million places and 50 categories, this creates up to 5 billion sorted set entries across all shards — in practice, places belong to only 2–5 categories, keeping the actual count manageable. Alternatively, a single all-categories key per shard with category filtering in the ranking step reduces memory at the cost of scanning more irrelevant candidates.</HighlightBlock>
        <HighlightBlock as="p" tier="important">GEORADIUS vs. PostGIS for retrieval: Redis GEORADIUS is faster (in-memory, O(log N + M)) but has limitations — it stores only a point per member (no metadata), requires the application to do a separate round-trip to fetch place details, and has limited filtering capability. PostGIS ST_DWithin supports arbitrary SQL filters (category, minimum rating, open-now) in the spatial query itself, returning already-filtered candidates. For systems where the candidate pool is large (&gt;1,000 candidates) and pre-filtering is important, PostGIS is preferable despite being slower (~20ms vs. ~5ms). For systems where speed is paramount and the ranking stage can filter, Redis GEORADIUS is the right choice.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Affinity Score Update</h3>
        <HighlightBlock as="p" tier="important">The exponential moving average update for cuisine affinity: newScore = α × 1.0 + (1 - α) × oldScore on a visit event, where α = 0.1 (visit weight — each visit shifts the score 10% toward 1.0). On a dismiss event: newScore = α × 0.0 + (1 - α) × oldScore (each dismiss shifts toward 0.0). The decay factor α = 0.1 means it takes approximately 7 visits to a cuisine to bring its affinity score from 0 to 0.5. This prevents a single anomalous visit (e.g., visiting a fast food restaurant once because it was the only option) from permanently dominating the user's affinity profile. The full affinity recomputation (nightly batch job) uses a more sophisticated model (matrix factorization on the user-place visit matrix) and overwrites the incremental EMA scores, providing a clean slate from which the incremental updates continue.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">Retrieve-then-rank vs. approximate nearest neighbor: the retrieve-then-rank pipeline (Redis GEORADIUS → score all candidates → top N) is exact — every place within the radius is scored and the true top N is returned. An alternative is approximate nearest neighbor (ANN) search, which sacrifices a small amount of recall for dramatically lower latency. ANN libraries (FAISS, ScaNN, Annoy) build an approximate index over the feature vectors of all places (embedding proximity, category, rating into a vector) and find the approximate top-K by vector similarity rather than distance in geographic space. ANN is appropriate when the ranking signals are complex (deep learning models with hundreds of features) and the exact retrieval is too expensive. For a 5-signal linear model scored over 200 candidates, exact retrieval is fast enough and ANN adds unnecessary complexity.</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">Personalization vs. discovery: strong personalization (high affinity weight) gives the user more of what they already like but reduces serendipitous discovery of new venues. Pure novelty (low affinity weight, high diversity constraint) exposes users to unfamiliar places but risks irrelevance. The system implements a "explore mode" toggle: when enabled, the affinity weight drops to 0.05 and a diversity constraint is applied (no two consecutive results from the same cuisine). The default mode balances personalization with novelty by including at least 3 results outside the user's top affinity cuisines in every 10-result page.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A location-based recommendation system requires: (1) Redis GEORADIUS for geo candidate retrieval — O(log N + M), returns 200 candidates within 5km in &lt;5ms; (2) S2 cell sharding at level 5 (~250km cells) for global scale — parallel queries to relevant shards; (3) user affinity profile: cuisine affinity scores, price preference, distance comfort — cached in Redis 10 min TTL, updated near-real-time via Kafka events; (4) multi-signal ranking: score = proximity×0.40 + rating×0.30 + affinity×0.20 + popularity×0.10; Bayesian rating confidence; log-scaled popularity; (5) open-now filter using RRULE-based hours + IANA timezone; (6) visited-place deduplication from profile visitedPlaceIds set; (7) real-time feedback loop: Kafka impression/visit/dismiss events → EMA affinity update within 30s; (8) cold start: onboarding survey seeds profile → collaborative filtering from geo-similar users → gradual transition to personal model at 5+ visits; (9) context signals: time-of-day, day-of-week, weather — applied as weight multipliers; (10) explore mode: reduce affinity weight, enforce cuisine diversity constraint.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
