"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-maps-exploration-ui",
  title: "Design a Maps Exploration UI (like Google Maps)",
  description:
    "Architecture for a Google Maps-like exploration UI: Mapbox Vector Tile (MVT) format rendered client-side with WebGL, z/x/y tile addressing with 30-day CDN cache for base tiles and 30-second TTL for traffic overlays, tile server rendering from OpenStreetMap vector data on CDN miss, PostGIS GIST index with KNN for proximity search, prefix-trie autocomplete under 20ms p50, place detail cards with real-time busyness data, GPS probe aggregation into per-road-segment speed tiles refreshed every 30 seconds, and S2 geometry library for spatial indexing.",
  category: "high-level-design",
  subcategory: "maps-location-intelligence",
  slug: "maps-exploration-ui",
  wordCount: 4900,
  readingTime: 28,
  lastUpdated: "2026-05-14",
  tags: ["hld", "maps", "google-maps", "vector-tiles", "postgis", "webgl", "geospatial", "cdn"],
  relatedTopics: ["location-based-recommendation-system", "route-optimization-ui"],
};

export default function MapsExplorationUiArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="crucial">A maps exploration UI allows users to pan, zoom, search for places, and view real-time information like traffic and business hours overlaid on an interactive map. The core challenges are: (1) rendering — a world map at all zoom levels contains petabytes of geographic data; only the visible tiles should be fetched, and they must render smoothly at 60 fps as the user pans; (2) search — users expect instant autocomplete as they type, and search results should be biased toward their current viewport; (3) freshness — traffic conditions change every few minutes and must be reflected on the map without requiring full tile regeneration; (4) scale — a service like Google Maps serves billions of tile requests per day and hundreds of millions of search queries.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The foundational architectural decision is the tile-based map rendering model: the world is divided into a grid of tiles at each zoom level (z/x/y addressing). At zoom 0, the entire world fits in one 256×256 tile. At each zoom increment, each tile splits into four, so zoom 14 has 2^28 ≈ 268 million tiles. The client computes which tiles are visible in the current viewport and fetches only those, enabling efficient CDN caching (tiles are static once rendered, cacheable for weeks) and client-side rendering (the client assembles tiles into a seamless map).</HighlightBlock>
        <p><strong>Explicit scope:</strong> Tile rendering pipeline (vector tiles, CDN caching, WebGL client rendering), place search and autocomplete, place detail cards, and traffic overlay. Not in scope: turn-by-turn routing (separate article), location-based recommendations (separate article), or map editing.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Tile-based map rendering:</strong> The client (browser or mobile app) uses a mapping library (Mapbox GL JS, Google Maps JS API) that manages the tile grid. As the user pans or zooms, the library computes the z/x/y coordinates of all tiles in the viewport (typically 12–20 tiles per view at zoom 14) and issues parallel HTTP requests to the tile CDN. Tile URL format: /tiles/&#123;z&#125;/&#123;x&#125;/&#123;y&#125;.mvt (Mapbox Vector Tile format). The CDN (CloudFront, Fastly) caches tiles at the edge with a 30-day TTL. On a cache miss, the CDN origin-fetches from the tile server, which renders the tile by querying the vector data store (OSM data in PostgreSQL with PostGIS). The rendered MVT bytes are returned to the CDN, which caches them and returns them to the client. The client's WebGL renderer (Mapbox GL) applies styles (road widths, building colors, label placement) to the vector data, producing smooth zoom-level-independent rendering with anti-aliasing.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Vector tiles vs. raster tiles:</strong> Raster tiles (PNG images) are pre-rendered server-side at fixed zoom levels, simple to serve, but large (each tile is a full image) and not smoothly scalable between zoom levels (zooming in causes blurriness until the next zoom level's tiles load). Vector tiles (MVT) contain the raw geographic data (line coordinates, polygon boundaries, point locations) and are styled client-side by WebGL. They are smaller (compressed binary protobuf), can be rendered at any zoom level without blurriness, and support dynamic styling (change road color, highlight a business) without re-fetching tiles. The tradeoff is client-side rendering complexity — the browser must run a WebGL shader to render the map — which requires a capable GPU and has a higher initial JavaScript bundle size.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Place search and autocomplete:</strong> The search bar sends a query to GET /search?q=&#123;query&#125;&amp;lat=&#123;lat&#125;&amp;lng=&#123;lng&#125;&amp;radius=50km. Autocomplete (triggered on each keystroke with 150ms debounce): a prefix trie built from all place names and addresses, stored in Redis as a sorted set per prefix character (the "Radix tree with Redis Sorted Sets" pattern). Each prefix maps to the top 10 results by relevance score (score = popularity × proximity bias). Autocomplete p50 latency target: &lt;20ms. Full-text search (submitted query): Elasticsearch index with geo-distance scoring — results are boosted by proximity to the user's current viewport center. The search results panel shows name, category icon, rating, distance, and "open now" status. Clicking a result drops a pin on the map and centers the viewport on the place.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Place detail card:</strong> Clicking a pin or search result opens a place detail card. The card data is fetched from GET /places/&#123;placeId&#125; which returns: name, formatted address, phone number, website URL, opening hours (structured as RRULE-like weekly schedule), current busyness level (percentage of typical maximum occupancy, derived from aggregated location signals), photos (presigned S3 URLs served via CDN), user rating aggregate, and review count. Real-time busyness: aggregated from anonymized GPS dwell time signals — when many devices with location sharing enabled stop moving at a location for 5+ minutes, the system infers the location is busy. The busyness signal is a rolling 15-minute aggregate, refreshed every 5 minutes, stored in Redis per placeId.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Traffic overlay tiles:</strong> Traffic is a separate tile layer overlaid on the base map. Traffic tiles have a 30-second CDN TTL (much shorter than base tiles) because road speeds change every few minutes. Traffic data pipeline: GPS probes (mobile devices with navigation active) send their speed and heading to the probe ingestion service every 5 seconds. The ingestion service buffers probes in a Kafka topic. A stream processor (Flink) aggregates probes per road segment over 30-second windows, computing the median speed for each segment. Segments are classified: green (&gt;80% free-flow speed), yellow (50–80%), red (&lt;50%), dark red (&lt;25%). The aggregated speed data is written to a traffic tile store. On tile request, the tile server joins the road network with the current speed classification to color-code the roads and renders a traffic MVT tile. Traffic tiles are generated per z/x/y on-demand and cached at the CDN for 30 seconds.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Spatial indexing with PostGIS:</strong> Place data (restaurants, shops, landmarks) is stored in PostgreSQL with a geometry column (ST_Point containing lat/lng). A GIST index on the geometry column enables fast spatial queries. For "find all coffee shops within 1km of this point": SELECT * FROM places WHERE category = 'coffee_shop' AND ST_DWithin(geom, ST_MakePoint(-122.4, 37.7)::geography, 1000) ORDER BY ST_Distance(geom, ST_MakePoint(-122.4, 37.7)::geography) LIMIT 20. The GIST index uses the R-tree data structure internally, which groups nearby points into bounding rectangles for efficient spatial pruning. For queries requiring K-nearest neighbors (find the closest N places regardless of category), PostGIS uses the KNN operator (&lt;-&gt;), which leverages the GIST index for efficient distance ordering without computing all distances.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>S2 geometry library for hierarchical spatial indexing:</strong> Google's S2 library (also used by DynamoDB, Redis GEORADIUS, and many geo-aware databases) maps the Earth's surface to a Hilbert space-filling curve. Each point on Earth gets a 64-bit cell ID at one of 31 zoom levels (cell level 14 covers approximately 600 square meters). S2 cells at the same level are approximately equal-area, which avoids the distortion of latitude/longitude grids near the poles. The maps system uses S2 for: indexing places by their S2 cell ID (enables fast "find all places in this viewport" queries by fetching places whose cell IDs fall within a set of covering cells), sharding the road graph by geographic region (cells at level 8, approximately 25km × 25km, are the sharding unit for the routing graph), and computing which tiles need to be re-rendered when a road speed update arrives (the segment's S2 cell determines which tiles contain it).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Tile pre-generation and freshness:</strong> Popular areas (cities, tourist destinations) at popular zoom levels (z10–z16) are pre-generated and stored in the tile cache before any user requests them. A tile pre-generation job runs whenever the underlying map data is updated (OSM data updates weekly; transit schedules update daily). Pre-generated tiles are stored in S3 and pushed to the CDN. For rarely-requested tiles (remote areas, low-zoom tiles covering ocean), generation is on-demand and cached after the first request. The tile generation job uses a priority queue: tiles that were recently invalidated (due to data updates) and that have high request volumes are re-generated first. Tile cache invalidation: when a road is rerouted or a business permanently closes, the affected tiles are identified by their z/x/y coordinates (computable from the affected coordinates) and a cache purge is issued to the CDN for those specific tile URLs.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The maps system has four planes: the tile plane (MVT tile server, CDN, pre-generation job, traffic overlay pipeline), the search plane (autocomplete trie in Redis, Elasticsearch for full-text + geo search), the place data plane (place DB in PostgreSQL + PostGIS, busyness aggregator, photo CDN), and the probe ingestion plane (GPS probe Kafka topic, Flink aggregator for traffic, S2 cell–based road speed store). The client (Mapbox GL JS) renders tiles, overlays, and pins using WebGL, managing the tile fetch lifecycle autonomously based on the viewport state.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The system's most important performance characteristic is the tile cache hit rate. With a 30-day CDN TTL on base tiles and a world of finite tile coordinates, the hit rate for popular areas approaches 99.99% — the CDN absorbs virtually all traffic for these tiles without touching the origin. The traffic tile plane has a much lower hit rate (30s TTL means each unique tile is fetched from origin ~2880 times per day), but traffic tiles are only requested when the user has the traffic layer enabled, and traffic-aware rendering is a smaller fraction of total tile requests.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/maps-location-intelligence/maps-exploration-ui.svg"
          alt="Maps exploration UI: client requests z/x/y MVT tiles from CDN (30-day TTL); CDN miss renders from OSM vector store on tile server; search sends query to PostGIS KNN with viewport bias; autocomplete uses Redis prefix trie under 20ms; place detail card fetches busyness from Redis rolling aggregate; traffic overlay tiles have 30s TTL fed by GPS probe Flink aggregation."
          caption="MVT tiles via CDN (30-day base / 30s traffic); WebGL client rendering; PostGIS GIST KNN for proximity search; Redis prefix trie autocomplete &lt;20ms; GPS probe → Flink 30s agg → traffic speed tiles; S2 cells for spatial sharding"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Vector Tile Generation Pipeline</h3>
        <HighlightBlock as="p" tier="important">OSM (OpenStreetMap) data is the source for the road network, building footprints, land use, and POI data. The raw OSM data (PBF format, ~75GB for the full planet) is imported into PostgreSQL with PostGIS using osm2pgsql. The tile server (Tegola, Martin, or a custom server using the go-spatial/geom library) receives a tile request z/x/y, computes the bounding box of the tile in WGS84 coordinates, queries PostGIS for all features whose geometry intersects the bounding box at the appropriate zoom level (using ST_Intersects and zoom-level-specific simplification — roads that are below a certain width threshold at a given zoom level are omitted from the tile), serializes the features into MVT protobuf format, and returns the compressed bytes. Tile size target: &lt;100KB compressed for z14 tiles over dense urban areas; typical tiles are 20–40KB. The tile server is stateless and horizontally scalable — multiple instances behind a load balancer, with the CDN acting as a cache in front.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Search Architecture</h3>
        <HighlightBlock as="p" tier="important">Autocomplete is implemented as a Redis Sorted Set prefix lookup. On indexing, each place name "Coffee Bean" generates prefixes: "c", "co", "cof", "coff", etc. Each prefix key in Redis maps to a sorted set of placeIds scored by a pre-computed relevance score (popularity rank × category weight). On each keystroke, the client queries GET /autocomplete?q=cof&amp;lat=37.7&amp;lng=-122.4, which does a Redis ZREVRANGEBYSCORE lookup on the key "autocomplete:cof" (biased toward the user's region by using per-region prefix keys: "autocomplete:us-west:cof"). The top 10 results are returned. The prefix trie is rebuilt nightly from the full place database. For full-text search (submitted queries, not autocomplete), Elasticsearch is used with a geo_distance boost — results closer to the user's viewport center receive a higher score via a function_score query.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Real-Time Busyness Data</h3>
        <HighlightBlock as="p" tier="crucial">Busyness is a privacy-sensitive signal derived from aggregated, anonymized location data. The system uses differential privacy techniques (adding calibrated Laplace noise to aggregate counts) to ensure that no individual's location can be inferred from the published busyness percentage. Individual probe signals are processed in the secure aggregation pipeline — raw lat/lng readings are mapped to a placeId (using reverse geocoding and geofence matching) and immediately discarded; only the count per placeId per 5-minute window is retained. The aggregated count is normalized against the historical maximum for that place and time slot (historical data stored in a time-series database — e.g., TimescaleDB — partitioned by place and time-of-day/day-of-week). The busyness percentage is published to Redis with a 5-minute TTL per placeId. The place detail API reads from Redis, returning the live busyness percentage and the "typical for this time" bar chart data (drawn from the historical time-series).</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">Raster vs. vector tiles: raster tiles are simpler to generate (pre-render to PNG) and have no client-side rendering requirements (any browser can display a PNG). They are appropriate for older clients or low-powered devices. Vector tiles require WebGL and a heavier JavaScript runtime, but provide smoother zooming, smaller download sizes, and dynamic styling flexibility (change theme from light to dark without re-fetching tiles). Modern maps services default to vector tiles for the better user experience, with raster fallback for compatibility. The decision involves weighing client capability (mobile devices with limited GPU), bundle size (Mapbox GL JS is ~300KB), and the need for dynamic map features like custom styling or 3D building extrusion.</HighlightBlock>
        <HighlightBlock as="p" tier="important">CDN cache hit rate for traffic tiles: with a 30-second TTL, each traffic tile at a given z/x/y coordinate is cached for only 30 seconds. For a city with 10,000 traffic tiles at zoom 12 and 1 million users viewing the traffic layer, the CDN receives 10,000 / 30 ≈ 333 cache misses per second for traffic tiles alone. This is a significant origin load compared to base tile cache misses (which are nearly zero for popular areas). Mitigation: (1) use a longer TTL (2 minutes) with stale-while-revalidate — the client sees slightly stale traffic data but the origin load drops 4×; (2) pre-push traffic tiles to the CDN from the tile server immediately after each 30-second aggregation cycle (CDN "push" model), so the cache is warm before any client requests the tile; (3) only enable traffic overlay for zoom levels ≥ 10 (coarser tiles cover more area, reducing the tile count by 4× for each zoom level reduction).</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A Google Maps-like exploration UI requires: (1) MVT (Mapbox Vector Tile) format — protobuf-encoded geographic features rendered client-side with WebGL; (2) z/x/y tile addressing — viewport computes visible tile grid, fetches tiles in parallel; (3) CDN with 30-day TTL for base tiles (near-100% hit rate for popular areas), 30s TTL for traffic tiles; (4) tile server generates MVT from PostGIS on CDN miss — stateless, horizontally scalable; (5) S2 geometry library for spatial sharding and efficient coverage queries; (6) PostGIS GIST index with KNN operator for proximity search (&lt;-&gt; distance ordering); (7) Redis prefix trie autocomplete under 20ms p50 with per-region bias; (8) Elasticsearch with function_score geo boost for full-text place search; (9) GPS probe ingestion → Kafka → Flink 30s aggregate → per-segment speed classification → traffic MVT tiles; (10) busyness signal: differential-privacy-protected count aggregate per placeId per 5-minute window, normalized against historical max, Redis TTL 5 minutes; (11) tile pre-generation for popular areas; selective CDN purge by z/x/y on data updates.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
