"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-google-calendar-system",
  title: "Design a Calendar System (like Google Calendar)",
  description:
    "Architecture for a Google Calendar-like system: event data model with RRULE recurrence stored once and expanded on query, EXDATE exception handling for single-occurrence edits, iCalendar .ics format for interoperability, CalDAV sync with server-side syncToken for delta updates, timezone-aware storage and rendering, shared calendar ACL with viewer/editor/owner roles, reminder pipeline with timezone-correct alarm delivery, conflict detection for overlapping events, and real-time push via WebSocket for collaborative editing.",
  category: "high-level-design",
  subcategory: "scheduling-calendar-systems",
  slug: "google-calendar-system",
  wordCount: 5000,
  readingTime: 30,
  lastUpdated: "2026-05-14",
  tags: ["hld", "calendar", "recurrence", "rrule", "caldav", "icalendar", "sync", "timezone", "reminders"],
  relatedTopics: ["meeting-scheduling-system", "resource-booking-system"],
};

export default function GoogleCalendarSystemArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A calendar system must reliably store, query, and synchronize events across billions of users and their multiple devices. The two hardest problems are recurrence and timezones. Recurrence: a recurring event ("every Tuesday at 9am") should not require storing thousands of individual event rows — it should be stored once as a rule and expanded on demand. But users need to edit single occurrences ("move just this Tuesday's meeting"), which creates exceptions. Timezones: a "9am meeting" should appear at 9am in the user's current timezone, even when they travel — but the event must survive DST transitions without moving to a different wall-clock time.</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">Synchronization is the third major challenge. A calendar must stay consistent across a user's phone, tablet, laptop, and a shared calendar visible to colleagues — in real time. The system must handle offline edits (the user edits their calendar on a plane), merge conflicts (two users edit the same shared event simultaneously), and deletions (an event deleted on one device must disappear on all devices).</HighlightBlock>
        <p><strong>Explicit scope:</strong> Event CRUD with recurrence, range queries, CalDAV/iCal sync, shared calendars with ACL, reminders, and timezone handling. Not in scope: meeting scheduling (finding mutual free time — that is a separate article), resource booking, or video conferencing integration.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Event data model and recurrence:</strong> Each event is stored as a master event row with fields: eventId, calendarId, title, description, location, startTime (UTC), endTime (UTC), startTimezone (IANA timezone string, e.g., "America/New_York"), rrule (RFC 5545 recurrence rule string, null for one-time events), exdates (array of excluded UTC datetimes for single-occurrence deletions), status (confirmed/tentative/cancelled), updated_at (for sync). The RRULE is stored as a string: "FREQ=WEEKLY;BYDAY=TU;COUNT=52" represents "every Tuesday for 52 weeks." Occurrences are never pre-materialized into the database — they are computed on read by expanding the RRULE within the requested date range. This keeps storage O(1) per recurring series regardless of how many occurrences it has.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Recurrence exception handling:</strong> When a user edits a single occurrence of a recurring event ("move just this Tuesday's meeting to 10am"), the system creates a new one-off event row with originalEventId pointing to the master, and overrideDate set to the specific occurrence date being replaced. The master event's exdates array gets the original occurrence's UTC datetime appended (so the master stops generating that occurrence). When querying a date range, the server: (1) expands the master RRULE within the range; (2) removes exdates from the expansion; (3) fetches override events in the range; (4) merges and returns. This three-step merge is performed in the API layer, not in SQL.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Range query and caching:</strong> The calendar UI requests events for a visible date range (e.g., the current week view: GET /events?calendarId=X&amp;start=2026-05-11&amp;end=2026-05-17). The query fetches: all one-time events within the range (simple date range SQL), all recurring master events whose RRULE might produce occurrences in the range (requires checking RRULE DTSTART and UNTIL/COUNT), and all override events in the range. RRULE expansion happens in the API server (not in the database). Results are cached in Redis per user per week: key = userId:calendarId:week:2026-W20, TTL = 5 minutes. Cache invalidation: any mutation to a calendar's events publishes an invalidation event to a Kafka topic, which the cache layer subscribes to and deletes the affected week keys.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Shared calendars and ACL:</strong> A calendar has an access control list (ACL) with entries: &#123;userId, role&#125; where role is one of viewer (can see events), editor (can create/edit/delete events), or owner (can manage ACL and delete the calendar). Free/busy visibility: a viewer who should not see event details can still see "busy" blocks without titles. ACL checks happen on every event mutation — the API verifies the requesting user has at minimum editor role on the target calendar. Shared calendar events are stored in the calendar owner's calendar namespace; the shared user subscribes to the calendar (stored in a calendar_subscriptions table: &#123;subscriberId, calendarId&#125;). The subscriber's query fetches events from all subscribed calendars and merges them.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>iCalendar / CalDAV synchronization:</strong> CalDAV is the standard protocol for calendar synchronization used by Apple Calendar, Outlook, and Thunderbird. The server implements: PROPFIND (list user's calendars with their properties), REPORT with a calendar-query filter (fetch events in a date range), and REPORT with sync-collection (delta sync: "give me everything changed since syncToken X"). The syncToken is a monotonically increasing counter per calendar (stored in the calendar row). When any event in the calendar is mutated, the calendar's syncToken increments. The sync-collection REPORT returns all events with updated_at greater than the timestamp corresponding to the provided syncToken, plus a new syncToken. The client stores the new syncToken and sends it on the next sync request.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Timezone correctness:</strong> Events are stored in UTC plus an IANA timezone string ("America/New_York"). The timezone string is stored separately from the UTC time because DST rules change (governments change DST rules), and the stored UTC time would become wrong if re-derived from a UTC offset. Storing the IANA identifier allows re-computing the correct UTC time if DST rules change for that timezone. All-day events are stored as date-only (no time component, no timezone). For recurring events, each occurrence's local time is computed by: (1) taking the DTSTART local time from the RRULE; (2) converting to UTC using the stored IANA timezone for that specific occurrence date (DST-aware). A weekly recurring meeting at 9am in "America/New_York" will have different UTC times for occurrences in winter (EST, UTC-5) vs. summer (EDT, UTC-4), which is correct — the user expects it at 9am local time regardless of DST.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Scale:</strong> Google Calendar serves ~500M users. Event table: sharded by calendarId (users own multiple calendars; each calendar's events are co-located). Secondary index on (calendarId, startTime) for range queries. The recurring RRULE expansion adds CPU cost at query time — mitigated by the per-week Redis cache and by limiting RRULE expansion to at most 1 year ahead (events beyond 1 year are not expanded until the query window reaches them). Write throughput: event mutations are low-frequency (a few per user per day) but must be globally consistent — Google Calendar uses Spanner for multi-region consistency with the recurring event master.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Conflict handling:</strong> Two users simultaneously editing the same shared event (e.g., two editors of a team calendar both try to update the same event's time) creates a conflict. Resolution: last-write-wins based on updated_at timestamp. The losing write is rejected with a 409 Conflict response containing the current server state. The client UI shows a conflict dialog: "Someone else updated this event while you were editing. Here is the latest version — your changes have been discarded." For high-contention shared calendars (a team calendar with many active editors), optimistic locking via ETag headers is used: the client sends an If-Match header with the event's current ETag (hash of the event content), and the server rejects the update with 412 if the ETag no longer matches.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Reminder delivery:</strong> Reminders are user-configurable per event (e.g., "notify me 15 minutes before" or "notify me 1 day before"). Reminders are stored as an array in the event row: &#123;method: "popup"/"email", minutes: 15&#125;. A reminder worker job runs every minute and queries: events starting within the next 16 minutes (a 1-minute buffer to account for job execution delay) that have a 15-minute reminder and have not yet been notified. The reminder worker is timezone-aware: it converts the event start time to the user's local timezone and checks that the alarm should fire now (accounting for DST). Reminders are delivered via push notification (for popup) or email. Duplicate protection: a reminder_sent flag is set on the reminder entry after delivery, preventing re-delivery on the next job run.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The calendar backend has three layers: the API layer (handles CRUD, RRULE expansion, ACL checks), the sync layer (CalDAV server, WebSocket push for real-time updates), and the storage layer (Spanner/PostgreSQL for events, Redis for expanded event cache and sync state). The API layer is stateless and horizontally scalable. The sync layer maintains WebSocket connections per user session — connection state is stored in Redis (which pod holds the connection for a given userId, used for targeted push when an event is mutated by another user or device).</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">Real-time push: when user A edits an event on the shared calendar, the mutation is written to the database. A Kafka consumer reads the mutation event, looks up all subscribers of that calendar in the calendar_subscriptions table, and pushes an invalidation notification to each subscriber's WebSocket connection (via the Redis connection registry). The subscriber's client re-fetches the affected week's events from the API (invalidating the Redis cache first). This gives near-real-time updates without polling.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/scheduling-calendar-systems/google-calendar-system.svg"
          alt="Google Calendar system: Client POST event with RRULE stored once on master; GET range query expands RRULE in API layer, merges EXDATE exceptions and overrides, cached per-week in Redis; CalDAV REPORT with syncToken for delta sync; .ics invite email with RSVP link; reminder cron 15min before in user TZ."
          caption="RRULE stored once, expanded on query (never materialized); 3-step merge: expand RRULE, remove EXDATE, overlay overrides; CalDAV syncToken delta sync; timezone stored as IANA string for DST-correctness; last-write-wins conflict with ETag"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">RRULE Expansion Algorithm</h3>
        <HighlightBlock as="p" tier="important">The RFC 5545 RRULE format describes recurrence rules: FREQ (DAILY/WEEKLY/MONTHLY/YEARLY), INTERVAL (every N periods), BYDAY (days of week), BYMONTHDAY, COUNT (total occurrences), UNTIL (end date). Expanding an RRULE for a date range requires: (1) parse the RRULE string; (2) generate all occurrences from DTSTART forward; (3) stop when the occurrence falls outside the requested range end or COUNT/UNTIL is reached; (4) skip occurrences in the event's EXDATE list. Libraries like rrule.js (JavaScript) or python-dateutil handle this. The expansion must be timezone-aware — "every Monday at 9am America/New_York" generates different UTC timestamps for winter vs. summer Mondays. Cap: never expand more than 730 occurrences (2 years) in one request, to prevent RRULE expansion from becoming a denial-of-service vector for rules like FREQ=MINUTELY without a COUNT limit.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Editing "this and following" occurrences: when a user edits from occurrence N onward, the system adds UNTIL=N-1 to the master event's RRULE (truncating it before occurrence N) and creates a new master event starting at occurrence N with the new properties. This creates a natural series split. The new master has a dtStart = the specific occurrence N datetime and its own RRULE for the tail of the series. All override events for occurrences &gt;= N that referenced the old master must be re-parented to the new master — a O(k) operation where k is the number of exceptions in the tail.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">CalDAV Sync Protocol</h3>
        <HighlightBlock as="p" tier="important">CalDAV sync uses the sync-collection REPORT defined in RFC 6578. The sync flow: client sends REPORT request with the last known syncToken (or empty for initial sync). Server responds with: the list of event URLs that changed since the syncToken (added/modified events with their iCalendar data, deleted events with just their URL), and the new syncToken. Client applies the delta: add/update the added/modified events in local storage, delete the removed events. Store the new syncToken. The syncToken is a monotonically increasing 64-bit integer stored per calendar. It increments on every write to that calendar (any event CRUD). Token rollover: the server retains event change history for at least 30 days. If the client's syncToken is older than 30 days, the server returns a 403 with a "sync token expired" error, forcing the client to do a full resync.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Free/Busy and Scheduling Assistant</h3>
        <HighlightBlock as="p" tier="important">Free/busy information is needed for scheduling meetings (the scheduling assistant shows when all invitees are free). The free/busy API: POST /freeBusy with a list of calendarIds and a time range. For each calendar, return the list of busy intervals (start/end in UTC). The response omits event titles for calendars where the requestor has only free/busy visibility. The free/busy computation: query all events in the time range for the requested calendars (expanding recurrences), return the union of their time intervals as "busy." This is cache-friendly: the same free/busy data is requested by every scheduling assistant query for a given set of users, so it is cached per (calendarId, dateRange) in Redis with a 1-minute TTL.</HighlightBlock>
        <HighlightBlock as="p" tier="important">All-day events and multi-day events: all-day events are stored as dates (not datetimes) and span midnight-to-midnight in the event's timezone. They appear as "busy" for the entire day in free/busy queries but are rendered differently in the calendar grid (as full-day banners rather than time-block cards). Multi-day events (e.g., a vacation spanning 5 days) are stored as a single event with startDate and endDate (inclusive) and rendered as a spanning banner across multiple days in the calendar UI.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">Materializing vs. expanding on query: pre-materializing all recurrence occurrences (storing each Tuesday's meeting as a separate row) would make range queries simple (a single date range SQL scan with no RRULE expansion). But it creates O(N×occurrences) rows — a "every day forever" event would require infinite rows. It also makes editing the master (e.g., changing a recurring event's title) an O(N) update across all occurrence rows. Expanding on query avoids both problems at the cost of CPU at query time, which the Redis week-level cache handles. The hybrid approach used by some systems: materialize the next 3 months of occurrences, and expand further occurrences on demand. This reduces cache misses for recent events but adds complexity in keeping the materialized rows consistent with master edits.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Timezone storage: storing events in UTC + IANA timezone is the correct approach but adds complexity. An alternative — storing events purely in local time with a UTC offset — is simple but breaks across DST transitions. A meeting stored as "2026-03-07 09:00 UTC-5" (winter EST) would appear at 8am after DST spring-forward (because UTC-5 is now EDT UTC-4 for New York), which is wrong. The IANA string approach handles this correctly because the timezone library knows that "America/New_York" in March 2026 is UTC-4, not UTC-5.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A Google Calendar-like system requires: (1) event model with RRULE stored once on master + EXDATE array for excluded occurrences + override events for single-occurrence edits; (2) RRULE expansion at query time in the API layer (not in SQL), capped at 730 occurrences, cached per user per week in Redis (5-minute TTL); (3) 3-step range query merge: expand RRULE, remove EXDATEs, overlay overrides; (4) timezone storage as IANA string (not UTC offset) for DST-correctness; (5) CalDAV REPORT sync-collection with monotonically-increasing syncToken, 30-day change history retention; (6) shared calendar ACL (viewer/editor/owner), free/busy visibility tier; (7) real-time push via WebSocket + Redis connection registry for collaborative edits; (8) conflict resolution: last-write-wins by updated_at with ETag optimistic locking for high-contention shared calendars; (9) reminder worker querying events starting in next 16 minutes, timezone-aware alarm time, reminder_sent flag for dedup; (10) "this and following" edit splits the RRULE series with UNTIL on the old master and a new master for the tail.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
