"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-lld-token-streaming-buffer",
  title: "Design a Token Streaming Buffer",
  description:
    "A staff-level deep dive into the token streaming buffer system for LLM responses: ReadableStream internals, TextDecoder, SSE parsing, OpenAI and Anthropic formats, backpressure, Web Workers, TransformStream pipelines, and testing strategies.",
  category: "low-level-design",
  subcategory: "ai-modern-systems",
  slug: "token-streaming-buffer",
  wordCount: 4800,
  readingTime: 29,
  lastUpdated: "2026-05-16",
  tags: ["lld", "ai", "streaming", "buffering", "llm", "performance"],
  relatedTopics: ["streaming-chat-ui", "token-management-cost-optimization"],
};

export default function TokenStreamingBufferArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section><h2>Definition &amp; Context</h2><HighlightBlock as="p" tier="crucial" className="mb-4">System-design interview lens: frame Design a Token Streaming Buffer around system boundary, state ownership, failure handling, scalability, security, and observable recovery. This is the difference between describing a feature and designing a production system.</HighlightBlock><HighlightBlock as="p" tier="important" className="mb-4">Clarify the product promise, the non-negotiable correctness boundary, the main actor, and the failure mode users would actually notice first.</HighlightBlock><p>Token Streaming Buffer is an implementation-heavy low-level design problem. A principal-level answer must define authoritative state, client projections, lifecycle transitions, failure behavior, privacy boundaries, abuse controls, cost limits, rollback, and observability.</p><p>The ordered stream cursor and accumulated token projection are authoritative inside one response generation; raw byte chunks are transport fragments, not semantic boundaries.</p><ArticleImage src="/diagrams/system-design-problems/low-level-design/ai-modern-systems/token-streaming-buffer-runtime.svg" alt="Token Streaming Buffer runtime lifecycle" caption="Runtime lifecycle with authority boundaries and observable checkpoints." /></section>
      <section><h2>Core Concepts</h2><HighlightBlock as="p" tier="crucial" className="mb-4">Core interview invariant: the design must preserve correctness under latency, concurrency, partial failure, and changing permissions.</HighlightBlock><HighlightBlock as="p" tier="important" className="mb-4">Name the source of truth, derived state, speculative state, cache state, and audit or telemetry state separately; collapsing them hides most real design bugs.</HighlightBlock><HighlightBlock as="p" tier="important" className="mb-4">For Design a Token Streaming Buffer, the interviewer is checking whether you can defend why each subsystem exists, not just list components in a diagram.</HighlightBlock><p>The retained deep dive below covers the topic-specific implementation mechanics.</p>
      <h2>Why a Dedicated Streaming Buffer Layer Matters</h2>
      <p>
        The journey from a language model generating tokens on a GPU to characters appearing on a user's screen involves several layers of transformation, each with its own buffering concerns. Raw bytes arrive over TCP in segments whose boundaries are determined by network conditions. Those bytes must be decoded from UTF-8, parsed from the LLM provider's SSE or chunked-encoding format into individual token payloads, accumulated so that the render layer receives useful amounts of text per update, and then released to React state in synchronization with the browser's paint schedule. Without a deliberate buffer layer managing this pipeline, each of these concerns bleeds into the others, producing code that is simultaneously inefficient and fragile.
      </p>
      <HighlightBlock as="p" tier="important">
        The token streaming buffer system is the component responsible for absorbing the raw byte stream from the network, parsing it into structured token deltas, accumulating those deltas into batches of appropriate size, and flushing batches to the render layer at a rate that maximizes display smoothness without introducing perceptible latency. At 100 tokens per second, naive per-token React state updates produce 100 reconciliation cycles per second. With a properly designed buffer layer, that number drops to fewer than 60 — one per animation frame — while first-token display latency remains under 20 milliseconds.
      </HighlightBlock>
      <p>
        This article examines each stage of the pipeline in depth: the Fetch ReadableStream API and its reader/read-loop mechanics, TextDecoder's streaming mode and its handling of multi-byte character boundaries, SSE parsing from first principles, the exact wire formats of OpenAI and Anthropic streaming responses, buffering strategies including ring buffers and deques for backpressure, the drip-effect controlled release pattern, Web Worker offloading for parse-intensive workloads, the TransformStream composable pipeline pattern, error handling within the stream, and testing strategies for streaming components.
      </p>
<h2>The Fetch ReadableStream API in Depth</h2>
      <p>
        When you call fetch and the response body is a streaming HTTP response (either chunked transfer encoding or an EventSource-compatible stream), response.body is a ReadableStream object. A ReadableStream is a pull-based interface — data flows only when the consumer actively requests it by calling the stream's reader. This pull model is fundamental to understanding backpressure: if the consumer stops pulling, the TCP receive buffer fills up, and the sender's transmission is naturally throttled without any explicit flow-control signaling.
      </p>
      <p>
        Obtaining a reader is done by calling response.body.getReader(), which returns a ReadableStreamDefaultReader. This locks the stream to the reader — no other reader can be attached until this one is released. The reader exposes a read() method that returns a Promise resolving to a ReadableStreamReadResult, an object with two fields: done (a boolean) and value (a Uint8Array when done is false, or undefined when done is true). The standard consumption loop awaits reader.read() in a while(true) loop, breaks on done === true, and processes the Uint8Array value on each iteration.
      </p>
      <HighlightBlock as="p" tier="important">
        Cancellation of a ReadableStream reader is performed by calling reader.cancel() rather than simply stopping the read loop. reader.cancel() signals upstream that no more data is needed, allowing the browser to abort the underlying network request. If you just stop calling reader.read() without cancelling, the connection remains open and the browser continues downloading data into the receive buffer indefinitely, wasting bandwidth and keeping the server connection alive. When using AbortController alongside a ReadableStream, the fetch itself is aborted via the controller's signal, which causes the next reader.read() to reject with an AbortError. The cleanup code in the catch block should call reader.releaseLock() to allow the underlying stream to close cleanly.
      </HighlightBlock>
      <p>
        The read loop must also handle the case where the readable stream is closed by the server without sending a done signal through the SSE protocol layer (for example due to a network interruption). In this case, reader.read() resolves with done === true immediately. Code that only checks done === true at the end of processing may miss the opportunity to detect an unexpected early termination. A robust implementation records whether a protocol-level termination marker (the DONE sentinel in OpenAI's format, or the message_stop event in Anthropic's format) was received, and if the stream ends without that marker, treats the termination as an error rather than a successful completion.
      </p>

      <h2>TextDecoder: Streaming Mode and Multi-Byte Boundaries</h2>
      <p>
        The Uint8Array chunks from reader.read() must be converted to JavaScript strings before SSE parsing can proceed. TextDecoder provides this conversion, but it must be instantiated with specific options to handle streaming correctly. The default TextDecoder instantiation (new TextDecoder()) processes each Uint8Array in isolation — any multi-byte UTF-8 sequence that happens to be split across two chunk boundaries produces a replacement character (the Unicode replacement character U+FFFD) for the bytes in the first chunk.
      </p>
      <HighlightBlock as="p" tier="crucial">
        To handle multi-byte character boundaries correctly, instantiate TextDecoder with the stream option: new TextDecoder("utf-8", then pass options with stream set to true). This stateful instantiation maintains a partial-character buffer between decode calls. If the last byte of a chunk is the first byte of a three-byte UTF-8 sequence, the streaming decoder holds it in its internal buffer and waits for the remaining bytes in the next chunk's decode call before emitting the complete character. This is essential for any content that may include non-ASCII characters — code comments in Japanese, responses in Arabic, mathematical symbols — and silently broken without the streaming option. The same decoder instance must be reused across all chunks of a single response; creating a new TextDecoder for each chunk defeats the streaming mode.
      </HighlightBlock>
      <p>
        BOM handling is a related concern. The UTF-8 Byte Order Mark (the three-byte sequence 0xEF, 0xBB, 0xBF) sometimes appears at the beginning of text streams from certain Windows-based or .NET-based servers. TextDecoder with the ignoreBOM option set to false (the default) strips this sequence automatically. If you see a spurious leading character in your first SSE event parse, a BOM is a likely culprit. Setting ignoreBOM to true preserves the BOM bytes in the output, which can be useful if you need to detect encoding from the BOM explicitly, but for LLM streaming APIs, the default BOM-stripping behavior is correct.
      </p>

      <h2>SSE Parsing from First Principles</h2>
      <p>
        Server-Sent Events is a protocol layered on top of HTTP. The SSE wire format is simple but has several edge cases that production parsers must handle. An SSE stream consists of events separated by blank lines (two consecutive newlines). Each event consists of one or more fields, each field being a key-value pair on a single line formatted as the field name, a colon, an optional space, and the field value. The four standard field names are data (the event payload), event (an optional event type name), id (an optional event ID for reconnection), and retry (a suggested reconnection interval in milliseconds).
      </p>
      <p>
        A line beginning with a colon is treated as a comment and discarded. A field name with no colon is treated as a field with an empty value. A single event may span multiple data lines — each data line's value is appended to the event's data field with a newline separator between them, and the combined value is delivered when the blank line signals event completion. Building a robust SSE parser from scratch requires maintaining state across chunk boundaries: the parser needs to know whether it is in the middle of a field name, in the middle of a field value, between fields within an event, or between events.
      </p>
      <HighlightBlock as="p" tier="important">
        A production-quality SSE parser maintains a line accumulator (because line boundaries may not align with chunk boundaries), an event object being assembled (with data, event type, and id fields), and a complete-events queue. The processing sequence for each newly decoded string is: split on newline characters, append the first piece to any partial line from the previous chunk, process each complete line through the field parser, and retain the last piece (which may be an incomplete line) in the partial-line buffer for the next iteration. When a blank line is encountered, the accumulated event object is dispatched to the consumer and the event accumulator is reset. This line-accumulation pattern ensures correct parsing even when chunk boundaries fall in the middle of a field value or between the final field and the blank line terminator.
      </HighlightBlock>
      <p>
        The id field has a specific role in reconnection. When the client reconnects after a dropped SSE connection using the EventSource API, it sends the last received event ID in a "Last-Event-ID" HTTP header. The server uses this to resume the stream from the point of interruption. In a custom fetch-based SSE implementation, you must track the last received id manually and include it in the "Last-Event-ID" header if implementing reconnection. For LLM streaming APIs, reconnection from a specific event ID is generally not supported (the API generates a fresh response on each request), but tracking the last id is still useful for logging and debugging stream interruptions.
      </p>

      <h2>OpenAI Streaming Format</h2>
      <p>
        The OpenAI Chat Completions streaming API sends a sequence of SSE events where each event's data field is a JSON object representing a partial response chunk. The outer JSON structure contains an id (the completion ID), object ("chat.completion.chunk"), created (a Unix timestamp), model (the model that generated the chunk), and choices (an array of choice objects). Each choice has an index, a delta object, and a finish_reason field (null during streaming, set to a terminal value on the last chunk).
      </p>
      <HighlightBlock as="p" tier="important">
        The delta object carries the incremental content for that chunk. For text completions, delta.content contains the token string. For the first chunk of a response, delta.role is set to "assistant" (subsequent chunks omit this field). For function calling, delta.function_call or delta.tool_calls carries incremental function call arguments. A robust parser handles the case where delta.content is null (which occurs on the first chunk when only role is set) by treating it as an empty string rather than appending "null" to the display text. The terminal sentinel is a data field containing exactly "[DONE]" — not a JSON object but the literal four-character string "[DONE]". The parser must detect this exact string and treat it as stream termination, not attempt to JSON.parse it.
      </HighlightBlock>
      <p>
        The finish_reason on the final content chunk (just before the [DONE] sentinel) indicates the termination reason. The value "stop" means natural completion. "length" means the response was truncated at the max_tokens limit — this should be surfaced to the user as a truncated response indicator rather than appearing as a normal completion. "content_filter" means the safety system intervened. "tool_calls" means the model completed a tool call request. "function_call" is the legacy equivalent of "tool_calls." Each reason may warrant different post-stream UI behavior.
      </p>

      <h2>Anthropic Streaming Format</h2>
      <p>
        The Anthropic Messages streaming API uses a richer event-type system within SSE. Each SSE event has both an "event:" field specifying the event type and a "data:" field with a JSON payload. The sequence of event types for a typical streaming response follows a defined lifecycle: "message_start" (contains the message id and metadata), "content_block_start" (signals the beginning of a content block, with an index and type field), "content_block_delta" (carries incremental content for a specific content block), "content_block_stop" (signals the end of a content block), "message_delta" (carries updated stop_reason, stop_sequence, and output token count at the end of the message), and "message_stop" (the terminal event, signaling the stream is complete).
      </p>
      <p>
        The index field on content_block_delta events is critical for multi-content-block responses. A message with both a text block and a tool use block generates interleaved deltas referencing different indices. A parser that ignores the index and appends all delta text together will produce garbled output by mixing tool call JSON with prose text. The correct implementation maintains a map from content block index to a string accumulator, and routes each delta to the appropriate accumulator based on its index field.
      </p>
      <HighlightBlock as="p" tier="important">
        The delta payload structure for text blocks within content_block_delta events is an object with type set to "text_delta" and a text field containing the incremental string. For tool use blocks, the delta type is "input_json_delta" and the partial_json field carries incremental JSON characters for the tool input arguments. Processing input_json_delta deltas requires JSON stream parsing if you want to display partially-formed tool arguments — otherwise buffer all input_json_delta deltas until the content_block_stop event and parse the complete JSON at once. The Anthropic format's explicit event lifecycle is more verbose than OpenAI's format but provides cleaner structural boundaries for multi-block responses.
      </HighlightBlock>

      <h2>Buffering Strategy: Ring Buffers, Deques, and Backpressure</h2>
      <p>
        The simplest token buffer is a JavaScript string that grows via concatenation: accumulator += delta.text on each parsed event. V8's string concatenation is optimized for this pattern — short string appends are O(1) amortized due to rope data structures. For text rendering use cases, this simple concatenator is the correct choice. The buffer is a single string, the flush operation copies the full current string to React state, and memory consumption is proportional to response length.
      </p>
      <p>
        Ring buffers (circular queues) are appropriate when individual token objects need to be processed separately rather than concatenated — for example, in an audio synthesis pipeline where each token must be submitted to a text-to-speech service individually, or in an analytics pipeline counting token arrivals per time window. A ring buffer of fixed capacity N holds the last N tokens. When the buffer is full and a new token arrives, the oldest entry is overwritten. This provides bounded memory regardless of response length, at the cost of losing old entries if the consumer falls behind.
      </p>
      <HighlightBlock as="p" tier="important">
        Backpressure is the mechanism by which a slow consumer signals a fast producer to slow down. In the browser, the ReadableStream protocol implements implicit backpressure through the pull model: if the consumer stops calling reader.read(), the browser stops reading from the TCP receive buffer, which eventually causes the OS kernel's receive buffer to fill, which causes TCP to apply flow control to the sender. This means backpressure is implemented in the streaming buffer by simply pausing the read loop — stopping the while(true) iteration until the render layer has drained its queue. Implement this with a semaphore: a boolean or counter that the flush mechanism sets when the render layer is busy and the read loop checks before each reader.read() call. If the semaphore indicates the render layer is backed up, the read loop awaits a promise that the flush mechanism resolves when rendering completes.
      </HighlightBlock>
      <p>
        For LLM streaming at typical rates (20 to 100 tokens per second), the render layer's capacity — 60 flushes per second via rAF, each capable of updating thousands of characters — far exceeds the production rate. Backpressure is rarely triggered in practice unless the device is severely resource-constrained (low-end mobile, heavy concurrent JavaScript workloads). Implementing backpressure adds code complexity for a rare scenario. The practical engineering decision is to implement a simple high-watermark check: if the accumulator exceeds 50,000 characters (representing several minutes of continuous streaming), force a flush and log a warning. This catches pathological cases without adding the complexity of full flow-control signaling.
      </p>

      <h2>The Drip Effect: Controlled Release Rate</h2>
      <p>
        The rAF-gated flush mechanism provides frame-aligned rendering, but there is a subtlety in how accumulated text is released. If 500 tokens arrive in a single network burst — which can happen when a server is replaying a cached response or when network conditions cause coalescing — flushing all 500 tokens in a single rAF callback produces a large text jump. The user sees a blank placeholder followed by a wall of text appearing at once, destroying the streaming illusion.
      </p>
      <HighlightBlock as="p" tier="important">
        The drip effect is a controlled release rate that limits how many characters are flushed per animation frame regardless of how many are available in the accumulator. Instead of flushing the entire accumulator each frame, flush at most N characters per frame where N is chosen to produce a visually smooth display speed — typically 200 to 400 characters per frame (roughly 1,000 to 2,000 words per second of displayed text, which appears as fast typing). If the accumulator contains more than N characters, the next frame picks up where the previous one left off. This means the display intentionally lags behind the accumulator when bursts occur, smoothing the visual presentation. The drip rate should be configurable: faster for users who prefer maximum speed, slower for users with cognitive processing preferences or accessibility needs.
      </HighlightBlock>
      <p>
        The drip effect introduces a tradeoff: for short responses where the entire content arrives quickly, the drip rate determines how long the user waits to see the full response. A 200-token response arriving instantly but displayed at 300 characters per frame at 60fps takes 200 tokens times 4 characters per token divided by 300 characters per frame divided by 60 frames per second — approximately 45 milliseconds of display time. This is imperceptible. For a 5,000-token response arriving instantly, the drip display takes approximately 1.1 seconds. That may be desirable for the streaming effect or undesirable for users who prefer immediate full display. Adaptive drip rate — starting slow and accelerating as the accumulator depth grows — provides a reasonable middle ground.
      </p>

      <h2>Web Worker Offloading</h2>
      <p>
        The SSE parsing and JSON parsing steps in the streaming pipeline involve string processing that, at high token rates or with large SSE payloads, can consume measurable main-thread time. For a standard LLM API response this is not a concern — parsing 100 tokens per second of JSON objects takes microseconds of CPU time. However, in scenarios where the LLM output includes large structured payloads (function call arguments with multi-kilobyte JSON objects, or verbose structured output schemas), the parsing step can take 1 to 3 milliseconds per event, approaching the frame budget.
      </p>
      <p>
        Moving the parse loop to a Web Worker offloads this work from the main thread. The fetch and ReadableStream reading must remain on the main thread (the Fetch API is not available in Workers in all browsers, though support is improving). The pattern is to read chunks on the main thread, transfer Uint8Array chunks to the Worker via postMessage with the transferable option (which transfers the buffer's ownership without copying), perform TextDecoding, SSE parsing, and JSON parsing in the Worker, and post the parsed token delta objects back to the main thread via MessageChannel. MessageChannel provides lower latency than postMessage to the worker's message queue because it uses a dedicated channel rather than the shared Worker message queue.
      </p>
      <HighlightBlock as="p" tier="important">
        The transferable transfer of Uint8Array buffers to the Worker is critical for performance. Without transferable transfer, postMessage serializes the typed array by copying its bytes — an O(n) copy per chunk. With transferable transfer, the underlying ArrayBuffer's ownership transfers to the Worker in O(1) time, and the original Uint8Array on the main thread becomes detached (zero-length). The Worker receives an undetached view of the transferred buffer. This zero-copy transfer is what makes the Worker pattern practical for high-throughput streaming — a naive postMessage copy would negate the performance benefit of offloading.
      </HighlightBlock>

      <h2>TransformStream: Composable Pipeline Architecture</h2>
      <p>
        The Web Streams API's TransformStream class provides a clean mechanism for building composable streaming pipelines. A TransformStream has a writable side (where bytes go in) and a readable side (where transformed output comes out). Multiple TransformStreams can be chained using pipeThrough, creating a declarative pipeline that processes data through a sequence of transforms without manual loop management.
      </p>
      <p>
        For the token streaming use case, a composable pipeline can be structured as four stages. The first stage takes the raw response body ReadableStream and applies a TextDecoder transform that converts Uint8Array chunks to decoded strings — this is a TextDecoderStream, available natively in modern browsers. The second stage is a custom LineAccumulator TransformStream that accumulates decoded strings and emits complete lines (splitting on newline, buffering incomplete lines across chunk boundaries). The third stage is a custom SSEParser TransformStream that receives complete lines, accumulates them into SSE events (splitting on blank lines), and emits parsed event objects with data, type, and id fields. The fourth stage is a custom TokenParser TransformStream that receives SSE event objects, JSON-parses the data field, extracts the token delta from the provider-specific structure, and emits plain token delta strings.
      </p>
      <HighlightBlock as="p" tier="crucial">
        This four-stage pipeThrough chain produces a ReadableStream of token delta strings. The consumer of this final stream calls getReader() on it and accumulates the deltas in the string accumulator for rAF-gated flushing. The composability benefit is testability: each TransformStream stage can be tested in isolation by feeding a ReadableStream of test inputs and asserting the output ReadableStream's values. The pipeline can also be extended by inserting additional stages — for example, a SentenceDetector stage that emits sentence-boundary events alongside token deltas, useful for audio synthesis pipelines. The pipeThrough API handles backpressure propagation automatically: if the downstream readable side is not being consumed, the upstream writable side applies backpressure to the source.
      </HighlightBlock>

      <h2>Error Handling Within the Stream</h2>
      <p>
        Errors in a streaming pipeline can originate at any stage: the network layer, the HTTP response status, the SSE wire format, or the JSON payload. Each requires different handling. HTTP error status codes (400, 429, 500) are detected before the read loop begins by inspecting response.status and response.ok. A non-OK response status means the body contains an error payload rather than a streaming response. Read the error body (it is usually small, so a single response.json() call is appropriate) and surface the structured error message to the UI before starting any streaming state.
      </p>
      <p>
        Mid-stream network errors manifest as rejected promises from reader.read(). The error type distinguishes the cause: AbortError indicates intentional cancellation, TypeError with a specific message indicates a network failure (connection dropped, TCP reset). A robust stream loop catches errors around the read call, distinguishes AbortError from network errors, and transitions the message to the appropriate terminal state — stopped for intentional abort, error for network failure.
      </p>
      <HighlightBlock as="p" tier="important">
        Malformed JSON recovery is necessary because some SSE event payloads may be malformed — partial JSON objects, unexpected nulls, or encoding artifacts from proxy servers that modify the response body. Wrap each JSON.parse call in a try-catch. On a parse error, log the raw SSE event data (for debugging), increment a malformed-event counter, and skip the event rather than aborting the entire stream. If malformed events accumulate (more than 5 in a single response), abort the stream and surface an error — this pattern distinguishes occasional proxy artifacts from systematic format incompatibilities. For retry with the last event ID, include the most recently successfully parsed event's id in the Last-Event-ID header of the retry request, allowing the server to resume from a known-good position if it supports this.
      </HighlightBlock>

      <h2>Testing Streaming Components</h2>
      <p>
        Testing components that consume streaming data requires creating mock ReadableStreams that deliver data in controlled sequences. In Jest or Vitest, construct a mock ReadableStream by passing a start function to the ReadableStream constructor that uses a controller to enqueue chunks on a schedule. To simulate a bursty network, enqueue multiple chunks synchronously before returning control to the event loop. To simulate slow delivery, use setTimeout to enqueue chunks with delays. To simulate a mid-stream error, call controller.error() after delivering partial data.
      </p>
      <p>
        Testing the SSE parser in isolation requires feeding a stream of Uint8Array-encoded SSE text and asserting that the emitted parsed event objects have correct data, type, and id fields. Test specifically: events split across chunk boundaries (the event data line arrives in two chunks), multi-line data fields (multiple data: lines that should be concatenated with newlines), comment lines (should be ignored), and the [DONE] sentinel (should trigger stream end without being parsed as JSON). Testing each of these boundary conditions individually is much simpler with the TransformStream architecture, where each stage has a clean test surface.
      </p>
      <HighlightBlock as="p" tier="important">
        Testing the batching behavior of the rAF flush loop requires controlling time in the test environment. Vitest and Jest both support fake timers that allow advancing time programmatically. However, requestAnimationFrame is not available in the test environment (jsdom does not implement it). Mock requestAnimationFrame with a synchronous stub that invokes the callback immediately, then test that the accumulator state before the mock rAF call is non-empty and empty after, confirming the flush mechanism works. For integration tests that verify the full pipeline from mock ReadableStream through render, use React Testing Library's findByText with async matchers to wait for text to appear in the rendered output after the mock rAF callback fires. Avoid testing specific batching timing in integration tests — test the eventual result rather than the intermediate states to keep tests resilient to rAF timing changes.
      </HighlightBlock>
      <p>
        Load testing the streaming buffer requires driving the pipeline at rates far exceeding typical LLM output: 10,000 tokens per second, sustained for 30 seconds. Create a mock stream that enqueues pre-encoded SSE events as fast as the event loop allows. Measure frame rate using a requestAnimationFrame timestamp-delta monitor running in parallel. A correctly implemented buffer layer maintains 60fps (or very close to it) during load because the rAF flush loop is the only path from the accumulator to the render layer, and it executes at most once per frame. If frames drop during load testing, the rAF callback is taking more than 16ms, indicating the React render triggered by the setState is doing too much work — typically caused by expensive markdown re-parsing on each flush rather than diffing from the previous accumulated text.
      </p>





</section>
      <section><h2>Architecture &amp; Flow</h2><HighlightBlock as="p" tier="crucial" className="mb-4">Architecture decisions to make explicit: state model, API contracts, cache policy, async workflow, authorization, rollout, and rollback.</HighlightBlock><HighlightBlock as="p" tier="important" className="mb-4">Walk the hard path end to end: permission check, input validation, async work, timeout or partial failure, user-visible fallback, telemetry, and rollback.</HighlightBlock><HighlightBlock as="p" tier="important" className="mb-4">Call out which path is synchronous, which path is asynchronous, which artifacts are immutable, and which updates may arrive out of order.</HighlightBlock><p>Model the runtime as explicit transitions: decode bytes to frame SSE to parse delta to queue text to rAF flush. Every asynchronous completion carries a generation, version, or correlation id so stale work can be rejected safely. Separate user intent, untrusted transport input, validated intermediate state, durable truth, and derived UI projection.</p><ArticleImage src="/diagrams/system-design-problems/low-level-design/ai-modern-systems/token-streaming-buffer-recovery.svg" alt="Token Streaming Buffer failure containment and rollback" caption="Failure containment, rollback controls, and audit evidence." /></section>
      <section><h2>Trade offs &amp; Comparison</h2><HighlightBlock as="p" tier="crucial" className="mb-4">Trade-off lens: optimize for correctness and recoverability first, then latency, cost, developer velocity, and UX polish.</HighlightBlock><HighlightBlock as="p" tier="important" className="mb-4">Compare centralized vs distributed ownership, server-authoritative vs client-speculative state, and strong consistency vs eventual consistency where the product allows it.</HighlightBlock><HighlightBlock as="p" tier="important" className="mb-4">A staff/principal answer should state what gets worse when the simpler design is chosen, and what operational burden appears when the more robust design is chosen.</HighlightBlock><p>The ordered stream cursor and accumulated token projection are authoritative inside one response generation; raw byte chunks are transport fragments, not semantic boundaries.</p><p>The major pressure points are split UTF-8 code points, split SSE frames, malformed JSON, provider format variation, backpressure, burst delivery, cancellation, and missing terminal markers. Prefer explicit bounded degradation over hidden correctness loss. Caches and optimistic UI improve latency only when invalidation, expiry, cancellation, and stale-response rejection are designed with them.</p></section>
      <section><h2>Best practices</h2><HighlightBlock as="p" tier="crucial" className="mb-4">Best practice: make the invariant testable through explicit states, typed events, idempotent operations, scoped permissions, and observable transitions.</HighlightBlock><HighlightBlock as="p" tier="important" className="mb-4">Instrument the system around user-visible outcomes: latency, error rate, fallback rate, conversion, stale-state duration, and rollback success.</HighlightBlock><HighlightBlock as="p" tier="important" className="mb-4">Keep escape hatches governed. Temporary bypasses, manual overrides, and emergency controls should have owner, reason, expiry, and audit evidence.</HighlightBlock><p>Use typed state machines, immutable identifiers, bounded queues, idempotent writes, cancellation propagation, versioned contracts, redacted logs, privacy-aware retention, and stage-level metrics. Test stale callbacks, retries, partial failure, duplicate input, slow consumers, access-control changes, rollback, and degraded dependencies.</p></section>
      <h3>Principal defense: consistency, cost, and rollback</h3><p>State the consistency boundary explicitly. User intent, request generation, model or retrieval bundle version, and terminal status belong to one attributable execution. Streaming tokens and previews are derived projections; durable history, approved revisions, feedback events, and citation access checks are authoritative records. Reject late generations after cancellation or supersession even when transport continues to deliver bytes.</p><p>Defend cost as a product constraint, not an infrastructure footnote. Bound context, retrieval fan-out, concurrent generations, retry budgets, preview depth, and retained history. Record bundle id, latency by stage, token or candidate volume, refusal reason, and fallback outcome. Roll back by immutable revision or alias swap so a bad prompt, model, parser, or retrieval policy can be isolated without rewriting evidence.</p><h3>Trade-off under interview pressure</h3><p>The central trade-off is responsiveness versus attributable correctness. Streaming, caching, and optimistic previews reduce perceived latency, but each adds stale-generation and rollback paths. Prefer a slightly slower guarded projection over an answer, dataset, or generated tree whose version and provenance cannot be defended.</p><section><h2>Common Pitfalls</h2><HighlightBlock as="p" tier="crucial" className="mb-4">Most dangerous failure modes: stale state, hidden partial failure, unbounded retries, ownership ambiguity, and missing observability.</HighlightBlock><HighlightBlock as="p" tier="important" className="mb-4">Do not present a happy-path component graph as the full design. Interviewers will push on retries, stale data, permission changes, overload, deletion, and incident recovery.</HighlightBlock><HighlightBlock as="p" tier="important" className="mb-4">Avoid vague words like scalable, secure, and reliable unless you attach them to concrete limits, policies, SLOs, and failure handling behavior.</HighlightBlock><p>Avoid treating derived UI as authoritative, accepting stale asynchronous completion, hiding unsupported states, leaking sensitive payloads into telemetry, retrying non-idempotent work blindly, and adding expensive AI calls without latency and cost budgets.</p></section>
      <section><h2>Real-world use cases</h2><HighlightBlock as="p" tier="crucial" className="mb-4">Real-world relevance: the same design shows up when teams need a reusable, observable, and governable product capability rather than a one-off screen.</HighlightBlock><HighlightBlock as="p" tier="important" className="mb-4">Tie the article back to adoption: how multiple teams integrate, how the system rolls out gradually, how migrations happen, and how operators know the feature is healthy.</HighlightBlock><p>This design applies to LLM text streaming, tool-call argument assembly, agent status feeds, and any frame-budgeted incremental response UI.</p></section>
      <section><h2>Common interview question with detailed answer</h2><HighlightBlock as="p" tier="crucial" className="mb-4">Strong answer structure: define the invariant, draw the state/data flow, identify the bottleneck, handle failure, name trade-offs, and close with metrics and tests.</HighlightBlock><HighlightBlock as="p" tier="important" className="mb-4">If pressed for staff/principal depth, discuss ownership boundaries, operational runbooks, migration plan, abuse prevention, and how the design fails safely.</HighlightBlock><h3>What state is authoritative, and what may remain optimistic?</h3><p>The ordered stream cursor and accumulated token projection are authoritative inside one response generation; raw byte chunks are transport fragments, not semantic boundaries.</p><h3>What fails first under scale, abuse, or degraded dependencies?</h3><p>Pressure-test split UTF-8 code points, split SSE frames, malformed JSON, provider format variation, backpressure, burst delivery, cancellation, and missing terminal markers. Bound queues, reject stale transitions, preserve provenance, and make degraded behavior explicit rather than silently returning misleading UI.</p><h3>How do you recover or roll back without corrupting user-visible state?</h3><p>retain decoder state, buffer partial frames, cap malformed events, abort stale generations, expose partial output, and instrument first-token and flush latency</p><h3>How do you make the design observable in production?</h3><p>Emit redacted correlation ids, stage latency, terminal status, retry count, rejection reason, version identifiers, queue depth, and recovery outcome. Alert on ratios and tail latency, not only aggregate success counts.</p><h3>How do you defend the architecture against a simpler alternative?</h3><p>Start with the simplest state machine that preserves authority boundaries. Add asynchronous stages, caching, workers, or secondary indexes only when measured latency, scale, or isolation requirements justify their operational cost.</p></section>
      <section><h2>References</h2><ul><li><a href="https://developer.mozilla.org/en-US/docs/Web/API/Streams_API" target="_blank" rel="noreferrer">MDN Streams API</a></li><li><a href="https://developer.mozilla.org/en-US/docs/Web/API/AbortController" target="_blank" rel="noreferrer">MDN AbortController</a></li><li><a href="https://owasp.org/www-project-cheat-sheets/" target="_blank" rel="noreferrer">OWASP Cheat Sheet Series</a></li><li><a href="https://www.w3.org/WAI/ARIA/apg/" target="_blank" rel="noreferrer">WAI-ARIA Authoring Practices</a></li></ul></section>
    </ArticleLayout>
  );
}
