"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-dynamic-config-management-ui",
  title: "Design a Dynamic Config Management UI (like Consul / LaunchDarkly Config)",
  description:
    "Architecture for a dynamic configuration management system: namespaced key-value store with type-enforced schemas and environment-scoped values, immutable versioned rows with diff tracking and one-click rollback, approval workflow for production changes, Redis pub/sub fan-out pushing config deltas to all subscribed service pods via SSE within 500ms, polling fallback every 30 seconds with version watermark, service-side local in-memory cache with 5-minute TTL as circuit-breaker, and immutable audit log recording who changed what value in which environment from which IP address.",
  category: "high-level-design",
  subcategory: "feature-configuration-admin-systems",
  slug: "dynamic-config-management-ui",
  wordCount: 4900,
  readingTime: 28,
  lastUpdated: "2026-05-14",
  tags: ["hld", "config-management", "consul", "feature-flags", "redis", "sse", "audit-log", "versioning"],
  relatedTopics: ["remote-app-configuration-system", "kill-switch-emergency-control-panel"],
};

export default function DynamicConfigManagementUiArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A dynamic configuration management system allows engineering and operations teams to change application behavior at runtime without deploying new code. Instead of embedding configuration values (feature flags, timeouts, rate limits, UI copy, API endpoint URLs) in environment variables or deployment artifacts — which require a full redeploy to change — a config management system stores these values in a central store that services read at runtime. When a value changes, all running service instances receive the new value within seconds.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The core challenges are: (1) correctness — a misconfigured value (wrong type, out-of-range number, malformed JSON) deployed to production can take down services; (2) safety — changes to production config must go through an approval workflow, and any bad change must be reversible in seconds; (3) propagation latency — after an engineer commits a config change, all service instances must receive the new value quickly (sub-second for critical changes); (4) reliability — the config system must not become a single point of failure; services must continue operating if the config API is temporarily unavailable, using a locally-cached copy.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Config write pipeline (validation, approval, versioning), fan-out push to services, service-side read and caching, rollback, and audit logging. Not in scope: feature flag targeting (per-user rollouts — covered in the remote app configuration article) or kill-switches (covered separately).</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Namespaced key-value store with type enforcement:</strong> Configs are organized in namespaces (e.g., "payments", "search", "api-gateway"). Each config key has a registered schema: name, type (string, int, float, boolean, JSON), description, allowed range (for numerics — e.g., timeout must be 100ms–30,000ms), and environment (dev, staging, prod). On write, the API validates the new value against the schema before persisting: type coercion check (e.g., "true" can be coerced to boolean true; "abc" cannot be coerced to int — returns 400), range validation (e.g., max_connections must be 1–10,000), and JSON schema validation for complex values. Schema registration is a one-time operation done when a config key is first introduced. Unregistered keys cannot be written — this prevents typos creating phantom keys that no service reads.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Immutable versioned rows with diff:</strong> Every config write creates a new row in the config_versions table: (versionId UUID, namespace, key, value, environment, changedBy userId, changedAt timestamptz, reason text, previousVersionId UUID). The current value for a key is always the most recent version row. Previous rows are never updated or deleted — they form an immutable version history. The admin UI shows a diff between any two versions (using a standard text diff algorithm for string values; a structured diff for JSON values). Version IDs are monotonically increasing per key — the current version number is exposed as an ETag for conditional reads. The diff view is essential for post-incident analysis: "which config changed just before the outage started?"</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Approval workflow for production:</strong> Config changes to the production environment require approval from a second engineer (the "four-eyes" principle). Flow: engineer submits a change (status = 'pending_approval'); the system sends a Slack message and email to all on-call approvers; an approver reviews the diff in the UI and approves or rejects; on approval, the system persists the change and triggers fan-out. Changes to dev and staging environments are auto-approved (no workflow — faster iteration). The approval record (who approved, when, their comment) is stored alongside the version row. Time-to-live on pending approvals: 24 hours — if not approved within 24 hours, the pending change expires and the engineer must resubmit (prevents stale approvals from being accidentally applied during incidents).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Fan-out push via Redis pub/sub and SSE:</strong> When a config change is committed, the Config API publishes a delta event to Redis pub/sub: PUBLISH config:&#123;namespace&#125; &#123;key, newValue, versionId&#125;. All Config API pods subscribe to this channel. Each pod maintains a pool of SSE connections from service instances — services connect to GET /config/stream?namespace=payments and receive a persistent SSE connection. When a pod receives a pub/sub event, it fans out the delta to all SSE connections it holds. Service instances update their in-memory config map immediately on receiving the SSE event, without restarting. The SSE approach avoids the overhead of long-polling (each service pod holds one SSE connection to one Config API pod, not one connection per config key).</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Polling fallback with version watermark:</strong> Not all service instances maintain a persistent SSE connection (some are in restricted network environments, some use serverless functions that start cold for each request). For these, a polling fallback is provided: GET /config/&#123;namespace&#125;?since=&#123;versionId&#125; returns all keys whose version is newer than the provided versionId. Services poll every 30 seconds. The version watermark (the last versionId the service has seen) prevents redundant data transfer — if no config has changed since the service's last poll, the response is HTTP 304 Not Modified with no body. The polling interval (30 seconds) is a configurable default; services can request shorter intervals (minimum 5 seconds, to prevent polling stampedes) for namespaces that contain time-sensitive config (e.g., rate limits during a traffic spike).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Service-side local cache as circuit-breaker:</strong> Services maintain an in-process copy of their config namespace. On startup, the service fetches the full namespace from the Config API and stores it in memory. This local copy is used for all config reads — the service never makes a synchronous config API call on the hot path (doing so would add network latency and create a dependency on the config service availability). The local cache TTL is 5 minutes: after 5 minutes without a successful sync (either SSE event or poll response), the service continues serving requests using the stale local copy and logs a "config service unreachable" warning. This circuit-breaker behavior ensures that a Config API outage does not propagate to service outages. The 5-minute TTL is generous enough to allow the Config API to restart or failover without causing a service cascade failure.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Environment isolation and promotion:</strong> Each config key has separate values per environment (dev, staging, prod). The admin UI supports a "promote" action: copy the current staging value to prod as a pending change (which then goes through the approval workflow). This prevents manual copy-paste errors when promoting a tested config value from staging to prod. Environments are isolated at the namespace level — a service in the production environment can only read prod values; it cannot read dev or staging values even if they share the same Config API cluster. Isolation is enforced by the API via the service's authentication token, which is scoped to a specific environment at token creation time.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Audit log and compliance:</strong> Every config change (write, approval, rejection, rollback) is appended to an immutable audit log table: (eventId, timestamp, actor userId, action ENUM, namespace, key, environment, oldValue, newValue, reason, sourceIp, userAgent). The audit table uses an INSERT-only database user (no UPDATE or DELETE). The audit log is exposed in the admin UI as a searchable timeline: "show all changes to the payments namespace in the last 7 days, sorted by time." For compliance requirements (SOC 2, ISO 27001), the audit log is exported to an immutable data store (S3 Object Lock) monthly. Audit queries: "who changed the rate_limit_per_second key?" and "what was the value of max_retry_count at 14:37 UTC on May 3?" (answered by selecting the most recent version row with changedAt &lt;= the query timestamp).</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="crucial">The system has three planes: the write plane (Admin UI → Config API → validation + approval → config_versions INSERT → Redis PUBLISH), the read/push plane (SSE connections from services → Redis SUB on Config API pods → fan-out on change; polling fallback every 30s), and the service runtime plane (in-process config map, updated by SSE events or polls, with 5-minute local TTL as circuit-breaker). The Config API is stateless and horizontally scalable — multiple pods, each with a Redis subscription and a pool of SSE connections. State lives in PostgreSQL (config_versions, audit_log) and Redis (current config cache, pub/sub).</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/feature-configuration-admin-systems/dynamic-config-management-ui.svg"
          alt="Dynamic config management: admin submits config change with validation and approval for prod; committed change triggers Redis PUBLISH to all Config API pods; pods fan out via SSE to connected service instances; services update in-memory config immediately; polling fallback every 30s with version watermark 304 short-circuit; local cache 5-minute TTL as circuit-breaker; rollback re-publishes old value as new version; immutable audit log records all changes."
          caption="Versioned immutable rows; approval gate for prod; Redis pub/sub + SSE fan-out &lt;500ms; 30s poll fallback with version watermark; 5-min local TTL circuit-breaker; one-click rollback; audit log INSERT-only"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Config Schema Registry</h3>
        <HighlightBlock as="p" tier="important">The schema registry stores the definition for each config key: namespace, key name, value type, description, allowed values (for enums), min/max (for numerics), JSON schema (for complex values), default value, and sensitivity flag (sensitive configs — API keys, connection strings — are stored encrypted and masked in the UI, showing only the last 4 characters). New keys are registered via PUT /config-schemas/&#123;namespace&#125;/&#123;key&#125; — this is a code review process (the schema definition is committed to a git repository and applied via a CI job, not editable through the admin UI). This prevents ad-hoc schema creation and ensures all config keys are documented. The schema registry is cached in Redis (TTL 5 minutes) — validation reads from Redis on every write, not from the database.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Rollback Implementation</h3>
        <HighlightBlock as="p" tier="important">Rolling back to a previous version is implemented as publishing the old value as a new version row — not by deleting the current version. This preserves the full version history and makes the rollback itself auditable (the audit log shows "rollback by alice@example.com to version 42, reason: 'outage post-deploy'"). The rollback API: POST /configs/&#123;namespace&#125;/&#123;key&#125;/rollback &#123;targetVersionId, reason&#125;. The server fetches the target version row, validates that the target value is still schema-valid (the schema may have changed since the target version was written — if the target value is no longer valid, the rollback is rejected with a 422 Unprocessable Entity and the operator must choose a different target version or write a new value manually). On success, a new version row is inserted with the old value and a reference to the targetVersionId, and the fan-out is triggered.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Sensitive Config Encryption</h3>
        <HighlightBlock as="p" tier="important">Configs marked as sensitive (API keys, database passwords, OAuth secrets) are encrypted at rest using envelope encryption: the config value is encrypted with a data encryption key (DEK) using AES-256-GCM; the DEK is encrypted with a key encryption key (KEK) stored in AWS KMS or HashiCorp Vault. The encrypted value is stored in the database; the DEK is stored alongside it (also encrypted). On read, the server decrypts the DEK using KMS and then decrypts the value. The admin UI never displays the full plaintext value — it shows a masked value (e.g., "••••••••abcd"). Decrypted values are never logged. Access to sensitive config values is separately audited (every read is logged, in addition to writes). Sensitive configs are not included in the SSE stream or polling responses — they are fetched via a separate authenticated endpoint that requires the service's identity certificate, not just the namespace token.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="crucial">Push (SSE) vs. poll: the SSE approach delivers config changes within milliseconds of a commit, which is critical for time-sensitive configs like rate limits or circuit breaker thresholds. The downside is connection management complexity — the Config API must maintain long-lived connections from all service instances, which requires careful connection timeout handling, reconnect logic, and load balancer configuration (the load balancer must not terminate idle SSE connections — long-lived HTTP connections require sticky sessions or connection-aware routing). The polling approach is simpler (no persistent connections) but introduces latency proportional to the polling interval (up to 30 seconds). Most systems use both: SSE for services that support it (server processes with long-running connections), polling for serverless functions and batch jobs that can't maintain persistent connections.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Centralized store vs. git-based config: an alternative to a custom config store is storing config values in a git repository (GitOps pattern). Each config change is a pull request — reviewable, diffable, and revertible via standard git tooling. The git repository is the source of truth; a sync daemon watches for commits and applies them to the running services. GitOps provides stronger audit trails (git history is tamper-evident) and familiar developer workflows. The downside is propagation latency (a git commit → CI pipeline → sync daemon cycle takes 2–5 minutes, vs. &lt;1 second for a Redis pub/sub push) and the lack of runtime type validation (git stores everything as text; type errors are caught at application startup, not at commit time). For organizations that need sub-second config propagation (dynamic rate limits, kill-switches), a centralized store with push is necessary. For organizations where the primary use case is managing application settings that change infrequently, GitOps is a simpler and more auditable choice.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A dynamic config management system requires: (1) namespaced key-value store with registered schemas — type, range, JSON schema validation on write; unregistered keys rejected; (2) immutable versioned rows — INSERT-only config_versions table, ETag per version, full diff history; (3) approval workflow for prod — four-eyes principle, Slack/email notification, 24-hour expiry on pending approvals; (4) Redis PUBLISH on commit → SSE fan-out to all subscribed service pods — &lt;500ms propagation; (5) polling fallback — GET /config/&#123;namespace&#125;?since=&#123;versionId&#125; every 30s; 304 Not Modified if no change; (6) service-side local cache — in-process config map updated by SSE or poll; 5-min TTL circuit-breaker during Config API outage; (7) rollback — publish old value as new version (auditable, preserves history); schema validation on rollback value; (8) sensitive config — AES-256-GCM encryption, KMS envelope encryption, masked in UI, separate authenticated endpoint, read audit log; (9) audit log — INSERT-only, captures actor, action, namespace, key, env, old/new value, ip, timestamp; (10) environment isolation — service token scoped to environment; promote workflow for staging → prod.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
