"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-kill-switch-emergency-control-panel",
  title: "Design a Kill-Switch / Emergency Control Panel",
  description:
    "Architecture for a kill-switch and emergency control panel: MFA-gated activation with optional second-approver for critical switches, Redis SET with TTL for sub-5ms state write, Redis pub/sub fan-out propagating switch state to all service pods within 500ms, service-level 5-second safety-net polling as fallback, graceful degradation responses (stale cache / 503 / maintenance page) on active switch, automatic TTL expiry to prevent indefinite lockout, immutable append-only audit log with PagerDuty alert on every activation, scope targeting (all traffic / specific region / specific user segment), and heartbeat dashboard confirming acknowledgment percentage across pods.",
  category: "high-level-design",
  subcategory: "feature-configuration-admin-systems",
  slug: "kill-switch-emergency-control-panel",
  wordCount: 5000,
  readingTime: 29,
  lastUpdated: "2026-05-14",
  tags: ["hld", "kill-switch", "circuit-breaker", "emergency", "incident-response", "redis", "graceful-degradation", "sre"],
  relatedTopics: ["dynamic-config-management-ui", "remote-app-configuration-system"],
};

export default function KillSwitchEmergencyControlPanelArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A kill-switch (also called an emergency control panel or "big red button") is a system that allows on-call engineers to instantly disable a feature, service, or traffic flow during an incident — without a code deployment. During a production outage, every minute of downtime costs revenue and erodes user trust. The ability to disable a malfunctioning feature in seconds (rather than the 10–30 minutes a typical deployment takes) is one of the most valuable tools in an SRE's toolkit.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Kill-switches differ from regular feature flags in several critical ways: (1) speed — a kill-switch must propagate to all service instances within 500 milliseconds, not the seconds-to-minutes acceptable for regular config changes; (2) reliability — the kill-switch system must work even during a partial infrastructure outage (it is most needed precisely when things are broken); (3) scope — a kill-switch may affect an entire service, a specific endpoint, a geographic region, or a specific user segment; (4) safety — accidentally activating a kill-switch in production can be as damaging as the incident it was meant to mitigate, so strong authentication (MFA) and optional dual approval are required; (5) reversibility — the switch must be easy to deactivate once the incident is resolved, and must auto-expire to prevent indefinite lockout.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Kill-switch activation, propagation, service-side enforcement and graceful degradation, auto-expiry, and audit/alerting. Not in scope: general feature flag gradual rollout (covered in the remote config article) or service circuit breakers (automatic, not operator-triggered).</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Switch catalog and definition:</strong> Each kill-switch is pre-defined in a switch catalog before it is needed. Definition fields: name (unique identifier, e.g., "disable-checkout"), description (human-readable explanation of what the switch disables), impact (severity enum: CRITICAL / HIGH / MEDIUM, used to determine approval requirements), scope options (GLOBAL / by-region / by-user-segment), protected services (list of service names that enforce this switch), graceful degradation behavior (what each protected service should do when the switch is active: return stale cache, return 503, show maintenance page, redirect to fallback URL), and default TTL (how long the switch stays active before auto-expiring, e.g., 30 minutes). Switches are defined in code (committed to a configuration repository) and registered in the switch catalog on deployment. Ad-hoc switch creation (defining a new switch at incident time) is not supported — creating a switch during an incident is too slow and error-prone. All anticipated failure scenarios must have corresponding pre-defined switches.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>MFA-gated activation:</strong> Activating a kill-switch requires: (1) the operator must be authenticated (valid session); (2) the operator must complete an MFA challenge (TOTP code from an authenticator app or a WebAuthn hardware key tap) — this prevents accidental activation from an unlocked browser tab; (3) for switches with impact = CRITICAL, a second approver must confirm within 2 minutes (if no second approver is available, the operator can override with an acknowledgment: "I understand I am activating this without dual approval during an active incident"); (4) the operator must provide a mandatory reason string (linked to an incident ticket — e.g., "INC-4821: checkout service returning 500 errors on all payment methods"). The reason string is the first thing logged and appears prominently in the PagerDuty alert, making it easy for the broader team to understand why the switch was activated. Activation API: POST /switches/&#123;name&#125;/activate &#123;reason, scope, expiresInSeconds, mfaToken, incidentId&#125;.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Sub-5ms state write to Redis:</strong> On activation, the system writes to Redis immediately: SET switch:&#123;name&#125; ACTIVE EX &#123;expiresInSeconds&#125;. The Redis write is the critical path — it must complete in under 5ms (typical Redis write latency is 0.5–2ms on a co-located cluster). The Redis key format encodes the scope: switch:&#123;name&#125;:global for global scope, switch:&#123;name&#125;:region:eu-west-1 for region-scoped, switch:&#123;name&#125;:segment:premium for segment-scoped. After the Redis write, the system writes to the PostgreSQL switch_activations table (for audit durability), publishes to the Kafka switch-events topic (for durability — Kafka retains the event even if subscribers are temporarily down), and triggers the Redis pub/sub notification. The Redis write happens first because it is the mechanism by which services enforce the switch — the audit DB write can lag behind by milliseconds without impact.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Propagation via Redis pub/sub:</strong> All service pods (across all instances of all protected services) subscribe to the Redis pub/sub channel switches:&#123;name&#125; at startup. When the switch is activated, Redis pub/sub delivers the message to all subscribers within milliseconds. Each subscribing pod: (1) updates its in-process switch state map (&#123;switchName: ACTIVE | INACTIVE&#125;); (2) logs the switch state change; (3) begins enforcing the switch on all subsequent requests. The propagation latency (Redis pub/sub round-trip from publish to subscriber delivery) is typically 1–5ms within a datacenter, 20–50ms across regions. Total time from operator pressing "Activate" to all pods enforcing the switch: typically &lt;200ms within a region, &lt;1 second globally.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Safety-net polling every 5 seconds:</strong> Redis pub/sub is at-most-once delivery — if a pod is temporarily disconnected from Redis when the pub/sub message arrives (network hiccup, Redis failover), it misses the message. The safety net: every service pod polls Redis GET switch:&#123;name&#125; every 5 seconds, independent of the pub/sub subscription. If the poll reveals an ACTIVE switch that the pod hasn't seen via pub/sub, the pod enforces the switch immediately. The 5-second poll interval means the worst-case propagation delay for a pod that missed the pub/sub event is 5 seconds. This is acceptable — it is far faster than the minutes a deployment would take, and the vast majority of pods receive the pub/sub event within milliseconds.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Graceful degradation responses:</strong> Each protected service defines its graceful degradation behavior for each switch in its service configuration. When a service's request handler checks the switch state (at the request entry point, before any business logic) and finds ACTIVE, it takes the configured graceful action: (1) return stale cache — serve the last-cached response for this endpoint, even if stale; appropriate for read endpoints where stale data is acceptable during an incident; (2) return 503 Service Unavailable — for write endpoints where stale data is not acceptable; includes a Retry-After: 300 header advising clients to retry in 5 minutes; (3) show maintenance page — for user-facing endpoints, redirect to a static maintenance page hosted on a CDN (independent of the affected service); (4) redirect to fallback — redirect to a degraded-mode URL (e.g., disable recommendations but continue serving the main feed). The graceful degradation behavior is pre-configured per switch per service, tested in staging, and never improvised at incident time.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Auto-expiry and deactivation:</strong> Every switch activation must specify an expiresInSeconds (maximum 4 hours; default 30 minutes). The Redis key TTL enforces the expiry — the key automatically disappears from Redis at TTL expiry, and all pods see INACTIVE on their next poll (within 5 seconds). This prevents the common incident anti-pattern of forgetting to turn a switch off after the incident is resolved, leaving a service degraded for hours or days. At expiry, the system publishes a "switch expired" event to the audit log and sends a Slack notification ("switch 'disable-checkout' auto-expired after 30 minutes — verify service is healthy"). Manual deactivation before expiry: POST /switches/&#123;name&#125;/deactivate &#123;reason&#125; — same MFA requirement as activation; Redis DEL; pub/sub PUBLISH with state=INACTIVE.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Heartbeat dashboard and pod acknowledgment:</strong> The control panel UI shows a real-time dashboard of switch enforcement status across all pods. After activating a switch, the operator should see confirmation that all pods have received and acknowledged the switch within a few seconds. Implementation: each pod that receives the switch activation (via pub/sub or poll) sends an acknowledgment event to the control panel via an internal metrics endpoint: POST /metrics/switch-ack &#123;switchName, podId, acknowledgedAt&#125;. The control panel aggregates acks and displays: "87/89 pods acknowledged within 500ms; 2 pods pending." Pods that have not acknowledged within 5 seconds are highlighted in the dashboard — the operator can check the logs of those specific pods. Unacknowledged pods (e.g., pods being restarted, pods in a different availability zone with connectivity issues) are also checked during the safety-net poll and self-acknowledge on the next poll cycle.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The kill-switch system has three planes: the activation plane (control panel UI → API with MFA auth → Redis SET + DB INSERT + Kafka publish + pub/sub), the enforcement plane (all service pods subscribe to Redis pub/sub + poll every 5s → check switch state on each request → graceful degradation), and the observability plane (pod acknowledgment heartbeats → control panel dashboard, PagerDuty alert on activation, audit log). The system is designed to be highly available under failure: even if the Control Panel API is down, already-activated switches remain enforced (Redis TTL still ticks, pods still poll Redis). The only operations that require the Control Panel API are activation and deactivation — enforcement is fully decoupled from it.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/feature-configuration-admin-systems/kill-switch-emergency-control-panel.svg"
          alt="Kill-switch emergency control panel: operator activates with MFA and reason; Redis SET switch state with TTL under 5ms; DB INSERT for audit; Redis pub/sub fans out to all service pods within 500ms; each pod updates in-memory flag and begins enforcing on requests; safety-net poll every 5 seconds; services return stale cache or 503 or maintenance page; pod acknowledgments feed real-time dashboard; switch auto-expires via Redis TTL; deactivation triggers pub/sub INACTIVE event and audit log entry."
          caption="MFA + optional dual approval; Redis SET &lt;5ms; pub/sub &lt;500ms propagation; 5s safety-net poll; graceful degradation: stale cache / 503 / maintenance page; Redis TTL auto-expiry; pod ack heartbeat dashboard; immutable audit + PagerDuty alert"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Switch State Check in Service Code</h3>
        <HighlightBlock as="p" tier="important">Service teams integrate the kill-switch client library (a thin wrapper around Redis GET and pub/sub subscription). The switch check is a single in-memory map lookup — the pub/sub listener and the poll loop maintain a thread-safe map of &#123;switchName: boolean&#125;. The check call: switchClient.isActive("disable-checkout") returns a boolean in under 1 microsecond (no I/O). This overhead is negligible even if called on every HTTP request. The check is placed at the request entry point — typically as a middleware/interceptor that runs before any business logic, so the service fails fast and does not waste resources processing requests it will ultimately reject. For scope-targeted switches (region or segment), the check includes the request context: switchClient.isActive("disable-checkout-eu", &#123;region: request.region&#125;) — the client checks both the global switch key and the scope-specific key.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Control Panel UI Design</h3>
        <HighlightBlock as="p" tier="crucial">The control panel UI is a separate, independently deployed application with its own authentication and authorization system (not sharing auth infrastructure with the main product — this ensures the control panel remains accessible even during a main auth service outage). The UI surfaces: (1) a switch catalog (all pre-defined switches with their description, impact level, and current state — INACTIVE / ACTIVE / PENDING_APPROVAL); (2) an activation flow with a prominent confirmation dialog showing estimated impact (how many users are affected, which services are protected, what the graceful degradation behavior is); (3) the real-time pod acknowledgment dashboard (shows propagation progress in the seconds after activation); (4) a history timeline of all activations and deactivations with reasons and actors; (5) a "simulate" mode (staging environment only) where operators can test the full activation flow without affecting production. The UI is a static single-page application hosted on a CDN — it does not require the main application server to be operational, which is crucial during an incident where the main servers may be the problem.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Multi-Region Consistency</h3>
        <HighlightBlock as="p" tier="important">For globally distributed services, a switch activation in one region must propagate to all regions. Multi-region design: (1) the Control Panel API writes to a global Redis cluster (cross-region replication enabled — primary in us-east-1, replicas in eu-west-1 and ap-southeast-1); (2) Redis pub/sub events are delivered from the primary to subscribers in all regions via the replication channel; (3) the 5-second safety-net poll from each pod reads from the nearest Redis replica (not the primary — replica read reduces latency and avoids overloading the primary). Cross-region replication latency for the pub/sub event: 50–150ms (dependent on the physical distance between regions). This means the worst-case propagation time to all regions is under 200ms for the pub/sub path, and 5 seconds + replication latency for the safety-net poll path. In the rare case of a full region partition (all Redis connections from a region are severed), services in that region continue using their in-memory switch state (which does not expire — it was set by the last successful pub/sub or poll). If the in-memory state is ACTIVE (the switch was activated before the partition), services continue to enforce the switch correctly. If the in-memory state is INACTIVE and the switch was activated after the partition, services in the disconnected region will not enforce the switch until connectivity is restored.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="crucial">Redis pub/sub vs. Kafka for propagation: Redis pub/sub delivers messages in &lt;5ms but is at-most-once (messages are not stored — a subscriber that is offline when the message arrives misses it). Kafka provides at-least-once delivery with message storage (consumers that reconnect can replay missed messages). For kill-switch propagation, Kafka would ensure that pods restarting during an incident eventually receive the switch activation even if they were offline during the Redis pub/sub event. However, Kafka's consumer delivery latency is higher (50–500ms vs. &lt;5ms for Redis pub/sub), and the complex consumer group management adds operational overhead. The design uses Redis pub/sub for speed (most cases) and the 5-second safety-net poll as the reliability mechanism (handles missed pub/sub events). The Kafka topic (switch-events) is used for audit durability — events are stored for 7 days and can be replayed for post-incident analysis — but it is not the primary propagation mechanism.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Kill-switch vs. circuit breaker: an application circuit breaker (like Hystrix or Resilience4j) is an automatic, code-level mechanism that opens when a downstream dependency fails (too many errors → circuit opens → requests short-circuit with fallback). A kill-switch is a manual, operator-triggered mechanism. Both implement graceful degradation but serve different scenarios: circuit breakers handle automatic recovery from transient failures (connection timeouts, service unavailability); kill-switches handle deliberate, operator-controlled disablement (a feature is causing data corruption, a vendor service has a security incident). Kill-switches should be layered above circuit breakers — a service might have an automatic circuit breaker that opens when the payment provider returns errors, and a manual kill-switch that the operator activates to proactively disable checkout before the circuit breaker would naturally open.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A kill-switch emergency control panel requires: (1) pre-defined switch catalog — name, impact level, scope options, protected services, graceful degradation behavior, default TTL; no ad-hoc creation at incident time; (2) MFA-gated activation — TOTP or WebAuthn; dual approval for CRITICAL switches; mandatory reason + incidentId; (3) Redis SET switch:&#123;name&#125; ACTIVE EX &#123;ttl&#125; — &lt;5ms write; then DB INSERT + Kafka publish; (4) Redis pub/sub PUBLISH — fan-out to all subscribed service pods in &lt;500ms within region, &lt;200ms cross-region replica; (5) in-process switch state map — O(1) check per request via thin client library; scope-aware check (global + region + segment keys); (6) safety-net poll — Redis GET every 5 seconds per pod — handles pods that missed pub/sub; (7) graceful degradation — stale cache / 503 + Retry-After / CDN maintenance page / fallback redirect — pre-configured per switch per service; (8) auto-expiry — Redis TTL (max 4 hours, default 30 min); Slack notification on expiry; (9) deactivation — same MFA gate; Redis DEL + pub/sub INACTIVE; (10) pod ack heartbeat — pods POST acknowledgment after enforcement; control panel shows % acked within 500ms; (11) audit log + PagerDuty — every activation and deactivation appended to immutable audit log; PagerDuty alert fires on activation.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
