"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-remote-app-configuration-system",
  title: "Design a Remote App Configuration System (like Firebase Remote Config)",
  description:
    "Architecture for a Firebase Remote Config-like system: client SDK sends user context (userId, appVersion, platform, country) to server-side targeting engine that evaluates priority-ordered rules and returns a resolved config map, CDN-served global defaults with ETag 304 short-circuit for non-targeted payloads under 5ms, on-device rule caching for offline evaluation, stale-while-revalidate SDK fetch pattern, Redis-cached rule sets with 60-second TTL, config publish triggers Redis pub/sub and CDN purge, and A/B experiment assignment embedded in the config evaluation response.",
  category: "high-level-design",
  subcategory: "feature-configuration-admin-systems",
  slug: "remote-app-configuration-system",
  wordCount: 4800,
  readingTime: 27,
  lastUpdated: "2026-05-14",
  tags: ["hld", "remote-config", "firebase", "feature-flags", "sdk", "targeting", "a-b-testing", "cdn"],
  relatedTopics: ["dynamic-config-management-ui", "kill-switch-emergency-control-panel"],
};

export default function RemoteAppConfigurationSystemArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A remote app configuration system allows product teams to change the behavior and appearance of a mobile or web application without releasing a new app version. Instead of embedding values like button colors, feature flags, promotion banners, and algorithm parameters in the app binary — which requires App Store review and user updates to take effect — these values are fetched from a remote server at runtime. The server can return different values for different users based on targeting rules (country, app version, user segment, A/B experiment group).</HighlightBlock>
        <HighlightBlock as="p" tier="important">The system is distinct from a general-purpose config management system in one key way: the consumer is an end-user mobile or web app (not a backend service). This introduces constraints: (1) the app may be offline and must still function correctly using cached config; (2) the config response must be fast (the app waits for it before rendering or on each session start); (3) millions of apps fetch config simultaneously — the system must handle massive read scale with minimal server load; (4) the app cannot receive SSE pushes (mobile apps in the background cannot maintain persistent connections) — config updates are received on the next app foreground/launch.</HighlightBlock>
        <p><strong>Explicit scope:</strong> SDK config fetch with targeting, CDN-served global defaults, offline SDK behavior, rule evaluation engine, config publish and cache invalidation. Not in scope: A/B experiment result analysis (covered in the experimentation article), kill-switches (separate article), or backend service config (covered in the dynamic config article).</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>SDK-based config fetch with user context:</strong> The SDK (bundled with the app) fetches config on each app launch (and optionally on foreground after a minimum interval). The fetch is a POST /config/eval &#123;appId, userId, appVersion, platform, country, customAttributes&#125;. The server evaluates targeting rules against the provided context and returns a resolved config map: &#123;key: value&#125; pairs representing the "winning" value for each config key given the user's context. The server-side evaluation model ensures that targeting logic stays on the server (not exposed in the app binary, preventing users from manipulating targeting by modifying client-side logic). The resolved config is a flat key-value map; the SDK stores it in local persistent storage (SharedPreferences on Android, UserDefaults on iOS) for offline access.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Targeting rule evaluation:</strong> Rules are defined as conditions on user context attributes. Rule structure: (priority int, condition expression, key, value). Condition examples: "appVersion &gt;= 2.5.0 AND country IN [US, CA, GB]", "userId % 10 == 3" (10% of users by user ID hash), "customAttributes.isPremium == true". Rules are evaluated in priority order — the first rule whose condition evaluates to true for the user's context determines the value for that key. If no rule matches, the default value is returned. The condition evaluator supports: string equality/regex, numeric comparison, version comparison (semantic versioning), set membership (IN/NOT IN), percentage rollout (hash(userId + key) % 100 &lt; rolloutPercentage), and boolean flags. All rules for an appId are loaded from Redis (TTL 60 seconds) at eval time — the eval is CPU-bound (in-memory rule evaluation against the context), typically completing in &lt;5ms per request.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>CDN path for global defaults:</strong> Most config keys have the same default value for all users (no targeting rules apply). Serving these via the targeted eval endpoint is wasteful — it requires a server-side rule evaluation even though the result is always the default. Optimization: the system maintains a separate "defaults" endpoint GET /config/defaults?appId=X&amp;appVersion=Y that returns all config values using the default rules only (no user context). This response is cacheable — it does not vary by user — and is served from the CDN (CloudFront, Fastly) with a 5-minute TTL. The SDK fetches defaults first (fast, from CDN edge, typically &lt;50ms round-trip), then in parallel fetches the targeted override eval (slower, requires server-side evaluation). The final config in the SDK is: default values overridden by targeted values. ETag support: the CDN serves an ETag with the defaults response; on subsequent fetches, the SDK sends If-None-Match: &#123;etag&#125;; if the defaults haven't changed, the CDN returns HTTP 304 Not Modified with no body, saving bandwidth.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Offline SDK behavior and stale-while-revalidate:</strong> The SDK always operates in a "use cache, then update" pattern. On app launch: (1) immediately load the config from the local persistent cache (so the app can render without waiting for a network call); (2) in the background, fetch fresh config from the server; (3) on successful fetch, update the local cache for the next launch. The app never blocks on the config fetch — it uses the cached (possibly stale) config for the current session. This stale-while-revalidate pattern means: on first launch (no cache), the app waits for the initial config fetch before rendering. On subsequent launches, the app renders immediately from cache and updates config for the next launch. Offline behavior: if the fetch fails (no network), the app uses the cached config indefinitely. If the cache itself is empty (e.g., storage was cleared), the app uses a bundled defaults file included in the app binary — this is the ultimate fallback and ensures the app always has a valid config even on first offline launch.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Scale: millions of concurrent fetches:</strong> A popular app with 100M daily active users, each launching the app once per day, generates 100M config eval requests per day — approximately 1,160 requests/second on average, with 5–10× spikes during peak hours (morning commute, evening usage). Most of these requests resolve to default values (no targeting rules apply). The CDN handles the default requests (high cache hit rate, ~99%). The targeted eval endpoint handles the remainder — users in A/B experiments, users in specific countries with targeted promotions, premium users with different feature sets. At 5% targeted users, the eval endpoint handles ~60 requests/second baseline, easily handled by 10–20 stateless eval servers. For sudden spikes (a major promotion going live), the eval server auto-scales horizontally.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Config publish and cache invalidation:</strong> When an admin publishes a new config version (new rule, updated default value), the system must invalidate cached responses quickly. Invalidation chain: (1) update the rule set in the config store DB; (2) Redis PUBLISH to invalidate the in-memory rule cache on all eval server pods (next eval request re-fetches from DB into Redis); (3) CDN purge for the affected appId's defaults endpoint (CDN API call — takes 5–30 seconds to propagate to all edge nodes); (4) the Redis rule cache TTL (60 seconds) ensures that even without an explicit invalidation, all eval servers have fresh rules within 60 seconds. The combination of Redis pub/sub (near-instant for most pods) and TTL-based expiry (safety net for pods that missed the pub/sub event) ensures eventual consistency within 60 seconds. Mobile apps receive the new config on their next launch (stale-while-revalidate — the current session continues with the old config, the next session gets the new config).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>A/B experiment assignment:</strong> A/B experiment assignment is a special case of targeting rule: "assign user to experiment group A or B based on a hash of (userId + experimentId)". The hash-based assignment is deterministic — the same user always gets the same assignment for the same experiment — and stateless (no per-user experiment assignment record needs to be stored on the server; the assignment is computed on every eval from the rule). The assignment is included in the config eval response: the config key "checkout_button_color" resolves to "blue" for group A and "green" for group B. The SDK logs an "experiment exposure" event when it first uses an experiment-assigned config value — this event is used by the analytics pipeline to attribute metric changes to experiment variants.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Rate limiting and SDK throttling:</strong> A buggy app that fetches config on every API call (instead of once on launch) would flood the config service. SDK throttling: the SDK enforces a minimum fetch interval (default 12 hours for production — configurable). Requests more frequent than the minimum interval return the cached config immediately without hitting the server. The minimum fetch interval is configurable by the server — on the config eval response, the server includes a Retry-After header specifying the next allowed fetch time. If the server is under load, it can dynamically increase the minimum interval for all clients (e.g., set Retry-After: 86400 during a traffic spike to push all clients to a 24-hour interval). Rate limiting at the API gateway level: per-appId rate limits (e.g., 10 million requests/day per appId) prevent a single misbehaving app from consuming all eval capacity.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The system has three tiers: the CDN tier (serves non-targeted defaults, handles the majority of traffic, near-zero server cost per request), the eval tier (stateless eval servers, rule evaluation against user context, Redis rule cache), and the admin tier (config management UI, publish workflow, CDN purge). The SDK embeds the fetch logic and local cache. The eval tier is the only stateful dependency at request time — it needs Redis for the rule cache. The CDN tier has no dependencies on the eval tier for cache hits.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/feature-configuration-admin-systems/remote-app-configuration-system.svg"
          alt="Remote app configuration: SDK sends user context to Config API; targeting engine loads rules from Redis 60s cache; evaluates priority-ordered conditions; returns resolved config map; non-targeted defaults served from CDN with ETag 304 short-circuit; SDK caches on-device for offline; stale-while-revalidate pattern; admin publish triggers Redis PUBLISH and CDN purge; next SDK fetch gets updated config."
          caption="Server-side targeting eval; Redis rule cache 60s TTL; CDN ETag 304 short-circuit for defaults; stale-while-revalidate SDK; bundled defaults for offline cold start; hash-based deterministic A/B assignment; Retry-After throttle header"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Rule Evaluation Engine</h3>
        <HighlightBlock as="p" tier="important">The rule evaluation engine processes a list of rules in priority order and returns the first matching value for each config key. Rules are stored as a JSON array per (appId, environment) in the config store DB, loaded into Redis on first access (TTL 60 seconds). The evaluation algorithm: for each config key, iterate rules in priority order; evaluate the condition expression against the user context; return the first matching value. Condition evaluation uses a simple expression tree (no general-purpose scripting language — scripting languages have security risks like infinite loops and code injection). Supported operators: == (equality), != (inequality), &gt; &lt; &gt;= &lt;= (numeric), IN/NOT IN (set membership), MATCHES (regex — restricted to safe patterns), AND/OR/NOT (logical), semver_gte/semver_lt (semantic version comparison). The expression evaluator is a pure function with no I/O — it runs entirely in memory against the provided context object. Evaluation of 200 rules for a user context typically takes under 1ms on a modern CPU.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Percentage Rollout Implementation</h3>
        <HighlightBlock as="p" tier="important">Percentage rollout (e.g., "show new checkout flow to 10% of users") uses a deterministic hash: rolloutBucket = murmurhash3(userId + keyName) % 100. If rolloutBucket &lt; rolloutPercentage (10), the user is in the rollout group. The hash is deterministic — the same user always gets the same bucket for the same key. Adding keyName to the hash input prevents all keys from rolling out to the exact same 10% of users (correlation between rollouts of different keys, which would confound A/B analysis). The rollout percentage is stored in the rule definition and can be gradually increased (0% → 5% → 25% → 50% → 100%) via successive admin edits — each increase is committed as a new rule version and published via the normal publish pipeline. The gradual rollout strategy allows the team to monitor metrics (error rate, conversion rate, latency) at each step and halt the rollout if a regression is detected.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="crucial">Server-side vs. client-side rule evaluation: server-side evaluation (the server evaluates rules against the user's context and returns resolved values) keeps the rule definitions private (not embedded in the app binary — competitors cannot reverse-engineer targeting logic), allows targeting based on server-side signals (account history, fraud score), and ensures all clients use the same evaluation logic (no SDK versioning issues with rule evaluation bugs). Client-side evaluation (the server ships all rules to the client; the client evaluates locally) enables zero-latency config reads (no network call needed for flag evaluation after initial rule download) and offline flag evaluation without a bundled defaults fallback. Firebase Remote Config uses server-side evaluation; LaunchDarkly offers both. For most production systems, server-side evaluation is preferred for security and consistency; client-side evaluation is used for ultra-low-latency requirements (e.g., evaluating a flag on every page render).</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">Config vs. feature flags: "remote config" and "feature flags" are often used interchangeably but have different optimization profiles. Feature flags are boolean (on/off) and are evaluated very frequently (on every page render or API call) — they need sub-millisecond local evaluation. Remote config values are richer (strings, JSON, numbers) and are fetched less frequently (once per session or hour) — server-side evaluation latency (50–200ms) is acceptable. Systems like LaunchDarkly optimize for feature flag evaluation (client-side rule download, streaming updates) while Firebase Remote Config optimizes for remote config (server-side eval, session-level fetch). A production system often needs both: feature flags for A/B tests evaluated on every render, and remote config for session-level settings that don't change within a session.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A remote app configuration system requires: (1) SDK sends user context (userId, appVersion, platform, country, customAttributes) to POST /config/eval; (2) server-side rule evaluation: priority-ordered conditions (equality, numeric, semver, set, percentage rollout) evaluated against context in &lt;5ms from Redis rule cache (60s TTL); (3) resolved config map returned as &#123;key: value&#125; — first matching rule wins, default if no match; (4) CDN defaults endpoint GET /config/defaults for non-targeted payloads — ETag 304 short-circuit; 5-minute CDN TTL; (5) stale-while-revalidate SDK: load from local cache → render → background fetch → update cache for next session; (6) offline fallback: cached config → bundled defaults (included in app binary); (7) A/B assignment: murmurhash3(userId + keyName) % 100 — deterministic, stateless, correlated per-key; (8) publish invalidation: Redis PUBLISH (eval pods pick up in &lt;1s) + CDN purge (5–30s) + 60s TTL safety net; (9) SDK throttle: minimum 12-hour fetch interval enforced client-side; Retry-After server override for traffic shaping; (10) rate limiting: per-appId daily quota at API gateway.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
