"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-user-preference-learning-system",
  title: "Design a User Preference Learning System",
  description:
    "Architecture for a user preference learning system: explicit signal collection (ratings, topic picks, preference toggles), implicit signal inference (dwell time, scroll depth, save/share patterns), preference model representation (interest vectors, topic affinity graphs, recency-weighted decay), cold start strategies, preference conflict resolution, GDPR compliance (right to erasure, preference export), and real-time vs. batch preference update pipelines.",
  category: "high-level-design",
  subcategory: "personalization-systems",
  slug: "user-preference-learning-system",
  wordCount: 5100,
  readingTime: 31,
  lastUpdated: "2026-05-11",
  tags: ["hld", "personalization", "preference-learning", "cold-start", "gdpr", "implicit-signals", "feature-store"],
  relatedTopics: ["user-personalization-engine-ui", "recommendation-tuning-system"],
};

export default function UserPreferenceLearningSystemArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <p>A user preference learning system answers the question: given all the signals a user has produced—explicit ratings, implicit behavioral patterns, stated preferences, and contextual interactions—what does this user want to see next? It is distinct from the recommendation ranking system (which produces a ranked list of items) and the personalization engine (which manages the serving pipeline). The preference learning system is concerned with building and maintaining an accurate model of the user's interests that can be consumed by any downstream system: ranking models, search result ordering, notification targeting, email digest curation.</p>
        <p>The problem is harder than it appears. Stated preferences (a user selects "Machine Learning" during onboarding) do not reliably predict engagement (the same user may click System Design articles 80% of the time). Revealed preferences (click patterns) are noisy: users click thumbnails, not articles; a click does not confirm interest, only curiosity. Engagement duration (dwell time) is a better signal of genuine interest but is harder to collect and interpret (a user staring at an article for 3 minutes may be reading it attentively or have left the tab open while making coffee). Preferences change over time: a user who was deeply interested in React hooks in 2022 may now be primarily interested in distributed systems, but older signals still exist in the system. Preferences are contextual: the same user wants different content at 8am on a commute (short-form, mobile) vs. 9pm on a Saturday (long-form, desktop). A preference learning system must handle all of these dimensions simultaneously.</p>
        <p><strong>Explicit scope:</strong> This article covers the preference data model, signal collection and processing pipeline, preference update mechanisms (real-time and batch), cold start, preference decay, privacy compliance, and the preference query API. The ranking model that consumes preference data is treated as an external consumer with a defined interface.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <li><strong>Signal ingestion:</strong> Collect and process explicit signals (topic selection, thumbs up/down, save, follow, unfollow, "hide topic") and implicit signals (click, dwell time, scroll depth, share, re-open). Each signal type has a defined weight and TTL (time-to-live for its contribution to the preference model).</li>
          <li><strong>Preference model:</strong> Maintain a per-user preference representation: a topic affinity map (topic → affinity score in [−1.0, 1.0]), a content-type preference (short-form/long-form/video/interactive), a reading depth preference (title-only skimmer vs. full-article reader), a recency preference (up-to-date content vs. evergreen), and an active session context (what is the user interested in right now, based on their last 5 interactions in this session).</li>
          <li><strong>Cold start:</strong> New users with no behavioral history must receive a reasonable initial preference model within 60 seconds of their first explicit signal (onboarding topic selection). The system must gracefully degrade from explicit-signal-only to implicit-signal-only as signals accumulate.</li>
          <li><strong>Preference query API:</strong> External systems (ranking model, search, notifications) query the preference API:{" "}
            <code>{`GET /preferences/{userId}?context=homepage`}</code> returns the user&apos;s current preference vector and confidence scores. The API must respond within 10ms (Redis-backed).</li>
          <li><strong>User control:</strong> Users can view, edit, and delete their preference data via a preference dashboard. Changes take effect within 5 seconds. Users can reset their preference model to cold-start state.</li>
          <li><strong>Privacy compliance:</strong> GDPR right to erasure: deleting a user account triggers deletion of all preference data within 24 hours. Right to data portability: users can export their preference data as JSON. Preference data must not be shared across user accounts or used to infer sensitive attributes.</li>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <li><strong>Freshness:</strong> Explicit signals (thumbs up/down, topic hide) must be reflected in the preference model within 5 seconds. Implicit signals (click, dwell) must be reflected within 60 seconds.</li>
          <li><strong>Scale:</strong> Support 10M daily active users, each producing an average of 50 signals per session. Signal ingestion pipeline must handle 500K events/second at peak.</li>
          <li><strong>Consistency:</strong> The preference model must be eventually consistent. A user who saves 3 articles in category X must see that reflected in their next feed request (after the 60-second freshness window). Strong consistency (read-your-writes guarantee) is not required for implicit signals.</li>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <p>The system has four planes. The signal collection plane: the frontend SDK collects behavioral events and sends them to the Signal Ingestion Service via a batched HTTP endpoint (POST /signals, batches of up to 50 events per request). The ingestion service validates, deduplicates, and publishes events to Kafka. The preference computation plane: two pipelines consume from Kafka. The real-time pipeline (Apache Flink) processes explicit signals and high-weight implicit signals (saves, shares), updating the preference model in Redis within seconds. The batch pipeline (Apache Spark, runs every 15 minutes) recomputes the full preference model incorporating all signals with proper decay weighting, writing the result to Redis and S3. The preference serving plane: the Preference API reads from Redis and serves preference vectors to downstream consumers (ranking model, search, notifications) with sub-10ms latency. The user control plane: the Preference Dashboard reads and writes to a Preference Edit Store (PostgreSQL), which triggers invalidation of the Redis cache and a recomputation event to the batch pipeline.</p>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/personalization-systems/user-preference-learning-system.svg"
          alt="User preference learning system architecture showing signal collection (explicit signals follow +1.0 save +0.5 thumbs-up +0.3 thumbs-down -0.8 hide topic -1.0 onboarding pick +0.4; implicit signals dwell ≥90s +0.3 share +0.4 re-open +0.25 dwell 30-90s +0.15 dwell <30s +0.05 click-no-dwell +0.02; signal ingestion service validate deduplicate batch 50 events/30s → Kafka signals topic 500K ev/s peak → raw signals S3 Parquet 90d retention GDPR delete nightly; preference edit store PostgreSQL explicit signals only), preference computation Flink streaming real-time <5s (explicit + high-weight implicit validate deduplicate resolve topicId incremental affinity update Redis keyed stream by userId RocksDB state flush 5s) + Spark batch every 15 min (full recompute active users last 15 min read 90d signals S3 apply decay e^-λt aggregate by topicId → Redis + S3 snapshots; also computes format pref reading depth recency pref), preference data model per user Redis hash (topic affinity map topicId → score [-1.0,1.0] sparse 5-20 topics prune |score|<0.05; format preference short_form long_form video interactive batch-computed; reading depth scalar [0,1] 0=skimmer 1=full-reader from scroll depth; confidence score 0 to 1 blends learned + global pop score=conf×learned+(1-conf)×global_pop; signal decay w(t)=w₀·e^-λt follow 365d save 90d dwell≥90s 30d thumbs-down 30d click-only 3d hide topic 7d floor batch applies full decay every 15 min), cold start confidence-weighted blend no special casing (Phase 0 conf=0 global pop → Phase 1 3+ topics conf≈0.2 20% pers → Phase 2 10-50 interactions conf≈0.6 60% pers → Phase 3 50+ conf≈0.9 full pers), GDPR (right to erasure PG+Redis sync <1s Kafka tombstone S3 nightly 24h; data minimization dwell bucketed no raw coords no keystrokes sensitive topics no implicit signals), preference query API Redis <10ms GET /preferences/{userId} full model GET /preferences/{userId}/topics <5ms POST /preferences/{userId}/context session-adjusted <8ms cache 60s TTL invalidated by Flink downstream ranking search notifications email export JSON portability."
          caption="Signal collection (explicit + implicit → Kafka), Flink real-time pipeline and Spark batch pipeline writing to Redis preference store, preference data model (topic affinity map, format pref, reading depth, confidence, decay function), cold start confidence-weighted phases, GDPR compliance cascade, and query API serving downstream consumers"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Signal Taxonomy and Weights</h3>
        <p>Signals are classified by source (explicit vs. implicit), strength (high/medium/low), and decay rate (how quickly the signal's contribution to the preference model decreases over time).</p>
        <p>Explicit signals (user-initiated, high reliability): Topic follow (+1.0, no decay for 365 days), topic unfollow (−0.5, removes prior follow signal), save/bookmark (+0.5, 90-day decay), thumbs up on item (+0.3, 60-day decay), thumbs down / not interested (−0.8, 30-day decay), "hide topic" (−1.0 floor for 7 days), onboarding topic selection (+0.4, 180-day decay—discounted vs. follow because stated preferences are less reliable than revealed behavior).</p>
        <p>Implicit signals (inferred from behavior, lower reliability): dwell time ≥ 90 seconds on an article (+0.3, 30-day decay—strong engagement indicator), dwell time 30–90 seconds (+0.15, 14-day decay), dwell time &lt; 30 seconds (+0.05, 7-day decay—curiosity only), click without dwell &lt; 10 seconds (+0.02, 3-day decay—likely thumbnail mismatch), share (+0.4, 45-day decay—one of the strongest implicit signals; sharing to others implies the user found the content highly valuable), re-open (opening an item the user already visited before, +0.25, 21-day decay—indicates the user wanted to return to the content).</p>
        <p>Session context signals (used for within-session preference boosting only, not persisted): the last 5 items the user interacted with in the current session boost the relevance of their categories for the remainder of the session. Session context weight decays to zero when the session ends (defined as 30 minutes of inactivity). Session context is stored in the in-memory state of the serving layer and is not written to the preference store.</p>
        <p>Signal decay function: each signal's contribution at time t is: contribution(t) = initial_weight × e^(−λt), where λ = ln(2) / half_life_days. A "thumbs up" signal with initial_weight=0.3 and half_life=60 days will contribute 0.15 at day 60, 0.075 at day 120, and effectively 0 by day 240. This prevents the preference model from being dominated by old signals and ensures it reflects the user's current interests rather than their historical interests.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Preference Model Representation</h3>
        <p>Each user's preference model consists of four components stored as a Redis Hash:</p>
        <p><strong>Topic affinity map:</strong> a dictionary of <code>{`{topicId → affinity_score}`}</code> where affinity_score is the weighted sum of all signal contributions for that topic, normalized to [−1.0, 1.0]. Topics with |affinity_score| &lt; 0.05 are pruned from the map (reducing storage). The map is sparse: most users have strong affinity for 5–20 topics out of thousands in the taxonomy. The topic affinity map is the primary input to the ranking model&apos;s feature set.</p>
        <p><strong>Content format preferences:</strong> a per-format preference score: <code>{`{short_form: 0.8, long_form: 0.3, video: 0.1}`}</code>. Derived from the correlation between the user&apos;s dwell time distribution and content lengths. A user who consistently achieves high dwell time on articles &gt; 5000 words gets a high long_form score. Format preferences are computed by the batch pipeline and are not updated in real-time.</p>
        <p><strong>Reading depth profile:</strong> a scalar in [0, 1] representing the user's typical reading depth (derived from scroll depth signals). 0 = title skimmer, 1 = full-article reader. Used to rank articles by appropriate reading depth within a topic. A user with depth=0.2 should be shown more listicles and summaries; a user with depth=0.9 should be shown in-depth technical analyses.</p>
        <p><strong>Recency preference:</strong> a scalar in [0, 1] representing the user's preference for fresh vs. evergreen content (derived from the correlation between item age at click time and dwell). 0 = prefers evergreen content (clicks and engages with content regardless of age), 1 = prefers recency (disproportionately clicks and engages with content published in the last 7 days).</p>
        <p>Confidence scores: each component has an associated confidence score (0–1) representing how many signals have been observed. A user with 3 interactions has low confidence (≈0.1); a user with 100 interactions has high confidence (≈0.9). Downstream systems use confidence scores to blend the learned preference with global popularity defaults: recommended_score = confidence × learned_preference_score + (1 − confidence) × global_popularity_score. This natural confidence weighting handles the cold start problem without special-casing: a new user (confidence≈0) sees global popularity; a veteran user (confidence≈1) sees fully personalized rankings.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Real-Time Update Pipeline</h3>
        <p>The Flink streaming pipeline processes explicit signals and high-weight implicit signals within seconds. Pipeline stages: (1) Signal validation: discard malformed events (missing userId, unknown topicId). (2) Deduplication: idempotency key = (userId, itemId, signalType, sessionId) deduplicated in a Flink state store with 1-hour TTL. (3) Topic resolution: map itemId to topicId(s) by looking up the item's category labels from a Redis-cached item metadata store (item metadata changes infrequently; TTL 1 hour). (4) Affinity update: for each (userId, topicId, signalType) tuple, compute the signal contribution (initial_weight adjusted for existing decay) and apply an incremental update to the user's topic affinity score in Redis: new_score = clamp(old_score + contribution, −1.0, 1.0). (5) Confidence update: increment the confidence counter for the user. (6) Explicit signal persistence: write explicit signals (thumbs up/down, topic follow/unfollow) to a PostgreSQL Preference Edit Store for durability and user-facing display in the preference dashboard. Implicit signals are not individually persisted to PostgreSQL (too high volume); only their aggregate effect on the preference model is persisted via the batch pipeline's S3 snapshots.</p>
        <p>The Flink pipeline operates as a keyed stream partitioned by userId, ensuring that all signals for a given user are processed by the same Flink task (avoiding concurrent writes to Redis for the same user from multiple Flink tasks). Each Flink task holds a local state (in RocksDB) for its partition of users, reducing Redis write frequency by buffering micro-updates and flushing every 5 seconds per user.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Batch Recomputation Pipeline</h3>
        <p>The Spark batch pipeline runs every 15 minutes and recomputes the full preference model for all users who had signal activity in the past 15 minutes (incremental recomputation, not a full table scan). For each active user: (1) Read all signals from the raw signals table (S3, Parquet) for the past 90 days. (2) Apply exponential decay to each signal's contribution based on its age. (3) Aggregate decayed contributions by topicId to produce the topic affinity map. (4) Compute format preference and reading depth from the full signal history. (5) Write the recomputed preference model to Redis (overwriting the real-time incremental update) and to S3 as a snapshot. The batch pipeline's full recomputation is more accurate than the real-time incremental update (which does not apply decay to existing affinity scores—only adds new contributions). The 15-minute batch cycle ensures that decay effects are applied at least hourly, preventing the model from gradually drifting as old signals fail to decay in the incremental pipeline.</p>
        <p>Batch pipeline latency vs. freshness: the 15-minute cycle means that immediately after the batch runs, a user's preference model may be 15 minutes "stale" in the batch dimension (not reflecting the very latest batch recomputation). This is acceptable because the real-time pipeline handles the immediate freshness requirement for explicit signals. The batch pipeline is the "ground truth" model; the real-time pipeline is the "recent delta" layer on top of it.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Cold Start Strategy</h3>
        <p>Cold start has three phases. Phase 0 (zero interactions, new user): the preference API returns a cold-start profile with all topic affinities set to 0 and confidence=0. Downstream systems use global popularity defaults (confidence × learned + (1−confidence) × global, where confidence=0 reduces to pure global popularity). Phase 1 (onboarding signal, 1–10 interactions): the user completes the onboarding interest picker (selecting 3+ topics). These explicit selections are written immediately to Redis as preference signals with initial_weight=0.4 and confidence bumped to 0.2. The feed is now 20% personalized (topic-matched to stated interests) and 80% global popularity. Phase 2 (signal accumulation, 10–50 interactions): as behavioral signals accumulate, confidence rises. At 50 interactions (typically 3–5 sessions), confidence reaches ~0.6, and the feed is 60% personalized. Phase 3 (full personalization, 50+ interactions): confidence reaches 0.9+. The feed is nearly fully personalized.</p>
        <p>Onboarding interest picker design: the interest picker presents a grid of topic tiles with icons. Selecting a tile adds the topic to the initial preference set. The picker requires a minimum of 3 selections to proceed (enforced by disabling the "Continue" button until 3+ are selected). The displayed topics are the 20 most popular topics globally plus 5 topics inferred from the user's signup context (e.g., "Data Science" if the user signed up with a .edu email and the referral source was a data science blog). The picker includes a search box to find specific topics not shown in the grid. On confirmation, the selected topics are written synchronously to the Preference Edit Store and Redis; the user's first feed request (which occurs ~2 seconds after completing onboarding) will reflect these initial preferences.</p>
        <p>Cross-domain cold start: if the platform supports multiple content domains (e.g., system design, machine learning, frontend development), cold start in one domain should not require a new onboarding flow if the user is established in another domain. The preference system infers cross-domain relevance: a user with high affinity for "distributed systems" in the system design domain is likely interested in "scalable ML training infrastructure" in the ML domain. A cross-domain interest inference model (a small collaborative filtering layer trained on users who are active in multiple domains) seeds preference estimates in the new domain from the user's established preferences in their primary domain. Cross-domain inference is clearly labeled in the preference dashboard ("Based on your System Design interests, you might like these ML topics") and the user can accept, dismiss, or edit each inferred preference.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Preference Conflict Resolution</h3>
        <p>Preference conflicts arise when explicit and implicit signals contradict each other. A user may follow a topic (explicit positive signal, weight +1.0) but consistently skip articles from that topic (implicit negative signal from low dwell time). Or a user may thumbs-down an article in a category but continue clicking on articles from that category (possibly disliking the specific author, not the category). The preference system resolves conflicts using a signal hierarchy.</p>
        <p>Explicit negative signals take precedence over implicit positive signals for the specific item/topic: a "hide topic" action (−1.0 floor) suppresses all items from that topic for 7 days regardless of implicit engagement signals. This ensures the user's stated preference is respected immediately. After the suppression expires, the implicit signals resume contributing. For topic follow conflicts (user follows a topic but shows low engagement), the preference score reflects the blend of both signals—a topic followed but never engaged with will have a net affinity of approximately +0.4 (follow weight) − accumulated negative implicit signals. If the net falls below +0.1 after 60 days, the system may notify the user: "You haven't engaged with [Topic] in a while—would you like to unfollow it?" This surfacing of stale preferences is a key UX element for keeping the preference model accurate without requiring users to proactively manage it.</p>
        <p>Recency weighting in conflict: more recent signals receive higher weighting in conflict resolution. If a user disliked System Design content 6 months ago (decayed weight ≈ 0.03) but has been heavily engaging with System Design articles for the past 2 weeks (accumulated weight ≈ 0.6), the recent positive signals dominate and the preference model correctly reflects the user's current interests. The exponential decay function naturally handles this without special conflict logic.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Privacy and GDPR Compliance</h3>
        <p>The preference learning system handles personally sensitive behavioral data and must meet GDPR requirements as a first-class concern, not an afterthought.</p>
        <p>Data minimization: signal collection is limited to what is necessary for preference learning. The system collects item category, dwell duration bracket (not raw dwell time—bucketed into &lt;10s, 10–30s, 30–90s, 90+s), and scroll depth bracket. Raw scroll coordinates, mouse movements, and keystrokes are never collected. The item's content is not sent to the preference system (only its category labels and ID).</p>
        <p>Right to erasure: when a user requests account deletion (or triggers "Reset my preferences"), the following cascade occurs: (1) Preference Edit Store: delete all rows for the userId (synchronous, completes within 1 second). (2) Redis: delete all preference keys for the userId (synchronous, completes within 1 second). (3) Kafka: signals already published to Kafka are not retroactively deletable (Kafka is immutable). A userId tombstone is published to a deletion_requests Kafka topic. The Flink pipeline and batch pipeline both subscribe to this topic and skip processing for tombstoned users. (4) S3 raw signals: a deletion job runs nightly, scanning the past 90 days of raw signal Parquet files and removing records for tombstoned users. This is the slowest step and completes within 24 hours. (5) S3 preference snapshots: deleted by the nightly deletion job as well. The 24-hour window for S3 deletion is compliant with GDPR's "without undue delay" requirement (interpreted as within 30 days; 24 hours is well within this).</p>
        <p>Data portability: <code>{`GET /preferences/{userId}/export`}</code> returns a JSON document containing the user&apos;s topic affinity map, content format preferences, and the list of all explicit signals (topic follows, thumbs up/down, saved items) with their timestamps. Implicit signal history is not individually exportable (too high volume and not meaningful in isolation); instead, the export includes the aggregate preference model and a summary of interaction counts per category. The export is generated on-demand from the Preference Edit Store and Redis (not S3) to ensure it reflects the current state rather than a stale snapshot.</p>
        <p>Sensitive attribute protection: the preference model must not infer or store signals correlated with protected attributes (race, religion, political views, health status). Topic taxonomy review: topics that could proxy for protected attributes (e.g., "Religious Technology", "Political Commentary") are flagged in the topic taxonomy. For flagged topics, the preference model stores explicit follow/hide actions but does not compute implicit affinity (no click/dwell tracking for these topics). This prevents the system from building a behavioral profile of a user's religious or political interests from their reading patterns—only their stated preferences are recorded.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Preference Query API Design</h3>
        <p>The Preference API is the interface between the preference store and all downstream consumers. It returns the preference model in a form optimized for the querying system's needs.</p>
        <p><code>{`GET /v1/preferences/{userId}`}</code>: returns the full preference model as JSON. Fields: topic_affinities (top 50 topics by |affinity| score, with confidence), format_preferences, reading_depth, recency_preference, confidence (overall), last_updated timestamp. Used by: the ranking model feature extraction pipeline (reads all fields), the preference dashboard (for display to the user).</p>
        <p><code>{`GET /v1/preferences/{userId}/topics?limit=20&surface=homepage`}</code>: returns the top N affinity topics for a specific surface, optimized for the ranking model&apos;s candidate retrieval stage. Returns topic IDs and affinity scores sorted by affinity descending. Latency target: &lt; 5ms (pure Redis lookup, no computation).</p>
        <p><code>{`POST /v1/preferences/{userId}/context`}</code>: submits the current session context (last 5 item IDs interacted with) and returns a context-adjusted preference vector that boosts the categories of the recent session items. Used by: the ranking model for real-time session-aware re-ranking. The context adjustment is computed in-memory by the API server (no additional data store access) and is not persisted. Latency target: &lt; 8ms.</p>
        <p>Caching strategy: the full preference model (<code>{`GET /v1/preferences/{userId}`}</code>) is cached in Redis with a 60-second TTL. The topics endpoint (<code>{`GET /v1/preferences/{userId}/topics`}</code>) is a pre-materialized view updated by the preference computation pipeline and has no TTL (it is always current). Cache invalidation: when the Flink pipeline updates a user&apos;s affinity, it also invalidates (deletes) the full preference model cache entry for that user. The next read will recompute from the pre-materialized topic affinities. This ensures that explicit signal changes (thumbs down, topic hide) are reflected in the next request after the Flink update completes (~5 seconds).</p>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <p>Implicit signal noise: implicit signals like click and dwell time are noisy proxies for preference. A user may click a sensational headline out of curiosity and leave immediately (low dwell, not a preference signal for that topic) or may dwell on an article because they are confused by it (high dwell, but negative preference). The signal weight calibration (treating dwell &lt; 30 seconds as weak positive and click-without-dwell as very weak positive) mitigates this, but noise is inherent. One approach to reduce noise is to use richer signals: article completion rate (did the user reach the bottom?), scroll velocity (rapid scroll vs. slow read), and return visits (did the user come back to the article from a direct URL?). These richer signals require more complex collection infrastructure but produce significantly less noise.</p>
        <p>Preference convergence vs. exploration: a preference model that learns too aggressively (high weights, fast updates) will converge to a narrow set of topics after a few sessions, locking the user into a preference filter bubble that is very hard to escape. The system should resist convergence by maintaining an exploration budget in the preference model: a fraction of the feed (10%) is reserved for content from topics adjacent to (but not in) the user's top affinity topics, specifically to broaden the preference model with exposure to new areas. This exploration budget is separate from the recommendation diversity guardrail—the preference model's exploration affects future preference updates, not just the current feed render.</p>
        <p>Preference model complexity vs. interpretability: a deep learning model (e.g., a transformer trained end-to-end on user interaction sequences) would likely produce more accurate preference predictions than the weighted affinity map described here. However, a deep model produces an opaque embedding that cannot be displayed to the user in the preference dashboard, cannot be manually edited, and cannot be audited for protected attribute inference. The structured preference model (topic affinity map + format preferences) is deliberately interpretable: users can understand and control it, and engineers can audit it for fairness. The interpretability trade-off is worth accepting for a user-facing preference system; opaque deep models are more appropriate for the ranking model layer (which users never directly see or control).</p>
      </section>

      <section>
        <h2>Summary</h2>
        <p>A user preference learning system maintains a per-user preference model that drives personalization across all surfaces. The data model: topic affinity map (topicId → decayed weighted sum of signals, range [−1.0, 1.0]), content format preferences, reading depth, recency preference, and confidence score (used to blend learned preferences with global defaults for cold-start users). Signal taxonomy: explicit signals (follow +1.0, save +0.5, thumbs down −0.8, hide topic −1.0) and implicit signals (dwell ≥ 90s +0.3, share +0.4, re-open +0.25), all subject to exponential decay (half-lives of 7–365 days depending on signal type). Two pipelines: Flink real-time (5-second latency, explicit + high-weight implicit signals, incremental Redis update) and Spark batch (15-minute cycle, full recomputation with decay, writes to Redis + S3). Cold start uses a confidence-weighted blend: new users (confidence=0) see global popularity; established users (confidence=0.9+) see fully personalized recommendations—no special-casing required. Privacy: data minimization at collection (bucketed dwell, no raw coordinates), right to erasure cascade (Redis and PostgreSQL synchronous, S3 within 24h), protected attribute topic suppression (no implicit signals for religion/politics proxies). The preference query API serves pre-materialized topic affinities from Redis at &lt; 5ms, with cache invalidation triggered by the Flink pipeline within 5 seconds of an explicit signal. The defining constraint: the preference model must be interpretable and user-controllable—users must be able to understand why they see what they see and correct it when the model is wrong.</p>
      </section>
    </ArticleLayout>
  );
}
