"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-user-personalization-engine-ui",
  title: "Design a User Personalization Engine UI",
  description:
    "Architecture for a user personalization engine UI: behavioral signal ingestion via Kafka, online/offline feature store (Redis + S3), two-stage ranking (ANN retrieval + LightGBM scoring), A/B experiment assignment, cold-start onboarding flow, UI injection points (feed/hero/sidebar), explainability tooltips, inline feedback controls, preference dashboard, and filter-bubble diversity guardrails.",
  category: "high-level-design",
  subcategory: "personalization-systems",
  slug: "user-personalization-engine-ui",
  wordCount: 5000,
  readingTime: 30,
  lastUpdated: "2026-05-11",
  tags: ["hld", "personalization", "recommendation", "feature-store", "ranking", "a-b-testing", "cold-start"],
  relatedTopics: ["recommendation-tuning-system", "user-preference-learning-system"],
};

export default function UserPersonalizationEngineUIArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A user personalization engine sits between a content catalog (articles, products, videos, courses) and the user-facing UI, dynamically selecting and ordering content for each individual user based on their inferred preferences. The core product goal is to show users the items most likely to be relevant to them at this moment—increasing engagement metrics (CTR, dwell time, return visits) while avoiding the negative patterns of hyper-personalization (filter bubbles, addiction loops, rabbit holes). From an engineering perspective, a personalization system must solve: fast inference (ranking must complete within 50ms to meet page load SLAs), signal collection without overwhelming the backend (behavioral events occur on every user interaction and must be batched and sampled), and cold start (new users have no behavioral history and must receive reasonable recommendations until enough signals accumulate).</HighlightBlock>
        <p>The UI layer of the personalization engine is not just the presentation of ranked results—it includes the feedback controls that let users tune their experience, the explainability layer that builds trust by explaining why certain content is shown, and the onboarding flow that seeds the initial user profile. A personalization system without a feedback UI is a black box that users distrust and cannot correct when it goes wrong.</p>
        <p><strong>Explicit assumptions:</strong> The personalization API is a separate service consumed by the frontend via REST (GET /personalized-feed?userId=&amp;surface=homepage&amp;limit=20). The frontend is responsible for rendering the ranked results, collecting behavioral signals (click, dwell, scroll), and sending feedback (like/dislike) back to the API. The ranking model (LightGBM) runs server-side; the frontend does not perform any ranking computation.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibuild">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Personalized feed:</strong> The homepage feed is ordered by the personalization engine (not reverse-chronological). Each user sees a different ordering based on their interest profile.</HighlightBlock>
          <li><strong>Signal collection:</strong> The frontend collects and reports: clicks, dwell time (time an item is in the viewport), scroll depth, saves, and shares. Signals are batched and sent in 30-second intervals to avoid flooding the event ingestion API.</li>
          <li><strong>Feedback controls:</strong> Each feed item has inline controls: "More like this" (positive), "Not interested" (negative), "Hide topic" (topic-level suppression for 7 days), and "Save." Feedback is applied immediately (optimistic) to the local feed state.</li>
          <li><strong>Explainability:</strong> A "Why am I seeing this?" tooltip on each item explains the primary reason (e.g., "You read 12 System Design articles this week" or "Popular with users who liked X").</li>
          <HighlightBlock as="li" tier="important"><strong>Preference dashboard:</strong> A settings page where users can view their inferred interests, remove topics, add topics, suppress topics, and adjust the "personalization strength" slider (0 = popularity-based, 10 = fully personalized).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Cold start:</strong> New users complete an interest picker (select 3+ topics) during onboarding. Until 10 behavioral interactions are logged, the feed uses geo-popular content as a fallback.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Ranking latency:</strong> The personalization API must respond within 50ms at P99 (Redis feature lookup + ANN retrieval + LightGBM scoring).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Feed freshness:</strong> The ranked feed must not serve items already seen by the user in the past 7 days (deduplication on server using a seen-item Bloom filter per user).</HighlightBlock>
          <li><strong>Diversity:</strong> No more than 3 consecutive items from the same source, and at least 10% of slots must be from categories outside the user's top 3 interests (filter-bubble prevention).</li>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The system has two planes. The offline plane (batch, runs daily + hourly): user behavioral events flow from the frontend via Kafka to a Spark/Flink feature pipeline that computes user interest vectors, category affinity scores, and recency-weighted signals. These features are written to the offline feature store (S3/Hive for long-horizon features) and the online feature store (Redis for low-latency serving). The ranking model is retrained daily on the latest features. The online plane (real-time, per-request): when a user loads their feed, the personalization API looks up the user's features from Redis (under 5ms), retrieves 500 candidate items using ANN (Approximate Nearest Neighbor) search on the user's embedding vector, scores each candidate with the LightGBM model (20ms for 500 items), applies diversity re-ranking, and returns the top K items. The API also validates the A/B experiment bucket assignment for the user (to serve the correct model variant for users in treatment groups).</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/personalization-systems/user-personalization-engine-architecture.svg"
          alt="User personalization engine architecture showing signal ingestion pipeline (behavioral events click dwell scroll search → event bus Kafka batched deduped → feature pipeline Spark Flink streaming → feature store Redis online S3 offline → ranking model LightGBM ONNX &lt;50ms → personalization API ranked slots fallback → UI surfaces feed hero sidebar), user profile model (explicit signals ratings likes saves follows preference settings topics content types; implicit signals dwell time per item rolling 30d click-through rate per category scroll depth share re-open frequency; context features time of day day of week device location coarse session recency), feature store and ranking model (feature lookup &lt;5ms online store Redis user embedding recent CTR item features Redis category age popularity score offline store S3/Hive long-horizon interest vectors; two-stage ranking stage 1 candidate retrieval ANN FAISS on user embedding top 500 items stage 2 precision ranking LightGBM scores each candidate top K returned; diversity freshness boosts re-rank cap same-source slots max 3 boost items &lt;24h old exploration budget 10% slots reserved for random fresh items), A/B layer and UI surface injection (experiment assignment Hash userId + experimentId mod 100 bucket bucketing control 50% vs treatment 50% sticky same bucket for same user across sessions; UI injection points hero banner personalized CTA based on category affinity feed order server-ranked items replace static chronological sidebar Recommended for you widget top 5 items search ranked results personalized you may also like; latency SLA personalization API P99 &lt;50ms Redis feature lookup fallback popularity-based ranking if user cold-start), cold start strategy (new user onboarding interest picker 3+ topics seed profile geo-trending plus global popular as default feed ramp switch from popularity to personalized after 10 interactions), privacy guardrails (no cross-user data user vectors stored per-user never merged GDPR forget me deletes feature store entries within 24h filter bubble guard inject 10% diverse-category items each render), feedback loop (implicit clicks/dwell logged Kafka feature pipeline model, explicit thumbs-up/down updates preference store immediately, model retrain daily batch Spark plus hourly online update Flink)."
          caption="Signal ingestion (Kafka → Spark → Feature Store Redis + S3), two-stage ranking (ANN retrieval → LightGBM scoring), A/B experiment assignment, UI injection surfaces, cold-start strategy, privacy guardrails, and feedback loop"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Signal Collection and Batching</h3>
        <HighlightBlock as="p" tier="important">The frontend collects behavioral signals using three mechanisms. Click signals: an onClick handler on each feed item logs the item ID, position in the feed, and timestamp to a local signal queue. Dwell signals: an IntersectionObserver watches feed item elements; when an item enters the viewport, a timer starts; when it leaves or the user navigates away, the accumulated dwell time is logged. Scroll depth: the maximum scroll percentage of each item's container is tracked. These signals accumulate in a local queue (in-memory, not persisted) and are flushed to POST /events every 30 seconds or when the queue reaches 50 events—whichever comes first. On page unload (beforeunload), navigator.sendBeacon flushes remaining queued events. The 30-second batching prevents the event ingestion endpoint from being overwhelmed by per-click requests (a user reading a feed may click 20 items in 5 minutes—batching reduces this to 10 API calls instead of 20).</HighlightBlock>
        <HighlightBlock as="p" tier="important">Signal deduplication: the event ingestion service deduplicates events using an idempotency key (userId + itemId + eventType + sessionId) in Redis with a 1-hour TTL. Duplicate events (from retried sends or double-taps) are discarded. Signal sampling: for very high-frequency events like scroll (which fires every 50ms), the frontend samples at 1Hz (one event per second) before adding to the queue, reducing scroll events from 100+ per minute to 60.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Feature Store Architecture</h3>
        <HighlightBlock as="p" tier="crucial">The feature store has two tiers. The online store (Redis): stores the features needed for real-time ranking lookup. Per-user features: interest embedding vector (128-dimensional float array, stored as a Redis Hash field), recent category CTR (click-through rate per category in the past 7 days), seen-item Bloom filter (for deduplication). Per-item features: category, publication age, global popularity score, embedding vector. Redis lookup latency is under 5ms for a typical user feature set. The offline store (S3/Hive): stores long-horizon features computed by the Spark batch job. Long-horizon user features: 90-day category affinity scores, lifetime save/share rates per topic. These features are refreshed daily and loaded into Redis by a scheduled sync job. Feature freshness: online features (Redis) reflect activity up to 30 seconds ago (Flink streaming pipeline). Offline features (S3) reflect the state as of the most recent daily batch run (up to 24 hours stale).</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Two-Stage Ranking</h3>
        <HighlightBlock as="p" tier="important">Ranking all items in the catalog (potentially millions) against a user's embedding vector on every request is computationally intractable. The two-stage approach solves this. Stage 1 — Candidate retrieval: the user's 128-dimensional interest embedding vector is looked up from Redis. A FAISS (Facebook AI Similarity Search) ANN index, precomputed over all item embeddings, returns the 500 items nearest to the user's vector in embedding space. ANN retrieval typically takes under 20ms for millions of items. The ANN index is updated periodically (hourly) as new items are published. Stage 2 — Precision ranking: the 500 candidates are scored by the LightGBM model, which takes rich features (user context, item metadata, interaction history) rather than just embedding similarity. LightGBM scores 500 items in under 20ms. The top K candidates (e.g., K=20 for a homepage feed) are returned after diversity re-ranking.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Diversity re-ranking: after LightGBM scoring, the ranked list is post-processed: (1) No more than 3 consecutive items from the same source domain. (2) No more than 30% of slots from the same category. (3) 10% of slots (2 out of 20) are replaced with randomly selected fresh items (published within 24 hours) from categories outside the user's top 3 interests. This exploration budget prevents the recommendation system from becoming a pure exploit loop that only shows the user content they already know they like.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">A/B Experiment Assignment</h3>
        <HighlightBlock as="p" tier="crucial">The personalization engine runs multiple simultaneous experiments (e.g., testing two different LightGBM model variants, testing different diversity ratios, testing the impact of explainability tooltips on engagement). Experiment assignment uses a consistent hash: bucket = Hash(userId + experimentId) mod 100. A user always falls in the same bucket for a given experiment (sticky assignment), ensuring consistent experience across sessions. The API reads the user's experiment assignments from a configuration service and applies the appropriate model variant and parameters for the request. Experiment metrics (CTR, dwell time, return rate) are logged per-bucket and analyzed in a metrics dashboard.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">UI Injection Points</h3>
        <HighlightBlock as="p" tier="important">The personalized results are injected into four UI surfaces. Feed: the homepage feed replaces static reverse-chronological ordering with the server-ranked order. The frontend receives an array of item IDs in ranked order from the API and renders them in that sequence. The feed includes a "mix" marker at position 10 ("Freshly published") that separates the top personalized items from newer but lower-personalized items—signaling to the user that personalization is active. Hero banner: the hero slot (the large feature item at the top of the page) is separately ranked for the user's highest-affinity category, providing a targeted hook for high-intent users. Sidebar widget: a "Recommended for you" sidebar shows the top 5 items personalized for this user in a compact card format. Search results: when a user searches, the results page ranks matching items partially by relevance and partially by the user's affinity for the item's category (boosting System Design results for a user with high System Design affinity even for a generic query like "caching").</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Feedback Controls and Optimistic UI</h3>
        <HighlightBlock as="p" tier="important">Each feed item has four feedback controls. "More like this" (👍): clicking immediately boosts the item's category weight in the local user profile store (Zustand) by +0.1, and the next feed refresh (on scroll-to-bottom or manual refresh) will show more items from that category. The signal is sent to the API as an explicit positive event. "Not interested" (👎): the item is immediately removed from the local feed state (optimistic removal—the item disappears from the user's view instantly). The server receives a negative event and applies a −1.0 score penalty to the item and similar items. "Hide topic" (🚫): the topic is added to a local suppression list (persisted to localStorage and synced to the API). All future feed renders filter out items from that topic for 7 days. "Save" (🔖): the item is added to the user's saved collection and receives a strong positive signal (+0.5).</HighlightBlock>
        <HighlightBlock as="p" tier="important">Optimistic UI for "Not interested": the item is removed from the rendered list immediately. If the API call fails (network error), the item is re-inserted at its original position with a toast ("Failed to hide — tap to retry"). This gives instant feedback without waiting for the server, which is critical for the moderation feel of the "Not interested" action.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Explainability Layer</h3>
        <HighlightBlock as="p" tier="important">Each item returned by the personalization API includes an explanation field: the primary reason this item was ranked highly for this user. The explanation is generated server-side by examining the top contributing features in the LightGBM model's SHAP (SHapley Additive exPlanations) values for this item-user pair. Explanation templates: "You read N [Category] articles this week" (category affinity); "Popular with users who liked [Previously Viewed Item]" (collaborative filtering signal); "Trending in [User's Location]" (geo-trending signal); "Based on your saved items" (save history); "New from [Author you follow]" (explicit follow relationship). The explanation is shown in a tooltip triggered by hovering over a "?" icon on the item card. This builds user trust and transparency—users understand why they are seeing recommendations and can take corrective action (unfollowing, hiding the topic) when the explanation reveals an incorrect inference.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Cold Start and Profile Decay</h3>
        <HighlightBlock as="p" tier="important">Cold start (new users): on signup, users complete a 3-step onboarding flow. Step 1: Interest picker—a grid of 20+ topic tiles (System Design, Frontend, Machine Learning, etc.); users select at least 3. Step 2: Level preference (Beginner/Intermediate/Advanced)—informs content complexity ranking. Step 3: confirmation; the selected topics are written immediately to the feature store as initial interest signals. Until 10 behavioral interactions are logged, the feed uses geo-trending + global popular as the ranked order. After 10 interactions, the system switches to personalized ranking. This ramp prevents the recommendation system from "locking in" to the user's stated interests before enough behavioral evidence validates them—revealed preferences (actual clicks) are more reliable than declared preferences (topic picker selections). Profile decay: if a user is inactive for 30 days, their signals decay by 50% (half-life 30 days, exponential decay e^(−λt)). After 90 days of inactivity, all signals are treated as expired and the user returns to cold-start mode. This prevents the system from recommending topics the user was interested in 6 months ago but has since moved past.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/personalization-systems/user-personalization-engine-ui.svg"
          alt="Personalization engine UI showing cold-start onboarding flow (Step 1 interest picker select 3+ topics visual grid search box skip option uses geo-popular; Step 2 level preference beginner intermediate advanced informs content complexity ranking feature; Step 3 seed profile written to feature store immediate popularity-ranked feed rendered while model initializes; Warm-up after 10 interactions switch to personalized ranking signal 10 clicks dwells saves logged trigger model switch); feed state machine COLD 10 events WARMING model ready ACTIVE stale STALE no activity 30 days decay features re-prompt onboarding interest. Explainability UX Why am I seeing this explanation tooltip (article card based on System Design 94%, explanation chip Why this? You read 12 System Design articles this week similar users also liked this published 2h ago). Inline feedback controls per item (More like this, Not interested, Hide topic, Save; Not interested: boost category weight +0.1, penalize item score, suppress category 7 days). Preference dashboard /settings/personalization (My Interests System Design Frontend Architecture tags with remove x, Suppressed Topics Crypto, Personalization strength slider Off to Full controls exploration ratio). Signal weight table (Save Bookmark +0.5 strong intent, Dwell &gt;90s +0.3 engaged read, Click +0.1 curiosity, Not interested −1.0 negative feedback). Signal decay e^(−λt) λ = ln(2)/30d half-life 30 days signal from 30d ago 50% weight hard reset 90 days signal treated cold recency boost items &lt;24h old +0.2 score. Latency budget feature lookup Redis &lt;5ms ANN retrieval FAISS &lt;20ms LightGBM scoring &lt;20ms total P99 &lt;50ms."
          caption="Cold-start onboarding (interest picker → seed profile → warm-up at 10 interactions), feed state machine, explainability tooltip, inline feedback controls with optimistic UI, preference dashboard, signal weights/decay, and latency budget"
        />
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">Filter bubbles versus engagement: a pure exploit personalization system (always show what the user has liked before) maximizes short-term engagement but creates filter bubbles where users only see content confirming their existing views, and discover nothing new. The 10% exploration budget (random fresh items from outside top interests) and category diversity caps are guardrails against this. The trade-off is a small reduction in CTR for those 10% slots (users are less likely to click unfamiliar content) offset by improved long-term retention and user satisfaction (users report feeling "surprised and delighted" by serendipitous discoveries). The exploration ratio should be tunable per user (the "personalization strength" slider) and measured via A/B test for its effect on 30-day retention versus 1-day CTR.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Collaborative filtering versus content-based: content-based personalization (recommend items similar to what this user has liked, based on item attributes) works well when the user has explicit signals but does not benefit from other users' data. Collaborative filtering (recommend what similar users have liked) can surface items the user would not have found through content similarity alone, but requires a minimum number of interactions (typically 5+) to find similar users. The two-stage system combines both: the ANN embedding retrieval uses user-item collaborative embeddings (trained on all users' interaction history), while LightGBM incorporates content features. This hybrid captures both the "users like you liked this" signal and the "this matches your stated interests" signal.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Real-time versus batch feature updates: the Flink streaming pipeline updates the online feature store within 30 seconds of a behavioral event. This means a user who saves 3 articles in a category will see that category boosted in their feed within 30 seconds. The alternative (batch-only updates) would make the feed feel unresponsive to recent actions. The cost is the complexity of the streaming pipeline (Flink infrastructure, schema management, exactly-once delivery guarantees). For smaller platforms, a simplified approach is feasible: update the user's interest weights synchronously on each explicit feedback action (like/dislike) and use batch updates only for implicit signals.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A user personalization engine UI has three client-side concerns: signal collection (batched every 30s via IntersectionObserver for dwell, onClick for clicks, sampled scroll for depth), feedback controls (inline per-item thumbs/hide/save with optimistic UI), and profile transparency (preference dashboard + explainability tooltips). The server-side pipeline: behavioral events → Kafka → Flink streaming → online feature store (Redis, &lt;5ms lookup) → two-stage ranking (ANN FAISS retrieval 500 candidates + LightGBM precision scoring, total &lt;50ms P99) → diversity re-ranking (max 3 consecutive same-source, 10% exploration budget) → ranked feed. Cold start uses an interest picker (3+ topics) seeding the feature store immediately; the system ramps from popularity-based to personalized ranking after 10 behavioral interactions. A/B experiments use Hash(userId + experimentId) mod 100 for sticky consistent assignment. Explainability is driven by SHAP feature attribution from LightGBM, templated into natural language reasons. Profile decay uses exponential half-life (30 days) to prevent stale interest signals from dominating. The defining design constraint: personalization must not trap users—the exploration budget, diversity caps, topic suppression controls, and filter-bubble guardrails ensure the system broadens rather than narrows the user's content universe over time.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
