import type { ArticleRegistry } from "@/types/article";

/**
 * Article Registry
 *
 * This registry maps article paths to their metadata and dynamic loaders.
 * Format: "{category}/{subcategory}/{topic}-{version}"
 *
 * Example:
 * "frontend/rendering-strategies/client-side-rendering-concise": {
 *   metadata: {
 *     id: "article-frontend-csr-concise",
 *     title: "Client-Side Rendering (CSR)",
 *     description: "Overview of client-side rendering patterns and implementation.",
 *     category: "frontend",
 *     subcategory: "rendering-strategies",
 *     slug: "client-side-rendering",
 *     version: "concise",
 *     wordCount: 2500,
 *     readingTime: 10,
 *     lastUpdated: "2026-03-05",
 *     tags: ["rendering", "CSR", "browser"],
 *     relatedTopics: ["server-side-rendering", "static-site-generation"],
 *   },
 *   loader: () => import("./articles/frontend/rendering-strategies/client-side-rendering-concise"),
 * },
 *
 * Articles will be added to this registry using the generate-article-stub.ts script.
 */
export const articleRegistry: ArticleRegistry = {
  // Articles will be populated here as they are created
  "frontend/rendering-strategies/client-side-rendering-concise": {
    metadata: {
      id: "article-frontend-client-sid-concise",
      title: "Client-Side Rendering (CSR)",
      description: "Comprehensive guide to Client-Side Rendering (CSR) covering concepts, implementation, and best practices.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "client-side-rendering",
      version: "concise",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/client-side-rendering-concise"),
  },
  "frontend/rendering-strategies/client-side-rendering-extensive": {
    metadata: {
      id: "article-frontend-client-sid-extensive",
      title: "Client-Side Rendering (CSR)",
      description: "Comprehensive guide to Client-Side Rendering (CSR) covering concepts, implementation, and best practices.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "client-side-rendering",
      version: "extensive",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/client-side-rendering-extensive"),
  },
  "frontend/rendering-strategies/server-side-rendering-concise": {
    metadata: {
      id: "article-frontend-server-sid-concise",
      title: "Server-Side Rendering (SSR)",
      description: "Comprehensive guide to server-side rendering, covering execution, benefits, trade-offs, and implementation strategies.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "server-side-rendering",
      version: "concise",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","SSR","performance","SEO"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/server-side-rendering-concise"),
  },
  "frontend/rendering-strategies/server-side-rendering-extensive": {
    metadata: {
      id: "article-frontend-server-sid-extensive",
      title: "Server-Side Rendering (SSR)",
      description: "Comprehensive guide to server-side rendering, covering execution, benefits, trade-offs, and implementation strategies.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "server-side-rendering",
      version: "extensive",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","SSR","performance","SEO"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/server-side-rendering-extensive"),
  },
  "frontend/rendering-strategies/static-site-generation-concise": {
    metadata: {
      id: "article-frontend-static-sit-concise",
      title: "Static Site Generation (SSG)",
      description: "Deep dive into static site generation, pre-rendering strategies, build-time optimization, and when to use SSG.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "static-site-generation",
      version: "concise",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","SSG","performance","JAMstack"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/static-site-generation-concise"),
  },
  "frontend/rendering-strategies/static-site-generation-extensive": {
    metadata: {
      id: "article-frontend-static-sit-extensive",
      title: "Static Site Generation (SSG)",
      description: "Deep dive into static site generation, pre-rendering strategies, build-time optimization, and when to use SSG.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "static-site-generation",
      version: "extensive",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","SSG","performance","JAMstack"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/static-site-generation-extensive"),
  },
  "frontend/rendering-strategies/incremental-static-regeneration-concise": {
    metadata: {
      id: "article-frontend-incrementa-concise",
      title: "Incremental Static Regeneration (ISR)",
      description: "Complete guide to ISR, combining static generation with on-demand revalidation for dynamic content at scale.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "incremental-static-regeneration",
      version: "concise",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","ISR","Next.js","hybrid"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/incremental-static-regeneration-concise"),
  },
  "frontend/rendering-strategies/incremental-static-regeneration-extensive": {
    metadata: {
      id: "article-frontend-incrementa-extensive",
      title: "Incremental Static Regeneration (ISR)",
      description: "Complete guide to ISR, combining static generation with on-demand revalidation for dynamic content at scale.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "incremental-static-regeneration",
      version: "extensive",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","ISR","Next.js","hybrid"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/incremental-static-regeneration-extensive"),
  },
  "frontend/rendering-strategies/progressive-hydration-concise": {
    metadata: {
      id: "article-frontend-progressiv-concise",
      title: "Progressive Hydration",
      description: "Learn progressive hydration techniques for optimizing time-to-interactive by gradually activating components based on priority.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "progressive-hydration",
      version: "concise",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","hydration","performance","interactivity"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/progressive-hydration-concise"),
  },
  "frontend/rendering-strategies/progressive-hydration-extensive": {
    metadata: {
      id: "article-frontend-progressiv-extensive",
      title: "Progressive Hydration",
      description: "Learn progressive hydration techniques for optimizing time-to-interactive by gradually activating components based on priority.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "progressive-hydration",
      version: "extensive",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","hydration","performance","interactivity"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/progressive-hydration-extensive"),
  },
  "frontend/rendering-strategies/selective-hydration-concise": {
    metadata: {
      id: "article-frontend-selective--concise",
      title: "Selective Hydration",
      description: "Master selective hydration patterns to hydrate only interactive components, reducing JavaScript overhead and improving performance.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "selective-hydration",
      version: "concise",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","hydration","React","performance"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/selective-hydration-concise"),
  },
  "frontend/rendering-strategies/selective-hydration-extensive": {
    metadata: {
      id: "article-frontend-selective--extensive",
      title: "Selective Hydration",
      description: "Master selective hydration patterns to hydrate only interactive components, reducing JavaScript overhead and improving performance.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "selective-hydration",
      version: "extensive",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","hydration","React","performance"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/selective-hydration-extensive"),
  },
  "frontend/rendering-strategies/islands-architecture-concise": {
    metadata: {
      id: "article-frontend-islands-ar-concise",
      title: "Islands Architecture",
      description: "Explore islands architecture pattern for building performant web apps with isolated interactive components in a sea of static content.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "islands-architecture",
      version: "concise",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","architecture","Astro","performance"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/islands-architecture-concise"),
  },
  "frontend/rendering-strategies/islands-architecture-extensive": {
    metadata: {
      id: "article-frontend-islands-ar-extensive",
      title: "Islands Architecture",
      description: "Explore islands architecture pattern for building performant web apps with isolated interactive components in a sea of static content.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "islands-architecture",
      version: "extensive",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","architecture","Astro","performance"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/islands-architecture-extensive"),
  },
  "frontend/rendering-strategies/streaming-ssr-concise": {
    metadata: {
      id: "article-frontend-streaming--concise",
      title: "Streaming SSR",
      description: "Understand streaming server-side rendering for faster time-to-first-byte and improved perceived performance with progressive content delivery.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "streaming-ssr",
      version: "concise",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","SSR","streaming","React","performance"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/streaming-ssr-concise"),
  },
  "frontend/rendering-strategies/streaming-ssr-extensive": {
    metadata: {
      id: "article-frontend-streaming--extensive",
      title: "Streaming SSR",
      description: "Understand streaming server-side rendering for faster time-to-first-byte and improved perceived performance with progressive content delivery.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "streaming-ssr",
      version: "extensive",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","SSR","streaming","React","performance"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/streaming-ssr-extensive"),
  },
  "frontend/rendering-strategies/edge-rendering-concise": {
    metadata: {
      id: "article-frontend-edge-rende-concise",
      title: "Edge Rendering",
      description: "Learn edge rendering strategies for delivering personalized content with minimal latency using edge compute platforms.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "edge-rendering",
      version: "concise",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","edge","CDN","performance","Vercel"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/edge-rendering-concise"),
  },
  "frontend/rendering-strategies/edge-rendering-extensive": {
    metadata: {
      id: "article-frontend-edge-rende-extensive",
      title: "Edge Rendering",
      description: "Learn edge rendering strategies for delivering personalized content with minimal latency using edge compute platforms.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "edge-rendering",
      version: "extensive",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","edge","CDN","performance","Vercel"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/edge-rendering-extensive"),
  },
  "frontend/rendering-strategies/partial-hydration-concise": {
    metadata: {
      id: "article-frontend-partial-hy-concise",
      title: "Partial Hydration",
      description: "Discover partial hydration techniques for shipping less JavaScript by hydrating only necessary components on demand.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "partial-hydration",
      version: "concise",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","hydration","performance","optimization"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/partial-hydration-concise"),
  },
  "frontend/rendering-strategies/partial-hydration-extensive": {
    metadata: {
      id: "article-frontend-partial-hy-extensive",
      title: "Partial Hydration",
      description: "Discover partial hydration techniques for shipping less JavaScript by hydrating only necessary components on demand.",
      category: "frontend",
      subcategory: "rendering-strategies",
      slug: "partial-hydration",
      version: "extensive",
      wordCount: 0,
      readingTime: 0,
      lastUpdated: "2026-03-05",
      tags: ["frontend","rendering","hydration","performance","optimization"],
    },
    loader: () => import("./articles/frontend/rendering-strategies/partial-hydration-extensive"),
  },
};
