/**
 * Subcategory Articles Manifest — other
 *
 * AUTO-GENERATED by scripts/generate-article-routes.ts
 * DO NOT EDIT MANUALLY
 *
 * To update: run `pnpm generate-article-routes`
 */

export const otherArticles: Record<string, Array<{slug: string; title: string; description: string}>> = {
  "other/artificial-intelligence/additional-topics": [
    {
      "slug": "agent-orchestration",
      "title": "Agent Orchestration — Multi-Agent Coordination Patterns",
      "description": "Comprehensive guide to agent orchestration covering supervisor patterns, routing strategies, crew patterns, hierarchical planning, task decomposition, and production multi-agent architectures."
    },
    {
      "slug": "hugging-face",
      "title": "Hugging Face Ecosystem",
      "description": "Comprehensive guide to the Hugging Face ecosystem covering the Model Hub, Datasets library, Inference API, Spaces, AutoTrain, and the broader open-source AI infrastructure."
    },
    {
      "slug": "langchain",
      "title": "LangChain Framework — Building LLM Applications",
      "description": "Comprehensive guide to LangChain covering framework architecture, chains, memory systems, tools, agents, expression language, and evaluation for production LLM application development."
    },
    {
      "slug": "plugins",
      "title": "AI Plug-In Architecture — Extensibility and Sandboxing",
      "description": "Comprehensive guide to AI plug-in architecture covering extensibility patterns, sandboxing, capability negotiation, security boundaries, and production plugin ecosystem design."
    },
    {
      "slug": "workflow",
      "title": "AI Workflow Design — Pipelines, Evaluation Loops, and CI/CD for AI",
      "description": "Comprehensive guide to AI workflow design covering pipeline patterns, evaluation loops, CI/CD for AI systems, human-in-the-loop processes, and production workflow architecture."
    }
  ],
  "other/artificial-intelligence/core-concepts": [
    {
      "slug": "agentic-rag",
      "title": "Agentic RAG — Advanced Retrieval Patterns for Production AI Systems",
      "description": "Comprehensive guide to agentic RAG covering HyDE, multi-query retrieval, parent-child chunking, self-querying retrieval, multi-hop reasoning, GraphRAG, structured data RAG (text-to-SQL), and enterprise multi-tenant retrieval architectures."
    },
    {
      "slug": "agents",
      "title": "AI Agents — Autonomous LLM-Powered Systems",
      "description": "Comprehensive guide to AI agents covering agent loops, ReAct paradigm, tool use and function calling, memory systems, planning strategies, and action execution for building autonomous LLM-powered systems."
    },
    {
      "slug": "ai-application-architecture",
      "title": "AI Application Architecture — Integration Patterns for Production",
      "description": "Comprehensive guide to AI application architecture covering sync vs async integration, streaming responses, fallback strategies, latency SLOs, error handling, rate limiting, and production system design patterns."
    },
    {
      "slug": "ai-cost-management",
      "title": "AI Cost Management — Token Economics and Budget Optimization",
      "description": "Comprehensive guide to AI cost management covering token economics, response caching, model selection for cost optimization, budget guardrails, usage quotas, and production cost control strategies."
    },
    {
      "slug": "ai-inference-serving",
      "title": "AI Inference Serving — vLLM, TGI, and Production LLM Deployment",
      "description": "Comprehensive guide to AI inference serving covering vLLM, Text Generation Inference, TensorRT-LLM, continuous batching, PagedAttention, KV cache management, quantization formats in serving, GPU scheduling, and throughput optimization for production LLM deployments."
    },
    {
      "slug": "ai-memory-architecture",
      "title": "AI Memory Architecture — Long-term Memory for Agents and AI Systems",
      "description": "Comprehensive guide to AI memory architecture covering episodic, semantic, and procedural memory types, vector memory stores, key-value memory, memory consolidation strategies, privacy-aware memory (retention and deletion policies), and production memory system design for long-running AI agents."
    },
    {
      "slug": "ai-model-deployment",
      "title": "AI Model Deployment — Serving Patterns and Production Operations",
      "description": "Comprehensive guide to AI model deployment covering model serving patterns (batch, real-time, edge), model versioning, canary deployments for AI, model rollback, blue-green for models, and production serving infrastructure."
    },
    {
      "slug": "ai-observability-monitoring",
      "title": "AI Observability and Monitoring",
      "description": "Comprehensive guide to AI observability covering LLM tracing, evaluation frameworks, quality metrics, cost tracking, latency monitoring, and drift detection for production AI systems."
    },
    {
      "slug": "ai-safety-security",
      "title": "AI Safety and Security — Prompt Injection, Data Leakage, and Governance",
      "description": "Comprehensive guide to AI safety covering prompt injection attacks, data leakage prevention, output validation, adversarial attacks, content moderation, jailbreak detection, and responsible AI governance."
    },
    {
      "slug": "ai-testing-evaluation",
      "title": "AI Testing and Evaluation — Quality Assurance for LLM Systems",
      "description": "Comprehensive guide to AI testing and evaluation covering output testing patterns, evaluation frameworks (RAGAS, DeepEval), golden datasets, regression testing for AI, A/B testing models, and quality gates."
    },
    {
      "slug": "context-window",
      "title": "Context Window — Architecture and Management",
      "description": "Comprehensive guide to context windows covering KV caching, sliding window attention, context compression, RoPE, long-context retrieval, and production context management strategies."
    },
    {
      "slug": "data-engineering-for-ai",
      "title": "Data Engineering for AI — Training Data Pipelines and Curation",
      "description": "Comprehensive guide to data engineering for AI covering data pipelines for training and fine-tuning, data cleaning, synthetic data generation, data labeling strategies, dataset versioning, and data quality management."
    },
    {
      "slug": "embeddings",
      "title": "Embeddings — Semantic Vector Representations",
      "description": "Comprehensive guide to embeddings covering embedding properties, dimensionality trade-offs, semantic similarity, clustering, classification, embedding model selection, and multimodal embeddings."
    },
    {
      "slug": "fine-tuning-vs-rag",
      "title": "Fine-Tuning vs RAG — The Core Architectural Decision",
      "description": "Comprehensive guide to fine-tuning versus RAG trade-offs covering PEFT/LoRA/QLoRA, evaluation methodology, production decision frameworks, and when to use each approach."
    },
    {
      "slug": "large-language-models",
      "title": "Large Language Models (LLMs)",
      "description": "Comprehensive guide to Large Language Models covering transformer architecture, training methodology, scaling laws, capabilities, limitations, and production considerations for software engineers integrating LLMs into applications."
    },
    {
      "slug": "llm-gateway",
      "title": "LLM Gateway — Centralized AI Proxy for Production Systems",
      "description": "Comprehensive guide to the LLM Gateway pattern covering unified auth, intelligent model routing, cost attribution, rate limiting, semantic caching, request logging, and production architecture for centralizing all LLM calls in an organization."
    },
    {
      "slug": "mcp",
      "title": "Model Context Protocol (MCP)",
      "description": "Comprehensive guide to the Model Context Protocol covering standardized tool-use architecture, resource discovery, server/client design, integrations, and building MCP-compatible tools and servers."
    },
    {
      "slug": "multi-agents",
      "title": "Multi-Agent Systems — Coordinated AI Agent Architectures",
      "description": "Comprehensive guide to multi-agent systems covering agent orchestration patterns, coordination strategies, debate and consensus mechanisms, role specialization, conflict resolution, and production-scale multi-agent architectures."
    },
    {
      "slug": "multi-modal-ai",
      "title": "Multi-Modal AI — Vision, Audio, and Document Understanding Systems",
      "description": "Comprehensive guide to multi-modal AI covering vision language models (VLMs), image input and generation APIs, document understanding (PDF extraction, table parsing), audio transcription integration, multi-modal RAG, and production architecture for systems combining text, images, audio, and documents."
    },
    {
      "slug": "prompt-optimization",
      "title": "Prompt Optimization — DSPy, OPRO, and Systematic Prompt Engineering",
      "description": "Comprehensive guide to prompt optimization covering DSPy (Declarative Self-Improving LM Programs), OPRO (Optimization by PROmpting), self-consistency with majority voting, tree-of-thought, systematic A/B testing for prompts, prompt regression testing in CI/CD, and automated prompt improvement techniques."
    },
    {
      "slug": "prompting",
      "title": "Prompt Engineering & Prompt Design Patterns",
      "description": "Comprehensive guide to prompt engineering covering system prompts, few-shot prompting, chain-of-thought reasoning, structured output generation, prompt templating, versioning, and production prompt management."
    },
    {
      "slug": "rag",
      "title": "Retrieval-Augmented Generation (RAG)",
      "description": "Comprehensive guide to RAG covering document chunking strategies, embedding pipelines, retrieval optimization, hybrid search, reranking, and RAG evaluation frameworks for production systems."
    },
    {
      "slug": "skills",
      "title": "Skills — LLM Capability Discovery and Composition",
      "description": "Comprehensive guide to skill systems for LLM agents covering skill registration, capability discovery, composition, routing, and skill-based agent architecture."
    },
    {
      "slug": "structured-output",
      "title": "Structured Output — JSON Mode, Function Calling, and Constrained Generation",
      "description": "Comprehensive guide to structured output covering JSON mode, function calling APIs, constrained decoding with Outlines and Guidance, schema validation, retry strategies for parse failures, and reliability patterns for extracting structured data from LLMs."
    },
    {
      "slug": "tokens",
      "title": "Tokens — Tokenization in Large Language Models",
      "description": "Deep dive into tokenization algorithms (BPE, WordPiece, SentencePiece), token economics, cost implications, multilingual tokenization, and how token design affects LLM performance and production systems."
    },
    {
      "slug": "vector-db",
      "title": "Vector Databases — Semantic Search at Scale",
      "description": "Comprehensive guide to vector databases covering vector indexing algorithms (HNSW, IVF, PQ), similarity metrics, scaling strategies, product comparison, and production vector database architecture."
    }
  ],
  "other/data-structures-algorithms/algorithms": [
    {
      "slug": "activity-selection",
      "title": "Activity Selection",
      "description": "Activity selection — the canonical greedy: earliest-finish-first for max non-overlapping activities, exchange-argument proof, and variants (min rooms, weighted intervals)."
    },
    {
      "slug": "backtracking-fundamentals",
      "title": "Backtracking Fundamentals",
      "description": "Backtracking — choose-explore-unchoose template, state-space tree, pruning strategies (constraint propagation, bound, symmetry, MRV), and patterns for combinatorial search."
    },
    {
      "slug": "bellman-ford",
      "title": "Bellman-Ford Algorithm",
      "description": "Single-source shortest paths that tolerate negative edges and detect negative cycles — the V-1 relaxation passes, SPFA, Johnson's reweighting, and the routing-protocol legacy."
    },
    {
      "slug": "bfs",
      "title": "Breadth-First Search (BFS)",
      "description": "BFS — layer-by-layer graph traversal, shortest paths in unweighted graphs, multi-source / 0-1 / bidirectional variants, and direction-optimizing scaling to billion-vertex graphs."
    },
    {
      "slug": "binary-search",
      "title": "Binary Search",
      "description": "Binary Search — O(log n) divide-and-conquer search over sorted data. The lower_bound / upper_bound / parametric-search template behind databases, compilers, and rate limiters."
    },
    {
      "slug": "bipartite-matching",
      "title": "Bipartite Matching — Augmenting Paths &amp; Hopcroft-Karp",
      "description": "Bipartite matching finds the largest set of vertex-disjoint edges between two vertex sets — the foundation for job assignment, scheduling, and network flow problems."
    },
    {
      "slug": "bitmask-dp",
      "title": "Bitmask DP (TSP and Beyond)",
      "description": "Bitmask DP — subset-indexed DP with 2ⁿ states. Held-Karp TSP in O(n²·2ⁿ), assignment, profile DP, and sum-over-subsets transforms."
    },
    {
      "slug": "boyer-moore",
      "title": "Boyer-Moore String Matching",
      "description": "Sublinear average-case substring search using right-to-left comparison with bad-character and good-suffix heuristics — the algorithm behind grep, ripgrep, and libc's strstr."
    },
    {
      "slug": "bubble-sort",
      "title": "Bubble Sort",
      "description": "Staff-level deep dive into bubble sort — adjacent-swap mechanics, early-termination optimization, cocktail-shaker variant, cache behavior, and the educational role bubble sort plays despite its O(n²) disqualification from production."
    },
    {
      "slug": "bucket-sort",
      "title": "Bucket Sort",
      "description": "Bucket Sort — distribute into k buckets, sort each, concatenate. Linear expected time on uniformly distributed data; the sort behind histogram equalization and range partitioning."
    },
    {
      "slug": "coin-change",
      "title": "Coin Change",
      "description": "Coin change — the canonical unbounded-knapsack problem. Min-coins DP, count-of-ways, why greedy fails, canonical systems, and BFS/Dijkstra alternatives for huge amounts."
    },
    {
      "slug": "counting-sort",
      "title": "Counting Sort",
      "description": "Counting Sort — non-comparative linear-time sorting for small integer ranges. The stable workhorse inside radix sort and histogram-based sorts."
    },
    {
      "slug": "dfs",
      "title": "Depth-First Search (DFS)",
      "description": "DFS — recursive and iterative graph traversal, edge classification, three-color cycle detection, and applications in topological sort, SCC, articulation points, and backtracking."
    },
    {
      "slug": "dijkstra",
      "title": "Dijkstra's Algorithm",
      "description": "Single-source shortest paths on graphs with non-negative edge weights — the greedy relaxation skeleton, priority-queue tradeoffs, and production variants from A* to contraction hierarchies."
    },
    {
      "slug": "divide-and-conquer",
      "title": "Divide & Conquer + Master Theorem",
      "description": "Divide & conquer paradigm — recurrence relations, Master Theorem cases, Akra–Bazzi generalization, and production applications from merge sort to MapReduce."
    },
    {
      "slug": "dp-fundamentals",
      "title": "Dynamic Programming Fundamentals",
      "description": "DP Fundamentals — optimal substructure, overlapping subproblems, memoization vs tabulation, state design, and the principled path from recursion to O(n²) wins."
    },
    {
      "slug": "dp-on-trees",
      "title": "Dynamic Programming on Trees",
      "description": "DP on trees — subtree DP in a single DFS, rerooting for all-root answers in linear time, and pattern variants for MIS, diameter, and tree knapsack."
    },
    {
      "slug": "edit-distance",
      "title": "Edit Distance (Levenshtein)",
      "description": "Levenshtein edit distance — O(mn) DP, the three-operation recurrence, Hirschberg's space-optimal variant, banded Ukkonen, and applications from spell check to DNA alignment."
    },
    {
      "slug": "exponential-search",
      "title": "Exponential Search",
      "description": "Exponential Search — doubling-bracket then binary search. O(log i) for unbounded sorted streams and arrays where the target is near the start."
    },
    {
      "slug": "floyd-warshall",
      "title": "Floyd-Warshall Algorithm",
      "description": "All-pairs shortest paths in O(V³) — the three-nested-loop dynamic program, semiring generalization to transitive closure and bottleneck paths, and where it beats running Dijkstra V times."
    },
    {
      "slug": "graph-coloring",
      "title": "Graph Coloring & Chromatic Number",
      "description": "Graph coloring assigns colors to vertices so no two adjacent vertices share a color — the foundation of register allocation, exam scheduling, and frequency assignment, with greedy algorithms for practical solutions and NP-hardness for exact chromatic number."
    },
    {
      "slug": "greedy-fundamentals",
      "title": "Greedy Algorithm Fundamentals",
      "description": "Greedy algorithms — greedy-choice property, optimal substructure, exchange arguments, matroids, fractional knapsack, and when to reach for DP instead."
    },
    {
      "slug": "heap-sort",
      "title": "Heap Sort",
      "description": "Heap Sort — guaranteed O(n log n) in-place sorting via binary-heap extraction. Introsort's safety net and the Linux kernel's sort of choice."
    },
    {
      "slug": "huffman-coding",
      "title": "Huffman Coding",
      "description": "Huffman coding — optimal prefix codes via greedy merge, canonical Huffman, length-limited variants, and its role in DEFLATE and JPEG."
    },
    {
      "slug": "insertion-sort",
      "title": "Insertion Sort",
      "description": "Staff-level deep dive into insertion sort — shift-and-insert mechanics, adaptiveness on nearly-sorted input, binary insertion variant, the role as small-array base case in Tim Sort and Pdqsort, and cache-friendly O(nk) behavior."
    },
    {
      "slug": "interpolation-search",
      "title": "Interpolation Search",
      "description": "Interpolation Search — O(log log n) on uniformly distributed sorted data by guessing position from value, O(n) worst case on skewed data."
    },
    {
      "slug": "job-sequencing",
      "title": "Job Sequencing with Deadlines",
      "description": "Job sequencing — max-profit selection under deadlines via greedy + DSU or min-heap, exchange-argument proof, and scheduling-family comparisons."
    },
    {
      "slug": "jump-search",
      "title": "Jump Search",
      "description": "Jump Search — O(√n) block-skipping search on sorted arrays. A middle ground between linear and binary when random access is expensive."
    },
    {
      "slug": "karatsuba-multiplication",
      "title": "Karatsuba Multiplication",
      "description": "Karatsuba multiplication — the first sub-quadratic integer multiplication, divide-and-conquer with three sub-multiplications, Toom–Cook and Schönhage–Strassen successors."
    },
    {
      "slug": "kmp",
      "title": "Knuth-Morris-Pratt (KMP)",
      "description": "Linear-time exact string matching via the failure function — the LPS array, the no-text-backtrack invariant, and how KMP generalizes to Z-algorithm, Aho-Corasick, and string-period analysis."
    },
    {
      "slug": "knapsack-01",
      "title": "0/1 Knapsack",
      "description": "0/1 Knapsack — the archetypal DP. O(nW) pseudo-polynomial, NP-hard in input size. Unbounded, subset-sum, and meet-in-the-middle variants."
    },
    {
      "slug": "kruskals-mst",
      "title": "Kruskal's Minimum Spanning Tree",
      "description": "Greedy edge selection with union-find — sort edges, accept those that don't form a cycle, stop at V-1. The cut and cycle properties, comparison with Prim and Borůvka, and production extensions."
    },
    {
      "slug": "linear-search",
      "title": "Linear Search",
      "description": "Linear Search — sequential O(n) scan. The default, cache-optimal, branchless-friendly search for small, unsorted, or streaming data."
    },
    {
      "slug": "longest-common-subsequence",
      "title": "Longest Common Subsequence (LCS)",
      "description": "LCS — the O(mn) DP underlying diff, git merge, bioinformatics alignment, and version control. State design and Hunt-Szymanski optimization."
    },
    {
      "slug": "longest-increasing-subsequence",
      "title": "Longest Increasing Subsequence (LIS)",
      "description": "LIS — from O(n²) DP to O(n log n) patience-sort. Patience piles, tail arrays, binary search, and the Erdős-Szekeres connection."
    },
    {
      "slug": "maximum-flow",
      "title": "Maximum Flow — Ford-Fulkerson, Edmonds-Karp &amp; Dinic's",
      "description": "Maximum flow algorithms find the greatest feasible flow through a capacity-constrained network from source to sink — the foundation of network reliability, bipartite matching, and assignment problems."
    },
    {
      "slug": "merge-sort",
      "title": "Merge Sort",
      "description": "Staff-level deep dive into merge sort — divide-and-conquer mechanics, stable merge, top-down vs bottom-up, in-place and natural variants, Tim Sort and external merge sort as production descendants."
    },
    {
      "slug": "n-queens",
      "title": "N-Queens",
      "description": "N-Queens — the canonical backtracking benchmark. Place n queens on n×n board with no two attacking via row-by-row DFS, bitmask state, and symmetry pruning."
    },
    {
      "slug": "np-completeness",
      "title": "NP-Completeness & Computational Complexity",
      "description": "NP-completeness theory explains why certain problems are computationally hard — P/NP/NP-hard/NP-complete classes, polynomial reductions, Cook-Levin theorem, classic NP-complete problems, and practical coping strategies including approximation algorithms, FPT, and heuristics."
    },
    {
      "slug": "permutations-and-combinations",
      "title": "Permutations & Combinations",
      "description": "Permutations, combinations, and subsets via backtracking — three skeletons (subsets, permute, combine), bitmask iteration, lexicographic next_permutation, Heap's Algorithm, and duplicate handling."
    },
    {
      "slug": "prims-mst",
      "title": "Prim's Minimum Spanning Tree",
      "description": "Frontier-based MST construction with a min-heap — grow the tree by always pulling the cheapest crossing edge. Cut-property correctness, dense-graph wins, and how it relates to Dijkstra."
    },
    {
      "slug": "quick-sort",
      "title": "Quick Sort",
      "description": "Quick Sort — partition-based in-place sorting with expected O(n log n), the workhorse behind introsort, Pdqsort, and most production sort() implementations."
    },
    {
      "slug": "quickselect",
      "title": "Quickselect",
      "description": "Quickselect — linear-time k-th smallest via partition-and-recurse, randomized pivoting, median-of-medians worst-case, and production top-k patterns."
    },
    {
      "slug": "rabin-karp",
      "title": "Rabin-Karp Algorithm",
      "description": "Rolling-hash pattern matching that wins on multi-pattern, 2D, and fingerprinting problems — polynomial hashing, collision strategy, and the rsync/dedup ecosystem built on top of it."
    },
    {
      "slug": "radix-sort",
      "title": "Radix Sort",
      "description": "Radix Sort — LSD and MSD variants, digit-by-digit linear-time sorting. The fastest known sort for fixed-width integer keys on both CPU and GPU."
    },
    {
      "slug": "randomized-algorithms",
      "title": "Randomized Algorithms",
      "description": "Randomized algorithms leverage randomness for better expected performance — Las Vegas vs Monte Carlo distinction, QuickSort expected O(n log n) analysis, universal hashing, reservoir sampling, Chernoff bounds, Bloom filters, and probabilistic data structures used in production systems."
    },
    {
      "slug": "selection-sort",
      "title": "Selection Sort",
      "description": "Staff-level deep dive into selection sort — the minimum-swap comparison sort, tournament-selection extension, heapsort as the O(n log n) descendant, and why selection sort wins when writes are the dominant cost."
    },
    {
      "slug": "shell-sort",
      "title": "Shell Sort",
      "description": "Staff-level deep dive into Shell sort — gap sequences, h-sortedness, theoretical complexity bounds for Shell, Hibbard, Sedgewick, Ciura sequences, and Shellsort's niche between insertion sort and O(n log n) algorithms."
    },
    {
      "slug": "sudoku-solver",
      "title": "Sudoku Solver",
      "description": "Sudoku solver — backtracking with row/column/box bitmasks, MRV branching, naked/hidden singles, Dancing Links exact-cover, and Norvig-style propagation."
    },
    {
      "slug": "suffix-array",
      "title": "Suffix Array & LCP Array",
      "description": "Suffix arrays provide O(n log n) construction and O(P log n) pattern matching for string problems — the practical alternative to suffix trees with lower memory overhead and better cache behavior."
    },
    {
      "slug": "tarjans-scc",
      "title": "Tarjan's Strongly Connected Components",
      "description": "Linear-time SCC decomposition via a single DFS with index and low-link timestamps — the algorithm, the condensation DAG, 2-SAT solving, and where it beats Kosaraju."
    },
    {
      "slug": "ternary-search",
      "title": "Ternary Search",
      "description": "Ternary Search — divide the range into thirds to find the extremum of a unimodal function. O(log n) with larger constants than binary search."
    },
    {
      "slug": "topological-sort",
      "title": "Topological Sort",
      "description": "Linear ordering of a DAG that respects dependencies — Kahn's BFS algorithm, DFS post-order, cycle detection, and the DAG-DP patterns built on top."
    },
    {
      "slug": "word-search",
      "title": "Word Search",
      "description": "Word Search — backtracking DFS on a 2D grid for word existence, Word Search II with trie-pruned multi-word search, and the broader grid-search pattern family."
    }
  ],
  "other/data-structures-algorithms/data-structures": [
    {
      "slug": "arrays",
      "title": "Arrays",
      "description": "Staff-level deep dive into arrays — contiguous memory layout, dynamic resizing with amortized analysis, cache behavior, V8 elements kinds, TypedArrays, and real-world trade-offs against linked and hash-based alternatives."
    },
    {
      "slug": "b-trees",
      "title": "B-Trees & B+ Trees",
      "description": "The disk-friendly self-balancing tree behind nearly every relational database index — high-fanout nodes match page sizes, keep height tiny, and turn billion-row lookups into 4 page reads."
    },
    {
      "slug": "bit-manipulation",
      "title": "Bit Manipulation",
      "description": "Staff-level deep dive into bit manipulation — bitwise operators, population count, bitmasks for compact set representation, XOR identities, endianness, SIMD-adjacent techniques, and language-level quirks in JavaScript."
    },
    {
      "slug": "bloom-filters",
      "title": "Bloom Filters",
      "description": "A probabilistic membership test that uses k hash functions and a bit array to answer 'is x in the set?' with no false negatives, bounded false positives, and a fraction of the memory of an exact set."
    },
    {
      "slug": "count-min-sketch",
      "title": "Count-Min Sketch",
      "description": "A sublinear-space sketch for approximate frequency counting over high-cardinality streams — bounded error guarantees, mergeable across nodes, and the structure behind heavy-hitter detection in DDoS protection and analytics."
    },
    {
      "slug": "disjoint-set-union-find",
      "title": "Disjoint Set (Union-Find)",
      "description": "A forest of parent pointers that tracks dynamic equivalence classes — Kruskal's MST, connected components, percolation, and incremental clustering all collapse to two operations: union and find."
    },
    {
      "slug": "doubly-linked-lists",
      "title": "Doubly Linked Lists",
      "description": "Staff-level deep dive into doubly linked lists — bidirectional traversal, O(1) arbitrary deletion, LRU cache composition with hash maps, intrusive variants, and concurrency challenges."
    },
    {
      "slug": "fenwick-tree",
      "title": "Fenwick Tree (Binary Indexed Tree)",
      "description": "The Fenwick tree (BIT) gives O(log n) prefix sum queries and point updates using only an n-length array — the workhorse behind inversion counting, order statistics, and mutable range sum queries."
    },
    {
      "slug": "graphs",
      "title": "Graphs",
      "description": "Vertices, edges, and the algorithms that exploit them — adjacency representations, traversal, shortest paths, and the engineering trade-offs behind real-world graph systems."
    },
    {
      "slug": "hash-tables",
      "title": "Hash Tables",
      "description": "Staff-level deep dive into hash tables — hash function design, chaining versus open addressing, load factor and resizing, Robin Hood hashing, V8 internals, and concurrent hash map strategies."
    },
    {
      "slug": "heaps-priority-queues",
      "title": "Heaps & Priority Queues",
      "description": "Staff-level deep dive into binary heaps and priority queues — implicit array layout, sift-up/sift-down mechanics, heap construction in linear time, d-ary variants, Fibonacci heaps, and real-world scheduler applications."
    },
    {
      "slug": "hyperloglog",
      "title": "HyperLogLog",
      "description": "A cardinality estimator that counts billions of distinct items in kilobytes — leading-zero registers and harmonic mean deliver ~1% accuracy at fixed memory, mergeable across shards."
    },
    {
      "slug": "lsm-trees",
      "title": "LSM Trees",
      "description": "Log-structured merge trees turn random writes into sequential I/O via in-memory MemTables, immutable SSTables, and background compaction — the storage backbone of RocksDB, Cassandra, and modern NoSQL."
    },
    {
      "slug": "merkle-trees",
      "title": "Merkle Trees",
      "description": "A binary hash tree that commits to arbitrary-size data with a single root digest, enabling O(log n) inclusion proofs and efficient anti-entropy sync between replicas."
    },
    {
      "slug": "persistent-data-structures",
      "title": "Persistent Data Structures",
      "description": "Persistent data structures preserve all previous versions after updates — enabling time-travel queries, undo/redo systems, functional programming, and database MVCC through structural sharing that keeps update costs to O(log n) new nodes."
    },
    {
      "slug": "queues",
      "title": "Queues",
      "description": "Staff-level deep dive into queues — FIFO semantics, circular buffers, bounded vs unbounded designs, concurrent and lock-free variants, backpressure, and the role of queues in message brokers and schedulers."
    },
    {
      "slug": "segment-tree",
      "title": "Segment Tree & Lazy Propagation",
      "description": "A comprehensive deep-dive into segment trees and lazy propagation: build, query, and update algorithms, lazy deferral mechanics, persistent and coordinate-compressed variants, and how to apply them in LeetCode problems and real-world range aggregation systems."
    },
    {
      "slug": "singly-linked-lists",
      "title": "Singly Linked Lists",
      "description": "Staff-level deep dive into singly linked lists — node topology, pointer rewiring, memory fragmentation, lock-free concurrent variants, and the narrow set of workloads where they beat arrays."
    },
    {
      "slug": "skip-lists",
      "title": "Skip Lists",
      "description": "A probabilistic alternative to balanced trees: stacked linked lists with express lanes deliver O(log n) search, insert, and delete without rotations — the structure behind Redis sorted sets and Java's ConcurrentSkipListMap."
    },
    {
      "slug": "sparse-table",
      "title": "Sparse Table & Range Minimum Query (RMQ)",
      "description": "Sparse tables achieve O(1) range minimum/maximum queries after O(n log n) preprocessing by exploiting overlapping power-of-2 intervals — the data structure behind O(1) LCA and suffix LCP queries."
    },
    {
      "slug": "splay-tree",
      "title": "Splay Tree — Self-Adjusting BST",
      "description": "Splay trees are self-adjusting binary search trees that achieve O(log n) amortized performance by splaying (rotating) recently accessed nodes to the root — naturally adapting to access patterns without storing balance information."
    },
    {
      "slug": "stacks",
      "title": "Stacks",
      "description": "Staff-level deep dive into stacks — LIFO semantics, array-backed versus linked-list-backed implementations, call-stack frames, monotonic stack techniques, and concurrent stack designs."
    },
    {
      "slug": "strings",
      "title": "Strings",
      "description": "Staff-level deep dive into strings — Unicode encodings, immutability, interning, rope structures, V8 ConsString/SlicedString internals, and the algorithms that exploit string structure for sub-linear search."
    },
    {
      "slug": "trees",
      "title": "Trees",
      "description": "Staff-level deep dive into trees — binary search trees, balanced variants (AVL, red-black), traversal patterns, persistent trees, and the role of trees as indexes and scheduler structures."
    },
    {
      "slug": "tries",
      "title": "Tries",
      "description": "Prefix trees that exploit shared key prefixes for O(L) lookup independent of n — the structure behind autocomplete, IP routing, and modern key-value indexes."
    }
  ],
  "other/leetcode/patterns": [
    {
      "slug": "backtracking",
      "title": "Backtracking Pattern",
      "description": "Choose, explore, un-choose — DFS with disciplined state management. Enumerate subsets, permutations, and combinations; solve N-queens and sudoku; prune aggressively."
    },
    {
      "slug": "binary-search",
      "title": "Binary Search Pattern",
      "description": "Logarithmic search by halving a monotone search space — the canonical pattern for sorted-array lookup, lower_bound / upper_bound, and parametric search where you binary-search the answer."
    },
    {
      "slug": "bit-manipulation",
      "title": "Bit Manipulation Pattern",
      "description": "Bitwise operations, XOR identities, popcount tricks, and bitmask DP — the toolkit for compact set representation and constant-factor speedups."
    },
    {
      "slug": "cyclic-sort",
      "title": "Cyclic Sort Pattern",
      "description": "Place each value at its target index in O(n) time and O(1) extra space — the canonical pattern for missing/duplicate problems on bounded integer ranges."
    },
    {
      "slug": "divide-and-conquer",
      "title": "Divide and Conquer Pattern",
      "description": "Split a problem into independent subproblems, solve recursively, and combine — the structural backbone of sort, search, and a host of clever algorithms."
    },
    {
      "slug": "dynamic-programming",
      "title": "Dynamic Programming Pattern",
      "description": "Trade exponential recursion for polynomial time by memoising overlapping subproblems — the most asked, most feared, and most rewarding pattern in coding interviews."
    },
    {
      "slug": "fast-slow-pointers",
      "title": "Fast & Slow Pointers (Floyd's Tortoise and Hare)",
      "description": "Two pointers advancing at different speeds detect cycles, find midpoints, and locate cycle entries in linked lists and iterated functions — all in O(n) time and O(1) space."
    },
    {
      "slug": "graph",
      "title": "Graph Pattern",
      "description": "BFS, DFS, Dijkstra, topological sort, and the engineering choices behind graph representation, traversal, and shortest-path algorithms."
    },
    {
      "slug": "greedy",
      "title": "Greedy Pattern",
      "description": "Make the locally optimal choice at every step, never reconsider, and rely on the greedy-choice property to deliver a globally optimal answer in linear or near-linear time."
    },
    {
      "slug": "hash-table",
      "title": "Hash Table Pattern",
      "description": "The O(1) average-case lookup that turns repeated linear searches into single passes — the most pervasive interview pattern, underpinning two-sum, anagram grouping, longest consecutive sequence, and most cache designs."
    },
    {
      "slug": "heap",
      "title": "Heap Pattern",
      "description": "Priority-queue workhorse for top-k, k-way merge, Dijkstra, two-heaps median, and event scheduling — O(log n) push/pop with O(1) peek."
    },
    {
      "slug": "in-place-linked-list-reversal",
      "title": "In-Place Linked List Reversal Pattern",
      "description": "The prev/curr/next triple-step that reverses a singly linked list in O(n) time and O(1) extra space — the substrate for k-group reversal, palindrome checks, reorder list, and any problem that needs to walk a singly linked list backwards."
    },
    {
      "slug": "k-way-merge",
      "title": "K-way Merge Pattern",
      "description": "Merge k sorted streams with a min-heap of frontiers — O(N log k) time, O(k) space — and the trick for matrix and virtual-list queries."
    },
    {
      "slug": "linked-list",
      "title": "Linked List Pattern",
      "description": "Pointer-surgery techniques for singly and doubly linked lists — dummy heads, fast/slow pointers, splicing, and the design problems (LRU, LFU) that pair a list with a hash map for O(1) operations."
    },
    {
      "slug": "math",
      "title": "Math Pattern",
      "description": "Number theory, modular arithmetic, fast exponentiation, sieves, and combinatorics — closed-form thinking that turns brute force into logarithmic."
    },
    {
      "slug": "merge-intervals",
      "title": "Merge Intervals Pattern",
      "description": "Sort by start time, walk once, merge or append — the universal scaffold for problems where the input is a list of intervals and the question is about their union, overlap, or scheduling."
    },
    {
      "slug": "monotonic-queue",
      "title": "Monotonic Queue Pattern",
      "description": "A deque maintained in monotone order with eviction at both ends — the linear-time tool for sliding-window max / min and DP transitions where the optimum comes from a bounded suffix."
    },
    {
      "slug": "monotonic-stack",
      "title": "Monotonic Stack Pattern",
      "description": "A stack maintained in monotone order, evicting violators on push — the linear-time tool for next-greater / smaller queries, histogram rectangles, and lex-smallest-after-removals problems."
    },
    {
      "slug": "prefix-sum",
      "title": "Prefix Sum Pattern",
      "description": "Linear preprocessing that turns range-sum queries into O(1) lookups, and — combined with a hash map — collapses an entire family of subarray-sum-equals-k problems from O(n²) to O(n)."
    },
    {
      "slug": "queues",
      "title": "Queues Pattern",
      "description": "FIFO scheduling for breadth-first search, level-order traversal, topological sort, and the design problems that pair a queue with a hash map or a fixed-size buffer to hit O(1) per operation."
    },
    {
      "slug": "range-query",
      "title": "Range Query Pattern",
      "description": "Range query pattern decision guide — when to use prefix sum, Fenwick tree, segment tree with lazy propagation, sparse table, persistent segment tree, or Mo's algorithm, with classic LeetCode problems mapped to each structure."
    },
    {
      "slug": "recursion",
      "title": "Recursion Pattern",
      "description": "Base cases, reduction, and combination — the discipline of solving a problem by reducing it to a smaller instance, with stack-depth and tail-call awareness."
    },
    {
      "slug": "sliding-window",
      "title": "Sliding Window Pattern",
      "description": "Linear-time technique for contiguous-range problems where a window grows and shrinks across an array or string while maintaining an aggregate — the canonical pattern for substring, subarray, and rate-counting questions."
    },
    {
      "slug": "stack",
      "title": "Stack Pattern",
      "description": "LIFO bookkeeping for nested structure — bracket matching, expression evaluation, iterative DFS, and the family of design problems where the next answer depends on the most recent unfinished thing."
    },
    {
      "slug": "string",
      "title": "String Pattern",
      "description": "Sliding-window, hashing, stack, trie, and substring-search techniques applied to strings — the umbrella pattern that intersects every other algorithmic family."
    },
    {
      "slug": "top-k-elements",
      "title": "Top K Elements Pattern",
      "description": "Bounded-heap, quickselect, and bucket-sort techniques for selecting the k best elements — the dominant pattern for streaming and frequency questions."
    },
    {
      "slug": "tree",
      "title": "Tree Pattern",
      "description": "Recursive decomposition over binary trees and BSTs — the four traversal orders, the top-down vs. bottom-up split, and the canonical problems (LCA, diameter, max path sum, validate BST) that test the discipline."
    },
    {
      "slug": "trie",
      "title": "Trie Pattern",
      "description": "Prefix tree for string sets — O(L) insert and search, prefix-shared storage, and the substrate for autocomplete, wildcard matching, dictionary-grid search, and bit-trie XOR problems."
    },
    {
      "slug": "two-pointer",
      "title": "Two-Pointer Pattern",
      "description": "Linear-time technique that uses two indices walking through one or two sequences to replace nested loops — the foundational Leetcode pattern for sorted-array pair problems and in-place rewrites."
    },
    {
      "slug": "union-find",
      "title": "Union-Find Pattern",
      "description": "Disjoint-set union for online connectivity, MST construction, cycle detection, and equivalence-class problems — near-O(1) per operation with path compression and union by rank."
    }
  ],
  "other/leetcode/problems": [
    {
      "slug": "3sum",
      "title": "3Sum",
      "description": "3Sum interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "add-and-search-word",
      "title": "Add and Search Word",
      "description": "Add and Search Word interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "alien-dictionary",
      "title": "Alien Dictionary",
      "description": "Alien Dictionary interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "best-time-to-buy-and-sell-stock",
      "title": "Best Time to Buy and Sell Stock",
      "description": "Best Time to Buy and Sell Stock interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "binary-tree-level-order-traversal",
      "title": "Binary Tree Level Order Traversal",
      "description": "Binary Tree Level Order Traversal interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "binary-tree-maximum-path-sum",
      "title": "Binary Tree Maximum Path Sum",
      "description": "Binary Tree Maximum Path Sum interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "climbing-stairs",
      "title": "Climbing Stairs",
      "description": "Climbing Stairs interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "clone-graph",
      "title": "Clone Graph",
      "description": "Clone Graph interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "coin-change",
      "title": "Coin Change",
      "description": "Coin Change interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "combination-sum",
      "title": "Combination Sum",
      "description": "Combination Sum interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "construct-binary-tree-from-preorder-and-inorder-traversal",
      "title": "Construct Binary Tree from Preorder and Inorder Traversal",
      "description": "Construct Binary Tree from Preorder and Inorder Traversal interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "container-with-most-water",
      "title": "Container With Most Water",
      "description": "Container With Most Water interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "contains-duplicate",
      "title": "Contains Duplicate",
      "description": "Contains Duplicate interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "counting-bits",
      "title": "Counting Bits",
      "description": "Counting Bits interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "course-schedule",
      "title": "Course Schedule",
      "description": "Course Schedule interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "decode-ways",
      "title": "Decode Ways",
      "description": "Decode Ways interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "detect-cycle-in-a-linked-list",
      "title": "Detect Cycle in a Linked List",
      "description": "Detect Cycle in a Linked List interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "encode-and-decode-strings",
      "title": "Encode and Decode Strings",
      "description": "Encode and Decode Strings interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "find-median-from-data-stream",
      "title": "Find Median from Data Stream",
      "description": "Find Median from Data Stream interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "find-minimum-in-rotated-sorted-array",
      "title": "Find Minimum in Rotated Sorted Array",
      "description": "Find Minimum in Rotated Sorted Array interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "graph-valid-tree",
      "title": "Graph Valid Tree",
      "description": "Graph Valid Tree interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "group-anagrams",
      "title": "Group Anagrams",
      "description": "Group Anagrams interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "house-robber-ii",
      "title": "House Robber II",
      "description": "House Robber II interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "house-robber",
      "title": "House Robber",
      "description": "House Robber interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "implement-trie",
      "title": "Implement Trie (Prefix Tree)",
      "description": "Implement Trie (Prefix Tree) interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "insert-interval",
      "title": "Insert Interval",
      "description": "Insert Interval interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "invert-flip-binary-tree",
      "title": "Invert/Flip Binary Tree",
      "description": "Invert/Flip Binary Tree interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "jump-game",
      "title": "Jump Game",
      "description": "Jump Game interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "kth-smallest-element-in-a-bst",
      "title": "Kth Smallest Element in a BST",
      "description": "Kth Smallest Element in a BST interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "longest-common-subsequence",
      "title": "Longest Common Subsequence",
      "description": "Longest Common Subsequence interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "longest-consecutive-sequence",
      "title": "Longest Consecutive Sequence",
      "description": "Longest Consecutive Sequence interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "longest-increasing-subsequence",
      "title": "Longest Increasing Subsequence",
      "description": "Longest Increasing Subsequence interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "longest-palindromic-substring",
      "title": "Longest Palindromic Substring",
      "description": "Longest Palindromic Substring interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "longest-repeating-character-replacement",
      "title": "Longest Repeating Character Replacement",
      "description": "Longest Repeating Character Replacement interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "longest-substring-without-repeating-characters",
      "title": "Longest Substring Without Repeating Characters",
      "description": "Longest Substring Without Repeating Characters interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "lowest-common-ancestor-of-bst",
      "title": "Lowest Common Ancestor of BST",
      "description": "Lowest Common Ancestor of BST interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "maximum-depth-of-binary-tree",
      "title": "Maximum Depth of Binary Tree",
      "description": "Maximum Depth of Binary Tree interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "maximum-product-subarray",
      "title": "Maximum Product Subarray",
      "description": "Maximum Product Subarray interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "maximum-subarray",
      "title": "Maximum Subarray",
      "description": "Maximum Subarray interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "meeting-rooms-ii",
      "title": "Meeting Rooms II",
      "description": "Meeting Rooms II interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "meeting-rooms",
      "title": "Meeting Rooms",
      "description": "Meeting Rooms interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "merge-intervals",
      "title": "Merge Intervals",
      "description": "Merge Intervals interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "merge-k-sorted-lists",
      "title": "Merge K Sorted Lists",
      "description": "Merge K Sorted Lists interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "merge-two-sorted-lists",
      "title": "Merge Two Sorted Lists",
      "description": "Merge Two Sorted Lists interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "minimum-window-substring",
      "title": "Minimum Window Substring",
      "description": "Minimum Window Substring interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "missing-number",
      "title": "Missing Number",
      "description": "Missing Number interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "non-overlapping-intervals",
      "title": "Non-overlapping Intervals",
      "description": "Non-overlapping Intervals interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "number-of-1-bits",
      "title": "Number of 1 Bits",
      "description": "Number of 1 Bits interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "number-of-connected-components-in-an-undirected-graph",
      "title": "Number of Connected Components in an Undirected Graph",
      "description": "Number of Connected Components in an Undirected Graph interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "number-of-islands",
      "title": "Number of Islands",
      "description": "Number of Islands interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "pacific-atlantic-water-flow",
      "title": "Pacific Atlantic Water Flow",
      "description": "Pacific Atlantic Water Flow interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "palindromic-substrings",
      "title": "Palindromic Substrings",
      "description": "Palindromic Substrings interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "product-of-array-except-self",
      "title": "Product of Array Except Self",
      "description": "Product of Array Except Self interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "remove-nth-node-from-end-of-list",
      "title": "Remove Nth Node From End Of List",
      "description": "Remove Nth Node From End Of List interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "reorder-list",
      "title": "Reorder List",
      "description": "Reorder List interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "reverse-a-linked-list",
      "title": "Reverse a Linked List",
      "description": "Reverse a Linked List interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "reverse-bits",
      "title": "Reverse Bits",
      "description": "Reverse Bits interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "rotate-image",
      "title": "Rotate Image",
      "description": "Rotate Image interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "same-tree",
      "title": "Same Tree",
      "description": "Same Tree interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "search-in-rotated-sorted-array",
      "title": "Search in Rotated Sorted Array",
      "description": "Search in Rotated Sorted Array interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "serialize-and-deserialize-binary-tree",
      "title": "Serialize and Deserialize Binary Tree",
      "description": "Serialize and Deserialize Binary Tree interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "set-matrix-zeroes",
      "title": "Set Matrix Zeroes",
      "description": "Set Matrix Zeroes interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "spiral-matrix",
      "title": "Spiral Matrix",
      "description": "Spiral Matrix interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "subtree-of-another-tree",
      "title": "Subtree of Another Tree",
      "description": "Subtree of Another Tree interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "sum-of-two-integers",
      "title": "Sum of Two Integers",
      "description": "Sum of Two Integers interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "top-k-frequent-elements",
      "title": "Top K Frequent Elements",
      "description": "Top K Frequent Elements interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "two-sum",
      "title": "Two Sum",
      "description": "Two Sum interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "unique-paths",
      "title": "Unique Paths",
      "description": "Unique Paths interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "valid-anagram",
      "title": "Valid Anagram",
      "description": "Valid Anagram interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "valid-palindrome",
      "title": "Valid Palindrome",
      "description": "Valid Palindrome interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "valid-parentheses",
      "title": "Valid Parentheses",
      "description": "Valid Parentheses interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "validate-binary-search-tree",
      "title": "Validate Binary Search Tree",
      "description": "Validate Binary Search Tree interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "word-break-problem",
      "title": "Word Break Problem",
      "description": "Word Break Problem interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "word-search-ii",
      "title": "Word Search II",
      "description": "Word Search II interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    },
    {
      "slug": "word-search",
      "title": "Word Search",
      "description": "Word Search interview guide focused on pattern recognition, invariants, trade-offs, edge cases, and staff-level explanation quality."
    }
  ],
  "other/ci-cd/continuous-deployment-cd": [
    {
      "slug": "cd-fundamentals-release-pipeline-architecture",
      "title": "CD Fundamentals and Release Pipeline Architecture",
      "description": "Staff-level guide to CD Fundamentals and Release Pipeline Architecture with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    },
    {
      "slug": "database-migrations-continuous-deployment",
      "title": "Database Migrations in Continuous Deployment",
      "description": "Staff-level guide to Database Migrations in Continuous Deployment with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    },
    {
      "slug": "deployment-observability-slo-gates-rollback",
      "title": "Deployment Observability, SLO Gates, and Automated Rollback",
      "description": "Staff-level guide to Deployment Observability, SLO Gates, and Automated Rollback with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    },
    {
      "slug": "deployment-strategies-rolling-blue-green-canary",
      "title": "Deployment Strategies: Rolling, Blue-Green, Canary",
      "description": "Staff-level guide to Deployment Strategies: Rolling, Blue-Green, Canary with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    },
    {
      "slug": "environment-promotion-configuration-management",
      "title": "Environment Promotion and Configuration Management",
      "description": "Staff-level guide to Environment Promotion and Configuration Management with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    },
    {
      "slug": "infrastructure-as-code-deployment-pipelines",
      "title": "Infrastructure as Code in Deployment Pipelines",
      "description": "Staff-level guide to Infrastructure as Code in Deployment Pipelines with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    },
    {
      "slug": "progressive-delivery-feature-flags",
      "title": "Progressive Delivery and Feature Flags",
      "description": "Staff-level guide to Progressive Delivery and Feature Flags with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    },
    {
      "slug": "release-governance-approvals-auditability",
      "title": "Release Governance, Approvals, and Auditability",
      "description": "Staff-level guide to Release Governance, Approvals, and Auditability with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    }
  ],
  "other/ci-cd/continuous-integration-ci": [
    {
      "slug": "branching-strategies-merge-policies",
      "title": "Branching Strategies and Merge Policies",
      "description": "Staff-level guide to Branching Strategies and Merge Policies with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    },
    {
      "slug": "build-systems-artifact-management",
      "title": "Build Systems and Artifact Management",
      "description": "Staff-level guide to Build Systems and Artifact Management with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    },
    {
      "slug": "ci-caching-pipeline-performance",
      "title": "CI Caching and Pipeline Performance",
      "description": "Staff-level guide to CI Caching and Pipeline Performance with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    },
    {
      "slug": "ci-fundamentals-pipeline-architecture",
      "title": "CI Fundamentals and Pipeline Architecture",
      "description": "Staff-level guide to CI Fundamentals and Pipeline Architecture with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    },
    {
      "slug": "ci-security-supply-chain-checks",
      "title": "CI Security and Supply Chain Checks",
      "description": "Staff-level guide to CI Security and Supply Chain Checks with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    },
    {
      "slug": "flaky-test-detection-quarantine",
      "title": "Flaky Test Detection and Quarantine",
      "description": "Staff-level guide to Flaky Test Detection and Quarantine with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    },
    {
      "slug": "monorepo-ci-at-scale",
      "title": "Monorepo CI at Scale",
      "description": "Staff-level guide to Monorepo CI at Scale with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    },
    {
      "slug": "test-automation-strategy-ci",
      "title": "Test Automation Strategy in CI",
      "description": "Staff-level guide to Test Automation Strategy in CI with topic-specific architecture, trade-offs, failure modes, interview questions, and production delivery guidance."
    }
  ]
};
