"use client";
import { useEffect, useMemo, useState } from "react";
type Candidate = { id: string; title: string; relevance: number; freshness: number; engagement: number };
type RankingState = { weights: { relevance: number; freshness: number; engagement: number }; candidates: Candidate[]; rankedIds: string[]; lastMessage: string };
export default function Page() {
  const [state, setState] = useState<RankingState | null>(null);
  const [weights, setWeights] = useState({ relevance: 0.5, freshness: 0.2, engagement: 0.3 });
  async function refresh() { const response = await fetch('/api/ranking/state'); const data = (await response.json()) as RankingState; setState(data); setWeights(data.weights); }
  async function optimize() { const response = await fetch('/api/ranking/optimize', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(weights) }); setState((await response.json()) as RankingState); }
  useEffect(() => { void refresh(); }, []);
  const rankedItems = useMemo(() => state?.rankedIds.map((id) => state.candidates.find((candidate) => candidate.id === id)).filter(Boolean) as Candidate[] ?? [], [state]);
  return <main className="mx-auto max-w-6xl px-6 py-10"><h1 className="text-3xl font-bold">Ranking Optimization</h1><p className="mt-2 text-slate-300">Tune ranking weights, compare candidate ordering, and inspect how relevance, freshness, and engagement affect the final feed order.</p><section className="mt-8 grid gap-6 lg:grid-cols-[320px,1fr]"><article className="rounded-xl border border-slate-800 bg-slate-900/60 p-5 text-sm text-slate-300"><label className="block">Relevance weight</label><input type="number" step="0.1" value={weights.relevance} onChange={(event) => setWeights((current) => ({ ...current, relevance: Number(event.target.value) }))} className="mt-2 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2" /><label className="mt-4 block">Freshness weight</label><input type="number" step="0.1" value={weights.freshness} onChange={(event) => setWeights((current) => ({ ...current, freshness: Number(event.target.value) }))} className="mt-2 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2" /><label className="mt-4 block">Engagement weight</label><input type="number" step="0.1" value={weights.engagement} onChange={(event) => setWeights((current) => ({ ...current, engagement: Number(event.target.value) }))} className="mt-2 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2" /><button onClick={optimize} className="mt-4 rounded bg-sky-600 px-4 py-2 text-sm font-semibold hover:bg-sky-500">Optimize ranking</button><p className="mt-4">{state?.lastMessage}</p></article><article className="rounded-xl border border-slate-800 bg-slate-900/60 p-5 text-sm text-slate-300"><ul className="space-y-3">{rankedItems.map((item, index) => <li key={item.id} className="rounded-lg border border-slate-800 p-4"><div className="font-semibold text-slate-100">#{index + 1} {item.title}</div><div className="mt-1 text-slate-400">relevance {item.relevance} · freshness {item.freshness} · engagement {item.engagement}</div></li>)}</ul></article></section></main>;
}
