"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-fraud-detection-risk-alert-ui",
  title: "Design a Fraud Detection / Risk Alert UI",
  description:
    "Architecture for a payment fraud detection and risk alert system: real-time transaction scoring pipeline (rule engine + ML model, sub-100ms decision), velocity checks (card/device/IP rate limiting), device fingerprinting and behavioral biometrics, step-up authentication for high-risk transactions (OTP, biometric), analyst review queue with case management, model feature engineering (transaction graph, merchant category, time-of-day patterns), feedback loop for false positive reduction, risk score explanation for declined transactions, and chargeback prediction to proactively flag disputes.",
  category: "high-level-design",
  subcategory: "payments-fintech-systems",
  slug: "fraud-detection-risk-alert-ui",
  wordCount: 5000,
  readingTime: 30,
  lastUpdated: "2026-05-14",
  tags: ["hld", "fraud-detection", "risk-scoring", "velocity-checks", "device-fingerprint", "ml-scoring", "step-up-auth", "chargeback"],
  relatedTopics: ["transaction-history-reconciliation-ui", "payment-gateway-integration-ui"],
};

export default function FraudDetectionRiskAlertUiArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A fraud detection system must make a real-time decision (allow, challenge, or block) for every transaction within the payment's latency budget — typically &lt;100ms before the payment request is forwarded to the bank. Too many false positives (legitimate transactions blocked) reduce conversion rate and frustrate good customers. Too many false negatives (fraudulent transactions allowed) cause financial losses and chargebacks. The system must optimize the tradeoff between fraud loss rate and false positive rate, and this tradeoff is different for different risk tolerances (a crypto exchange tolerates less fraud than a grocery store).</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">The system has two components: the real-time scoring engine (makes the allow/challenge/block decision for each transaction in &lt;100ms) and the analyst review dashboard (shows flagged transactions, case management, model retraining feedback). The real-time engine is a pipeline: rule engine (fast, deterministic checks) → ML model (slower but more accurate) → decision. The analyst dashboard is an internal tool for the fraud operations team — it shows the fraud alert queue, case details, investigation tools, and model performance metrics.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Real-time scoring pipeline (rules + ML), velocity checks, device fingerprinting, step-up authentication, analyst review queue, feedback loop, risk score explanation, and chargeback prediction. Not in scope: AML (anti-money laundering) compliance, KYC verification, or account takeover prevention (a related but separate system).</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Real-time transaction scoring pipeline:</strong> Every payment request goes through the fraud scoring pipeline before being forwarded to the payment processor. The pipeline has two stages: (1) Rule engine (10ms budget): deterministic rules checked in priority order — is this card on the block list? Is the transaction amount above the user's typical 99th percentile spend? Is the device ID associated with a known fraud ring? Is the IP on a Tor exit node or VPN? Rules that match immediately return a decision (block for severe rules, challenge for medium rules). (2) ML model (50ms budget): if no rule triggers a block/challenge, the transaction's feature vector is computed and scored by the fraud model. The model outputs a probability of fraud (0.0–1.0). Score &gt;0.8 → block, 0.4–0.8 → challenge (step-up authentication), &lt;0.4 → allow. The total pipeline latency target is &lt;100ms including the ML inference.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Velocity checks:</strong> Velocity rules detect abnormal transaction frequency, which is a strong fraud signal. Checks tracked in Redis (sliding window counters): card velocity (max 5 transactions per card per 10 minutes), device velocity (max 10 transactions from the same device per hour), IP velocity (max 20 transactions from the same IP per hour), merchant velocity (max 3 transactions to the same merchant in 5 minutes from the same card), and amount escalation (3 transactions of escalating amounts on the same card in 30 minutes — a testing pattern). Each counter is a Redis INCR with an EXPIRE set to the window duration. A counter exceeding its limit triggers a "velocity exceeded" rule, which contributes to the risk score (partial trigger → challenge; multiple velocity limits exceeded → block).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Device fingerprinting and behavioral biometrics:</strong> Device fingerprinting collects browser/device signals to identify the device: screen resolution, color depth, timezone, installed fonts (via canvas fingerprint), WebGL renderer, audio fingerprint, hardware concurrency, and touch support. The fingerprint is a hash of these signals — the same device produces the same fingerprint consistently across sessions (even after clearing cookies). A new device fingerprint associated with a known user's card is a risk signal — "This card is being used from a new device." Behavioral biometrics: typing rhythm (time between keystrokes during card number entry), mouse movement patterns, and touch pressure/angle (on mobile) are collected during checkout. Abnormal patterns (robotic key timing suggesting automation, or dramatically different typing rhythm from the user's historical pattern) increase the risk score.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Step-up authentication for high-risk transactions:</strong> When the risk score is in the challenge range (0.4–0.8), the system triggers step-up authentication instead of outright blocking: (1) OTP via SMS or email ("We detected an unusual payment. Enter the OTP sent to your registered phone to proceed."); (2) biometric verification (FaceID or fingerprint on mobile, via WebAuthn); (3) 3DS2 bank authentication (for card payments). The step-up challenge result is fed back into the fraud pipeline: if the OTP is verified, the risk score is reduced and the payment proceeds. If OTP verification fails or times out, the transaction is blocked. The step-up challenge is invisible for legitimate users (they recognize the OTP as a normal security measure) but blocks automated fraud bots that cannot complete the challenge.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Analyst review queue and case management:</strong> Transactions with scores in the manual review range (e.g., 0.6–0.8 during model uncertainty periods) are placed in an analyst review queue. The review UI shows: transaction details (amount, merchant, card last 4, device fingerprint), the risk score and top contributing features ("High risk: new device + unusual amount + Tor exit node"), the user's transaction history (30-day chart showing spending patterns), and similar past fraud cases. Actions: approve (allow the transaction), decline (block it), and escalate (send to senior analyst). Approved transactions that later result in chargebacks are flagged as "confirmed fraud" and used as training labels for model retraining. The queue is prioritized by fraud score (higher score = higher priority) and age (older cases surface before expiry).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>ML model features and retraining:</strong> The fraud model is a gradient boosting model (XGBoost or LightGBM) trained on labeled transaction data (fraud = 1, legitimate = 0). Key features: transaction amount (absolute and relative to user's historical average), time since last transaction from this card, time since card was added to the account, merchant category code (MCC), country of transaction vs. user's home country, device risk score (from fingerprint freshness and fingerprint reputation), velocity features (transactions in last 1hr/24hr/7d), and graph features (is this card connected to known fraudulent accounts via shared device or IP?). The model is retrained weekly on new labeled data (analyst verdicts + chargeback outcomes). The retrained model is deployed via a feature flag: shadow mode first (scores both old and new model, compares decisions without acting on the new model's output), then gradual rollout (10% of traffic → 100%).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Risk score explanation for declined transactions:</strong> When a transaction is declined, the user sees a reason (in compliant phrasing — regulations limit what can be disclosed, and revealing exact fraud signals would allow fraudsters to evade them). User-facing message: "This transaction could not be completed for security reasons. If you believe this is an error, please contact support." Internal message (shown to support agents): the top 3 risk factors with their contribution to the score: "New device (contributes 0.35), IP on blocked list (contributes 0.28), amount exceeds 99th percentile (contributes 0.15)." The explanation is generated using Shapley values (SHAP) — a model-agnostic explanation technique that attributes the model's output to individual features. SHAP values are pre-computed for each scored transaction and stored for up to 90 days.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Chargeback prediction:</strong> A separate model predicts whether an approved transaction will result in a chargeback within 90 days (based on historical chargeback patterns). High chargeback probability transactions are flagged for proactive outreach: "We noticed your recent purchase at MerchantX may have an issue. If you didn't make this purchase, please report it now." Early reporting prevents chargebacks (which cost the merchant ~$25 in chargeback fees and potential card brand penalties) by converting them to direct disputes resolved before the chargeback deadline. The chargeback prediction model runs asynchronously (not in the real-time scoring pipeline) — it processes approved transactions in a batch job 5 minutes after approval.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The fraud detection system has three planes: the real-time scoring plane (in the payment request path, &lt;100ms budget), the async enrichment plane (runs after approval/block decision, computes additional signals for analyst review and model retraining), and the model management plane (feature engineering, training, evaluation, and deployment). The real-time scoring plane: payment request arrives → feature extraction (from the request payload + Redis cached velocity counters + device fingerprint lookup) → rule engine evaluation → if no block → ML model inference (pre-loaded in memory as a serialized ONNX model) → decision → response to payment service.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The analyst review queue is populated by a Kafka consumer that reads from the fraud_decisions topic (decisions from the real-time pipeline). Transactions with challenge or manual_review decisions are inserted into the review queue database (PostgreSQL). The analyst dashboard reads from this database. Analyst verdicts are written back to the fraud_verdicts Kafka topic, consumed by the model retraining pipeline.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/payments-fintech-systems/fraud-detection-risk-alert-ui.svg"
          alt="Fraud detection system: payment request → rule engine (10ms: block list, velocity, Tor IP) → ML model (50ms: XGBoost feature vector, score 0-1) → decision (allow &lt;0.4, challenge 0.4-0.8, block &gt;0.8); velocity checks in Redis sliding window (card 5/10min, IP 20/hr); device fingerprint (canvas+WebGL+audio hash, new device = risk signal); step-up auth on challenge (OTP/biometric/3DS2); Kafka fan-out: manual review queue + chargeback prediction batch; analyst review UI (SHAP top-3 features, approve/decline/escalate); weekly model retrain with analyst verdicts + chargeback labels; shadow mode → gradual rollout."
          caption="Rule engine 10ms + ML 50ms = &lt;100ms total, Redis velocity counters (sliding window), device fingerprint hash, step-up OTP/biometric on 0.4–0.8 score, SHAP feature attribution, weekly retrain with shadow mode, chargeback prediction batch 5min post-approval"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Feature Extraction Pipeline</h3>
        <HighlightBlock as="p" tier="crucial">Feature extraction must complete in &lt;40ms to leave budget for the rule engine and ML model. Features are extracted from three sources: (1) the transaction payload (instant, no I/O): amount, currency, merchant MCC, card BIN (first 6 digits, used to look up card country and card type from a pre-loaded BIN database in memory); (2) Redis velocity counters (1–5ms I/O): card velocity, IP velocity, device velocity, merchant velocity — all from pre-incremented Redis INCR counters; (3) user profile cache (1–5ms I/O): user's historical average transaction amount, 99th percentile amount, days since account creation, number of saved payment methods — cached in Redis and refreshed daily. The feature vector is assembled from all three sources and passed to the rule engine.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Graph features (is this card connected to known fraudulent accounts?) are not computed in real-time (graph traversal is expensive). Instead, a daily batch job computes a "fraud affinity score" for each card and device ID based on their connections in the transaction graph (two accounts share a device ID → are connected; connected accounts with fraud labels → elevated affinity score). This score is precomputed and cached in Redis, included as a feature in the real-time feature vector without requiring graph traversal at query time.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Rule Engine Priority and Maintenance</h3>
        <HighlightBlock as="p" tier="important">The rule engine executes rules in priority order — higher-priority rules short-circuit evaluation. Rule tiers: tier 1 (hardcoded, always execute first): card on blocklist, device ID on blocklist, transaction amount exceeds absolute maximum (&#36;10,000 for unverified accounts); tier 2 (configurable by fraud ops team via the admin dashboard): velocity limits, country block list, BIN country mismatch; tier 3 (experimental, A/B tested): new signals under evaluation by the data science team. Rules are stored in a database and cached in memory (refreshed every 60 seconds). Fraud ops can add, modify, and disable rules via the admin dashboard without code deployment. Rule changes are logged to the audit trail with the rule definition, the operator who made the change, and the reason.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">False Positive Reduction and Model Calibration</h3>
        <HighlightBlock as="p" tier="important">False positives (legitimate transactions blocked) are tracked via two signals: (1) user complaints — when a user calls support and successfully disputes a block, the transaction is marked as a false positive; (2) step-up success rate — for transactions that triggered step-up authentication, the fraction that successfully completed step-up and were legitimate (not subsequently charged back) indicates the step-up threshold accuracy. If step-up success rate is &gt;95% (most challenged transactions are legitimate), the challenge threshold is too low — raise it. If step-up success rate is &lt;80%, the threshold is too high — lower it. This feedback loop calibrates the model thresholds using operational metrics, not just model accuracy metrics on the training set.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="crucial">Rule engine vs. pure ML: rule-based systems are interpretable (a human can explain exactly why a transaction was blocked), fast (no model inference), and predictable (the same input always produces the same output). But rules don't generalize — fraud patterns evolve, and rules must be manually updated. ML models learn complex patterns automatically but are opaque (why did the model score this transaction 0.85?). The right architecture is hybrid: rules for the most severe, well-understood fraud patterns (stolen card BIN, known fraud device) and ML for the nuanced scoring. Rules also provide a safety net when the ML model has low confidence — if the model is out-of-distribution (transaction type not seen during training), a conservative rule can block the transaction while the model would have given a 0.5 score.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Latency vs. accuracy: more features improve model accuracy but increase feature extraction time. The &lt;100ms budget is the hard constraint. Features that require additional I/O (external API calls, complex graph queries) cannot be included in the real-time pipeline unless they can be precomputed and cached. Features with high predictive power but high latency (e.g., real-time device reputation lookup from a third-party API) must be either precomputed or batched and applied to the next transaction from the same device — accepting that the first transaction from a new device has less feature coverage.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A fraud detection system requires: (1) real-time scoring pipeline (&lt;100ms: rule engine 10ms → ML inference 50ms → decision; allow &lt;0.4, challenge 0.4–0.8, block &gt;0.8); (2) velocity checks (Redis INCR sliding window: card 5/10min, IP 20/hr, device 10/hr, merchant 3/5min per card); (3) device fingerprinting (canvas + WebGL + audio hash, new device = risk signal, behavioral biometrics keystroke timing); (4) step-up authentication (OTP/biometric/3DS2 on challenge, OTP verified → score reduced, fail/timeout → block); (5) analyst review queue (SHAP top-3 feature attribution, approve/decline/escalate, prioritized by score and age); (6) ML model (XGBoost/LightGBM, features: amount relative to history, velocity, MCC, country mismatch, device risk, precomputed graph affinity); (7) model deployment (weekly retrain with analyst verdicts + chargeback labels, shadow mode → 10% rollout → 100%); (8) chargeback prediction (async batch 5min post-approval, proactive user outreach); (9) SHAP feature attribution (pre-computed per scored transaction, 90-day retention, shown to support agents not end-users); and (10) false positive calibration (step-up success rate feedback loop, threshold adjustment based on operational metrics). The core design principle: fraud detection is an adversarial system — assume fraudsters will probe the rules and adapt; use model-based scoring for generalization and rules for the known-bad patterns that are too severe to risk a false negative.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
