"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-payment-gateway-integration-ui",
  title: "Design a Payment Gateway Integration UI (like Stripe Checkout)",
  description:
    "Architecture for a payment gateway integration UI: PCI-DSS compliant iframe-based card capture with Stripe Elements, payment intent lifecycle (created → processing → succeeded/failed), 3D Secure authentication flow, idempotency keys for safe retries, webhook handling for async payment events, retry logic with exponential backoff, saved payment method management, multi-currency display and conversion, partial capture and refund flows, and checkout abandonment recovery.",
  category: "high-level-design",
  subcategory: "payments-fintech-systems",
  slug: "payment-gateway-integration-ui",
  wordCount: 5000,
  readingTime: 30,
  lastUpdated: "2026-05-14",
  tags: ["hld", "payment-gateway", "stripe", "pci-dss", "3d-secure", "idempotency", "webhooks", "checkout"],
  relatedTopics: ["upi-wallet-payment-flow", "transaction-history-reconciliation-ui"],
};

export default function PaymentGatewayIntegrationUiArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A payment gateway integration UI connects the merchant's checkout page to a payment processor (Stripe, Adyen, Braintree). The design challenge is not just the UI — it is the end-to-end payment lifecycle, from card data capture to money movement confirmation, including all the failure modes: network timeouts during charge, bank declines, 3D Secure authentication challenges, webhook delivery failures, and duplicate charge prevention under retries.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The most critical constraint is PCI-DSS (Payment Card Industry Data Security Standard) compliance. Merchants must never touch raw card numbers — even storing a card number in a JavaScript variable on the merchant's page creates PCI scope. The architecture must ensure card data flows directly from the browser to the payment processor, bypassing the merchant's servers entirely. This is achieved via iframe-based card capture (Stripe Elements, Braintree hosted fields): the card input field lives in an iframe served from the payment processor's domain, and the card number never appears in the merchant's JavaScript execution context.</HighlightBlock>
        <p><strong>Explicit scope:</strong> PCI-compliant card capture, PaymentIntent lifecycle, 3D Secure flow, idempotency, webhook handling, saved payment methods, refund flows, and checkout abandonment. Not in scope: ACH/SEPA bank transfers, cryptocurrency payments, or marketplace split payments.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>PCI-compliant card capture with Stripe Elements:</strong> The checkout page embeds Stripe Elements: stripe.elements() creates a hosted iframe for the card number, expiry, and CVC fields. These iframes are served from Stripe's domain (js.stripe.com) — the merchant's JavaScript cannot read the iframe's content. When the user submits, stripe.confirmCardPayment(clientSecret, &#123;payment_method: &#123;card: cardElement&#125;&#125;) is called — Stripe's SDK tokenizes the card data inside the iframe (card number → payment method ID), sends it directly to Stripe's servers, and returns a result to the merchant's page. The merchant's server never sees the card number; it only receives the PaymentIntent ID and status from Stripe's API.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>PaymentIntent lifecycle:</strong> Before the checkout page loads, the merchant's server creates a PaymentIntent: POST https://api.stripe.com/v1/payment_intents with amount, currency, and idempotency key. Stripe returns a clientSecret (a token that authorizes the browser to confirm this specific payment). The clientSecret is passed to the frontend (never logged or stored beyond the session). The PaymentIntent states: created → requires_payment_method (waiting for card) → requires_confirmation (card entered, not yet charged) → requires_action (3DS challenge needed) → processing (charge submitted to bank) → succeeded (bank approved) → canceled or payment_failed. Each state transition is reflected in the UI: a spinner during processing, success animation on succeeded, error message on failure with the decline reason decoded from the Stripe error code.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>3D Secure (3DS2) authentication flow:</strong> Card issuers may require 3DS2 challenge (the bank's authentication popup). After stripe.confirmCardPayment, if the PaymentIntent status is requires_action, Stripe's SDK automatically opens the 3DS challenge (a redirected iframe or popup from the issuing bank). The merchant's page shows a "Verifying with your bank..." loading state. On 3DS completion, the SDK resolves with the final PaymentIntent status. The merchant's page never directly handles the 3DS communication — Stripe's SDK manages the iframe lifecycle, postMessage coordination, and timeout handling. If 3DS times out (&gt;5 minutes), the PaymentIntent transitions to payment_failed with an authentication_required decline code.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Idempotency keys for safe retries:</strong> Every charge request from the merchant's server to Stripe includes an idempotency key (a UUID generated per checkout attempt, stored in the session). If the network request to Stripe times out, the merchant's server retries with the same idempotency key — Stripe guarantees that the same key produces the same result (if the first request succeeded, the retry returns the same PaymentIntent without charging again). The idempotency key is tied to the checkout session: a new key is generated if the user changes the cart or starts a new checkout. Idempotency keys expire after 24 hours — retries after 24 hours create new charges.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Webhook handling for async payment events:</strong> Payment outcomes (charge.succeeded, charge.failed, payment_intent.payment_failed, refund.created) are delivered to the merchant's webhook endpoint by Stripe. The webhook handler: (1) verifies the Stripe-Signature header (HMAC-SHA256 of the raw request body using the webhook secret) to prevent spoofing; (2) processes the event idempotently (if the webhook is delivered twice — Stripe guarantees at-least-once delivery — the second delivery should be a no-op); (3) updates the order status in the database; (4) sends the fulfillment email. The webhook handler returns 200 within 5 seconds — heavy work (email sending, inventory updates) is enqueued to a background job queue to avoid timeout. Stripe retries failed webhooks up to 72 hours with exponential backoff.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Saved payment method management:</strong> Logged-in users can save payment methods (cards) for future use. The saved card is stored as a Stripe Customer + PaymentMethod ID — never as raw card data. On the merchant's side, the users table stores &#123;stripeCustomerId&#125;. To save a card: attach the PaymentMethod to the Stripe Customer (POST /v1/payment_methods/&#123;id&#125;/attach &#123;customer&#125;). To charge a saved card: create a PaymentIntent with customer and payment_method, with confirm: true and off_session: false (for on-session charges with 3DS capability) or off_session: true for subscription charges. The saved cards list (GET /v1/payment_methods?customer=&#123;id&#125;&type=card) is fetched from Stripe, not from the merchant's DB.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Retry logic with exponential backoff:</strong> Network failures during payment confirmation are retried with exponential backoff: initial delay 1s, multiplier 2×, max 5 retries, max delay 30s. Retryable errors: network timeouts, Stripe 500/503 errors, rate limit (429). Non-retryable: card declines (402 with decline code), authentication errors (401). The retry state is shown to the user: "Payment processing — please wait." The user is not shown the retry count (it creates anxiety). If all retries exhaust, the error is surfaced: "Payment could not be processed — please try again or use a different card." The checkout form is re-enabled for the user to retry manually.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Checkout abandonment recovery:</strong> If the user starts checkout but doesn't complete payment (closed tab, form abandoned), the merchant sends an abandonment recovery email after 1 hour. The email includes a link to resume the checkout with the same cart contents. The resume link uses a signed JWT (signed with the merchant's secret) containing the cart ID and user ID — this pre-populates the cart and skips cart reconstruction. The PaymentIntent from the abandoned session is not reused (it may have expired or been in a non-recoverable state) — a new PaymentIntent is created on checkout resume. The abandonment event is tracked in analytics for funnel optimization.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The checkout flow has three participants: the browser (React checkout page with Stripe Elements), the merchant's backend (Node.js API server managing PaymentIntents and order state), and Stripe (the payment processor). The card data path is browser → Stripe directly (iframe capture + SDK tokenization). The charge path is merchant server → Stripe API (with idempotency key). The outcome path is Stripe → merchant webhook endpoint (async event delivery). The browser polls for order confirmation by calling the merchant's GET /api/orders/&#123;id&#125; endpoint (which reads from the database, updated by the webhook handler).</HighlightBlock>
        <HighlightBlock as="p" tier="important">The merchant's server never stores card data. It stores: order records (amount, currency, status, stripePaymentIntentId), customer records (stripeCustomerId for saved card associations), and webhook event records (event ID + processed status, for idempotent duplicate handling). The webhook event store is the source of truth for payment outcomes — the PaymentIntent status from Stripe's API is the secondary source.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/payments-fintech-systems/payment-gateway-integration-ui.svg"
          alt="Payment gateway integration UI: Stripe Elements iframe card capture (card data never touches merchant JS); merchant server creates PaymentIntent with idempotency key; confirmCardPayment triggers 3DS challenge if required; PaymentIntent states (created→requires_action→processing→succeeded); Stripe webhooks (HMAC-SHA256 verified, idempotent, 5s response → background queue); saved payment methods stored as Stripe Customer+PaymentMethod IDs; retry with exponential backoff (max 5 retries, 30s max delay); abandonment recovery email at 1hr with signed JWT resume link."
          caption="Stripe Elements iframe (PCI-DSS, card never in merchant JS), PaymentIntent lifecycle, 3DS2 auto-managed by SDK, idempotency key per checkout, HMAC-SHA256 webhook verify, saved cards via Stripe Customer ID, exponential backoff retries"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">PaymentIntent Creation and Client Secret Lifecycle</h3>
        <HighlightBlock as="p" tier="crucial">The PaymentIntent is created server-side before the checkout page renders (in the page's getServerSideProps or in a POST /api/checkout/create-intent call triggered when the user clicks "Proceed to Payment"). The clientSecret returned by Stripe is embedded in the page (as a JavaScript variable or a data attribute on a non-visible element). It authorizes exactly one confirmation attempt for this specific payment amount and currency — it cannot be used to charge a different amount or currency, and it expires after 24 hours. The clientSecret must be protected: it should not appear in query strings (where it would be logged by CDNs), not in localStorage (where XSS could steal it), and not transmitted over HTTP (always HTTPS). It is passed as a JavaScript variable in the server-rendered HTML, accessible only to scripts on the same origin.</HighlightBlock>
        <HighlightBlock as="p" tier="important">PaymentIntent creation is idempotent at the merchant's server level too: if the page refreshes, the server checks if a valid (non-expired, non-canceled) PaymentIntent already exists for this checkout session. If yes, it returns the existing clientSecret. If no, it creates a new one. This prevents creating multiple PaymentIntents for the same cart — duplicate intents waste money if all are confirmed.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Decline Handling and User Messaging</h3>
        <HighlightBlock as="p" tier="crucial">Card declines must be communicated clearly without alarming the user unnecessarily. Stripe decline codes map to user-facing messages: insufficient_funds → "Your card has insufficient funds. Please use a different card or contact your bank."; card_declined (generic) → "Your card was declined. Please try a different card."; expired_card → "Your card has expired. Please update your payment method."; incorrect_cvc → "The card security code is incorrect. Please re-enter and try again." Decline codes that reveal security information (stolen_card, pickup_card) are not shown verbatim to the user — they receive the generic "card declined" message to prevent card testing attacks (where attackers test stolen card details by looking for card_not_enrolled vs. do_not_honor responses).</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Partial Capture and Refund Flows</h3>
        <HighlightBlock as="p" tier="important">For orders where the final amount is not known at charge time (e.g., hotel pre-authorizations, where the final bill depends on mini-bar usage), the PaymentIntent is created with capture_method: 'manual'. This authorizes the card for the estimated amount but does not capture the funds. After the final amount is known, the merchant calls POST /v1/payment_intents/&#123;id&#125;/capture with amount_to_capture (less than or equal to the authorized amount). Uncaptured authorizations expire in 7 days (for cards) or 2 days (for certain card networks). Partial refunds: POST /v1/refunds with amount less than the charge amount. The remaining captured amount stays with the merchant. Full refund: POST /v1/refunds without amount. Refunds take 5–10 business days to appear on the customer's statement — the merchant's UI shows "Refund initiated" immediately and "Refund completed" when the refund.updated webhook arrives with status: 'succeeded'.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Multi-Currency Display</h3>
        <HighlightBlock as="p" tier="crucial">For international merchants, prices are displayed in the user's local currency (detected from the browser's Accept-Language header and GeoIP). The displayed price is: merchant_price_USD × exchange_rate. Exchange rates are fetched from a currency API (Open Exchange Rates, European Central Bank) hourly and cached in Redis. The actual charge happens in the merchant's settlement currency (USD, EUR) — the display currency conversion is informational only. Stripe supports presentment currency (charge in the user's local currency, Stripe handles the conversion and currency risk) for merchants with a connected account in that country. The checkout form clearly labels the charge currency: "You will be charged $29.99 USD (≈ ₹2,490 INR at today's rate)."</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">Stripe hosted checkout (redirect) vs. Stripe Elements (embedded): Stripe's hosted checkout page (redirect to checkout.stripe.com) is zero-code, handles 3DS automatically, and is always PCI-compliant — but the user leaves the merchant's site, which reduces conversion rates and brand consistency. Stripe Elements (embedded iframes) keeps the user on the merchant's site but requires more integration work and careful PCI scope management. For high-volume merchants with design control requirements, Elements is the right choice. For side projects and MVPs, hosted checkout is faster to ship.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Synchronous confirmation vs. webhook-driven outcomes: stripe.confirmCardPayment returns a result synchronously (the promise resolves when Stripe has processed the charge and received the bank's response). This is sufficient for most payments. But some payment methods (bank transfers, SEPA Direct Debit, Klarna) are async — the charge is accepted but not confirmed for hours or days. For these methods, the checkout page must show a "Payment pending" state and use webhook polling (the frontend polls GET /api/orders/&#123;id&#125; every 30 seconds until status changes from pending to confirmed or failed). The order confirmation email is sent by the webhook handler, not immediately on the frontend.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A payment gateway integration UI requires: (1) Stripe Elements iframe card capture (PCI-DSS compliant, card number never in merchant JS, iframe served from Stripe's domain); (2) server-side PaymentIntent creation with idempotency key (per checkout session UUID, 24hr expiry, reused on page refresh); (3) clientSecret handling (server-rendered HTML variable, HTTPS only, not in localStorage or query string); (4) stripe.confirmCardPayment with automatic 3DS2 challenge management (SDK-managed iframe, merchant shows "Verifying..." state); (5) PaymentIntent lifecycle UI (created→processing→succeeded, decline code mapped to user-friendly messages, card_stolen never shown verbatim); (6) webhook handler (HMAC-SHA256 signature verify, 5s response with background queue, idempotent duplicate handling, exponential backoff retry by Stripe for 72 hours); (7) saved payment methods (Stripe Customer + PaymentMethod IDs, never raw card data, off_session for subscriptions); (8) exponential backoff retries (1s initial, 2× multiplier, max 5 retries, max 30s delay, retryable vs. non-retryable error classification); (9) partial capture (capture_method: manual, 7-day auth window, amount_to_capture on settle); and (10) abandonment recovery (1hr email with signed JWT resume link, new PaymentIntent on resume). Security invariant: the merchant's server never receives, transmits, or stores raw card numbers — PCI scope is limited to the Stripe integration code itself.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
