"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-transaction-history-reconciliation-ui",
  title: "Design a Transaction History & Reconciliation UI",
  description:
    "Architecture for a transaction history and reconciliation UI: paginated transaction ledger with cursor-based pagination, multi-dimensional filtering (date range, status, category, amount range), real-time transaction streaming via SSE for live balance updates, statement export in CSV/PDF with async generation, bank statement reconciliation (match merchant records against bank settlement files), discrepancy detection and alert system, dispute management workflow, running balance computation, and audit trail for all financial record modifications.",
  category: "high-level-design",
  subcategory: "payments-fintech-systems",
  slug: "transaction-history-reconciliation-ui",
  wordCount: 5000,
  readingTime: 30,
  lastUpdated: "2026-05-14",
  tags: ["hld", "transaction-history", "reconciliation", "ledger", "cursor-pagination", "statement-export", "dispute-management", "audit-trail"],
  relatedTopics: ["payment-gateway-integration-ui", "fraud-detection-risk-alert-ui"],
};

export default function TransactionHistoryReconciliationUiArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A transaction history UI serves two audiences with different needs: consumers (who want to see what they spent, filter by category, download statements for tax purposes, and dispute incorrect charges) and merchants (who need to reconcile received payments against bank settlements, identify missing credits, and produce accurate financial reports). The UI is a window into the financial ledger — it must be accurate, auditable, and never show stale data on financial records that affect money movement decisions.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The hardest problem is reconciliation: matching the merchant's internal transaction records (what the payment system recorded) against the bank's settlement files (what actually moved in the bank account). Discrepancies occur due to failed webhooks (the payment succeeded at the bank but the merchant's system never received the confirmation), bank fees deducted at settlement, and time zone differences in date boundaries. Unreconciled discrepancies represent either missing revenue or unexplained debits — both require investigation and resolution.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Transaction ledger UI with pagination and filtering, real-time balance updates, statement export, bank reconciliation engine, discrepancy detection, dispute management, running balance, and audit trail. Not in scope: tax computation, accounting system integrations (QuickBooks, Tally), or multi-currency revaluation.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Cursor-based paginated transaction ledger:</strong> The transaction history is a reverse-chronological list of ledger entries: date, description, amount, category (auto-categorized from merchant name), running balance, and status (completed, pending, failed, reversed). Pagination uses cursor-based pagination (not offset-based): the cursor is the transaction ID of the last fetched item (e.g., GET /api/transactions?after=txn_1234&limit=25). Cursor pagination avoids the "page drift" problem of offset pagination (where inserting a new transaction shifts all offset positions, causing items to appear twice or be skipped). The transaction ID is a time-ordered ULID — sorting by ID gives chronological order without a separate date sort. The list is virtualized (react-window or TanStack Virtual) for smooth scrolling through thousands of transactions without DOM bloat.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Multi-dimensional filtering:</strong> The filter panel allows combining: date range (calendar picker, with presets: today, last 7 days, last 30 days, this month, last month, custom), transaction type (credit/debit/all), status (completed/pending/failed), category (groceries/dining/utilities/..., auto-categorized but user-editable), amount range (min/max slider), and payment method (UPI/card/wallet/bank transfer). Filters are applied server-side (added as WHERE clauses to the ledger query) to support large transaction histories that cannot be fully loaded client-side. The active filter state is serialized to the URL (query string) so the filtered view is bookmarkable and shareable. Clearing all filters resets to the default view.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Statement export in CSV and PDF:</strong> Users can export their transaction history: CSV (for importing into spreadsheets, tax software, or accounting tools) and PDF (formatted bank statement with logo, account holder info, opening balance, transactions, and closing balance). Large exports (&gt;1,000 transactions or date ranges &gt;3 months) are generated asynchronously: the user clicks "Export" → the server enqueues an export job → returns a job ID → the UI polls GET /api/exports/&#123;jobId&#125; every 5 seconds → on completion, a download link is returned (pre-signed S3 URL with 24hr TTL) and a "Download ready" notification is shown. Small exports (&lt;1,000 transactions) are generated synchronously and returned as a file download response.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Bank statement reconciliation engine:</strong> The merchant uploads a bank settlement file (CSV or MT940 format, provided by the bank daily/weekly). The reconciliation engine: (1) parses the bank file into settlement records (date, amount, reference number, description); (2) matches each settlement record against the merchant's transaction records using the payment reference number as the primary key; (3) three-way matching: if the reference matches and amounts match → reconciled; if reference matches but amount differs → fee discrepancy (bank deducted a processing fee); if a transaction exists in the merchant's records but not in the bank file → unreconciled (possible webhook failure or bank error); if a record exists in the bank file but not in the merchant's records → unexpected credit (possible duplicate payment). The reconciliation result is stored as a report with a discrepancy count and a drillable list of unreconciled items.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Real-time balance updates via SSE:</strong> The account balance displayed in the header must update in real-time when payments arrive. An SSE stream (GET /api/balance/stream) pushes balance_updated events: &#123;newBalance: 12450.00, delta: +500.00, txnId: "txn_xyz"&#125;. The balance in the UI is updated optimistically on the event without a full page refresh. The SSE stream is reconnected automatically (EventSource handles reconnection with Last-Event-ID for message replay). For mobile or background tab scenarios, the balance is refreshed on tab visibility change (document.addEventListener('visibilitychange', refetchBalance)). The SSE stream is per-user and scoped to the user's account — each connection is authenticated via the session cookie.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Dispute management workflow:</strong> Users can dispute a transaction (incorrect charge, unauthorized payment). The dispute flow: (1) user clicks "Dispute" on a transaction → selects dispute reason (item not received, unauthorized charge, amount incorrect, duplicate charge); (2) uploads supporting evidence (screenshots, chat logs) via S3 presigned URL; (3) dispute is created in the system with status: open; (4) the payment processor's dispute API is called (Stripe: POST /v1/disputes/&#123;id&#125;/respond with evidence); (5) the dispute page shows the timeline: "Submitted → Under Review → Resolved". The dispute SLA: 45 business days for card chargebacks (Visa/Mastercard deadline), 15 business days for UPI disputes (NPCI mandate). Automated alerts notify the dispute handler when the SLA deadline is approaching (7 days before). Resolved disputes that are decided in the user's favor trigger a credit transaction in the ledger.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Running balance computation:</strong> The running balance column shows the account balance after each transaction. This requires computing a cumulative sum of all transactions in reverse chronological order. For accounts with millions of transactions, computing this on every query is expensive. Optimization: snapshot balances are stored at periodic checkpoints (e.g., the balance at the end of each month, stored as a cached snapshot). To compute the running balance for transactions in a given month, start from the month's snapshot and apply transactions forward. The snapshot is recomputed when reconciliation corrections are applied (corrections can change historical balances, requiring snapshot invalidation).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Audit trail for financial modifications:</strong> Every modification to a financial record (correcting a transaction description, reclassifying a category, applying a reconciliation credit, resolving a dispute) is logged to an immutable audit table: &#123;eventId, entityType, entityId, fieldChanged, oldValue, newValue, changedBy, changedAt, reason&#125;. The audit table is append-only — no updates or deletes (enforced by database row-level security removing UPDATE and DELETE privileges on the audit table). The audit trail is available to compliance and support teams via a separate admin dashboard. All modifications to financial records require a reason field — this is enforced at the API layer (the PATCH endpoint for transactions requires a reason string in the request body).</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The transaction history system has three data sources: the operational ledger (real-time transaction writes from the payment system, stored in PostgreSQL), the reconciliation store (matching records and discrepancy reports, stored in a separate schema), and the analytics warehouse (historical transaction data in ClickHouse or Redshift, used for reporting queries that are too expensive to run on the operational DB). The transaction history UI reads from the operational DB for recent transactions (last 90 days) and from the analytics warehouse for historical queries (older than 90 days). This split prevents analytics queries from impacting the performance of real-time payment processing on the operational DB.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The export service is a separate worker service that reads from both data sources, generates the requested file format, writes to S3, and updates the export job status in Redis. The reconciliation engine is a batch job that runs when the bank settlement file is uploaded — it reads the settlement file from S3, queries the operational ledger for the matching date range, performs the matching, and writes the results to the reconciliation store.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/payments-fintech-systems/transaction-history-reconciliation-ui.svg"
          alt="Transaction history and reconciliation UI: cursor-based pagination (ULID txnId, no offset drift); multi-dimensional server-side filtering (date/type/status/category/amount); SSE balance_updated stream with Last-Event-ID reconnect; async export (job queue → S3 presigned URL → 24hr TTL); bank settlement file upload → reconciliation engine (reference key matching, 3-way: reconciled/fee-discrepancy/unreconciled/unexpected-credit); dispute flow (reason + S3 evidence → payment processor API, 45-day chargeback SLA); running balance from monthly snapshots + forward delta; immutable append-only audit table."
          caption="Cursor pagination (ULID, no drift), SSE balance stream (Last-Event-ID), async export (S3 presigned 24hr), bank file 3-way reconciliation (ref key matching), dispute workflow (45-day SLA), snapshot running balance, immutable audit table (append-only)"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Ledger Data Model and Immutability</h3>
        <HighlightBlock as="p" tier="important">The ledger table is immutable: once a transaction record is written, it is never updated or deleted. Corrections are handled via compensating transactions: if a transaction was recorded incorrectly, a reversal entry is inserted (negative amount, reference to the original transaction ID) and a corrected entry is inserted. The net effect of the original + reversal + correction produces the correct balance, and the full history of the error and correction is preserved. This is the double-entry bookkeeping principle applied to software: the ledger is an append-only journal of financial facts, and the current state is derived by replaying the journal.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The ledger schema: &#123;txnId ULID PK, accountId, type: 'credit'|'debit', amount DECIMAL(12,2), currency CHAR(3), status: 'pending'|'completed'|'failed'|'reversed', description, category, paymentMethod, referenceId (external payment reference), parentTxnId (for reversals and corrections), createdAt, settledAt, metadata JSONB&#125;. The amount is always positive — the type field indicates direction. Balance queries: SELECT SUM(CASE WHEN type='credit' THEN amount ELSE -amount END) WHERE accountId = ? AND status = 'completed'.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Reconciliation Engine Matching Algorithm</h3>
        <HighlightBlock as="p" tier="important">The reconciliation matching runs in three passes: (1) exact match — join bank settlement records and merchant records on the payment reference ID and amount. Matched pairs are marked as "reconciled." (2) fuzzy match — for unmatched records after pass 1, attempt matching by amount + date (±1 day for time zone differences). If a unique match is found, mark as "reconciled with note" (reference mismatch, possibly due to reformatting by the bank). (3) manual review queue — all remaining unmatched records from both sides are added to the discrepancy queue for manual investigation.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Discrepancy types and automated handling: fee discrepancy (bank record = merchant record - bank_fee) → auto-create a fee debit entry in the ledger for the fee amount; exact duplicate (same reference ID appears twice in the bank file) → flag as "duplicate settlement," do not credit twice; missing settlement (merchant has a successful payment with no bank record) → create an "unreconciled" flag, alert the finance team, auto-query the bank API after 24 hours. The reconciliation report summarizes: total transactions, reconciled count, discrepancy count, discrepancy amount, and a breakdown by discrepancy type.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Transaction Categorization</h3>
        <HighlightBlock as="p" tier="important">Transactions are auto-categorized by merchant name using a merchant category code (MCC) database. MCC is a 4-digit code assigned by card networks to each merchant type. The categorization pipeline: merchant name → MCC lookup (precomputed dictionary, 50K+ merchant names) → category mapping (MCC 5411 = Grocery Stores → "Groceries"; MCC 5812 = Eating Places → "Dining"). For UPI transactions (where the merchant name is the VPA, e.g., dominos@icici), the VPA is mapped to a merchant name and category using a UPI merchant registry. Uncategorized transactions (VPA not in registry, unfamiliar merchant name) are categorized as "Other" and surfaced to the user for manual categorization. User-applied categories are stored and used to train a personalized classifier that improves categorization accuracy for that user's spending patterns over time.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="crucial">Operational DB vs. analytics warehouse for history queries: running a 12-month transaction history query on the operational PostgreSQL DB would lock rows and impact live payment processing. The split approach (operational DB for last 90 days, analytics warehouse for older data) keeps payment processing fast but adds complexity: the UI must query two different APIs depending on the date range, and data consistency between the two stores must be maintained via a nightly ETL job. An alternative: use a read replica of the operational DB for history queries. This avoids the two-system complexity but the read replica may still impact primary replication bandwidth at scale.</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">Statement PDF generation: generating a PDF for a 12-month statement with 5,000 transactions requires significant compute. Puppeteer (headless Chrome, rendering HTML to PDF) produces the best-formatted output but is slow (~10s for a large statement) and memory-intensive (~500MB per rendering process). Alternatives: PDFKit (programmatic PDF generation in Node.js, faster but less formatting control), WeasyPrint (Python, good HTML/CSS support), or a cloud PDF service (DocRaptor, Puppeteer as a service). For production, use a dedicated PDF rendering worker pool with Puppeteer, isolated from the web server, with a job queue to handle burst demand.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A transaction history and reconciliation UI requires: (1) cursor-based pagination (ULID txnId as cursor, no offset drift, TanStack Virtual for scrolling); (2) server-side multi-dimensional filtering (date/type/status/category/amount, URL-serialized filter state); (3) SSE balance stream (balance_updated event, Last-Event-ID reconnect, visibilitychange refetch); (4) async statement export (&lt;1K sync, &gt;1K job queue → S3 presigned URL 24hr TTL → polling); (5) bank file reconciliation (3-pass: exact ref match → fuzzy amount+date ±1day → manual queue; fee discrepancy auto-credit, duplicate flag, missing settlement alert + 24hr bank query); (6) dispute workflow (reason + S3 evidence, payment processor API, 45-day SLA alert at 7 days remaining, credit on resolution); (7) running balance (monthly checkpoint snapshots + forward delta, snapshot invalidated on reconciliation correction); (8) immutable append-only ledger (no UPDATE/DELETE, corrections via compensating transactions, double-entry bookkeeping); (9) audit trail (append-only table, reason required, no UPDATE/DELETE privileges); and (10) transaction categorization (MCC database + UPI registry, user-editable, personalized classifier). The core accounting principle: money never disappears — every discrepancy has a source and must be accounted for, either as a fee, a timing difference, or an error requiring correction.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
