"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-file-version-history-restore",
  title: "Design a File Version History & Restore System (like Google Drive / Dropbox)",
  description:
    "Architecture for a file version history and restore system: version row per save (versionId, fileId, s3Key, deltaKey, size, createdAt), bsdiff binary delta for text/docs vs full copy for binary files >50% changed, delta chain with max depth 100 before a new full snapshot, version list timeline with author and size delta, non-destructive restore via delta chain reconstruction uploaded as a new version, retention policy (free: 30 versions/30 days, paid: unlimited), nightly GC with 7-day grace period, and 30-day soft-delete trash with one-click restore.",
  category: "high-level-design",
  subcategory: "file-storage-cloud-drive-systems",
  slug: "file-version-history-restore",
  wordCount: 4900,
  readingTime: 29,
  lastUpdated: "2026-05-14",
  tags: ["hld", "version-history", "file-versioning", "delta-storage", "bsdiff", "google-drive", "dropbox", "restore"],
  relatedTopics: ["cloud-storage-ui", "file-sharing-permission-system"],
};

export default function FileVersionHistoryRestoreArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A file version history system allows users to see the history of changes to a file over time and restore any previous version. Every time a user saves a file (uploads a new version), the system captures that state as a named version that can be browsed and restored later. The core challenges are: (1) storage efficiency — naively storing a full copy of the file for every save is prohibitively expensive for large files or frequently-edited documents; (2) restore speed — reconstructing a version from a delta chain must be fast enough to feel responsive (sub-second for small files, a few seconds for large files); (3) retention policy — free users have a limited version window while paid users have unlimited history; and (4) consistency — a restore must be atomic and non-destructive (the current version must never be lost during a restore operation).</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">The fundamental design question is: full copies or deltas? Full copies are simple but expensive. Binary deltas (bsdiff) dramatically reduce storage for text-heavy files (e.g., a 10MB document that changes 1KB per save — full copies use 10MB × N saves, bsdiff uses 10MB + 1KB × N saves). The delta approach introduces complexity in restoration (you must reconstruct the version by applying a chain of deltas from the nearest snapshot) and risk (a corrupted delta in the chain makes all subsequent versions unrestorable). The system uses a hybrid approach: bsdiff deltas for text and document files with a chain depth limit (max 100 deltas before a new full snapshot), and full copies for binary files (images, videos, executables) where deltas are ineffective.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Version creation on every save, version list timeline, restore flow, delta vs. full copy storage strategy, retention policy and garbage collection, and soft-delete trash. Not in scope: collaborative editing (real-time co-authoring creates versions differently), the file upload mechanism itself (covered in the cloud storage article), or permissions (covered in the sharing article).</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Version creation on every save:</strong> When a user uploads a new version of a file (PUT /files/&#123;id&#125;), the system creates a new version row and decides whether to store the new version as a full copy or a binary delta against the previous version. Decision logic: (a) if the file is binary (image, video, executable, ZIP, PDF — detected by MIME type), always store a full copy (bsdiff on binary files produces poor compression and takes too long to compute); (b) if the file is text-based (plain text, Markdown, code, CSV, JSON, HTML, Word/OOXML documents) AND the previous version exists AND the delta is less than 50% of the file size, store the delta; (c) if the delta exceeds 50% of the file size (the file has been substantially rewritten), store a full copy and reset the delta chain counter; (d) if the current chain depth reaches 100 deltas, force a full copy (new snapshot) and reset the chain. The version row schema: (versionId UUID, fileId UUID, s3Key text — the S3 object key for the full copy or null, deltaKey text — the S3 object key for the delta binary or null, baseVersionId UUID — the version this delta was computed from, chainDepth int, size bigint, contentHash SHA-256, createdAt timestamptz, createdBy userId, label text optional).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Delta computation:</strong> The delta (bsdiff) is computed server-side when the new file content arrives. The server downloads the previous version's bytes from S3 (or the reconstructed bytes for delta-chained versions), runs bsdiff to produce a binary patch, uploads the patch to S3 under a separate key (e.g., s3://bucket/deltas/&#123;versionId&#125;.bspatch), and records the delta's S3 key in the version row. bsdiff is O(N log N) time and O(N) memory where N is the file size — acceptable for document-sized files (1–100MB) but too slow for very large files (&gt;500MB, which is why binary files always get full copies). The delta is applied using bspatch on restore.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Version list and timeline:</strong> GET /files/&#123;id&#125;/versions returns a paginated list of versions ordered by createdAt descending (newest first). Each version entry in the response: &#123;versionId, label, createdAt, createdBy (name, avatar), size, sizeDelta (change vs previous version — positive for growth, negative for shrink), contentHash, isDeltaStored&#125;. The client renders a timeline UI showing each save with the author, timestamp, and size change. Users can click a version to preview it (the API returns a presigned URL for the reconstructed version bytes) or to restore it. Named versions: users can label a specific version ("Q1 Final", "Before Major Refactor") — the label field is updated via PATCH /files/&#123;id&#125;/versions/&#123;versionId&#125;. Named versions are exempt from the automatic retention policy (they are never deleted by GC even when outside the retention window — only explicitly deleted by the user).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Restore flow:</strong> POST /files/&#123;id&#125;/restore &#123;versionId&#125; — restores the file to the state it was in at the specified version. The restore is non-destructive: it creates a new version (so the current state is preserved and itself restorable). The restore worker: (1) identifies the target version row; (2) if the target version has an s3Key (full copy), download directly; (3) if the target version has a deltaKey, walk the chain backward to the nearest ancestor with an s3Key (full snapshot), then forward-apply each delta using bspatch to reconstruct the target state; (4) upload the reconstructed bytes to S3 as a new object; (5) INSERT a new version row with the reconstructed bytes as a full copy (isRestored = true, restoredFromVersionId = targetVersionId); (6) UPDATE files SET currentVersionId = newVersionId. The old version is preserved intact. The restore is confirmed only after step 6 commits — the file is never left in an intermediate state. If the restore worker fails, the currentVersionId is not updated and the file remains at its prior state.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Retention policy:</strong> Free plan: retain the 30 most recent versions OR 30 days of history, whichever is fewer (i.e., if a file has 50 saves in one day, only the 30 most recent are kept). Paid plans: unlimited version history. Named versions are always retained regardless of plan. The retention policy is enforced by a nightly GC job (not at save time, to avoid slowing down the upload path). GC logic: for each file, SELECT versions ORDER BY createdAt DESC; find the cutoff position (version 31 or the first version older than 30 days, whichever comes first); mark versions beyond the cutoff as 'expired' (UPDATE versions SET status = 'expired' WHERE ...). Expired versions are not immediately deleted — they are soft-expired for 7 days (a grace period during which the user can recover by upgrading to a paid plan). After the grace period, a second GC pass hard-deletes the expired version rows and the S3 objects (for full copies) or S3 delta objects. S3 objects that are no longer referenced by any version row are deleted via a reference count maintained in the chunk_store table (same as the dedup chunk GC described in the storage article).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Delta chain integrity:</strong> A corrupted delta makes all versions downstream of it unrestorable. Mitigation: (1) each delta's SHA-256 hash is stored in the version row; the restore worker verifies the hash before applying the patch; (2) a background integrity checker runs weekly: for each version with a deltaKey, reconstruct the version bytes (walk the chain), compute the SHA-256, and compare with the stored contentHash; if they don't match, flag the version as 'corrupted' and alert the team; (3) every full snapshot (chainDepth = 0) version is an independent recovery point — a corrupted delta chain can be restorable from the nearest snapshot at the cost of losing the intermediate delta versions; (4) for high-value files (starred files or files with many views), the system eagerly materialises every Nth version as a full copy regardless of file type (N = 10), providing more frequent recovery points.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Soft-delete trash:</strong> When a user deletes a file, it is moved to the trash (files.status = 'trashed', trashedAt = now()). Trashed files retain all their version history. The user has 30 days to restore the file from trash (POST /trash/&#123;id&#125;/restore — sets status = 'active', clears trashedAt). After 30 days, a GC job permanently deletes the file and all its versions. The trash UI shows all trashed files with their trash date and "days remaining before permanent deletion." For shared files, only the owner can permanently delete or restore from trash; collaborators with edit access can move to trash but cannot permanently delete or restore.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Restore performance:</strong> Restore latency is dominated by the delta chain walk. With a max chain depth of 100 and typical document sizes of 1–10MB, the worst case is downloading 100 delta S3 objects (in parallel where possible — independent deltas can be pre-fetched) and applying 100 bspatch operations serially (each bspatch is O(N) where N is the result size). For a 10MB document with 100 1KB deltas, total restore time is approximately: 100 × (S3 presigned GET latency ~50ms) + 100 × (bspatch on 10MB ~10ms) = 5 seconds + 1 second = ~6 seconds worst case. This is acceptable for the restore flow (which is rare and expected to take a few seconds). For preview (user hovering over a version in the timeline to preview it), the system uses a lazy reconstruction approach: reconstruct on first preview request and cache the result in S3 with a 1-hour TTL presigned URL. Subsequent preview requests within the hour use the cached URL without re-running bspatch.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The version history system has three planes: the write plane (version creation on each save — delta computation, S3 upload, version row INSERT), the read plane (version list, preview reconstruction, restore), and the lifecycle plane (GC nightly job, integrity checker, trash cleanup). The delta computation happens synchronously in the upload complete handler (after the file bytes are in S3 but before the API returns the fileId to the client). The restore flow is handled by a dedicated restore worker service (asynchronous job, typically completes in 1–10 seconds depending on chain depth).</HighlightBlock>
        <HighlightBlock as="p" tier="important">S3 versioning (the native AWS S3 feature) is intentionally not used as the primary versioning mechanism. Native S3 versioning stores every PUT as a new version transparently, but it doesn't support: delta compression, named versions, custom retention policies, or the metadata (createdBy, label) needed for the timeline UI. The application-level version table gives full control over the version lifecycle and metadata, using S3 purely as a blob store for the version bytes or delta objects.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/file-storage-cloud-drive-systems/file-version-history-restore.svg"
          alt="File version history and restore system: every save creates a version row; bsdiff delta computed vs previous version if text-based and delta <50% of file size, otherwise full copy; delta chain capped at depth 100 then new full snapshot; version list returns timeline with author/size/delta; restore walks delta chain from nearest snapshot, reconstructs bytes, uploads as new version non-destructively; retention GC marks expired versions with 7-day grace, then hard-deletes S3 objects; trash is 30-day soft-delete."
          caption="Per-save version row: s3Key (full copy) or deltaKey (bsdiff patch); delta decision: text+delta<50% → bsdiff; chain depth >100 or binary → full snapshot; restore: walk chain → reconstruct → INSERT new version → UPDATE currentVersionId; GC: nightly, 7-day grace, named versions exempt; trash: 30-day soft-delete"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Delta Storage Strategy</h3>
        <HighlightBlock as="p" tier="important">bsdiff (binary diff) works by computing the difference between two byte arrays using a suffix array algorithm. It produces a compact binary patch that, when applied to the source bytes using bspatch, reconstructs the target bytes exactly. bsdiff works best on structured text (code, documents, JSON) where changes are localized. For binary files, bsdiff often produces patches larger than the original file (because binary formats like JPEG, MP4, or ZIP use internal compression that makes adjacent bytes appear random to diff algorithms). This is why the system uses full copies for binary files.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Delta chain traversal for restore: given a target version at chain depth D, the restore walk is: fetch version row for target → if deltaKey: fetch version row for baseVersionId → repeat until a version with s3Key is found (the nearest snapshot). This traversal requires D sequential database reads. Optimization: the version row stores not just baseVersionId (immediate parent) but also snapshotVersionId (the nearest ancestor snapshot). This allows the restore to download the snapshot in one step and then forward-apply D bspatch operations without needing to traverse the database chain. The snapshotVersionId is set at delta creation time (it is the version row where chainDepth = 0 that this delta is descended from).</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Version Row Lifecycle</h3>
        <HighlightBlock as="p" tier="important">Version rows transition through states: 'active' (current or historical, accessible), 'named' (user-labeled, exempt from GC), 'expired' (beyond retention window, in 7-day grace period), 'deleted' (soft-deleted, S3 objects pending cleanup). The currentVersionId on the files table always points to an 'active' version row. When a new version is created, the previous currentVersionId remains 'active' (accessible in version history). When a restore creates a new version, the restored-from version remains 'active' — both the old and the new version are in history. Version rows are never mutated (except status transitions and the label field) — this immutability simplifies the audit trail and makes the version history trustworthy.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Garbage Collection Design</h3>
        <HighlightBlock as="p" tier="crucial">The GC job runs nightly in a maintenance window. It processes files in batches (1,000 files at a time) to avoid long-running transactions. For each file, it computes the cutoff version (30th most recent OR first version older than 30 days, whichever yields fewer retained versions — the stricter rule). Named versions are excluded from the count (a file with 5 named versions and 30 unnamed versions keeps the 5 named + the 30 most recent unnamed = 35 versions, not 30). After computing the cutoff, the GC marks eligible versions as 'expired'. The 7-day grace period is tracked by the expiredAt timestamp — versions transition from 'expired' to 'deleted' only after expiredAt + 7 days. S3 object deletion is done after the version row is marked 'deleted' (never before — deleted S3 objects with live version rows would break restore). The GC uses a two-phase delete: (1) mark version row 'deleted' + record the s3Key in a pending_s3_deletes table; (2) a separate S3 cleanup job processes the pending_s3_deletes table in batches using the S3 DeleteObjects API (batch delete up to 1,000 objects per request). This two-phase approach is resilient to partial failures — if the S3 cleanup job crashes, the pending_s3_deletes table retains the keys and the cleanup retries on the next run.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">Full copies vs. delta chains: the delta approach requires more complex restore logic and introduces a dependency chain (a corrupted delta affects all downstream versions). The complexity is justified for document-heavy use cases (Google Docs, Notion, code repositories) where documents change incrementally and storage costs are significant. For a photo storage service (mostly immutable files — users rarely re-upload modified photos), deltas provide no value and the system should use full copies exclusively. The decision of when to use deltas should be configurable per file type or per workspace.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Non-destructive restore: always creating a new version on restore (rather than updating currentVersionId to point to the old version) has a storage cost (one extra copy of the file bytes for each restore). The benefit is safety — a user who restores to an old version and then realizes they want the version they just overwrote can find it in the version history as the version immediately before the restore. This eliminates an entire class of "I accidentally restored to the wrong version" support tickets. The storage cost is bounded by the number of restores (a rare operation) and is negligible compared to the value of the safety guarantee.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A file version history and restore system requires: (1) version row per save: &#123;versionId, fileId, s3Key, deltaKey, baseVersionId, chainDepth, size, contentHash, createdAt&#125;; (2) delta decision: text files + delta &lt;50% file size → bsdiff; binary files OR delta &gt;50% OR chainDepth = 100 → full copy new snapshot; (3) delta chain max depth 100 to bound restore walk; (4) version list timeline with author, size delta, and optional user label; named versions exempt from GC; (5) restore: walk delta chain from nearest snapshot → reconstruct bytes → INSERT new version → UPDATE currentVersionId — non-destructive, current state preserved; (6) restore performance: O(chain depth) bspatch operations — worst case ~6s for depth-100 10MB document; preview cached in S3 with 1hr presigned URL; (7) retention GC: nightly, free = 30 versions or 30 days, named versions exempt, 7-day grace before hard delete, two-phase S3 delete; (8) delta chain integrity: SHA-256 verification per delta, weekly background integrity checker, full snapshot every N versions for high-value files; (9) soft-delete trash: 30-day window, retains full version history during trash period, auto-purge after 30 days.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
