"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-ab-testing-platform-ui",
  title: "Design an A/B Testing Platform UI",
  description:
    "Architecture for an A/B testing platform UI: experiment creation with hypothesis and metric selection, deterministic user bucketing via hashed user ID, assignment service with consistent allocation, real-time result dashboard with statistical significance calculation, sample ratio mismatch detection, guardrail metric alerting, segment analysis (by country, device, cohort), experiment lifecycle management (draft, running, paused, concluded), and mutual exclusion groups to prevent experiment interference.",
  category: "high-level-design",
  subcategory: "experimentation-growth-systems",
  slug: "ab-testing-platform-ui",
  wordCount: 5000,
  readingTime: 30,
  lastUpdated: "2026-05-14",
  tags: ["hld", "ab-testing", "experimentation", "statistical-significance", "bucketing", "feature-flags", "guardrail-metrics", "sample-ratio-mismatch"],
  relatedTopics: ["feature-rollout-experimentation-system", "user-funnel-analytics-dashboard"],
};

export default function AbTestingPlatformUiArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">An A/B testing platform lets product teams run controlled experiments to measure the causal impact of a change. Rather than asking "did metrics go up after we shipped this feature?", an A/B test asks "did metrics go up because of this feature, controlling for everything else?" The platform handles the full lifecycle: designing experiments (hypothesis, variants, metrics), running them (bucketing users into control and treatment groups), analyzing results (statistical significance, confidence intervals), and deciding outcomes (ship, roll back, or extend the test).</HighlightBlock>
        <HighlightBlock as="p" tier="important">The two hardest problems: (1) consistent bucketing — a user assigned to the treatment group must see the treatment on every page load, every device, even after clearing cookies. Bucketing based on user ID (not session or cookie) with a deterministic hash function solves this. (2) Statistical validity — product teams will misinterpret results without guardrails. Peeking at results before statistical power is reached, ignoring sample ratio mismatches, and not accounting for novelty effects all lead to false conclusions. The platform UI must surface these issues prominently, not bury them in a statistics documentation page.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Experiment creation UI, bucketing logic, results dashboard with statistical significance, sample ratio mismatch detection, guardrail metric alerting, and experiment lifecycle management. Not in scope: the data pipeline that computes experiment metrics, Bayesian vs. frequentist debate, or multi-armed bandit allocation.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Experiment creation:</strong> The creation form captures: experiment name and hypothesis (free text), variants (control + 1–4 treatments with traffic allocation percentages that must sum to 100%), primary metric (the one metric the experiment is designed to move — e.g., checkout conversion rate), secondary metrics (monitored but not decision criteria), guardrail metrics (metrics that must not degrade — e.g., page load time, error rate), target audience filter (all users, or a segment: country = US, platform = mobile, user cohort = registered &gt; 30 days), and minimum detectable effect (MDE) — the smallest improvement worth detecting, used to calculate the required sample size and estimated run duration.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>User bucketing:</strong> Assignment is deterministic: bucket = hash(userId + experimentId) % 100. A user assigned to treatment sees treatment on every visit across devices (as long as they are logged in). The hash is computed client-side (in the feature flag SDK) so assignment is instantaneous with no server round trip. The salt (experimentId) ensures that two experiments running simultaneously assign users independently — a user in treatment for experiment A is not necessarily in treatment for experiment B. Traffic allocation: if treatment gets 50%, users with hash value 0–49 are in treatment; 50–99 are in control. Non-participating users (outside the target segment filter) are excluded before hashing.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Results dashboard:</strong> The results page shows per-variant: sample size, conversion rate (or mean value for continuous metrics), absolute lift (treatment − control), relative lift ((treatment − control) / control × 100%), p-value, and 95% confidence interval on the lift. Color coding: green if the confidence interval is entirely above zero (statistically significant positive), red if entirely below zero (statistically significant negative), grey if the confidence interval spans zero (not yet significant). A "Days to significance" estimate is shown using the current effect size and sample size trajectory. The dashboard polls GET /api/experiments/&#123;id&#125;/results every 60 seconds for in-progress experiments.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Guardrail metric alerting:</strong> Guardrail metrics are monitored throughout the experiment. If a guardrail metric degrades by more than a configured threshold (e.g., page load time increases by &gt;5% at p &lt; 0.05), an alert banner appears on the results dashboard: "⚠ Guardrail metric 'p95 load time' has degraded significantly in treatment. Consider pausing the experiment." The experiment owner receives an email notification. Automated pausing (stopping the experiment if a guardrail alert fires) is opt-in — most teams prefer manual review before pausing to avoid false positives shutting down valid experiments.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Sample ratio mismatch (SRM) detection:</strong> An SRM occurs when the actual ratio of users in each variant differs significantly from the configured allocation (e.g., configured 50/50 but observed 48/52). SRM invalidates the experiment — the groups are not comparable. The dashboard detects SRM using a chi-squared test on the observed vs. expected user counts. If the SRM p-value is &lt; 0.01, a red warning banner appears: "Sample Ratio Mismatch detected. The observed allocation (48%/52%) differs significantly from the configured allocation (50%/50%). Experiment results are unreliable until this is resolved." Common SRM causes: bot traffic, caching layers that bypass bucketing, or bugs in the assignment SDK.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Mutual exclusion:</strong> Two experiments that modify the same UI element can interfere with each other if the same user is enrolled in both. Mutual exclusion groups (MEGs) prevent this: experiments in the same MEG are guaranteed to enroll disjoint user sets. Implementation: MEG assignment is a top-level hash. Users with hash 0–49 are eligible for experiments in MEG-A; users 50–99 are eligible for MEG-B. Within MEG-A, individual experiments further sub-divide the 0–49 range. The experiment creation UI shows a warning if the new experiment's target overlaps with a running experiment that doesn't share a MEG.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Segment analysis:</strong> Beyond the overall result, the dashboard shows breakdowns by segment: by country (top 5 by traffic), by platform (desktop/mobile/tablet), and by user cohort (new vs. returning, free vs. paid). Each segment shows its own lift, confidence interval, and significance. Heterogeneous treatment effects (the treatment works well for mobile users but hurts desktop users) are surfaced automatically if any segment's result diverges significantly from the overall result. The segment analysis is a secondary tab — the primary tab shows the overall result to avoid cherry-picking a favorable segment.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The A/B testing platform has two runtime paths: the assignment path (fast, happens on every user request) and the analysis path (slower, runs on aggregated data). The assignment path: the feature flag SDK (loaded client-side) computes the user's bucket deterministically from userId + experimentId. It fetches the experiment configuration once (cached in localStorage, refreshed every 10 minutes) and returns the variant synchronously — no network round trip on the critical path. The assignment is logged as an event (user X was assigned to variant Y of experiment Z at time T) — this event stream feeds the analysis pipeline.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The analysis path runs asynchronously: a data pipeline (Spark/Flink) joins the assignment events with the metric events (conversions, page loads, errors) and computes per-variant metric values. These computed values are written to the experiment results store, which the dashboard reads via GET /api/experiments/&#123;id&#125;/results. The dashboard does not compute statistics itself — the statistics are pre-computed by the pipeline and the dashboard renders them. This keeps the dashboard fast and avoids inconsistent statistical methods across the team.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/experimentation-growth-systems/ab-testing-platform-ui.svg"
          alt="A/B testing platform UI: user bucketing via hash(userId+experimentId)%100 for deterministic assignment; experiment creation with hypothesis, variants, traffic allocation, primary/guardrail metrics, MDE and sample size estimate; results dashboard showing per-variant conversion rate, absolute and relative lift, p-value, 95% CI color-coded green/grey/red, days-to-significance; SRM detection via chi-squared test with red banner when p<0.01; guardrail metric alerting on degradation >threshold; segment analysis by country/platform/cohort as secondary tab; mutual exclusion groups for experiment isolation."
          caption="Deterministic hash bucketing (userId+experimentId, no network on critical path), results dashboard (lift, p-value, 95% CI color-coded), SRM detection (chi-squared p&lt;0.01 red banner), guardrail metric alerting, segment analysis (country/platform/cohort), mutual exclusion groups"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Deterministic Bucketing and SDK Design</h3>
        <HighlightBlock as="p" tier="important">The feature flag SDK is a small JavaScript module (ideally &lt;5KB) that loads synchronously in the page &lt;head&gt; — before any feature-gated code runs. It fetches the experiment configuration on initialization: GET /api/experiments/active returns an array of active experiment configs &#123;id, variants, allocation, targetFilter&#125;. This response is cached in localStorage with a 10-minute TTL. On each call to getVariant(experimentId), the SDK: (1) checks if the user passes the targetFilter (if not, returns 'control' without bucketing); (2) computes hash(userId + experimentId) using FNV-1a (fast, low collision rate, deterministic across environments); (3) maps the hash value to a variant based on the allocation ranges; (4) logs the assignment event to the analytics pipeline.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The logging is async and non-blocking — it fires a beacon (navigator.sendBeacon) so it does not delay page rendering or block on network failure. The assignment event schema: &#123;experimentId, variantId, userId, sessionId, timestamp, userAgent, country&#125;. The sessionId allows detecting SRM caused by bots (sessions with thousands of assignments from the same IP). The assignment log is the source of truth for "who was in what variant" — the pipeline joins this log with the metric events to compute results.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Statistical Significance in the UI</h3>
        <HighlightBlock as="p" tier="important">The results dashboard shows the frequentist two-sample z-test for proportions (for conversion metrics) and Welch's t-test (for continuous metrics like revenue or load time). The UI displays: the point estimate of the lift, the 95% confidence interval (CI) as a horizontal bar with a center dot and error bars, and the p-value. The CI visualization is more informative than a single p-value: a wide CI spanning zero means "not enough data yet"; a narrow CI entirely above zero means "confident positive effect"; a narrow CI spanning zero means "confident null effect (the true effect, if any, is too small to matter)." These are meaningfully different situations that the same p &gt; 0.05 label would obscure.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Sequential testing: the platform uses a corrected significance threshold when results are checked multiple times (α = 0.05 / number of peeks, or an always-valid p-value via the mSPRT method). A "peeking penalty" indicator shows how much the significance threshold has been adjusted from the planned α based on how many times the experimenter has viewed the results. This discourages premature conclusion while still allowing teams to monitor their experiments.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Experiment Lifecycle State Machine</h3>
        <HighlightBlock as="p" tier="crucial">Experiments move through states: Draft (being configured, not active) → Running (users being bucketed and metrics being collected) → Paused (bucketing stopped, existing assignments preserved) → Concluded (decided: shipped, rolled back, or abandoned). Transitions: Draft → Running requires owner sign-off on the configuration and at least one secondary reviewer (prevents launching misconfigured experiments). Running → Paused can be triggered manually or automatically by a guardrail alert. Paused → Running resumes bucketing. Running → Concluded requires recording the decision (ship/rollback/abandon) and the rationale. Concluded experiments are archived but their data is retained for at least 1 year (for audit and learning from past experiments).</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Experiment Creation: Sample Size Calculator</h3>
        <HighlightBlock as="p" tier="crucial">The creation form includes an inline sample size calculator. Inputs: baseline conversion rate (auto-populated from the last 7 days of the primary metric for the target segment), minimum detectable effect (MDE — the smallest lift worth detecting, e.g., 5% relative improvement), statistical power (default 80% — probability of detecting a true effect of size MDE), and significance level α (default 5%). Output: required sample size per variant and estimated days to reach that sample size (based on current daily traffic in the target segment). If the estimated duration exceeds 4 weeks, a warning is shown: experiments running longer than 4 weeks risk novelty effects, seasonality, and user behavior drift invalidating the results. The recommendation: increase the MDE (accept detecting only larger effects) or increase traffic allocation to reach the sample size faster.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">Frequentist vs. Bayesian: frequentist testing (p-values, confidence intervals) is the industry standard for A/B testing because it gives definitive "reject/don't reject the null" answers that executives understand. Bayesian testing (probability of being best, expected loss) is more intuitive for sequential monitoring (the posterior updates continuously, no multiple testing problem) but requires choosing priors and interpreting probability-of-superiority metrics that are less familiar. Most large-scale platforms (Optimizely, Statsig, Eppo) default to frequentist with sequential corrections for peeking — this is the pragmatic choice for a team without a dedicated statistician.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Client-side vs. server-side bucketing: client-side bucketing (in the JS SDK) is fast (no network round trip) but can be bypassed by users disabling JavaScript, bots, or server-side rendering that doesn't run the SDK. Server-side bucketing (the API returns the variant with every page request) is more reliable but adds latency. The hybrid approach: use server-side bucketing for critical experiments (pricing, checkout) where client-side bypass would be a problem; use client-side bucketing for low-stakes UI experiments where the latency is not acceptable.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">An A/B testing platform UI requires: (1) deterministic bucketing (hash(userId+experimentId)%100, FNV-1a, cached config 10min TTL, async sendBeacon assignment log); (2) experiment creation with MDE-based sample size calculator and estimated run duration; (3) results dashboard (per-variant lift + 95% CI bar visualization + p-value color-coded, polls every 60s); (4) SRM detection (chi-squared test on observed vs. expected allocation, p &lt; 0.01 red banner); (5) guardrail metric alerting (threshold degradation → banner + email, opt-in auto-pause); (6) segment analysis (country/platform/cohort breakdowns as secondary tab, heterogeneous effect auto-highlight); (7) mutual exclusion groups (top-level hash partitions disjoint user pools for interfering experiments); and (8) experiment lifecycle state machine (Draft→Running with sign-off, Running→Paused on guardrail, Running→Concluded with decision + rationale). The core principle: the platform must make statistical validity the default, not an advanced option — SRM detection, sequential testing corrections, and guardrail alerting should be on by default so teams cannot accidentally ship decisions based on invalid experiments.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
