"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-learning-platform-course-progress",
  title: "Design a Learning Platform (Course + Progress Tracking)",
  description:
    "Architecture for an online learning platform: course content delivery with video streaming (adaptive bitrate HLS), progress tracking with per-lesson completion events and resume playback, interactive exercises with automated grading, certificate issuance on course completion, learning path recommendations, cohort-based discussion forums, offline download with DRM-protected content, instructor dashboard with student engagement analytics, and spaced repetition review system for retention.",
  category: "high-level-design",
  subcategory: "knowledge-content-systems",
  slug: "learning-platform-course-progress",
  wordCount: 5000,
  readingTime: 30,
  lastUpdated: "2026-05-14",
  tags: ["hld", "learning-platform", "video-streaming", "progress-tracking", "hls", "drm", "certificate", "spaced-repetition"],
  relatedTopics: ["medium-like-article-platform", "qa-system-stackoverflow"],
};

export default function LearningPlatformCourseProgressArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">An online learning platform like Coursera or Udemy has two distinct user roles with opposing priorities: learners (who want frictionless content access, progress persistence, and motivation mechanisms) and instructors (who want student engagement analytics, content management tools, and revenue visibility). The platform's value proposition is structured learning — not just video hosting, but curriculum sequencing, progress tracking, and achievement signals (certificates) that are recognized by employers.</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">The hardest technical problems: (1) video delivery at scale — course videos are the largest bandwidth consumption; adaptive bitrate HLS streaming ensures learners on slow connections still complete lessons; (2) progress tracking reliability — a learner who watches 45 minutes of a video and loses connectivity must resume exactly where they left off; (3) DRM for content protection — instructors' paid courses must be protected from screen recording and unauthorized redistribution; and (4) offline access — mobile learners frequently study on planes and subways, requiring reliable offline download with DRM-protected playback.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Video streaming with HLS, progress tracking and resume, interactive exercises with grading, certificate issuance, learning path recommendation, cohort discussion forums, offline download, and instructor analytics. Not in scope: live streaming / webinars, payment processing, or enterprise SSO integrations.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Video streaming with adaptive bitrate (HLS):</strong> Course videos are uploaded by instructors via a resumable multipart upload (S3 multipart upload with presigned URLs, resuming from the last uploaded part on network failure). After upload, a transcoding pipeline (AWS Elemental MediaConvert or FFmpeg workers) generates HLS manifests with multiple quality renditions: 360p (500 Kbps), 540p (1.5 Mbps), 720p (3 Mbps), 1080p (5 Mbps). The HLS manifest (master.m3u8) and segment files (.ts) are stored in S3 and served via CloudFront. The video player (HLS.js or native HLS on iOS/Safari) automatically selects the quality tier based on the learner's measured bandwidth. Subtitles and transcripts are generated automatically (Whisper API) and stored as VTT files alongside the HLS segments.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Progress tracking and resume playback:</strong> Every 10 seconds during video playback, the player sends a heartbeat: POST /api/progress &#123;lessonId, position: 142.5, duration: 3600&#125;. The position is written to a progress record (userId, lessonId, lastPosition, completedAt). On lesson load, the player fetches GET /api/progress?lessonId=&#123;id&#125; and seeks to lastPosition. A lesson is marked "completed" when the learner has watched &gt;90% of the video (position &gt; duration × 0.9) — this threshold prevents marking lessons complete due to accidental seeks to the end. Progress events are written to both the database (for persistence) and a Redis sorted set (for the instructor's real-time engagement dashboard, where the score is the timestamp).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Interactive exercises with automated grading:</strong> Courses include quizzes (multiple choice, true/false), coding exercises (browser-based code execution via Pyodide for Python or a sandboxed Judge0 API for compiled languages), and peer-reviewed assignments. Multiple-choice grading is instant (client-side for immediate feedback, then confirmed server-side). Coding exercises are submitted to the judge service: the learner's code + test cases run in an isolated sandbox (2-second CPU timeout, 64MB memory limit, no network access). The judge returns: pass/fail per test case, execution time, memory usage. Peer reviews (for open-ended assignments) use a rubric-based evaluation form — each submission is reviewed by 3 peers, and the final grade is the median of the 3 peer scores.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Certificate issuance on course completion:</strong> A course is "completed" when all required lessons are marked complete and all graded assignments pass the minimum score threshold (configured per course, e.g., 70%). On completion, the certificate pipeline: (1) generates a unique certificate ID (UUID); (2) renders a PDF certificate (Puppeteer rendering an HTML template with the learner's name, course title, completion date, and a QR code linking to the verification URL); (3) stores the PDF in S3 and the certificate record in PostgreSQL; (4) sends a completion email with the PDF attached; (5) makes the certificate publicly verifiable at /certificates/&#123;certificateId&#125; (no login required — employers can verify). Certificates are tamper-evident: the verification URL resolves to the authoritative record in the database, not just the PDF.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>DRM and content protection:</strong> Paid course videos are protected with DRM (Widevine for Chrome/Android, FairPlay for iOS/Safari, PlayReady for Edge/Windows). The HLS manifests for DRM-protected content include a license server URL. When the player encounters a DRM-protected segment, it requests a license from the license server (POST /api/drm/license), which validates the learner's entitlement (has the learner enrolled in this course?) and returns a decryption key. The key is ephemeral (1-hour TTL) — the player must re-request a license after expiry. This prevents indefinite offline playback: a learner's DRM license expires after 48 hours of offline access, requiring reconnection to the license server to extend.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Offline download for mobile:</strong> Enrolled learners can download lessons for offline viewing. The download manager (in the mobile app) downloads the HLS video segments to local storage (HLS progressive download — download segments in order, play segments as they complete). A downloaded lesson is stored as: &#123;lessonId, localPath, downloadedAt, expiresAt: 48hrs&#125;. The app enforces the 48-hour DRM expiry by checking the expiresAt timestamp before starting offline playback. Downloaded content quota: 10 lessons per device to prevent full course extraction. Downloaded segments are encrypted at rest using the device's secure enclave key.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Spaced repetition review system:</strong> After completing a lesson, learners are shown a set of flashcard-style review questions (derived from the lesson's quiz questions). The review system uses the SM-2 spaced repetition algorithm: each card has a review interval (initially 1 day) and an ease factor (initially 2.5). After each review, the interval is updated based on the learner's rating (1=fail, 2=hard, 3=good, 4=easy): fail resets to 1 day; good multiplies the interval by the ease factor. The next review date is stored per card per user. A daily notification prompts learners to review their due cards. The spaced repetition system is a retention mechanism — it increases certificate completion rates by reinforcing material after lessons are finished.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Instructor analytics dashboard:</strong> Instructors see per-lesson engagement metrics: average completion rate (% of enrolled learners who completed the lesson), average watch time (minutes watched / lesson duration), drop-off chart (% of learners who dropped off at each 10% of the video), and quiz pass rates. At the course level: total enrollments, completion rate, average rating, and revenue (if paid). The drop-off chart reveals specific segments where learners disengage — instructors use this to identify confusing explanations or pacing issues. Analytics are computed from the progress heartbeat events (aggregated nightly by a batch job for historical data, and from Redis for last-24-hour near-real-time data).</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The platform has three primary backends: the content service (course metadata, lesson content, curriculum structure), the progress service (progress heartbeats, completion tracking, certificate issuance), and the media service (video upload, transcoding pipeline, HLS delivery, DRM license serving). These communicate via a shared PostgreSQL database and an event bus (Kafka) for cross-service events (e.g., "lesson completed" → triggers spaced repetition card creation and checks course completion).</HighlightBlock>
        <HighlightBlock as="p" tier="important">Video delivery is entirely CDN-based: the media service writes HLS segments to S3, CloudFront serves them globally, and the platform never proxies video bytes through origin servers. The DRM license server is the only video-related component that requires origin processing (to validate entitlement). The web frontend is Next.js with SSR for course pages (personalized — shows learner's progress) and ISR for the course catalog (revalidated when course metadata changes).</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/knowledge-content-systems/learning-platform-course-progress.svg"
          alt="Learning platform architecture: instructor video upload via S3 multipart presigned URL → FFmpeg transcoding → HLS manifests (360p/720p/1080p) served via CloudFront CDN; DRM license server validates enrollment and returns ephemeral 1-hour key; learner progress heartbeat every 10s → PostgreSQL + Redis; course completion check via Kafka event → certificate pipeline (Puppeteer PDF + QR code + email); spaced repetition SM-2 algorithm with daily review notifications; instructor analytics from aggregated progress events (nightly batch + Redis near-real-time); cohort discussion forum with thread moderation."
          caption="HLS adaptive bitrate (360p–1080p, Whisper transcript), DRM license (Widevine/FairPlay, 1hr TTL, 48hr offline), progress heartbeat (10s, PostgreSQL + Redis), course completion → Puppeteer certificate (QR + email), spaced repetition SM-2, instructor drop-off chart (10% buckets)"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Video Transcoding Pipeline</h3>
        <HighlightBlock as="p" tier="crucial">Instructor uploads a video via a multipart presigned URL flow: (1) POST /api/upload/init returns &#123;uploadId, presignedUrls: [url1, url2, ...]&#125; — one presigned URL per 50MB chunk; (2) the client uploads chunks in parallel (navigator.serviceWorker or a background fetch, resumable on failure); (3) after all chunks are uploaded, POST /api/upload/complete &#123;uploadId, etags&#125; triggers S3 CompleteMultipartUpload. A Kafka event triggers the transcoding worker: it launches an FFmpeg job (or MediaConvert job) to transcode the source video into 4 HLS rendition streams + generate the master manifest + extract keyframes for the thumbnail strip. The transcoding job emits progress events (0%, 25%, 50%, 75%, 100%) that the instructor's upload UI polls (SSE stream at /api/upload/&#123;id&#125;/progress). On completion, the lesson record is updated with the HLS manifest URL and the lesson becomes available to enrolled learners.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Progress Heartbeat and Reliability</h3>
        <HighlightBlock as="p" tier="crucial">The 10-second heartbeat is the most frequent write in the system. At 100K concurrent learners, this is 10K writes/second — not trivial. The progress service handles this load via: (1) write batching — the API server buffers heartbeats in memory (or Redis) for 5 seconds and bulk-inserts the batch to PostgreSQL (one INSERT per 5-second batch per user, not per heartbeat); (2) UPSERT semantics — INSERT INTO progress (userId, lessonId, lastPosition, updatedAt) VALUES (...) ON CONFLICT (userId, lessonId) DO UPDATE SET lastPosition = EXCLUDED.lastPosition, updatedAt = EXCLUDED.updatedAt — atomic update, no read-before-write; (3) async write to the instructor's real-time Redis dashboard — a Kafka consumer aggregates heartbeat events and updates Redis counters asynchronously, so the write path is not blocked by the analytics write.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Offline heartbeat buffering: on mobile, when the learner goes offline mid-lesson, the app buffers heartbeats in IndexedDB. On reconnection, the buffered heartbeats are flushed in order. The server accepts out-of-order heartbeats (taking the maximum position seen for a lesson, not the last-received) — this handles cases where heartbeats arrive out of order after network recovery.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Cohort Discussion Forums</h3>
        <HighlightBlock as="p" tier="important">Each course has a cohort forum — a threaded discussion board where learners can post questions and instructors (or TAs) can respond. The forum is structured per-lesson (a discussion thread attached to each lesson) and per-course (a general forum). Forum posts use the same Markdown editor as the article platform. Timestamps on discussion posts are shown as relative to the lesson video position ("Posted at 12:34 in the video") — learners watching at 12:34 see a notification that there's a discussion at this point in the video. The forum is moderated by the instructor and designated TAs. Instructors can pin posts (FAQ answers) and mark posts as "instructor answered" (similar to the Q&A platform's "accepted answer" mechanism).</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Learning Path Recommendation</h3>
        <HighlightBlock as="p" tier="important">After completing a course, the platform recommends the next course in a curated learning path (e.g., "You completed Python Basics — next: Python for Data Science"). Learning paths are curated by the platform team (not ML-generated) for structured sequences (beginner → intermediate → advanced). Supplementary recommendations (courses outside the path) are ML-generated: a collaborative filtering model (matrix factorization on the enrollment matrix — users who enrolled in course A also enrolled in course B) produces course recommendations ranked by predicted rating. The recommendation model runs nightly, and the output (top-10 recommended course IDs per user) is stored in Redis. The "recommended for you" section on the home page reads from Redis with a CDN-cacheable API response (the same recommendations for the same user for up to 30 minutes).</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">HLS vs. DASH: HLS (HTTP Live Streaming) has native support in iOS/Safari and is the industry standard for learning platforms targeting mobile learners. DASH (Dynamic Adaptive Streaming over HTTP) offers better codec flexibility (VP9, AV1) for bandwidth savings, but lacks native iOS support, requiring the Shaka player library. For a learning platform where iOS learners are a significant segment, HLS is the safer default. A hybrid approach — HLS primary, DASH for platforms with native support — can reduce CDN egress costs for learners on modern Android/Chrome but adds transcoding complexity.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Certificate fraud: PDF certificates can be forged (edited in a PDF editor). The QR code + public verification URL is the authoritative verification mechanism — employers are instructed to verify via the URL, not the PDF. The platform's brand value depends on the certificate being unforgeable at the verification layer, even if the PDF itself can be visually replicated. Some platforms (Credly, Accredible) use cryptographically signed Open Badges (JSON-LD) as the portable credential format — this is the emerging standard for verified digital credentials in the industry.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A learning platform requires: (1) video upload (S3 multipart presigned URL, resumable) → FFmpeg transcoding → HLS manifests (360p/720p/1080p, Whisper VTT transcript) served via CloudFront; (2) DRM (Widevine/FairPlay/PlayReady, 1-hour ephemeral license key, 48-hour offline TTL); (3) progress heartbeat (10s interval, UPSERT, 10K writes/sec via batching + Redis buffer, offline IndexedDB buffering with max-position reconciliation); (4) course completion check via Kafka event → Puppeteer PDF certificate (QR code + public verification URL, tamper-evident via database record); (5) interactive exercises (instant multiple-choice, Judge0 sandboxed code execution 2s/64MB, peer review rubric median); (6) spaced repetition SM-2 (per-card interval + ease factor, daily review notification, improves retention); (7) instructor analytics (completion rate, average watch time, 10% drop-off chart, quiz pass rate — nightly batch + Redis near-real-time); (8) cohort forum (threaded Markdown discussion, video-position timestamps, TA moderation, instructor-answered pin); and (9) learning path recommendation (curated paths + collaborative filtering nightly, Redis top-10 per user, 30-min CDN cache). Core principle: progress persistence is a trust contract with the learner — if resume playback fails or completion is not recorded, the learner loses faith in the platform and churns.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
