"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-ai-generated-content-moderation-ui",
  title: "Design an AI-Generated Content Moderation UI",
  description:
    "Architecture for a content moderation system: fast classifier + LLM scorer pipeline, policy-based routing, human review queue with SLA, appeal system, feedback-driven classifier retraining, and drift detection.",
  category: "high-level-design",
  subcategory: "ai-modern-systems",
  slug: "ai-generated-content-moderation-ui",
  wordCount: 5100,
  readingTime: 31,
  lastUpdated: "2026-05-10",
  tags: ["hld", "content-moderation", "llm", "classifier", "trust-safety", "review-queue", "appeals"],
  relatedTopics: ["ai-model-comparison-testing-interface", "ai-prompt-management-ui"],
};

export default function AiGeneratedContentModerationUiArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="crucial">Content moderation is a high-stakes, high-throughput problem: a social platform may publish millions of pieces of content per day, each of which could potentially contain harmful material. No team of human moderators can review this volume at the required speed. AI classifiers handle the volume but are imperfect—false positives (incorrectly flagging benign content) harm users and create a hostile experience; false negatives (missing actual violations) allow harmful content to remain visible. The moderation UI is the operational interface between the AI system and human moderators: it presents the AI's decisions for human review, accepts human corrections that improve the model over time, and provides policy operators with the controls to adjust thresholds and policies without requiring code changes.</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">The architecture must solve three distinct problems. First, the detection pipeline: getting content from submission to a routing decision (auto-block, queue for review, or auto-pass) in real time (under 200ms for text, under 2 seconds for images) using a two-stage approach (fast binary classifier + slower LLM scorer for borderline cases). Second, the human review workflow: presenting cases to moderators efficiently, with AI score context and action buttons, tracking SLA compliance, and capturing decisions as training signals. Third, the appeal system and feedback loop: allowing users to contest decisions, routing appeals for human review, and feeding human corrections back into the classifier training pipeline.</HighlightBlock>
        <p><strong>Explicit assumptions:</strong> The system moderates text content (user-generated posts and comments). The fast classifier is a fine-tuned BERT-based model (inference time under 50ms). The LLM scorer is a larger model that provides category-level confidence scores and a short justification (inference time 200–500ms). Human reviewers are trust-and-safety team members working in a web-based tool. The review queue has an SLA of 10 minutes (cases older than 10 minutes are escalated). Classifier retraining happens in batches (triggered at 500 new labeled samples). Shadow deployment validates a new classifier version against the current one before promotion.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibuild">Functional Requirements</h3>
        <ul className="space-y-2">
          <li><strong>Real-time detection:</strong> Every submitted piece of content passes through the detection pipeline before being published. The pipeline applies the fast classifier and, for borderline scores, the LLM scorer, and routes to auto-block, review queue, or auto-pass based on configured thresholds.</li>
          <li><strong>Review queue:</strong> The moderation UI shows a prioritized queue of flagged content. Cases are categorized by AI confidence (high, medium) and content category (hate speech, harassment, spam, adult content, PII). Queue filters allow moderators to focus on their specialty or the oldest cases approaching SLA.</li>
          <li><strong>Case review panel:</strong> Each case shows the content (with highlighted offending spans if available), the AI score breakdown by category, the AI's justification, and action buttons (Remove, Edit, Approve, Escalate, Add to Training Set).</li>
          <li><strong>SLA tracking:</strong> The queue shows the age of the oldest unreviewed case with a color-coded SLA indicator (green = within SLA, orange = approaching, red = overdue). A dashboard shows SLA compliance rate for the current shift.</li>
          <li><strong>Appeal system:</strong> Users whose content was removed can submit an appeal with a selected reason and optional freetext. Appeals are triaged: borderline cases are re-scored by the LLM scorer; clear cases are auto-resolved; complex cases are routed to senior reviewers. The user is notified of the decision with a reason.</li>
          <li><strong>Training feedback loop:</strong> Human review decisions (approved/removed + reason) are logged as labeled training samples. When the batch size reaches the threshold, a new classifier version is trained and shadow-deployed. If the shadow evaluation shows no regression, the new version is promoted to production.</li>
          <li><strong>Policy controls:</strong> Policy operators can adjust threshold configurations (auto-block cutoff, review range) per content category without a code deployment. Allowlists and blocklists bypass the classifier for known-safe or known-harmful patterns. An emergency kill switch forces all content into the review queue immediately.</li>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <li><strong>Detection latency:</strong> Fast classifier decision in under 50ms. LLM scorer decision in under 500ms for borderline cases. Total pipeline latency (before content is visible to other users) under 600ms for text.</li>
          <li><strong>Throughput:</strong> The detection pipeline must handle peak load without queuing: at 10K content submissions per minute, the classifier must process 10K items/min (approximately 167/second).</li>
          <li><strong>Review SLA:</strong> 95% of queued cases reviewed within 10 minutes.</li>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The detection pipeline runs synchronously in the content submission path. When a user submits content, the submission API calls the fast classifier before writing the content to the database. If the fast classifier returns a confidence below the auto-block threshold and above the auto-pass threshold (the "borderline" band), the LLM scorer is called to provide a category breakdown. The policy engine applies the thresholds to produce a routing decision. Auto-blocked content is not stored in the public content table. Review-queued content is stored as "pending" (visible only to the author, not other users) and written to the moderation queue. Auto-passed content is written directly to the public content table.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/ai-modern-systems/ai-generated-content-moderation-ui-architecture.svg"
          alt="Content moderation UI architecture showing detection pipeline (content input → fast classifier under 50ms binary pass/flag → LLM scorer category + confidence → policy engine rule-based thresholds → routing auto-block/queue/pass → review queue), moderation UI panels: review queue with case counts by confidence level (high 2 auto-blocked red, review 14 orange, passed 1204 green), queue filters by category and SLA tracking showing oldest unreviewed and SLA target; case review panel showing flagged content with highlighted text, AI score breakdown by category with harassment 0.87 high, action buttons remove/edit/approve plus escalate/add to training; policy config and metrics panel with threshold configuration and detection categories and moderation metrics precision 91% recall 84%."
          caption="Detection pipeline (fast classifier <50ms → LLM scorer → policy engine → route) + review queue with SLA tracking + case review panel with AI scores and action buttons"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Detection Pipeline Design</h3>
        <HighlightBlock as="p" tier="important">The fast classifier is a fine-tuned BERT-based binary classifier (harmful vs. not harmful) that runs in under 50ms on a GPU instance. It outputs a single probability score between 0 and 1. This classifier handles the volume: at 167 submissions per second with 50ms inference, a single GPU can process approximately 20 requests in parallel. The auto-block and auto-pass thresholds define three zones: auto-block (score above 0.90), borderline/review (score between 0.50 and 0.90), and auto-pass (score below 0.50). Approximately 15–20% of submissions fall in the borderline zone and proceed to the LLM scorer; the rest are routed immediately from the fast classifier decision alone.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The LLM scorer receives the borderline content and returns: a confidence score per category (hate speech, harassment, spam, adult, PII) each between 0 and 1, and a two-sentence justification explaining which specific phrases triggered the scores. The category scores replace the binary fast classifier score for borderline content, enabling category-specific threshold enforcement (the adult content threshold may be higher for an age-verified platform than the harassment threshold). The justification is shown to the human reviewer in the case review panel to accelerate decision-making.</HighlightBlock>
        <p>The policy engine translates scores into routing decisions using configurable thresholds. Per-category thresholds: a harassment score above 0.90 is auto-blocked even if hate speech score is 0.10. The maximum score across all categories determines the overall routing. Blocklist patterns (known slurs, spam domains) are checked first and bypass the classifier entirely—they are always auto-blocked regardless of the classifier output.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Review Queue and Case Prioritization</h3>
        <HighlightBlock as="p" tier="important">The review queue is ordered by priority, not by submission time. Priority is computed as a weighted combination of AI confidence (higher confidence cases are less uncertain and can be processed faster), content reach (content with more potential viewers is prioritized—a comment on a trending post is higher priority than a comment on a low-traffic post), and age (cases approaching the SLA deadline receive a priority boost). This ensures that high-reach, time-sensitive cases are reviewed before low-reach old cases.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Queue partitioning: moderators are assigned to specialized queues based on their training (hate speech reviewers, spam reviewers). This reduces cognitive load (a moderator doesn't switch between evaluating graphic content and spam in the same session) and improves consistency (specialized reviewers develop more calibrated judgment for their category). Queue sizes and SLA compliance are monitored in real time; if a queue falls behind its SLA, the system alerts the team lead to redistribute moderators.</HighlightBlock>
        <p>The case review panel shows: the content in its full context (for a comment, the original post it replies to is shown above). The AI's offending span highlights (specific sentences or phrases with confidence above 0.7 are underlined with a category label). The score breakdown by category with the LLM justification. Action buttons: Remove (content is deleted and the author is notified with the reason), Edit (for content that is fixable—the moderator sees a text editor with the offending phrase pre-selected), Approve (content is published, case is closed), Escalate (sends to a senior reviewer with the option to add context notes), and Add to Training Set (marks the case for the training pipeline, recording the moderator's decision as the ground truth label).</p>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Appeal System</h3>
        <p>Users whose content was removed see a removal notification with a reason category and a link to submit an appeal. The appeal form lets the user select a reason ("I believe this was removed in error," "My content was misclassified," "Context was missing") and add freetext context (limited to 500 characters). The appeal is then automatically triaged: the content is re-scored by the LLM scorer with an augmented prompt that includes the user's appeal context. If the re-score returns a confidence below 0.50 in all categories, the appeal is auto-resolved in the user's favor (the content is restored) and the moderator's original decision is logged as a false positive for training. If the re-score returns confidence above 0.80, the appeal is auto-resolved against the user (the removal is upheld) with a notification. Cases where the re-score returns a score between 0.50 and 0.80 are routed to a senior reviewer for manual resolution.</p>
        <HighlightBlock as="p" tier="important">Appeal SLA is 48 hours (longer than the initial review SLA because appeals are lower volume and less time-sensitive than pre-publish moderation). Users receive an email notification when their appeal is resolved, including the decision (upheld or overturned), the reason, and—for overturned decisions—an apology and a link to the restored content. Appeal decisions are logged separately from initial review decisions, allowing the system to compute the appeal overturn rate as a quality metric for the classifier and for initial reviewer calibration.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Feedback Loop and Classifier Retraining</h3>
        <HighlightBlock as="p" tier="important">Every human decision (approve or remove, with reason category) is written to the training sample store with the content, the AI's score, and the human label. When the training sample store accumulates 500 new labeled samples since the last training run, a retraining job is triggered. The retraining job: fine-tunes the fast classifier on the accumulated samples (mixed with the existing training set to prevent catastrophic forgetting), evaluates the new classifier version on a held-out evaluation set (precision, recall, false positive rate per category), and deploys it to a shadow environment.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Shadow deployment: the new classifier version runs in parallel with the current production version on 10% of incoming content (randomly sampled). Its decisions are logged but not acted upon. After 24 hours (or after the sample reaches a configured minimum), the shadow metrics are compared to the production metrics on the same content. If precision and recall have not regressed (no decrease of more than 2%), and the false positive rate has not increased (no increase of more than 1%), the new version is promoted. If regression is detected, the retraining job is logged as failed, an alert is sent to the ML team, and the new version is discarded. This closed-loop system means the classifier continuously improves as moderators make decisions.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Drift Detection and Policy Controls</h3>
        <p>Model drift is detected by monitoring the following signals over rolling 7-day windows: false positive rate (computed from appeal overturn rate—if appeals overturn more than 15% of removed content, the classifier is miscalibrated), category distribution shift (if the fraction of hate speech flags doubles week-over-week, either new content patterns are emerging or the model is drifting), and moderator agreement rate (if moderators approve more than 30% of AI-flagged cases in a category, the threshold for that category may be too low). Each drift signal triggers an alert to the ML team and a policy review recommendation.</p>
        <HighlightBlock as="p" tier="important">Policy controls allow threshold adjustments without code deployment: the thresholds are stored in a configuration service, loaded at startup, and cached with a 60-second TTL. Updating a threshold in the UI takes effect within 60 seconds across all detection pipeline instances. The emergency kill switch—forcing all content into the review queue—is a single threshold change (set all auto-pass thresholds to 0) that takes effect within 60 seconds. Time-boxed stricter policies can be configured with start and end times, automatically reverting when the period ends. This allows policy operators to respond to coordinated campaigns or breaking events without involving engineers.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/ai-modern-systems/ai-generated-content-moderation-ui-feedback-loop.svg"
          alt="Moderation feedback loop sequence diagram with 4 lifelines (Moderator UI, Decision Logger, Training Pipeline, Classifier v-n-plus-1). Steps: moderator removes/approves with reason → logger records labeled sample → training pipeline accumulates to 500 sample batch trigger → retrain and evaluate → shadow deploy comparing new vs current → regression detected blocks with alert → no regression promotes to production. Appeal system flowchart: user submits appeal → auto triage re-scores with higher accuracy model → auto-resolve if score flips clear or senior review if borderline, then decision and notification. Drift detection signals (false positive rate, overturn rate above 15%, category distribution shift) and policy override panel (configurable thresholds, allowlist/blocklist, emergency kill switch, time-boxed policies). SLA and volume metrics table."
          caption="Feedback loop (human decisions → training samples → batch retrain → shadow deploy → promote) + appeal system + drift detection signals + policy override controls"
        />
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">Synchronous versus asynchronous detection: running detection synchronously in the content submission path (before the content is stored) prevents harmful content from ever becoming visible to other users—but adds latency to every submission. The fast classifier (50ms) is acceptable latency for a comment post. An LLM scorer call (200–500ms) on every submission would be prohibitive. The two-stage approach (fast classifier for routing, LLM scorer only for borderlines) maintains acceptable latency for 80–85% of submissions while providing high-quality decisions for the 15–20% that need them. The trade-off: a false negative from the fast classifier (harmful content scored below the borderline threshold) bypasses the LLM scorer and is auto-passed. This is acceptable if the fast classifier is calibrated with a conservative threshold—erring toward false positives (borderline) over false negatives (pass) for the fast classifier stage.</HighlightBlock>
        <p>Moderator wellbeing: reviewing harmful content at high volume is psychologically damaging. The UI design should mitigate this: blurring or desaturating graphic content until the moderator explicitly reveals it (reducing unintended exposure), imposing mandatory break periods tracked by the system, providing access to support resources from within the moderation UI, and limiting exposure to the most severe categories to specialized, supported roles. These are not optional features—they are compliance and retention requirements for any serious trust-and-safety operation.</p>
        <HighlightBlock as="p" tier="important">Training data quality versus quantity: human review decisions are not uniformly high quality. A fatigued or poorly calibrated moderator makes worse decisions than a fresh, well-trained one. Feeding all human decisions into the training pipeline without quality filtering trains the classifier on noisy labels. Mitigations: track per-moderator agreement rate (how often a moderator's decision matches the senior reviewer's decision on the same case); weight training samples by moderator reliability score; route ambiguous cases to senior reviewers and use only senior decisions for training. The training pipeline should also apply active learning (prioritize cases where the current classifier and the human disagree, as these are most informative) rather than uniform random sampling from the review queue.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="important">A content moderation system combines a two-stage detection pipeline (fast binary classifier under 50ms → LLM scorer for borderline cases, routing to auto-block/review-queue/auto-pass) with a human review queue (prioritized by confidence × reach × age, with SLA tracking and category-specialized moderator assignment), an appeal system (re-score with LLM using user-provided context, auto-resolve clear cases, route borderline to senior reviewers, 48-hour SLA), and a feedback loop (human decisions logged as labeled samples → 500-sample batch trigger → fine-tune classifier → shadow deploy → regression check → promote). Policy controls (configurable thresholds, allowlists, blocklists, emergency kill switch) operate via a configuration service with 60-second TTL, allowing changes without code deployment. Drift detection monitors appeal overturn rate (above 15% triggers alert), category distribution shifts, and moderator agreement rate. The defining design tension is precision versus recall: high recall (catching more violations) increases false positives and moderator workload; high precision (fewer false positives) increases false negatives and platform harm. Thresholds must be tuned per category based on the severity of false negatives versus the cost of false positives—and must be revisited as the content distribution evolves.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
