"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-api-playground",
  title: "Design an API Playground (like Postman)",
  description:
    "Architecture for an API playground like Postman or Insomnia: request builder with URL, method, headers, and body editors; environment variables with secret masking; response viewer with syntax-highlighted JSON/XML, status code display, timing breakdown, and raw response toggle; request history and collection organization; authentication presets (Bearer token, OAuth 2.0, API key, Basic auth); code snippet generation for multiple languages; team workspaces with shared collections; and browser-based request proxying to bypass CORS restrictions.",
  category: "high-level-design",
  subcategory: "developer-experience-systems",
  slug: "api-playground",
  wordCount: 5000,
  readingTime: 30,
  lastUpdated: "2026-05-12",
  tags: ["hld", "api-playground", "postman", "request-builder", "cors-proxy", "environment-variables", "oauth", "collections", "code-generation"],
  relatedTopics: ["cicd-dashboard", "developer-documentation-system"],
};

export default function ApiPlaygroundArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">An API playground is an interactive client for exploring, testing, and documenting HTTP APIs. Postman, Insomnia, and Hoppscotch are canonical examples. The primary user is a developer who needs to: send HTTP requests to an API endpoint, inspect the response (status, headers, body), authenticate with various schemes (API key, Bearer, OAuth 2.0), and save requests for later use or share them with teammates. The secondary use case — sharing collections as living documentation — makes the playground a collaboration tool as well as a testing tool.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The defining technical challenge: browsers enforce CORS (Cross-Origin Resource Sharing), which blocks JavaScript from making requests to most third-party APIs unless the target server includes permissive CORS headers. An API playground running in the browser cannot directly call most APIs without CORS preflight failures. Solutions: (1) a server-side proxy that makes the request on behalf of the browser (bypasses CORS, but introduces a hop and requires trusting the proxy with API keys); (2) a browser extension or desktop app that runs outside the browser security model; (3) a service worker that intercepts requests and routes them through a proxy. Postman's desktop app uses the Node.js runtime to bypass CORS entirely — the web app uses a proxy. This architecture must decide which approach to take and design the CORS proxy securely.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Request builder, response viewer, environment variables, authentication presets, request history, collection management, and CORS proxy. Not in scope: automated test suites (Postman collection runner), mock server generation, or API monitoring.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Request builder:</strong> The request builder has four panels: (1) URL bar with method selector (GET/POST/PUT/PATCH/DELETE/HEAD/OPTIONS) and a "Send" button; (2) Headers editor — a key-value table with autocomplete for common headers (Content-Type, Authorization, Accept) and toggle checkboxes to disable individual headers without deleting them; (3) Body editor — shown for POST/PUT/PATCH; supports raw (JSON, XML, text with syntax highlighting via CodeMirror), form-data (key-value pairs with file upload support), and x-www-form-urlencoded; (4) Params editor — URL query parameters as key-value pairs that update the URL bar in real-time. All panels persist their state across navigation using the request store (Zustand + localStorage).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Environment variables:</strong> Environments are named sets of key-value pairs (e.g., "Development": &#123;BASE_URL: "http://localhost:3000", API_KEY: "dev-key"&#125;). Variables are referenced in the URL, headers, and body using &#123;&#123;VARIABLE_NAME&#125;&#125; syntax (Mustache-style). On send, all &#123;&#123;...&#125;&#125; tokens are replaced with the active environment's values before the request is made. Secret variables (marked as "secret") are masked in the UI (shown as •••••) and excluded from export/share. Environment data is stored locally; secrets are never sent to the server even for sync (they are excluded from the server-side sync payload and must be set manually in each environment).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Response viewer:</strong> The response panel shows: status code (color-coded: green for 2xx, orange for 3xx, red for 4xx/5xx) with reason phrase, response time (end-to-end in ms), response size (bytes), and headers table. The body is syntax-highlighted using a language-aware renderer (JSON is pretty-printed with collapsible objects, XML is formatted, HTML is displayed as code — not rendered). A "Raw" toggle shows the unprocessed response bytes. Large responses (&gt;1MB) are truncated at 10,000 lines with a "View full response in new tab" option that opens the raw bytes in a data: URI.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Collection management:</strong> Requests are organized into collections (folders of related requests). A collection can be shared with teammates in a workspace — changes sync in real-time via WebSocket (WebSocket is appropriate here because collection edits are bidirectional: any team member can edit). Sharing a collection generates a public link that renders the collection as read-only documentation (request names, descriptions, example responses). Collections can be exported as Postman-compatible JSON for import into other tools.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>CORS proxy architecture:</strong> For browser-based requests to third-party APIs, the playground routes requests through a CORS proxy: the browser sends the API request to POST /proxy with &#123;url, method, headers, body&#125;. The proxy server makes the actual HTTP request and returns the response. Security concerns: (1) the proxy must not allow requests to internal/private IP ranges (SSRF protection — validate the target URL against a blocklist: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8, 169.254.0.0/16); (2) the proxy should not store request bodies or headers (API keys pass through); (3) rate-limit proxy requests per user to prevent abuse.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Code snippet generation:</strong> The "Code" tab generates equivalent code for the current request in: JavaScript (fetch), Python (requests), cURL, Go (net/http), and Java (HttpClient). Code generation is pure client-side (no server call): a function takes the request object &#123;url, method, headers, body&#125; and emits language-specific strings. Variables are replaced with their current values in the generated code. The generated code is shown in a syntax-highlighted read-only CodeMirror editor with a "Copy" button.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Authentication presets:</strong> Pre-built auth helpers: (1) Bearer token — adds "Authorization: Bearer &#123;&#123;TOKEN&#125;&#125;" header; (2) Basic auth — base64-encodes "username:password" into the Authorization header; (3) API key — adds the key as a header or query param with a configurable name; (4) OAuth 2.0 — opens a popup to complete the OAuth flow, captures the access token, and stores it as a secret environment variable. The OAuth flow uses the same PKCE flow described in the authentication system article. The UI guides the user through grant type selection (authorization code, client credentials) and fills in the token fields automatically.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="crucial">The API playground is primarily a local application — most of its state (current request, history, environment variables) is stored in IndexedDB via a Dexie wrapper, not on the server. The server is involved for: (1) the CORS proxy (request forwarding); (2) workspace sync (team shared collections via WebSocket); (3) user authentication and subscription management. The local-first architecture means the app works offline for viewing and editing requests, with sync happening when the network is available. This is the right tradeoff for a developer tool — developers working in restricted networks should still be able to use their saved requests.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The request execution flow: user clicks Send → validate URL + resolve environment variables → check if target URL is allowed by CORS directly (same-origin or API with permissive CORS headers) → if CORS would fail, route through the proxy → receive response → parse and display. The CORS check is performed optimistically: the request is first attempted without the proxy; if it fails with a CORS error (TypeError with opaque response), it is automatically retried through the proxy. This avoids unnecessary proxy hops for APIs that already support CORS.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/developer-experience-systems/api-playground.svg"
          alt="API playground system: request builder (URL + method selector; headers KV table with autocomplete; body editor: JSON/XML/form-data CodeMirror; params → URL update; Zustand+IDB persist), environment variables ({{VARIABLE}} Mustache substitution; secret vars masked+excluded from sync; active env switcher), CORS proxy (POST /proxy → SSRF blocklist validate private IPs; proxy makes HTTP req; rate-limit per user; auto-retry through proxy on CORS TypeError), response viewer (status badge color 2xx/3xx/4xx; timing ms; size bytes; JSON pretty-print collapsible; raw toggle; >1MB truncate + data URI), collection management (WebSocket bidirectional sync; public share link → read-only docs; export Postman JSON), code generation (client-side: req object → fetch/curl/python/Go strings; env vars resolved; CodeMirror display + copy), auth presets (Bearer header; Basic base64; API key header/query; OAuth2 PKCE popup → store token as secret env var)."
          caption="Local-first request store (IDB + Zustand), {{variable}} Mustache substitution with secret masking, CORS proxy with SSRF protection (private IP blocklist), optimistic direct-first then proxy-retry, response viewer (JSON collapsible, raw toggle, >1MB truncate), team collection sync via WebSocket, client-side code generation (fetch/curl/python/Go), OAuth 2.0 PKCE popup flow"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Request Execution and Variable Resolution</h3>
        <HighlightBlock as="p" tier="important">The request execution pipeline: (1) Resolve environment variables — scan the URL, headers, and body for &#123;&#123;VARNAME&#125;&#125; tokens and replace them with the active environment's values. Unresolved variables (no matching key in the environment) are highlighted in red and a warning is shown below the URL bar: "Unresolved variable: API_KEY". (2) Validate the URL — check for basic validity (starts with http:// or https://), non-empty host. (3) Construct the fetch options — &#123;method, headers: Object.fromEntries(enabledHeaders), body: serializedBody&#125;. (4) Add auth headers from the auth preset (if configured). (5) Attempt the fetch. (6) If TypeError (CORS failure), retry via proxy. (7) Parse and display the response.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Request timing: the playground measures three timing components separately: DNS lookup, TCP connect + TLS handshake, and server response time. Using the Resource Timing API (performance.getEntriesByName(url)) after a fetch gives accurate sub-millisecond timing broken down by phase. This breakdown is shown as a horizontal stacked bar in the response panel, similar to browser DevTools network tab. For proxied requests, the timing represents proxy-to-target time (the proxy server returns X-Response-Timing headers with the breakdown).</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">CORS Proxy Security Design</h3>
        <HighlightBlock as="p" tier="important">The CORS proxy is the highest-risk component — it makes arbitrary HTTP requests on behalf of authenticated users. SSRF mitigation: before forwarding any request, the proxy resolves the target hostname to IP addresses (DNS lookup on the server) and rejects any IP in private/reserved ranges: 10.0.0.0/8 (RFC 1918), 172.16.0.0/12 (RFC 1918), 192.168.0.0/16 (RFC 1918), 127.0.0.0/8 (loopback), 169.254.0.0/16 (link-local), ::1 (IPv6 loopback), fc00::/7 (IPv6 ULA). This prevents an attacker from using the proxy to probe internal services (AWS metadata endpoint at 169.254.169.254, internal dashboards).</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">Additional proxy protections: (1) maximum response size limit (10MB — prevents the proxy from downloading large files on behalf of users and buffering them in memory); (2) request timeout (30 seconds — prevents long-polling or streaming responses from holding proxy connections open); (3) no request body logging (API keys in headers/body must not appear in proxy logs); (4) rate limiting (100 requests/minute per authenticated user, 10/minute for unauthenticated — unauthenticated use for public APIs only).</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Team Workspace Sync</h3>
        <HighlightBlock as="p" tier="important">Team collections are synchronized via WebSocket. The sync model: each collection item (request, folder) is versioned with a logical clock (lamport timestamp). On edit, the client sends an operation to the WebSocket server: &#123;type: "update_request", requestId, data: &#123;...&#125;, lamportClock: localClock + 1&#125;. The server applies the operation, advances the server clock, and broadcasts to all workspace members: &#123;type: "request_updated", requestId, data, lamportClock: serverClock, actorId&#125;. Conflict resolution: last-write-wins by lamport clock (whichever operation has the higher clock wins). This is simple and acceptable for a tool where concurrent edits to the same request are rare — developers usually work on different requests in parallel.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Offline edit handling: edits made while offline are buffered in a local operation queue (IndexedDB). On reconnection, the queued operations are replayed in order to the WebSocket server. If conflicts are detected (another user edited the same request while offline), the UI shows a conflict resolution dialog with a side-by-side diff of the local and remote versions, allowing the user to choose which to keep or merge manually.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Request History and Search</h3>
        <HighlightBlock as="p" tier="important">Every sent request is saved to a local history (IndexedDB, capped at 1000 entries with FIFO eviction). Each history entry stores: timestamp, method, URL (with variables unresolved — so the history shows &#123;&#123;BASE_URL&#125;&#125;/users, not the resolved URL, preserving portability across environments), status code, response time, and response size. History is not synced to the server (too much private data — URLs and response bodies may contain sensitive information). History search is full-text indexed using Fuse.js (fuzzy search across URL, method, and response body excerpt). The search is instant (client-side, no server round trip).</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">Browser extension vs. server proxy for CORS: a browser extension can bypass CORS restrictions entirely (extensions run with elevated privileges) and makes requests directly without a proxy hop. The tradeoff: extensions require installation (friction), are browser-specific, and can be disabled. A server-side proxy works in any browser with no installation but introduces a hop (adds latency, requires trusting the proxy with API credentials). For a web-first product, the proxy approach is standard. The proxy should be clearly documented as a passthrough with no logging of sensitive request data.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Secrets in shared collections: API keys and tokens in environment variables create a sharing risk — a developer might accidentally include a secret in an exported collection or a shared public link. Mitigations: (1) mark variables as "secret" to exclude them from exports; (2) scan exported JSON for common patterns (Bearer tokens, API key patterns) and warn before export; (3) public share links render only the request structure, never the environment values. The security model: environment variables containing secrets should be treated like .env files — stored locally, never committed or shared.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">An API playground requires: (1) request builder (URL + method, headers KV table, body CodeMirror editor with format switching, params ↔ URL sync — all persisted in IDB via Zustand); (2) &#123;&#123;variable&#125;&#125; Mustache substitution with secret masking and exclusion from sync/export; (3) CORS proxy with SSRF protection (DNS resolution → private IP blocklist, 10MB response cap, 30s timeout, no logging, rate limiting); (4) response viewer (status color, Resource Timing breakdown, JSON collapsible pretty-print, raw toggle, &gt;1MB truncate + data URI); (5) team collection sync via WebSocket with Lamport clock LWW conflict resolution and offline operation queue; (6) client-side code generation (request object → fetch/curl/python/Go strings); and (7) auth presets (Bearer, Basic, API key, OAuth 2.0 PKCE popup → store token as secret env var). The central design tension: maximum developer utility (send requests to any API) vs. security (proxy must not enable SSRF attacks or leak API credentials).</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
