"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-cicd-dashboard",
  title: "Design a CI/CD Dashboard (like GitHub Actions)",
  description:
    "Architecture for a CI/CD dashboard like GitHub Actions: pipeline run list with real-time status streaming via SSE, live log tail with ANSI color rendering and virtual scroll, DAG visualization of job dependencies, artifact download links, flaky test detection with historical pass-rate charts, branch and PR-scoped pipeline views, re-run and cancel actions with optimistic UI, deployment approval gates with audit log, and notification routing for pipeline failures.",
  category: "high-level-design",
  subcategory: "developer-experience-systems",
  slug: "cicd-dashboard",
  wordCount: 5000,
  readingTime: 30,
  lastUpdated: "2026-05-12",
  tags: ["hld", "cicd", "github-actions", "pipeline", "sse", "dag", "live-logs", "deployment-gates", "flaky-tests"],
  relatedTopics: ["api-playground", "developer-documentation-system"],
};

export default function CicdDashboardArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A CI/CD dashboard is a real-time observability and control plane for automated software delivery pipelines. GitHub Actions, GitLab CI, CircleCI, and Jenkins all solve the same core problem: give developers instant, contextual feedback on whether their code change broke anything, and where in the pipeline it broke. The dashboard surfaces pipeline runs triggered by commits and pull requests, shows the status and logs of each job, and provides controls to re-run failed jobs or cancel in-progress runs.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The defining technical challenge: pipeline runs produce a continuous, potentially high-volume stream of log output across many parallel jobs. The dashboard must render live log output (streamed in real-time as jobs execute) without blocking the browser's rendering thread, handle thousands of lines of ANSI-colored text efficiently, and allow the user to navigate between jobs and pipeline runs without losing their scroll position. This requires a combination of server-sent events (SSE) for efficient one-way streaming, virtual scrolling for large log files, and careful state management to persist viewed positions across navigation.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Pipeline run list, real-time log streaming, job DAG visualization, artifact management, flaky test detection UI, and deployment approval gates. Not in scope: the CI/CD execution engine itself, build agent provisioning, or secret management infrastructure.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Pipeline run list:</strong> A repository's pipeline runs are listed in reverse chronological order with: commit SHA (first 7 chars with a link to the commit), branch/PR context (branch name or "PR #123" badge), trigger (push, pull_request, manual), status badge (queued/running/success/failure/cancelled — color-coded), duration, and triggered-by (actor avatar and name). The list auto-updates via SSE — when a new run starts or an existing run changes status, the list updates without a page reload. Runs are filterable by branch, status, and trigger type. Each row is a link to the run detail page.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Job DAG visualization:</strong> A pipeline run is composed of jobs with dependency relationships (job B depends on job A). The job dependency graph is rendered as a left-to-right DAG. Each job node shows: job name, status icon, duration. Edges between nodes represent needs relationships. Parallel jobs at the same topological level are shown side-by-side. Clicking a job node navigates to that job's log view. The DAG is rendered with SVG (no canvas — SVG allows accessibility and linking). Layout is computed using a simple topological sort + column assignment algorithm on the client.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Live log streaming:</strong> Each job produces log output streamed line-by-line via SSE (GET /api/runs/&#123;runId&#125;/jobs/&#123;jobId&#125;/logs as an EventSource). Log lines contain: timestamp, step name, text content, ANSI escape codes for color. The ANSI codes are converted to styled spans client-side using a lightweight parser (ansi-to-html). Logs are rendered in a virtual scroll list — only the visible lines are in the DOM. On job completion, the SSE connection closes and the full log is available as a static download.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Re-run and cancel actions:</strong> A "Re-run all jobs" button and "Re-run failed jobs only" button on the run detail page. Clicking either opens a confirmation modal with the re-run scope and estimated queue time. On confirm: POST /api/runs/&#123;runId&#125;/rerun &#123;scope: "failed" | "all"&#125;. The UI optimistically shows the new run as "Queued" in the run list and navigates to the new run's detail page. "Cancel" on an in-progress run: DELETE /api/runs/&#123;runId&#125; — the UI optimistically shows the run as "Cancelling" and waits for the SSE status update to transition to "Cancelled".</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Log rendering performance:</strong> A single job may produce 100,000+ log lines (build logs, test output). Rendering all lines in the DOM would freeze the browser. Virtual scrolling (using TanStack Virtual or a custom implementation) renders only the ~40 visible lines at any time. The virtual scroll maintains a fixed-height container with total height = lineCount × lineHeight, and translates the visible window. Append-only log updates: new lines are appended to an array; the virtual list re-renders the visible window on each append. Auto-scroll to bottom is enabled by default; if the user scrolls up, auto-scroll is paused (user is reviewing older output).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Flaky test detection:</strong> A test is considered flaky if it fails in some runs and passes in others on the same commit SHA or branch. The dashboard shows a "Flaky tests" tab on the run detail page listing tests that have a &lt;95% pass rate over the last 30 runs. Each flaky test shows: test name, pass rate histogram (sparkline), last failure timestamp, and a "Mark as known flaky" action (which excludes it from blocking the pipeline). The pass rate data is pre-computed server-side on a daily cron — the UI fetches GET /api/repos/&#123;repoId&#125;/flaky-tests and renders the pre-computed data.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Deployment approval gates:</strong> A pipeline stage marked as "requires approval" (deploy to production) is blocked until an authorized approver (a user in the "deployers" group) clicks "Approve" or "Reject." The approval UI shows: the diff since the last deployment (commit range), the approver group, and a comment field. POST /api/runs/&#123;runId&#125;/approve &#123;decision: "approve" | "reject", comment&#125;. The approval action is audit-logged (approver, timestamp, comment, diff summary). The pipeline SSE stream updates the gate status from "waiting" to "approved/rejected" in real-time for all viewers of the run.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The CI/CD dashboard is an event-driven read interface backed by an append-only event store. Pipeline runs are state machines (queued → running → success/failure/cancelled). Each state transition is an event. The API serves current state (synthesized from events) for initial page load, and then the frontend subscribes to the SSE stream for incremental updates. This event-sourcing pattern ensures the UI never misses a state transition — it catches up from the last known event on reconnect, not from a fresh full-load.</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">Log streaming is the highest-throughput path: a busy build can produce 10MB/min of log output. SSE is preferred over WebSockets for log streaming because logs are strictly one-way (server to client) and SSE's built-in reconnection and Last-Event-ID resumption make it simpler than WebSocket for this use case. For very large logs (jobs with 1M+ lines), the client switches to polling-based pagination (GET /api/logs?after=lineId) rather than SSE, to avoid buffering the entire log stream in memory.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/developer-experience-systems/cicd-dashboard.svg"
          alt="CI/CD dashboard system: pipeline run list (GET /api/runs → reverse chronological; SSE EventSource /api/runs/events → status updates; filter by branch/status/trigger; commit SHA + actor avatar + duration + status badge), job DAG (topological sort + column assignment client-side; SVG nodes per job; status icon overlay; click node → navigate log view; edges = needs relationships), live log streaming (SSE EventSource /api/runs/{runId}/jobs/{jobId}/logs; ANSI→styled spans; TanStack Virtual fixed-height container; auto-scroll to bottom; user scrolls up → pause auto-scroll; job complete → close SSE → static download link), re-run and cancel (POST /api/runs/{runId}/rerun {scope}; optimistic 'Queued' in list; navigate to new run; DELETE /api/runs/{runId} → 'Cancelling' optimistic → SSE 'cancelled'), deployment gate (stage waiting → show diff + approver group + comment; POST /api/runs/{runId}/approve; SSE gate_update → all viewers see approved/rejected; audit log: approver+timestamp+comment), flaky tests (GET /api/repos/{repoId}/flaky-tests; pass rate histogram sparkline; <95% over 30 runs; 'Mark known flaky' POST)."
          caption="Pipeline run list (SSE real-time updates, filter by branch/status), job DAG (SVG topological layout, click to job logs), live log SSE stream (ANSI→spans, TanStack Virtual 100K+ lines, auto-scroll pause on user scroll-up), re-run/cancel optimistic UI, deployment approval gate (diff + audit log, SSE propagation to all viewers), flaky test detection (30-run histogram)"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Pipeline Run List and Real-Time Updates</h3>
        <HighlightBlock as="p" tier="important">The run list page loads the initial run list via GET /api/repos/&#123;repoId&#125;/runs?limit=25 (paginated, reverse-chron). It immediately opens an EventSource connection to GET /api/repos/&#123;repoId&#125;/runs/events. The server sends SSE events of two types: (1) run_created &#123;run: RunSummary&#125; — a new run appeared (prepend to list); (2) run_updated &#123;runId, status, duration&#125; — an existing run changed status (update in-place by ID). The run list is stored in Zustand (or React state) as a Map keyed by runId for O(1) updates. On SSE reconnect, the client sends Last-Event-ID to resume from the last event — no full reload needed.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Status badge colors: queued → grey, running → blue with a spinner, success → green, failure → red, cancelled → grey-strikethrough. The running spinner is a CSS animation (not JS-driven) so it does not contribute to JavaScript runtime. The duration for in-progress runs is computed client-side (Date.now() - run.startedAt in a setInterval) rather than streamed from the server — a small difference in precision that saves significant server fan-out for the duration field.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Job DAG Layout and SVG Rendering</h3>
        <HighlightBlock as="p" tier="important">The job DAG layout algorithm: (1) topological sort to determine an ordering that respects all needs edges; (2) assign each job a column (longest path from the source — this gives the earliest column where a job can appear); (3) assign rows (within a column, jobs are stacked vertically). The layout is a pure function of the jobs array and needs relationships — it is computed in a useMemo and re-runs only when jobs are added or their status changes. SVG is chosen over canvas for the DAG because: SVG nodes are focusable (keyboard navigation), SVG elements can have href attributes (linking to job log views), and SVG is easy to animate (CSS transitions on status color changes).</HighlightBlock>
        <p>Each job node is a &lt;rect&gt; with a foreign element or &lt;text&gt; for the label. Status is shown via a colored &lt;circle&gt; icon in the top-right corner of each node. Running jobs have a pulsing circle (CSS animation keyframes). The edge between jobs is an SVG &lt;path&gt; with a cubic Bézier curve (C command) — smooth curves look cleaner than straight lines when jobs overlap vertically. Edge color: grey for not-yet-started dependencies, green for completed dependencies, red for failed dependencies.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Live Log Streaming with Virtual Scroll</h3>
        <HighlightBlock as="p" tier="important">The log view component maintains a lines array (ref, not state — to avoid re-rendering on every append). On each SSE message event, the line is parsed (step name, timestamp, ANSI codes) and pushed to the ref array. A throttled state update (every 100ms via requestAnimationFrame) signals the virtual list to re-render with the new line count. This batching avoids calling setState() 1000 times/second on a fast build, which would cause jank.</HighlightBlock>
        <HighlightBlock as="p" tier="important">ANSI code parsing: a lightweight regex-based parser maps escape codes to CSS classes (e.g., ESC[32m → class="ansi-green", ESC[1m → class="ansi-bold"). The parser maintains a running state (current foreground color, background color, bold, italic) across lines — ANSI codes can span log lines in some CI environments. The parsed output is a React element array (dangerouslySetInnerHTML is not used — each ANSI segment is a &lt;span&gt; with a className). This avoids XSS from crafted ANSI sequences embedding HTML.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Virtual scroll mechanics: the container is a fixed-height &lt;div&gt; with overflow: auto. Total height = lineCount × LINE_HEIGHT (fixed at 20px for monospace). A positioner &lt;div&gt; inside has height = total height. The visible rows are absolutely positioned using transform: translateY(startIndex * LINE_HEIGHT). On scroll, the visible window [startIndex, endIndex] is recomputed and only those lines are rendered. The overscan (10 extra lines above and below) ensures smooth scrolling without blank flicker.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Deployment Approval Gate</h3>
        <HighlightBlock as="p" tier="important">The approval gate UI shows a "Waiting for approval" interstitial in the DAG between the build stage and the deploy stage. The interstitial contains: the approver group ("Production Deployers — 3 members"), the commit range since last deploy ("42 commits since last deploy to production"), a diff summary (files changed, insertions, deletions), and an expandable commit list. The approval form: a textarea for the approval comment (required) and "Approve" / "Reject" buttons. The buttons are disabled for non-approvers (the usePermission hook checks the "deploy:approve:production" permission).</HighlightBlock>
        <HighlightBlock as="p" tier="important">Approval submission: POST /api/runs/&#123;runId&#125;/gates/&#123;gateId&#125;/approve &#123;decision, comment&#125;. The server: (1) validates the approver is in the required group; (2) writes the approval record to the audit log; (3) emits a gate_updated SSE event to all run viewers. All users viewing the run see the gate transition from "waiting" to "approved" in real-time — the DAG node changes color, the pipeline continues to the deploy stage. The audit log entry (approver, timestamp, commit range, comment) is shown in a collapsible "Approval history" section below the gate node in the DAG.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="crucial">SSE vs. WebSocket for log streaming: SSE is simpler for unidirectional streaming (built-in reconnection, Last-Event-ID, native browser support via EventSource). WebSocket would be needed if the client needs to send messages to the server during log streaming (e.g., interactive terminal sessions for debugging). For read-only log tailing, SSE is the right choice. The limitation: SSE connections count against HTTP/1.1's 6 connections-per-origin limit. On HTTP/2, this is not a concern (multiplexed). Ensure the log streaming endpoint is served over HTTP/2, or use a single SSE multiplexer (one SSE connection per run, with all job logs multiplexed into it with a jobId field).</HighlightBlock>
        <HighlightBlock as="p" tier="important">DAG layout complexity: for most CI pipelines, the DAG is small (5–20 jobs) and the simple topological sort + column assignment is sufficient. For complex pipelines with many parallel stages (50+ jobs), a proper hierarchical layout algorithm (Sugiyama/layered graph drawing) would produce cleaner layouts. The tradeoff: Sugiyama layout is complex to implement correctly and a well-known library (dagre-d3) adds ~50KB gzipped. For most CI dashboards, the simple layout is adequate and the complexity of a full layout engine is not justified.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A CI/CD dashboard requires: (1) pipeline run list with SSE real-time updates (run_created + run_updated events, Last-Event-ID resumption, O(1) Map update by runId); (2) job DAG in SVG (topological sort + column assignment, Bézier edge curves, status color animations, keyboard-navigable nodes); (3) live log streaming via SSE (lines ref + 100ms rAF batched state update, ANSI→span CSS class parser, TanStack Virtual fixed-height scroll, auto-scroll pause on user interaction); (4) re-run/cancel with optimistic UI (POST /rerun → optimistic "Queued", DELETE → optimistic "Cancelling", SSE confirms final state); (5) deployment approval gate (approver group check, commit range diff, audit log, SSE gate_updated to all viewers); and (6) flaky test detection (server-side pre-computed pass rate, client renders sparkline histograms, "Mark known flaky" exclusion action). The central constraint: all high-frequency updates (log lines, status changes) must be pushed server-to-client via SSE to avoid polling overhead, with the UI optimized to handle append-only data without re-rendering the full list on every update.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
