"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-developer-documentation-system",
  title: "Design a Developer Documentation System (like Notion/Docusaurus)",
  description:
    "Architecture for a developer documentation system: markdown/MDX authoring with live preview, versioned documentation tied to software releases, full-text search with code snippet indexing, API reference auto-generation from OpenAPI/AsyncAPI specs, interactive code playground embeds with executable examples, feedback and contribution workflows (edit on GitHub), table of contents with scroll-spy, and documentation health metrics (broken links, stale pages, missing examples).",
  category: "high-level-design",
  subcategory: "developer-experience-systems",
  slug: "developer-documentation-system",
  wordCount: 5000,
  readingTime: 30,
  lastUpdated: "2026-05-12",
  tags: ["hld", "documentation", "docusaurus", "mdx", "openapi", "search", "versioning", "scroll-spy", "code-playground"],
  relatedTopics: ["api-playground", "cicd-dashboard"],
};

export default function DeveloperDocumentationSystemArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A developer documentation system is the primary interface between a software product and the developers who build with it. Stripe Docs, React Docs, and AWS documentation are canonical examples. The challenge: documentation must be accurate (in sync with the software), discoverable (developers find what they need quickly), and interactive (developers can try the API without leaving the docs). The system serves multiple personas: new developers exploring the API for the first time (tutorial-first), experienced developers looking up specific method signatures (reference-first), and contributors maintaining the docs (authoring workflow).</HighlightBlock>
        <HighlightBlock as="p" tier="important">The defining tension: documentation often lags behind the software it describes. A docs system must enforce or incentivize synchronicity between code and docs. The best docs systems are generated directly from code (OpenAPI specs, TypeDoc, Storybook) so they cannot fall out of sync. For hand-authored content, the system must provide signals about staleness: "This page was last updated 18 months ago. The API it describes changed in v2.3." Without staleness signals, developers cannot trust whether the docs reflect the current version.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Markdown/MDX authoring pipeline, full-text search, versioned documentation, API reference from OpenAPI specs, interactive code examples, scroll-spy ToC, and documentation health metrics. Not in scope: the CMS authoring interface, localization/i18n infrastructure, or A/B testing of documentation.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Versioned documentation:</strong> Documentation is versioned to match software releases (v1.0, v1.1, v2.0). The current version is served at /docs (no version prefix); older versions at /docs/v1.x/. A version switcher dropdown in the navigation allows switching between versions. When a user is on a versioned page (/docs/v1.x/authentication) and switches to v2.0, the system navigates to the equivalent v2.0 page (/docs/v2.0/authentication) if it exists, or to the v2.0 docs root if the page was removed or renamed. Version management: docs for new versions are created by copying the previous version's content and updating changed pages — the diff between versions is a git diff of the docs source.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Full-text search:</strong> Search covers all documentation pages including code snippets. The search index is built at deploy time (a static search index) using a tool like Pagefind or Flexsearch — the index is served as a static file and executed entirely client-side. This avoids a server-side search infrastructure for a read-heavy, relatively static corpus. Search results show: page title, URL, a text snippet with the query term highlighted (bold), and a breadcrumb (section &gt; page). Code snippets within pages are indexed separately and shown with a "Code" label in results — allowing developers to search for specific function names or error messages that appear only in code examples.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>OpenAPI-based API reference:</strong> The API reference section is auto-generated from an OpenAPI 3.0 spec file (openapi.yaml, committed to the repository). The docs build process parses the spec and generates reference pages for each endpoint: method + path, summary, description, request parameters (path, query, headers, body schema), response schemas, and example request/response pairs. Interactive "Try it" widgets on the reference pages use the same CORS proxy from the API playground to make live API calls from the browser. Authentication credentials for "Try it" are stored in browser localStorage (not the docs system server).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Interactive code examples:</strong> Code blocks in MDX can be marked as executable (```js sandbox). Executable code blocks are rendered with a "Run" button that executes the code in a sandboxed iframe using a service like CodeSandbox, StackBlitz, or a self-hosted sandpack instance. The sandbox has access to the current SDK version and any required API credentials the developer provides. The sandbox state (code, output) persists in the iframe's local storage — modifying the code and clicking Run shows the output inline below the code block. For Node.js/backend examples, execution is routed to a serverless sandbox (e.g., AWS Lambda) rather than a browser iframe.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Scroll-spy table of contents:</strong> The right-side Table of Contents (ToC) shows all h2 and h3 headings on the current page. As the user scrolls, the active heading is highlighted (the ToC item corresponding to the heading currently at the top of the viewport). Implementation: IntersectionObserver on all heading elements — when a heading enters/exits the viewport, update the activeHeadingId state. The ToC scrolls itself to keep the active item visible (if the page has many headings and the ToC is long). Clicking a ToC item scrolls the page to that heading using smooth-scroll and updates the URL hash (without a full page navigation).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Documentation health metrics:</strong> A health dashboard (accessible to maintainers) surfaces: broken internal links (detected at build time by the docs build pipeline), stale pages (not updated in &gt;90 days while the referenced API version changed), pages with no code examples, and pages with no "Last updated" timestamp. The dashboard data is generated as a JSON report during the docs build and exposed via a /docs/health endpoint (protected behind auth). It sends alerts to a Slack channel when: a page's staleness score crosses a threshold, or a broken link is detected in the build.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Edit on GitHub contribution flow:</strong> Every page has an "Edit this page" link that navigates to the page's source file in the GitHub repository (constructing the URL: https://github.com/org/repo/edit/main/docs/&#123;filepath&#125;). GitHub's web editor allows contributors to make small edits and submit a pull request without cloning the repository. The docs site automatically rebuilds from the PR preview branch via a CI/CD webhook — a preview URL is posted as a PR comment so reviewers can see the rendered docs before merging.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">Developer documentation is a publish-once, read-many workload. The build pipeline (triggered on git push to the docs repository) processes MDX files through a series of transformations: (1) frontmatter extraction (title, description, version, last-updated); (2) MDX compilation (React components embedded in markdown); (3) syntax highlighting of code blocks (Shiki or Prism — applied at build time, not runtime, so no highlighting library ships to the browser); (4) search index generation (Pagefind crawls the built HTML); (5) static HTML generation (Next.js static export or Astro). The result is a fully static site that is deployed to a CDN with no server component needed for reading — only the "Try it" API proxy and the collaborative features (comments, feedback) require a server.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Versioning is implemented at the file system level: docs/v1.x/ and docs/v2.0/ are separate directory trees. The build generates separate route namespaces for each version. The version switcher is a static dropdown — it does not require a server call to switch versions. CDN caching: the current version's pages are cached with short TTL (60 seconds) to pick up deployment updates quickly. Older version pages are cached aggressively (Cache-Control: public, max-age=31536000, immutable) — old docs do not change.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/developer-experience-systems/developer-documentation-system.svg"
          alt="Developer documentation system: build pipeline (git push → MDX compile + frontmatter extract; Shiki syntax highlight at build time; Pagefind search index from HTML; static export → CDN; PR preview via CI webhook), versioned docs (current /docs no prefix; old /docs/v1.x/; version switcher → navigate equivalent page; old versions: Cache-Control immutable; docs diff = git diff), full-text search (Pagefind client-side index; code snippets indexed separately; results: title+snippet+breadcrumb; query term bold-highlighted), OpenAPI ref gen (openapi.yaml → per-endpoint pages: method+path+params+schemas+examples; Try-it widget → CORS proxy → live API call; auth in localStorage), interactive sandbox (```js sandbox → Run button → sandpack iframe; SDK preloaded; output inline; Node.js → Lambda serverless sandbox), scroll-spy ToC (IntersectionObserver h2/h3; activeHeadingId state; ToC auto-scroll to active; click → smooth scroll + URL hash update), docs health (build-time: broken internal links; stale >90 days; no code examples; /docs/health endpoint auth-gated; Slack alert on threshold)."
          caption="Static build pipeline (MDX → Shiki highlight → Pagefind index → CDN static), versioned docs (directory-per-version, version switcher navigate-or-fallback), client-side Pagefind search (code snippets indexed separately), OpenAPI-generated reference with CORS-proxy Try-it, sandpack interactive code execution, IntersectionObserver scroll-spy ToC, build-time health metrics (broken links, staleness, Slack alerts)"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">MDX Compilation Pipeline</h3>
        <HighlightBlock as="p" tier="important">MDX allows React components to be embedded in Markdown. The docs use MDX for: custom callout boxes (&lt;Callout type="warning"&gt;), tabs for language-specific examples (&lt;Tabs&gt;&lt;Tab lang="js"&gt;...&lt;Tab lang="python"&gt;...&lt;/Tabs&gt;), interactive code sandboxes (&lt;CodeSandbox /&gt;), and API reference embeds (&lt;ApiEndpoint path="/users" method="GET" /&gt;). The MDX compilation happens at build time: the .mdx source is compiled to a JavaScript module that exports a React component. The compiled output is statically analyzed for: heading structure (to build the ToC), internal link targets (to check for broken links), and referenced API endpoints (to verify they exist in the OpenAPI spec).</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">Syntax highlighting at build time with Shiki: Shiki uses the same TextMate grammars as VS Code, producing accurate, VS Code-quality syntax highlighting. The output is static HTML with inline CSS classes — no JavaScript is needed at runtime for highlighting. The trade-off: Shiki increases build time (it must tokenize every code block) but eliminates runtime highlighting overhead entirely. For a docs site with thousands of code blocks, build time can be significant; Shiki supports incremental compilation (only re-highlight changed files) to keep build times acceptable.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Client-Side Search with Pagefind</h3>
        <HighlightBlock as="p" tier="important">Pagefind works by crawling the built HTML output and generating a compressed search index (typically 1–5% of the site's total HTML size — a 10MB site has a ~100–500KB search index). The index is split into chunks — only the chunk containing the search term is downloaded on demand (lazy loading). On first search, Pagefind downloads ~30KB of the Pagefind WASM binary and the initial index chunk. Subsequent searches within the same session use the cached index. Search latency: &lt;50ms for most queries (WASM execution is fast).</HighlightBlock>
        <HighlightBlock as="p" tier="important">Code indexing: by default, Pagefind indexes visible text — code blocks render as text and are indexed. To distinguish code results from prose results, code blocks are wrapped in a data-pagefind-filter="type:code" attribute during the MDX compilation. Search results with type=code show a code snippet icon and are grouped separately in the results UI. This allows developers to search "useEffect cleanup function" and find both the explanatory prose and the code example that contains the pattern.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">OpenAPI Reference Generation</h3>
        <HighlightBlock as="p" tier="important">The OpenAPI spec (openapi.yaml) is the source of truth for the API reference section. The docs build process runs a code generator (openapi-to-mdx, a custom or open-source transformer) that reads each endpoint in the spec and emits an MDX file: the endpoint's summary becomes the page title, the description becomes the introductory paragraph, request parameters are rendered as a structured table, request/response schemas are rendered as nested property tables with type and description columns, and example request/response pairs are shown as side-by-side JSON code blocks.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The "Try it" widget: each endpoint page has a form that pre-fills the endpoint URL and allows filling in parameters. On clicking "Run," the browser sends the request to the CORS proxy (same as the API playground), which forwards it to the actual API. Authentication is handled via a "Set API key" button that stores the key in localStorage (under a docs-specific key) and injects it into the Authorization header on every "Try it" request. The stored API key persists across page navigations in the same browser session, so the developer does not need to re-enter it for every endpoint.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Documentation Staleness Detection</h3>
        <HighlightBlock as="p" tier="important">Staleness detection is a build-time analysis that compares each docs page's last-updated date (from frontmatter or git log) against the last change date of the API endpoints it references. The docs build extracts API endpoint references from MDX files (via AST analysis of &lt;ApiEndpoint /&gt; components and code blocks containing endpoint paths). It then queries the OpenAPI spec's git history to find when each endpoint was last changed. If an endpoint changed after the docs page was last updated, the page is flagged as potentially stale.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The health report is generated as a JSON file at build time and deployed alongside the static site. It is consumed by: (1) the /docs/health dashboard (a protected page for maintainers showing a sortable table of health signals); (2) a Slack webhook that posts alerts when new broken links or high-staleness pages are detected (compared to the previous build's health report); (3) PR status checks — if a PR introduces a broken link, the CI check fails and blocks the PR merge until the link is fixed.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="crucial">Static search vs. server-side search: client-side search (Pagefind, Flexsearch) has no server cost and works offline. But it has limitations: the index must fit in memory (&lt;100MB practically), relevance ranking is basic (no machine learning-based ranking), and the index must be rebuilt on every docs update. Server-side search (Algolia DocSearch, Elasticsearch) provides ML-based ranking, analytics (what are developers searching for? What searches return no results?), and can index content dynamically without a rebuild. The tradeoff is cost (Algolia is not free at scale) and operational complexity. For most docs sites, client-side search is sufficient and preferred. As the site grows beyond ~50,000 pages or requires advanced ranking, server-side search becomes worth the cost.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Versioning strategy: directory-based versioning (separate file trees per version) is simple but creates maintenance overhead — a fix to a shared component must be applied to each version separately. An alternative: symbolic links or symlinks that allow shared content to be referenced across versions. The tradeoff: symlinks complicate the build process and git history. For most products, docs are only actively maintained for the current and one previous major version — older versions are frozen and not updated (with a banner: "This is documentation for an older version. See the current docs.").</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A developer documentation system requires: (1) static build pipeline (MDX → Shiki build-time highlighting → Pagefind HTML crawl → CDN static deploy; PR preview via CI webhook; incremental rebuild for Shiki); (2) directory-based versioning (current at /docs, old at /docs/vX.x/, version switcher navigate-or-fallback, old versions immutable-cached); (3) client-side Pagefind search (WASM + lazy chunk loading, code blocks separately filtered with data-pagefind-filter, results with breadcrumb and highlighted snippet); (4) OpenAPI-generated reference (per-endpoint MDX pages, parameter tables, side-by-side examples, CORS-proxy Try-it widget with localStorage auth key); (5) sandpack interactive code execution (```js sandbox → sandpack iframe + SDK preloaded + inline output; backend → Lambda serverless); (6) IntersectionObserver scroll-spy ToC (activeHeadingId state, smooth-scroll + URL hash, ToC auto-scroll to active item); and (7) build-time health report (broken links, staleness vs. OpenAPI git history, /docs/health dashboard, Slack alert on threshold breach, PR check block on broken links). The defining principle: documentation that can go stale is worse than no documentation — the system must enforce the coupling between docs and the code it describes.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
