"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-package-registry-ui",
  title: "Design a Package Registry UI (like npm)",
  description:
    "Architecture for a package registry UI like npm or PyPI: package search with typosquatting detection and relevance ranking, package detail page with version selector and changelog diff, dependency tree visualization with vulnerability overlay from OSV/CVE data, weekly download trend sparklines, bundle size impact estimator using bundlephobia-style analysis, package deprecation and security advisory banners, publisher trust indicators (verified publisher, provenance attestation), and unpublish/deprecate controls for package owners.",
  category: "high-level-design",
  subcategory: "developer-experience-systems",
  slug: "package-registry-ui",
  wordCount: 5000,
  readingTime: 30,
  lastUpdated: "2026-05-12",
  tags: ["hld", "package-registry", "npm", "dependency-tree", "supply-chain", "typosquatting", "vulnerability", "bundle-size", "provenance"],
  relatedTopics: ["cicd-dashboard", "developer-documentation-system"],
};

export default function PackageRegistryUiArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A package registry UI is the discovery, documentation, and trust surface for a software package ecosystem. npm, PyPI, crates.io, and Maven Central all solve the same core problem: help developers find the right package, evaluate it, and understand the risks of adding it as a dependency. The UI must balance discoverability (search and browse), information density (version history, download trends, dependency tree), and security signals (vulnerability advisories, publisher trust indicators, supply chain provenance).</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">The defining security challenge: package registries are high-value targets for supply chain attacks. Malicious packages are published under names similar to popular packages (typosquatting: "lodash" vs. "lodash_", "react" vs. "re-act"), or legitimate packages are compromised after publication (account takeover, malicious version injection). The UI must surface trust signals prominently without creating alert fatigue — a design where every package has the same warning level is as dangerous as no warnings at all. The UI must make the difference between "verified publisher, provenance attestation, no known vulnerabilities" and "unknown publisher, no attestation, 3 critical CVEs" immediately legible.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Package search, package detail page, dependency tree visualization, vulnerability overlay, download trend display, publisher trust indicators, and owner management controls. Not in scope: the package upload/publish flow, the registry storage layer, or the vulnerability scanning infrastructure.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Package search:</strong> Full-text search across package names, descriptions, and keywords. Search results are ranked by a combination of: download count (popularity), maintenance score (last publish date, open issues), quality score (test coverage, readme length), and text relevance (BM25). Typosquatting detection: if the query closely matches a popular package name (Levenshtein distance ≤ 2 from a top-1000 package), a warning banner appears: "Did you mean 'lodash'? The package 'lodash_' has very few downloads and was published recently." Search is implemented with an instant-search pattern: debounced 200ms API call to GET /api/search?q=&#123;query&#125;, results displayed inline without a full-page navigation.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Package detail page:</strong> The detail page shows: package name, current version, description, links (homepage, repository, issues), license, weekly download count (with 1-year trend sparkline), unpacked size, publish date, and "Install" command (npm install &#123;name&#125; with one-click copy). A version selector dropdown shows all published versions with their publish dates and a visual indicator for deprecated versions (strikethrough) and the latest/next/beta dist-tags. Clicking a version reloads the page with ?version=X.Y.Z — the page is server-rendered for each version so that version-specific pages are indexable and shareable.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Dependency tree visualization:</strong> The "Dependencies" tab shows a collapsible tree of the package's direct and transitive dependencies with version ranges. Each dependency node shows the resolved version and a vulnerability badge (critical/high/medium/low counts from the OSV database). The tree is lazy-loaded — only direct dependencies are shown initially; clicking a node expands its transitive dependencies on demand. This avoids rendering 10,000-node trees for packages like babel with massive dependency graphs. A "Flat list" toggle switches to a de-duplicated list view sorted by criticality, which is more practical for auditing.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Owner management controls:</strong> Package owners (authenticated) can: add/remove maintainers (with role: owner or maintainer), deprecate a version (sets the npm deprecation message shown in install warnings), unpublish a version within 72 hours of publication (after 72h, unpublishing requires contacting support to prevent breaking ecosystem dependencies), and manage 2FA requirements for publishing. Destructive actions (deprecate, unpublish) require re-authentication and show a confirmation modal with the downstream impact estimate ("This version is used by 847 other packages").</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Publisher trust indicators:</strong> Three tiers: (1) Verified publisher — the publisher's npm organization is linked to a verified GitHub organization or corporate domain; a blue checkmark badge is shown next to the publisher name. (2) Provenance attestation — the package was built and published via a verifiable CI/CD pipeline (GitHub Actions sigstore attestation — the SLSA provenance is stored and linked); a "Provenance" badge links to the build attestation. (3) No indicators — no badge, no verification. The absence of badges is itself a signal that developers should evaluate carefully. The trust tier is shown prominently on the package header, not buried in a details tab.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Bundle size impact:</strong> The "Bundle Size" tab shows the estimated contribution to a web bundle: minified size, gzip size, and brotli size. Displayed as a visual: a bar showing the package's size relative to common reference points (jQuery: 87KB, React: 44KB, lodash: 71KB). The analysis runs server-side (bundling the package in a controlled environment) and is cached per package version. A "Compare versions" feature shows the bundle size delta between two versions — useful for evaluating whether a minor version bump increased the bundle significantly.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Security advisory display:</strong> Known vulnerabilities are pulled from the OSV (Open Source Vulnerabilities) database via GET /api/packages/&#123;name&#125;/advisories. Each advisory shows: CVE ID, severity (CVSS score with color-coded label), affected version range, patched version, description, and a link to the full advisory. A prominent banner on the package header shows the highest-severity unpatched vulnerability: "Critical vulnerability: CVE-2023-XXXX affects versions &lt;2.1.0. Update to 2.1.0 or later." The banner is shown on all version pages where the version is in the affected range.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The package registry UI is a read-heavy, cache-heavy system. Package metadata (name, description, versions, dependencies) changes infrequently — a package might publish a new version once a week. Download stats change daily. Vulnerability advisories may appear at any time (but are relatively infrequent). The caching strategy: package metadata is cached aggressively at the CDN layer (Cache-Control: public, max-age=300, stale-while-revalidate=3600). Download stats are cached for 24 hours. Vulnerability data is cached for 1 hour with cache invalidation on new OSV database updates via webhook.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Search is the most latency-sensitive path — developers type and expect near-instant results. Search uses a pre-built inverted index (Elasticsearch or MeiliSearch) that is updated asynchronously when packages are published. Search results are not cached (queries are too diverse) but the search API is fast (&lt;50ms P99) because the index is in memory. The package detail page is server-rendered for SEO (package pages are frequently indexed and linked) with selective client-side hydration for interactive elements (version selector, dependency tree toggle, install command copy).</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/developer-experience-systems/package-registry-ui.svg"
          alt="Package registry UI system: search (BM25 + popularity + maintenance + quality score; typosquatting: Levenshtein ≤2 from top-1000 → warning banner; debounced 200ms GET /search; instant results inline), package detail (server-rendered per version; install cmd copy; version selector: deprecated strikethrough + dist-tags; 1yr download sparkline; trust badge: verified publisher checkmark / provenance SLSA / no badge = signal), dependency tree (direct nodes shown; click → expand transitive on demand; OSV vuln badge per node: critical/high/medium/low; flat-list mode sorted by severity), vulnerability advisories (GET /advisories from OSV; CVSS severity color; affected range; critical banner on header; patched version link), bundle size (server-side bundle analysis cached per version; minified+gzip+brotli bars; compare versions delta; reference bars: jQuery/React/lodash), owner controls (add/remove maintainers; deprecate version → npm warning; unpublish <72h → confirm modal + impact count; 2FA enforcement; re-auth gate)."
          caption="Instant search (BM25 + typosquatting Levenshtein ≤2 warning), server-rendered package detail per version (SEO, shareable), trust tiers (verified publisher checkmark + SLSA provenance badge), dependency tree lazy-expand + OSV vuln overlay per node, bundle size server-cached analysis (minified/gzip/brotli + compare versions), security advisory header banner, owner unpublish &lt;72h re-auth gate"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Search and Typosquatting Detection</h3>
        <HighlightBlock as="p" tier="important">The search API implements a multi-factor ranking score: score = 0.4 × textRelevance + 0.3 × downloadScore + 0.2 × maintenanceScore + 0.1 × qualityScore. textRelevance is BM25 over the package name, description, and keywords. downloadScore is log-normalized weekly download count (log10(downloads) / log10(maxDownloads)). maintenanceScore factors in days since last publish (recent = higher) and whether the package is deprecated. qualityScore includes readme length, test presence, and valid semantic versioning.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Typosquatting detection: for each search query, the server computes the Levenshtein distance between the query and each package in the top-1000 list (by download count). If any top-1000 package is within edit distance ≤ 2 of the query (but is not the query itself), and the queried package has &lt;100 weekly downloads, the warning is surfaced. The comparison is case-insensitive and also covers common substitutions (l↔1, 0↔o, -↔_). The top-1000 list is pre-computed and cached in Redis — the Levenshtein comparison against 1000 strings is fast enough to do on every search request (&lt;5ms).</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Dependency Tree Lazy Loading</h3>
        <HighlightBlock as="p" tier="important">The dependency tree is a recursive data structure with potentially hundreds of thousands of nodes for packages with many transitive dependencies. Rendering the full tree on load would be both slow and overwhelming. The lazy-load approach: the initial page load fetches only direct dependencies (GET /api/packages/&#123;name&#125;/dependencies?depth=1). Each dependency node has a "expand" chevron if it has its own dependencies. Clicking the chevron fetches that package's dependencies (GET /api/packages/&#123;depName&#125;/dependencies?depth=1) and inserts them as children of the clicked node in the tree state.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Circular dependency detection: some packages have circular dependencies in their transitive graph (rare but possible due to peer dependency patterns). The tree must detect and break cycles: maintain a Set of visited package names during expansion; if a package is already in the ancestor chain, render it as a leaf with a "circular dependency" label instead of expanding further. The flat list view de-duplicates packages by name (showing the resolved version that will actually be installed) and is pre-fetched from the server (GET /api/packages/&#123;name&#125;/dependencies?flat=true), which resolves the full dependency graph server-side using the npm resolution algorithm.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Download Statistics and Trend Charts</h3>
        <HighlightBlock as="p" tier="important">Download statistics are collected by the registry's download logging infrastructure and aggregated into daily totals per package per version. The sparkline on the package header shows the last 52 weeks of download data (weekly aggregates). The data is fetched from GET /api/packages/&#123;name&#125;/downloads?period=last-year and rendered as an SVG sparkline (no charting library — a sparkline is simple enough to render with SVG polyline: normalize values to [0, height] and map to x positions spaced across the SVG width). The sparkline shows color-coded trend arrows: green up-trend if the current week is &gt;10% above the 4-week average, red for down-trend.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Version-specific download breakdown: the "Downloads" tab shows a bar chart comparing download counts across the last 5 major versions, helping developers understand version adoption. A new major version with low adoption relative to the previous version indicates developers are hesitant to upgrade (possibly due to breaking changes or migration cost) — this is a useful signal for library maintainers and users evaluating upgrade risk.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">SLSA Provenance and Supply Chain Trust</h3>
        <HighlightBlock as="p" tier="crucial">SLSA (Supply-chain Levels for Software Artifacts) provenance attestations are cryptographically signed statements about how a package was built: what source commit, what CI/CD system, what build steps. For npm packages published via GitHub Actions with sigstore, the provenance is stored in the npm registry and linked to the package version. The registry UI fetches the provenance attestation from GET /api/packages/&#123;name&#125;@&#123;version&#125;/provenance and displays: the GitHub Actions run URL (linking to the exact CI run that produced this package), the commit SHA, the workflow file name, and the sigstore transparency log entry (a Rekor log ID that can be independently verified). This allows a developer to verify that the package on npm corresponds exactly to the code in the repository — detecting cases where a package was published with modified code not present in the repo's git history.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">Showing vulnerability warnings without overwhelming developers: if every package with any vulnerability shows a red badge, developers learn to ignore it (the "boy who cried wolf" problem). The design principle: show the highest-severity unpatched vulnerability prominently, but distinguish between "critical vulnerability in this package's own code" and "critical vulnerability in a transitive dependency that may not be reachable from your code." The former requires immediate action; the latter requires investigation. Color and icon severity must map to action urgency, not just presence of any advisory.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Unpublish policy design: allowing arbitrary package removal after publication breaks the ecosystem — other packages that depend on the removed package break at install time (the left-pad incident: the removal of a 17-line utility broke thousands of builds). The 72-hour window for self-service unpublish (before requiring support intervention) balances the need for typo/mistake correction against the stability of the ecosystem. The "downstream impact count" shown in the unpublish confirmation modal makes the real-world cost of the action tangible to the package owner.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A package registry UI requires: (1) instant search with typosquatting detection (BM25 multi-factor ranking, Levenshtein ≤ 2 from top-1000 → warning banner, debounced 200ms); (2) server-rendered package detail per version (SEO, shareable URLs, version selector with deprecated strikethrough, 52-week download sparkline); (3) publisher trust tiers (verified publisher checkmark, SLSA sigstore provenance link, no-badge as signal); (4) lazy-expanding dependency tree (depth=1 initial, click-to-expand, cycle detection with visited Set, flat-list de-duplicated mode); (5) OSV vulnerability overlay (per-node severity badge, critical header banner on affected versions, CVSS score color coding); (6) bundle size analysis (server-cached per version, minified/gzip/brotli bars, version compare delta); and (7) owner controls with re-auth gate (deprecate, unpublish &lt;72h with downstream impact count, 2FA enforcement for publishing). The central design challenge: making security signals legible and actionable without creating alert fatigue — the severity hierarchy must drive the user toward the correct response, not toward ignoring all warnings.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
