"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-ads-delivery-targeting-ui",
  title: "Design an Ads Delivery & Targeting UI (like Google Ads / Facebook Ads)",
  description:
    "Architecture for a real-time bidding ads delivery system: publisher ad slot request with userId and page context, user segment resolution from Redis under 2ms, OpenRTB bid request broadcast to 50 DSPs in parallel with 80ms hard deadline, second-price Vickrey auction with eCPM = bid × pCTR ranking, winning creative served via CDN in isolated iframe sandbox, impression and click beacons published to Kafka asynchronously, frequency capping with Redis INCR per user per day, click deduplication in 60-second window, conversion pixel for downstream purchase attribution, and invalid traffic (IVT) detection before billing.",
  category: "high-level-design",
  subcategory: "ads-monetization-systems",
  slug: "ads-delivery-targeting-ui",
  wordCount: 5100,
  readingTime: 30,
  lastUpdated: "2026-05-14",
  tags: ["hld", "ads", "rtb", "dsp", "targeting", "auction", "frequency-cap", "kafka", "openrtb"],
  relatedTopics: ["ads-analytics-dashboard", "creator-monetization-dashboard"],
};

export default function AdsDeliveryTargetingUiArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="crucial">An ads delivery and targeting system matches advertisements to users in real time based on who the user is (demographics, interests, behavioral signals) and what context they are in (page content, device, location, time of day). The entire pipeline — from a publisher's ad slot appearing on a user's screen to an ad being selected and rendered — must complete in under 100ms to not degrade the page load experience. This is the most latency-sensitive distributed system in commercial internet infrastructure.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The core mechanism is Real-Time Bidding (RTB): instead of the ad platform selecting the ad directly, it broadcasts the ad opportunity to multiple demand-side platforms (DSPs) representing advertisers, each of whom submits a bid price within a tight deadline. The highest effective bidder wins and their ad is shown. This creates a market that maximizes revenue for publishers while giving advertisers precise control over which audiences they reach and how much they pay per impression.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Ad slot request and user targeting, RTB auction, creative delivery, impression/click tracking, frequency capping, and conversion attribution. Not in scope: advertiser campaign creation UI (budget setting, audience builder, creative upload), or the DSP-side bidding strategy logic.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Ad slot request and user targeting:</strong> When a publisher's page loads, the publisher's ad SDK calls POST /ads/request with: slotId (which ad placement on the page), userId (hashed/pseudonymized), pageUrl (for content targeting), device type, geoIp (country, city, DMA), and contextual signals (IAB content categories detected on the page). The ad server resolves the user's targeting segment from Redis in under 2ms: GET seg:&#123;userId&#125; returns a compact binary blob encoding the user's interest categories (IAB taxonomy), income bracket, age bucket, household composition — derived from past behavioral data and updated nightly by the audience modeling pipeline. The resolved segment and page context are assembled into an OpenRTB 2.6 BidRequest JSON object, which is broadcast to all eligible DSPs.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>RTB auction with 80ms deadline:</strong> The ad server fans out the BidRequest to up to 50 DSPs simultaneously using parallel HTTP calls. Each DSP has 80ms to respond with a BidResponse containing: bid price in CPM (cost per 1,000 impressions), a reference to the ad creative, and any additional targeting constraints. DSPs that fail to respond within 80ms are dropped from this auction. The typical network round-trip to a co-located DSP is 5–20ms, leaving the DSP 60–75ms for its own internal bidding logic (user matching, campaign budget checks, ML bid prediction). The ad server collects all responses and passes them to the auction engine.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Second-price Vickrey auction:</strong> The auction engine ranks bids by effective CPM (eCPM = bid CPM × predicted CTR). eCPM adjusts the raw bid by the probability that the ad will be clicked — an ad with a 2% predicted CTR is worth twice as much as an ad with a 1% predicted CTR at the same bid price. The winner is the highest eCPM bid. The clearing price (what the winner pays) is the second-highest bid plus $0.01 — the second-price mechanism gives bidders an incentive to bid their true valuation (overbidding does not increase revenue). If all bids are below the publisher's floor price (set by the publisher in advance), no ad is shown and the slot falls back to a house ad or remains blank. The floor price is typically set to prevent the publisher's inventory from being devalued by very low bids.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Creative delivery and isolation:</strong> The winning creative is delivered to the publisher's page via the CDN (creativeUrl is a CDN-hosted asset — image, HTML5 banner, or video). Critically, the creative is rendered in a sandboxed iframe with no access to the parent page's DOM or cookies. This isolation prevents malicious ad code (malvertising) from stealing user data or hijacking the parent page. The iframe sandbox attribute disables: scripts from accessing parent, form submission, top-level navigation, and plugin loading. The ad server returns the creative URL and a beacon URL to the publisher's SDK; the SDK injects the iframe, which loads the creative from CDN and fires the impression beacon when fully loaded (using IntersectionObserver to confirm the ad is in the viewport — viewability tracking).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Frequency capping:</strong> Showing the same ad too many times to the same user degrades the user experience and wastes advertiser budget (the user has already seen and ignored the ad). Frequency capping limits: default cap is 3 impressions per day per ad per user (configurable by the advertiser). Implementation: Redis INCR freq:&#123;userId&#125;:&#123;adId&#125;:&#123;date&#125; before serving the ad. If the count exceeds the cap, the ad is excluded from the auction for this user. Redis key expires at midnight UTC (TTL set to end of day). The frequency cap check adds ~1ms to the auction path (Redis INCR is O(1)). For users who browse with multiple devices or clear cookies, frequency caps are enforced at the device level (cookie-based userId per device) — cross-device frequency capping requires probabilistic user matching which is a separate, more complex system.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Impression and click tracking pipeline:</strong> After the ad renders, the impression beacon fires: GET /ads/beacon?type=impression&amp;adId=X&amp;userId=Y&amp;slotId=Z. The beacon endpoint returns a 1×1 transparent GIF (HTTP 200) in under 5ms and publishes the event to Kafka asynchronously (the Kafka publish happens after the HTTP response is sent — it is non-blocking). The Kafka topic receives 1M–10M impression events per second at peak. Kafka is partitioned by campaignId — all events for the same campaign land on the same partition set, ensuring ordered processing and enabling efficient aggregation by campaign. Click tracking: when the user clicks the ad, the click goes through a redirect URL: GET /ads/click?adId=X&amp;userId=Y → 302 to the advertiser's landing page. The redirect is used to log the click (publish to Kafka) and check deduplication (Redis SETNX click:&#123;userId&#125;:&#123;adId&#125; with 60s TTL — duplicate clicks within 60 seconds are not counted). Click validation includes basic IVT detection: bots often click immediately after an impression (sub-second click latency is suspicious), click from the same IP as the impression server (internal traffic), or cookie-less requests (typical of scrapers).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Invalid traffic (IVT) detection:</strong> Ad fraud (fake impressions and clicks generated by bots to drain advertiser budgets) is a $100B+ annual problem. IVT detection layers: (1) pre-bid — the ad server checks each bid request against a blocklist of known bot IPs, datacenter IP ranges, and suspicious user agents; (2) post-impression — the Flink stream processor flags events with anomalous patterns (click rate &gt;50% of impressions from a single source, impression velocity far above typical for a publisher); (3) batch ML — a daily fraud model scores each impression/click event and marks likely fraudulent events as invalid; (4) advertiser-credit — detected invalid clicks are refunded to the advertiser's billing account at the end of the billing cycle. Invalid events are not deleted from the raw event log — they are marked with an ivt=true flag and excluded from billing aggregations but retained for analysis.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Conversion attribution:</strong> An advertiser wants to know if an ad impression or click led to a purchase. Conversion tracking: the advertiser places a conversion pixel (a JavaScript snippet or server-side API call) on their thank-you page. When a conversion fires, it sends POST /ads/conversion with: conversionType (purchase, signup), value (purchase amount), and the userId (from the advertiser's own session, if available). The conversion service looks up the user's recent ad exposures (last click within 7 days, last impression within 1 day — the standard attribution window) and attributes the conversion to the most recent qualifying ad interaction. The attribution model is last-click by default (the ad that was last clicked before conversion gets full credit). Multi-touch attribution models (linear — credit distributed equally across all touchpoints, position-based — 40% to first and last, 20% to middle) are computed by the analytics pipeline and available in the advertiser dashboard for comparison.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Audience segment pipeline:</strong> The user segment stored in Redis is computed nightly by the audience modeling pipeline. Input: the user's behavioral event log (pages visited, searches, purchases, video views — anonymized and aggregated). Processing: an offline batch job (Spark or Flink) classifies each user into IAB interest categories (Travel, Sports, Finance, etc.) using a combination of URL content classification (URL → IAB category via a trained classifier) and collaborative filtering (users who visit similar pages have similar interests). The resulting segment vector is a compact binary representation (bitset over 1,024 IAB categories + continuous features for age bracket, income, geo). Segments are written to Redis with a 25-hour TTL (refreshed daily). The Redis cluster holds segments for 500M daily active users — each segment is approximately 256 bytes, totaling ~128GB per Redis cluster, well within the capacity of a distributed Redis cluster.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The system has four planes: the real-time serving plane (ad server → segment lookup → RTB auction → creative delivery, all under 100ms), the event pipeline plane (Kafka impression/click/conversion events → Flink stream processing → ClickHouse for analytics and Redis for live budget tracking), the offline modeling plane (daily audience segmentation, pCTR model training, fraud model training), and the advertiser management plane (campaign CRUD, budget setting, targeting configuration — not latency-critical). The real-time serving plane is the critical path; the others are decoupled via Kafka and operate asynchronously.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/ads-monetization-systems/ads-delivery-targeting-ui.svg"
          alt="Ads delivery pipeline: publisher sends ad slot request; ad server resolves user segment from Redis under 2ms; broadcasts OpenRTB BidRequest to 50 DSPs in parallel; 80ms deadline drops late bids; second-price auction ranks by eCPM = bid × pCTR; winner creative served via CDN in sandboxed iframe; impression beacon fires to Kafka asynchronously; click redirect logs click and deduplicates; conversion pixel attributes to last click within 7 days."
          caption="Segment lookup Redis &lt;2ms; RTB 80ms deadline; 2nd-price Vickrey eCPM ranking; CDN iframe sandbox; freq cap Redis INCR; Kafka async events; IVT pre-bid blocklist + post-bid Flink; last-click attribution 7-day window"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">pCTR Model and eCPM Ranking</h3>
        <HighlightBlock as="p" tier="crucial">The predicted click-through rate (pCTR) model is the most important ML model in the ads system — it determines how bids are ranked, which directly affects auction revenue and ad relevance. The pCTR model predicts the probability that a given user will click a given ad in a given context. Features: ad creative features (size, format, category), user features (age bucket, interest segments, device type), context features (page category, time of day, day of week, position on page — above-fold ads have higher CTR than below-fold), and historical interaction features (the user's past CTR with this advertiser's ads — strong signal if available). Model architecture: logistic regression or gradient boosted trees (GBT) for latency, with a neural network for feature embedding (the neural network is run offline to generate feature embeddings; the logistic regression uses the embeddings as input and runs in under 1ms). The pCTR model is retrained daily on the previous day's impression and click log. It is served in-process within the ad server (not a separate RPC call) to minimize auction latency. Model size: approximately 50MB per model version, loaded into memory on startup.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Budget Pacing</h3>
        <HighlightBlock as="p" tier="important">Advertisers set a daily budget (e.g., $1,000/day). Without pacing, the budget could be exhausted in the first few hours (peak traffic is in the morning and evening), leaving no ads running for the rest of the day. Pacing strategies: (1) even pacing — distribute the budget evenly across 24 hours (target spend per hour = dailyBudget / 24); (2) accelerated pacing — spend as fast as possible until the budget is exhausted (used by advertisers who want maximum early exposure); (3) dayparting — concentrate spend in specific hours (e.g., only run ads 6pm–10pm). Even pacing implementation: a pacing controller runs every 5 minutes, checking Redis for the campaign's current spend (Redis HGET campaign:&#123;id&#125;:spend) and computing the current pace rate (spend / elapsed hours). If ahead of pace, the controller reduces the auction participation probability (throttle rate) — the ad server randomly skips some auctions for this campaign at the throttle rate. If behind pace, the throttle rate increases back toward 100%. This smooth pacing avoids the "budget cliff" where a campaign runs normally for half the day and then abruptly stops.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Creative Management and CDN</h3>
        <HighlightBlock as="p" tier="crucial">Ad creatives (images, HTML5 banners, video) are uploaded by advertisers to the creative management system, which: validates creative dimensions and file size against the slot specification, runs creative review (automated content policy check using a classifier trained on policy violations — adult content, misleading claims, prohibited products; plus human review queue for flagged creatives), encodes video to multiple resolutions (using FFmpeg — 1080p source → 720p, 480p, 360p for adaptive bitrate), and distributes the creative to the CDN. Once approved, the creative's CDN URL is stored in the creative database and referenced in BidResponse objects. Creatives are cached at the CDN edge with a long TTL (7 days) — they rarely change after approval. Creative invalidation (when an advertiser updates a creative after approval) is handled via URL versioning: the updated creative is uploaded as a new URL, invalidating the old URL in the CDN simultaneously.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">RTB latency vs. DSP count: broadcasting to 50 DSPs in parallel with an 80ms deadline requires the ad server to wait 80ms on every auction, even if all DSPs respond in 20ms. The wait time is bounded by the deadline, not the actual response times. Reducing the deadline to 50ms increases the proportion of dropped responses (DSPs with slower infrastructure can't respond in time) but decreases auction latency. Increasing the deadline to 120ms allows more DSPs to respond but increases total auction latency, degrading page load time. The 80ms deadline is an industry standard (OpenRTB specification recommendation) that balances fill rate (auction revenue) against user experience (page latency). For mobile ads, the deadline is sometimes reduced to 60ms because mobile page loads are more latency-sensitive.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Privacy and tracking: third-party cookies (the traditional mechanism for linking user behavior across different publisher sites to build audience segments) are being deprecated by browsers (Chrome's Privacy Sandbox initiative, Safari's ITP). The replacement mechanisms include: Topics API (browser discloses the user's top 5 interests from the past 3 weeks without identifying the user), Protected Audience API (remarketing without cross-site tracking — the browser holds the audience membership and runs a local auction), and contextual targeting (targeting based on the current page content rather than the user's history — no cross-site tracking required). These changes require the ad server's audience segment pipeline to evolve from cookie-based user tracking to cohort-based and on-device approaches, with significant implications for targeting precision and pCTR model accuracy.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="important">An ads delivery and targeting system requires: (1) ad slot request: publisher sends userId, slotId, pageUrl, geoIp; (2) user segment resolution: Redis GET seg:&#123;userId&#125; under 2ms — bitset over IAB interest categories; (3) OpenRTB BidRequest broadcast to 50 DSPs in parallel, 80ms hard deadline; (4) second-price Vickrey auction: rank by eCPM = bidCpm × pCTR; winner pays 2nd-highest bid + $0.01; floor price check; (5) winning creative served via CDN in sandboxed iframe (no DOM access, no top-level navigation); (6) impression beacon: async Kafka publish after HTTP response — non-blocking; (7) click redirect: dedup Redis SETNX 60s; basic IVT check (sub-second clicks, datacenter IPs); Kafka publish; (8) frequency cap: Redis INCR freq:&#123;userId&#125;:&#123;adId&#125;:&#123;date&#125; — expire at midnight; max 3/day default; (9) conversion attribution: last-click within 7 days; conversion pixel calls /ads/conversion with conversionType and value; (10) IVT detection: pre-bid blocklist, post-bid Flink anomaly, daily ML fraud model — refund credits end-of-cycle; (11) budget pacing: 5-minute pacing controller adjusts throttle rate to smooth spend across 24 hours.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
