"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-creator-monetization-dashboard",
  title: "Design a Creator Monetization Dashboard (like YouTube Studio / Substack)",
  description:
    "Architecture for a creator monetization dashboard: double-entry immutable ledger recording ad revenue, subscriptions, tips, affiliate commissions, and merchandise cuts per creator per content piece, daily batch job closing previous day books with RPM calculation, real-time balance from ledger SUM query cached in Redis 5 minutes, multi-revenue-stream breakdown UI, tax form gating (W-9/W-8BEN) before first payout, idempotent Stripe transfer with payoutId idempotency key, webhook-driven ledger debit on payout confirmation, threshold and minimum balance enforcement, and hold mechanics for fraud review and disputed transactions.",
  category: "high-level-design",
  subcategory: "ads-monetization-systems",
  slug: "creator-monetization-dashboard",
  wordCount: 4800,
  readingTime: 28,
  lastUpdated: "2026-05-14",
  tags: ["hld", "creator-economy", "monetization", "ledger", "stripe", "payout", "youtube", "substack"],
  relatedTopics: ["ads-delivery-targeting-ui", "ads-analytics-dashboard"],
};

export default function CreatorMonetizationDashboardArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="crucial">A creator monetization dashboard gives content creators visibility into how much money they are earning from their content, across multiple revenue streams, and provides a mechanism to withdraw those earnings. The system must handle: (1) revenue attribution — correctly attributing ad impressions and clicks to the specific piece of content that generated them, and computing the creator's share after the platform takes its cut; (2) multiple revenue streams — ad revenue (RPM-based), subscriptions (monthly recurring payments from fans), tips and super chats (one-time payments from fans during live events), affiliate commissions, and merchandise sales — each with different settlement timing and split rules; (3) accurate earnings — creators are financially dependent on these numbers; they must be correct, auditable, and reconciled to the actual payments; (4) payout — creators must be able to withdraw their balance to a bank account or payment service, with appropriate tax compliance (W-9 for US creators, W-8BEN for international).</HighlightBlock>
        <HighlightBlock as="p" tier="important">The foundational design decision is the double-entry ledger: every financial event is recorded as two entries (a credit to the creator's ledger and a debit to the platform's liability account, or vice versa). This ensures the ledger is always balanced and provides a complete audit trail. The ledger is append-only (no updates or deletes) — corrections are made via offsetting entries, not by modifying historical records.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Revenue attribution from multiple streams, ledger design, earnings dashboard, payout flow, tax gating, and idempotent payment processing. Not in scope: subscription billing (how subscribers are charged), the ad auction pipeline (separate article), or content management.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Double-entry immutable ledger:</strong> Every financial event creates one or more ledger entries. Schema: (entryId UUID, createdAt timestamptz, creatorId UUID, contentId UUID optional, entryType ENUM, amount DECIMAL(18,6), currency CHAR(3), direction ENUM credit/debit, referenceId UUID, description text, status ENUM pending/settled/reversed). Entry types: ad_revenue, subscription_revenue, tip_revenue, affiliate_commission, merchandise_commission, platform_fee, payout_debit, reversal, tax_withholding. The creator's available balance = SUM(amount WHERE direction=credit AND status=settled) − SUM(amount WHERE direction=debit AND status!=reversed). Pending entries (ad revenue before the month closes, chargebacks under review) are shown separately from settled entries. The ledger table is INSERT-only at the application level — the database user has INSERT and SELECT privileges but not UPDATE or DELETE. Corrections use reversal entries: if an entry is incorrect, a new entry of the opposite direction with referenceId pointing to the original entry is created.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Ad revenue attribution:</strong> When an ad auction closes on a creator's content, the clearing price (what the advertiser pays) is split: platform takes its share (typically 45–55% of gross revenue), creator receives the remainder. The attribution event: the ad server publishes an ad_revenue event to Kafka with &#123;adId, contentId, creatorId, clearingPriceMicros, currencyCode&#125;. A revenue attribution service consumes this Kafka topic, applies the platform fee rate for the creator's tier (new creators may have a higher platform fee; established creators with &gt;100K subscribers may negotiate lower fees), and INSERTs two ledger entries: a credit entry to the creator's ledger (creatorShare = clearingPrice × (1 − platformFeeRate)) and a debit entry from the platform's liability account. RPM (revenue per mille) = sum(creatorShare) / (totalImpressions / 1000) — computed over a rolling 28-day window and displayed prominently on the dashboard as the primary health metric for ad revenue.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Subscription revenue:</strong> Fans pay a monthly subscription fee to access exclusive content. When a subscription payment succeeds (Stripe webhook: customer.subscription.payment_succeeded), the revenue attribution service records: a credit to the creator's ledger for the creator's share (e.g., 85% of the subscription price after Stripe fees), and a debit from the fan's payment. Subscription revenue is recognized when payment succeeds, not when the subscription period ends (cash accounting for simplicity — accrual accounting would recognize revenue evenly over the subscription period). For annual subscriptions, the creator receives the full annual revenue upfront but the platform may prorate refunds if the fan cancels — this refund is recorded as a reversal entry in the ledger. Subscription revenue is more predictable than ad revenue and is displayed as a separate MRR (monthly recurring revenue) metric on the dashboard.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Payout flow:</strong> Creators request a payout via POST /creator/payout &#123;amount, payoutMethodId&#125;. Pre-payout checks: (1) tax form on file — US creators must have a W-9 on file; international creators need a W-8BEN; if missing, the API returns 403 with a link to complete the tax form; (2) minimum payout threshold — typically $100 (below this, payout is not cost-effective due to wire fees); (3) no hold — the account is not flagged for fraud review or disputed transactions; (4) available balance sufficient — availableBalance &gt;= requestedAmount; (5) verified identity — KYC (Know Your Customer) verification completed for payouts above $1,000/month. If all checks pass, the payout service calls Stripe Transfers API with an idempotency key equal to the internal payoutId (UUID generated and stored before the Stripe call). The Stripe response is awaited synchronously — on success, a payout_debit ledger entry is inserted and the payout record is set to status='processing'. The Stripe webhook payout.paid updates the payout status to 'paid' and confirms the debit.</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Earnings dashboard data model:</strong> The dashboard shows: available balance (settled credits minus debits), pending balance (pending credits not yet settled), MTD (month-to-date) earnings, last month earnings, RPM trend (last 12 months), top-earning content (sorted by creatorShare, last 30 days), revenue stream breakdown (pie chart: ad revenue %, subscription %, tips %, other %), and an earnings timeline (daily earnings bar chart, last 90 days). All of these are derived from the ledger via aggregation queries. The ledger grows at roughly 10,000–100,000 entries per day per active creator (ad impressions generate one entry per ad per content view, but these are batched by content and day in the daily reconciliation job). To avoid slow ledger scans for every dashboard load, a daily materialized summary table (creator_daily_summary) is maintained: one row per (creatorId, date, entryType) with the total amount. Dashboard queries hit this summary table (indexed by creatorId, date) rather than the raw ledger. The summary table is computed by a nightly batch job and also updated incrementally by the revenue attribution service via a Kafka consumer that maintains running totals in Redis (per creatorId, per entryType, per day), flushed to the summary table every hour.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Tax withholding and reporting:</strong> In the US, platforms must withhold 24% backup withholding tax for creators who fail to provide a valid W-9 or whose TIN (Tax Identification Number) is not validated by the IRS. Withholding: when a payout is processed, the tax engine checks the creator's tax status. If withholding is required, the payout amount is reduced by 24% and a tax_withholding debit entry is created in the ledger. The withheld amount is remitted to the IRS in the next quarterly tax payment. Year-end tax reporting: at the end of each calendar year, the platform generates 1099-NEC forms for US creators who earned &gt;$600 (new IRS threshold), and 1042-S forms for international creators with US-source income. These forms are generated by querying the ledger for total settled credits per creator per year, with withholding amounts, and sending them to the IRS via the FIRE (Filing Information Returns Electronically) system. 1099s are also made available in the creator's dashboard for download.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Idempotency and payout safety:</strong> The payout flow involves external payment systems (Stripe) that can fail midway — network timeouts, Stripe outages, or double submissions from the client. Idempotency design: before calling Stripe, the platform records a payout record in its database with status='initiated' and a globally unique payoutId. The Stripe API call uses payoutId as the Stripe idempotency key. If the Stripe call times out and the client retries, the same payoutId is used — Stripe returns the result of the original call without creating a duplicate transfer. If the platform-side database write fails after the Stripe call succeeds, the payout record is incomplete. A reconciliation job (runs hourly) detects discrepancies: payouts that exist in Stripe but not as 'paid' in the platform database — these are resolved by fetching the Stripe payout status and updating the platform record. The double-entry ledger ensures correctness: a payout_debit entry is only INSERTed after the Stripe transfer is confirmed paid (either synchronously from the API response or asynchronously from the webhook). If Stripe confirms the payout but the INSERT fails (database crash), the reconciliation job detects the missing debit entry and inserts it.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Hold mechanics for fraud and disputes:</strong> The platform can place a hold on a creator's account (blocking payouts) in situations: (1) suspected fraudulent activity (unusual spike in subscription revenue, which may indicate payment fraud); (2) copyright strike (content takedown — associated ad revenue is held pending review); (3) chargeback — a subscriber disputes a charge; the subscription revenue is placed on hold until the dispute resolves. Hold implementation: a creator_holds table tracks active holds with (holdId, creatorId, amount, reason, startedAt, expiresAt). The payout service checks for active holds before processing — if holds exist, the held amount is subtracted from the available balance. Holds that expire without resolution are automatically reversed (the held amount is returned to available balance) after a configurable hold period (typically 90 days). When a hold is resolved (copyright dispute dismissed, chargeback won), a reversal entry is INSERTed and the hold record is marked resolved.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The creator monetization system has three planes: the revenue attribution plane (Kafka consumers for ad_revenue, subscription_paid, tip_received events → revenue attribution service → ledger INSERTs → Redis running totals), the dashboard query plane (Analytics API → creator_daily_summary table or Redis cache → dashboard response), and the payout plane (payout API → pre-checks → Stripe Transfer API with idempotency → ledger debit → webhook confirmation). All financial state lives in the immutable ledger (PostgreSQL with INSERT-only access). The Redis cache is a derived read-through cache — if Redis is lost, the system falls back to querying the ledger directly, with higher latency but full correctness.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/ads-monetization-systems/creator-monetization-dashboard.svg"
          alt="Creator monetization dashboard: ad auction clearing price split by platform fee rate creates credit ledger entry for creator share; subscription payment creates subscription_revenue credit; creator views earnings dashboard showing balance MTD earnings RPM trend top content breakdown; payout request checks tax form balance threshold and hold then calls Stripe with payoutId idempotency key; webhook updates ledger debit on payout.paid; double-entry immutable ledger is source of truth."
          caption="Double-entry immutable ledger; RPM = creatorShare / (imps/1000); daily_summary materialized table; Redis 5min balance cache; Stripe idempotency key = payoutId; tax form W-9/W-8BEN gate; hold mechanic for disputes; reconciliation job hourly"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Ledger Query Performance</h3>
        <HighlightBlock as="p" tier="crucial">The raw ledger table grows without bound — a creator with 10 years of history and 10,000 daily entries has 36.5M rows. A balance query (SUM of all credits minus debits) on 36.5M rows takes seconds, which is unacceptable for a dashboard load. Optimization strategies: (1) running balance materialized view — the database maintains a running balance per creator, updated by a trigger on each INSERT. The trigger adds credit amounts and subtracts debit amounts from the creator's running_balance row. Dashboard balance query: SELECT balance FROM creator_balances WHERE creatorId = X — O(1), returns instantly. The running balance is eventually consistent (trigger-based updates are synchronous with the INSERT, so it is actually immediately consistent). (2) Balance snapshot — a monthly batch job computes the exact balance as of the last day of each month and stores it in a balance_snapshots table. The current balance = snapshot balance + incremental SUM since the snapshot date. This limits the incremental SUM scan to at most one month of entries (~300K rows for an active creator). (3) Partitioning — the ledger table is PARTITION BY RANGE (createdAt) with monthly partitions. PostgreSQL constraint exclusion ensures that queries with a date range touch only the relevant partitions, dramatically reducing I/O for month-scoped queries.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Multi-Currency Support</h3>
        <HighlightBlock as="p" tier="important">Creators are global — they earn ad revenue in the currency of the advertiser's market (a Japanese advertiser paying for impressions on a US creator's content pays in JPY; the creator receives USD). Currency conversion: all ledger entries are stored in both the original currency (clearingPriceMicros in JPY) and a platform-standard currency (USD equivalent at the exchange rate at event time). The exchange rate at event time is recorded in the ledger entry (exchangeRate field). The creator's balance is always displayed in the platform currency (USD) with an option to view in local currency. Payout: the creator can elect to receive payouts in USD (cheapest for the platform, avoids daily FX exposure) or local currency (requires the platform to hold FX positions or use a real-time FX service like Wise). For international payouts, the platform uses Stripe's multi-currency payout features: the platform holds a USD balance with Stripe, converts to local currency at spot rate + 1.5% platform FX fee, and initiates the local-currency transfer. The FX fee is recorded as a separate platform_fx_fee debit entry in the ledger.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">Cash vs. accrual accounting for ad revenue: ad revenue is settled on a monthly basis (advertisers pay their monthly invoice; the platform receives payment before distributing to creators). Under cash accounting, creators are credited when the platform actually receives the advertiser's payment. Under accrual accounting, creators are credited when the impression occurs, regardless of when the platform collects. Most creator platforms use accrual accounting for the dashboard (creators see their earned revenue immediately, which is motivating and accurate) but cash basis for tax reporting (simpler for most individual creators). The platform carries a liability equal to the sum of all accrued but not yet paid creator earnings — this liability appears on the platform's balance sheet. If an advertiser defaults (pays only part of their invoice), the platform must decide whether to credit creators for the full accrued amount (absorbing the loss) or claw back the unpaid portion (damaging creator trust). Most established platforms absorb the loss — advertiser credit risk is priced into the platform fee.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Payout timing: daily payouts (available the next business day) are popular with creators who want fast access to earnings but are expensive for the platform (each bank transfer has a fixed cost of $0.25–$2.00 — at $1 per transfer and 10M creators requesting daily payouts, the cost is $10M/day). Weekly or monthly payout cycles dramatically reduce per-transfer cost but frustrate creators with cash flow needs. The industry standard is a monthly payout cycle for ad revenue (matching the advertiser's billing cycle) with instant payout available for a fee (1–1.5% of the withdrawal amount, paid by the creator, using Stripe's Instant Payouts feature which disburses in under 30 minutes via debit card). This gives creators control over their payout timing while keeping platform costs manageable.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A creator monetization dashboard requires: (1) double-entry immutable ledger: INSERT-only, entry types (ad_revenue, subscription_revenue, tip, affiliate, payout_debit, reversal), amount in both source and USD currency; (2) revenue attribution: ad clearing price × (1 − platformFeeRate) → credit entry; RPM = creatorShare / (imps / 1000) over 28 days; (3) subscription revenue: Stripe webhook → credit on payment_succeeded; prorate reversal on cancellation; MRR metric; (4) balance computation: running_balance trigger (O(1)) + monthly snapshot + incremental SUM for accuracy; Redis 5-min cache; (5) daily summary table: nightly batch + hourly Redis flush → O(1) dashboard queries; (6) payout pre-checks: tax form (W-9/W-8BEN), KYC, minimum threshold ($100), no active holds, sufficient balance; (7) Stripe idempotency: INSERT payout record first, Stripe call with payoutId as idempotency key, webhook updates status to paid → ledger debit INSERT; (8) hold mechanics: holds table blocks payout up to held amount; auto-release at expiry or resolution entry; (9) tax compliance: 24% backup withholding on missing TIN; 1099-NEC &gt;$600 US; 1042-S for international; IRS FIRE submission; (10) multi-currency: entry in source currency + USD equivalent at spot rate; FX fee debit entry; Stripe multi-currency payouts.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
