"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-on-device-ai-inference-ui",
  title: "Design an On-Device AI Inference UI",
  description:
    "Architecture for an on-device AI inference UI: model loading and caching strategy (ONNX/TensorFlow.js, IndexedDB model storage, progressive chunk loading), WebGPU vs. WebAssembly execution backends, quantization tradeoffs (INT8/FP16 vs. FP32), streaming token generation with ReadableStream for LLM output, model selection UI (capability vs. size tradeoff), inference progress and cancellation, privacy-by-default architecture (no data leaves the device), memory pressure management (model eviction, tensor cleanup), and graceful degradation to cloud API when on-device inference is too slow.",
  category: "high-level-design",
  subcategory: "emerging-future-systems",
  slug: "on-device-ai-inference-ui",
  wordCount: 5000,
  readingTime: 30,
  lastUpdated: "2026-05-14",
  tags: ["hld", "on-device-ai", "webgpu", "onnx", "llm", "inference", "quantization", "transformers-js"],
  relatedTopics: ["voice-based-ui-system", "ar-vr-interface-system"],
};

export default function OnDeviceAiInferenceUiArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">On-device AI inference runs machine learning models directly in the browser or on the device, without sending data to a cloud server. The primary motivation is privacy: medical records, personal photos, financial documents, and private messages should not be transmitted to a third-party server for AI processing. The secondary motivation is latency and offline capability: inference with zero network round-trip eliminates the 100–500ms cloud API latency and allows the AI feature to work without internet connectivity.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The fundamental constraint is the device's compute budget. A large language model like Llama 3 8B requires ~16GB of GPU memory at FP16 precision — more than most laptops have available for the browser tab, and orders of magnitude beyond mobile devices. On-device AI inference therefore requires aggressive model optimization: quantization (INT8/INT4 reduces memory 4–8×), model distillation (smaller models with similar capabilities), and careful batching to maximize GPU utilization within the available VRAM. The UI must clearly communicate inference progress, estimated wait times, and gracefully degrade to cloud APIs when the device is incapable.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Model loading/caching strategy, WebGPU vs. WASM backends, quantization tradeoffs, streaming token generation, model selection UI, inference cancellation, privacy architecture, memory pressure management, and cloud fallback. Not in scope: model training or fine-tuning in the browser, federated learning, or custom CUDA kernels.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Model loading and IndexedDB caching:</strong> AI models are large binary files (100MB to 8GB). Loading from a CDN on every session would be prohibitively slow and expensive. Models are cached in IndexedDB after the first download. The download flow: (1) check IndexedDB for the model file (by hash of the model URL); (2) if not cached, download from CDN in chunks (fetch with Range header, 10MB chunks) with a progress bar showing download percentage; (3) each chunk is written to IndexedDB as it arrives (streaming write — no need to buffer the entire file in memory); (4) on completion, validate the file hash (SHA-256) against the CDN-provided hash to detect corruption or tampering; (5) on subsequent loads, read from IndexedDB — no network request. Model metadata (name, size, quantization level, supported tasks) is stored separately in a JSON config in localStorage for fast access without loading the full model binary.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Streaming token generation with ReadableStream:</strong> LLM inference generates text token by token. The UI should display tokens as they are generated (streaming output), not wait for the full response to complete. The inference engine (Transformers.js, llama.cpp compiled to WASM, or a custom WebGPU pipeline) exposes a ReadableStream of token strings. The UI reads from the stream using a reader: const reader = stream.getReader(); while(true) &#123; const &#123;done, value&#125; = await reader.read(); if(done) break; appendToken(value); &#125;. Tokens are appended to a &lt;div&gt; using textContent concatenation (not innerHTML — to prevent XSS if the model generates HTML). A blinking cursor is shown after the last token while generation is ongoing, removed on stream close.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Model selection UI with capability vs. size tradeoffs:</strong> The model selection UI presents a matrix of available models: name, size on disk, quantization level, supported tasks (text generation, summarization, image classification, embedding), and a "capability score" (a 1–5 rating of accuracy relative to the largest available model). The user selects a model based on their use case and available storage. A "recommended" badge highlights the best tradeoff for the device's capability (detected via navigator.deviceMemory, navigator.hardwareConcurrency, and a WebGPU adapter query for available VRAM). The model selection persists in localStorage — users don't re-select on every session.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Inference cancellation and progress:</strong> Long inference runs (summarizing a 50-page document) must be cancellable. The inference function accepts an AbortSignal: inference(input, &#123;signal: abortController.signal&#125;). The inference loop checks signal.aborted on each token generation step and throws an AbortError if set. The UI shows a "Cancel" button that calls abortController.abort(). On cancellation, the partial output is shown with a "Cancelled" badge — the user can read what was generated before cancellation. For determinate tasks (classification, embedding), a progress bar shows inference step count / total steps. For generative tasks (LLM), progress is indeterminate (tokens generated so far + tokens/second rate).</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>WebGPU vs. WebAssembly execution backend:</strong> WebGPU is the preferred backend for neural network inference: GPU parallelism reduces inference time by 10–50× compared to CPU-based WASM for matrix multiplication-heavy operations (the core of transformer attention). WebGPU availability: supported in Chrome 113+ and Edge 113+, not yet available in Firefox or Safari (as of 2025, behind flags). Feature detection: if (navigator.gpu) &#123; /* use WebGPU */ &#125; else &#123; /* fall back to WASM */ &#125;. The WASM backend uses SIMD (Single Instruction Multiple Data) instructions (WebAssembly SIMD proposal) for vectorized CPU operations — 4–8× faster than scalar WASM. SIMD availability: navigator.hardwareConcurrency &gt; 1 and WASM feature detection at runtime. The backend selection is automatic based on feature detection, with the WebGPU backend preferred when available.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Quantization tradeoffs (INT8/FP16 vs. FP32):</strong> Model quantization reduces the precision of model weights to use less memory and enable faster computation: FP32 (32-bit float): full precision, largest size, best accuracy. FP16 (16-bit float): half size, ~1% accuracy drop for most models, 2× faster on GPUs with FP16 units (most modern GPUs). INT8 (8-bit integer): quarter size vs. FP32, ~2–5% accuracy drop, ~4× faster on supported hardware. INT4 (4-bit): eighth size, ~5–15% accuracy drop, best for very large models on constrained devices. The model selection UI shows the accuracy tradeoff for each quantization level. The default recommendation: FP16 for devices with dedicated GPU; INT8 for mobile and integrated GPU; INT4 for models &gt;3GB on mobile devices. Quantized models are stored as separate files (not dynamically quantized at runtime, which would be too slow).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Memory pressure management:</strong> Browser tabs have limited memory (typically 2–4GB before the browser OOM-kills the tab). Large models occupy most of this budget, leaving little for application state and rendering. Memory pressure management: (1) load the model lazily (only when the user first requests an AI feature, not on app startup); (2) evict the model from memory when the user navigates to a page that doesn't use AI (unload the inference session, releasing GPU resources); (3) monitor memory pressure via the navigator.deviceMemory API and the PerformanceObserver memory-warning event; (4) if memory pressure is critical, fall back to cloud inference and display a notice: "On-device AI temporarily unavailable due to memory constraints. Using cloud processing." The model file remains in IndexedDB — only the in-memory session is evicted.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Graceful degradation to cloud API:</strong> On-device inference is not available for all users: old devices with no WebGPU, low-RAM devices where models don't fit, or incognito mode (where IndexedDB quota is minimal). The system detects these cases at startup and falls back to a cloud AI API (OpenAI, Anthropic, Google Gemini). The cloud fallback shows a clear UI notice: "AI processing on server — your data will be sent to [provider]." A privacy-sensitive mode (opt-in) skips cloud fallback entirely and disables AI features when on-device inference is unavailable. The API client uses the same interface as the on-device inference engine (same function signatures) — the UI layer is unaware of whether inference is on-device or cloud.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The on-device AI system has three layers: the model management layer (download, cache in IndexedDB, validate, version), the inference engine layer (backend selection WebGPU/WASM, session management, tensor operations), and the application layer (streaming output, cancellation, progress, UI integration). The inference engine runs in a Web Worker to prevent blocking the main thread during intensive computation — a large matrix multiplication can take 50ms, which would freeze the UI if run on the main thread. The Web Worker exposes an inference API via postMessage: the main thread sends the input prompt and receives streaming token events back.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Transformers.js (a port of Hugging Face's transformers library to JavaScript) is the recommended starting point: it provides a high-level API for running ONNX models with automatic WebGPU/WASM backend selection, model caching, and streaming generation. For more control over the inference pipeline (custom quantization, custom attention patterns), ONNX Runtime Web (the official ONNX JavaScript runtime) provides lower-level access to the execution graph.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/emerging-future-systems/on-device-ai-inference-ui.svg"
          alt="On-device AI inference UI: model download from CDN (10MB Range chunks → IndexedDB storage → SHA-256 hash validation); model load from IndexedDB into Web Worker → backend selection (WebGPU if navigator.gpu, else WASM+SIMD fallback); inference session in Web Worker → streaming tokens via postMessage → ReadableStream to UI; AbortController cancellation per token step; FP32/FP16/INT8/INT4 quantization selection in model picker UI; memory pressure monitoring → evict in-memory session on pressure; cloud API fallback (same interface) when on-device unavailable; privacy notice shown for cloud fallback."
          caption="IndexedDB model cache (10MB chunks, SHA-256 validation), Web Worker inference (WebGPU preferred, WASM SIMD fallback), streaming tokens via postMessage ReadableStream, AbortController cancellation, quantization picker (FP32/FP16/INT8/INT4), memory eviction on pressure, cloud API fallback with privacy notice"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">IndexedDB Model Storage and Versioning</h3>
        <HighlightBlock as="p" tier="important">Model files are stored in IndexedDB as ArrayBuffer chunks. The storage schema: one object store for model metadata (modelId, version, hash, downloadedAt, size) and one for binary chunks (key: modelId + chunkIndex, value: ArrayBuffer). On model load, chunks are read in order and concatenated into a single ArrayBuffer before being passed to the inference engine. For very large models (&gt;1GB), the chunks are streamed directly to the ONNX runtime's model loading API (which accepts a ReadableStream) without concatenating the entire file in memory — this prevents OOM during model loading.</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">Model versioning: the model metadata includes a version field. On app startup, the app checks the CDN model registry (a small JSON file listing current model versions) and compares against the cached version. If a new version is available, a non-blocking notification is shown: "Model update available. Download in background?" The update downloads the new model to a staging key in IndexedDB, validates the hash, then swaps the staging key to the active key atomically. The old version is deleted after the swap. This zero-downtime update ensures the user can continue using the current model while the update downloads.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">WebGPU Shader Pipeline for Inference</h3>
        <HighlightBlock as="p" tier="important">WebGPU inference uses compute shaders (WGSL — WebGPU Shading Language) for matrix multiplication (the core of transformer attention). The attention computation for a single token requires: Q = input × W_q, K = input × W_k, V = input × W_v, attention_scores = softmax(Q × K^T / sqrt(d_k)), output = attention_scores × V. Each of these is a matrix multiplication dispatched as a compute shader with workgroup sizes tuned for the GPU's compute unit count. The KV cache (key-value cache for previous tokens in the context) is stored as GPU buffers and reused across token generation steps — this is the key optimization that makes autoregressive generation fast (only the new token's computation needs to run, not the full context each step).</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Privacy Architecture and Data Minimization</h3>
        <HighlightBlock as="p" tier="crucial">The privacy-by-default architecture ensures: (1) no input data (prompts, documents, images) is sent to any server when on-device inference is active; (2) the inference Web Worker has no network access (the worker is created without the cross-origin-isolated flag and with a Content Security Policy that blocks fetch from the worker context); (3) inference telemetry (tokens/second, model size, task type) is collected only as aggregate anonymized metrics, never including the actual input or output content; (4) the privacy notice in the UI clearly distinguishes on-device mode (lock icon) from cloud mode (cloud icon with the provider name). The on-device mode badge is a trust signal — users who care about privacy actively prefer it.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">Model size vs. capability: smaller models (SmolLM 135M, Phi-3 mini 3.8B) run fast on-device but produce lower-quality outputs than large cloud models (GPT-4, Claude Opus). The on-device AI UI should be transparent about this tradeoff: show users a side-by-side comparison of on-device vs. cloud output quality for a representative task, and let them decide. Framing: "On-device: fast, private, good for simple tasks. Cloud: slower, sends data to server, best for complex tasks." Giving users agency over this tradeoff builds trust better than making the decision invisibly.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Cold start latency: loading a 500MB model from IndexedDB into GPU memory takes 2–5 seconds. This is acceptable if the user has explicitly requested an AI feature (they expect to wait). It is unacceptable if the AI feature is triggered automatically on page load. The model should be loaded lazily, on first user request, with a clear loading indicator. Model warmup (running a short dummy inference after loading) primes the GPU's compiled shader cache, reducing the first real inference latency from 500ms to &lt;100ms. Warmup should run in the background after load, not blocking the first user request.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">An on-device AI inference UI requires: (1) IndexedDB model cache (10MB Range chunks, SHA-256 validation, streaming chunk write, zero-downtime version swap); (2) Web Worker inference (isolates compute from main thread, postMessage streaming token events); (3) backend selection (WebGPU preferred via navigator.gpu, WASM SIMD fallback, automatic selection); (4) quantization picker UI (FP32/FP16/INT8/INT4, accuracy vs. size tradeoffs, device-appropriate default recommendation); (5) streaming token generation (ReadableStream reader, textContent append, blinking cursor, tokens/second rate display); (6) AbortController cancellation (checked per token step, partial output preserved with "Cancelled" badge); (7) memory pressure management (lazy model load, evict in-memory session on pressure, PerformanceObserver memory-warning, IndexedDB retained); (8) cloud API fallback (same function interface, privacy notice with provider name, privacy-sensitive mode opt-out); (9) WebGPU KV cache (GPU buffers reused across token steps, only new token computed); and (10) privacy architecture (no network in inference worker, no PII in telemetry, on-device lock badge vs. cloud icon). The governing tradeoff: on-device inference trades model capability for privacy and offline capability — be transparent about this tradeoff in the UI rather than hiding it.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
