"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-voice-based-ui-system",
  title: "Design a Voice-Based UI System",
  description:
    "Architecture for a voice-based UI system: wake word detection running on-device for privacy (Porcupine/Picovoice), streaming speech-to-text pipeline (WebSpeech API vs. Whisper streaming API), intent classification and slot filling for command parsing, text-to-speech response with prosody and SSML markup, conversation state machine for multi-turn dialogue, voice activity detection (VAD) with noise cancellation, voice persona management, accessibility compliance for deaf/hard-of-hearing users, and latency budget breakdown for sub-500ms response time.",
  category: "high-level-design",
  subcategory: "emerging-future-systems",
  slug: "voice-based-ui-system",
  wordCount: 5000,
  readingTime: 30,
  lastUpdated: "2026-05-14",
  tags: ["hld", "voice-ui", "speech-to-text", "wake-word", "intent-classification", "tts", "vad", "conversation-state"],
  relatedTopics: ["ar-vr-interface-system", "on-device-ai-inference-ui"],
};

export default function VoiceBasedUiSystemArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A voice-based UI system replaces or augments traditional touch/mouse interaction with spoken commands. The core challenge is the latency-accuracy tradeoff: users expect a response within 500ms of finishing speaking (the natural conversational pause), but high-accuracy speech recognition (especially for domain-specific vocabulary) requires either a large model that runs slowly on-device or a round-trip to a cloud API. The system must deliver accurate intent recognition within the latency budget.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Privacy is a secondary constraint: a system that continuously records audio and sends it to a cloud server is unacceptable for many use cases (healthcare, legal, enterprise). Wake word detection must run entirely on-device, streaming to the cloud only after the wake word is detected. The system must also be designed for accessibility: users who prefer voice interaction may rely on it exclusively (motor disabilities making touch difficult), so the voice UI must provide complete coverage of all app functionality, not just a subset of popular features.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Wake word detection, streaming STT pipeline, intent classification and slot filling, TTS response, conversation state machine, VAD, and accessibility compliance. Not in scope: voice biometric authentication, real-time translation, or telephony (PSTN) integration.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Wake word detection (on-device):</strong> The system continuously listens for a configured wake word ("Hey App", "OK Assistant") using an on-device keyword spotting model. The model runs on the audio input stream at very low CPU cost (&lt;5% CPU, &lt;1MB memory) using a compressed neural network (depthwise separable CNN or RNN-T quantized to INT8). Popular implementations: Porcupine (Picovoice), OpenWakeWord. The wake word model runs entirely locally — no audio is sent to any server until the wake word is detected. On detection, the system emits a wake event, plays a chime (audio feedback), and opens the microphone for command capture. False positive rate target: &lt;1 per hour of passive listening.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Streaming speech-to-text pipeline:</strong> After wake word detection, the audio stream is processed for speech recognition. Two options based on latency/accuracy tradeoffs: (1) WebSpeech API (SpeechRecognition): browser-native, zero setup, but offloads processing to the browser vendor's servers (Google in Chrome, Apple in Safari) — latency ~200ms, no control over the model; (2) Whisper streaming API: open-source Whisper model served as a WebSocket streaming endpoint — audio chunks (100ms frames) are sent as the user speaks, partial transcriptions are returned in real-time, final transcription is emitted on voice activity end. Whisper is preferred for domain-specific vocabulary (medical, legal, code) where the generic WebSpeech model performs poorly. The audio stream is encoded as 16-bit PCM mono at 16kHz before transmission.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Intent classification and slot filling:</strong> The transcribed text is parsed into an intent (what the user wants to do) and slots (the parameters of the action). Example: "Set a timer for 5 minutes" → intent: SET_TIMER, slots: &#123;duration: "5 minutes"&#125;. The classification runs a two-stage pipeline: (1) intent detection — a fine-tuned BERT-tiny model (or GPT-4o via API for complex intents) classifies the transcription into one of the registered intent classes; (2) slot extraction — named entity recognition (NER) extracts structured slots from the transcription. For simple command grammars, a rule-based parser (regex + keyword matching) is faster and more predictable than a neural model. The intent + slots are passed to the action dispatcher, which calls the appropriate app function.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Text-to-speech response with SSML:</strong> The system's spoken responses are generated by a TTS engine. The response text includes SSML (Speech Synthesis Markup Language) markup for prosody control: &lt;speak&gt;&lt;prosody rate="fast"&gt;Timer set for 5 minutes.&lt;/prosody&gt;&lt;break time="500ms"/&gt;&lt;emphasis level="strong"&gt;Starting now.&lt;/emphasis&gt;&lt;/speak&gt;. Browser-native TTS: Web Speech API SpeechSynthesis — no latency, but robotic voice quality and no SSML support in most browsers. Cloud TTS: ElevenLabs, Google TTS, or Azure Neural TTS — high-quality neural voices, full SSML, 100–300ms latency to first audio chunk. The audio is streamed (not buffered to completion) using AudioContext decodeAudioData on arriving chunks for minimal TTFA (time to first audio).</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Voice activity detection (VAD) and noise cancellation:</strong> VAD determines when the user has finished speaking (end of utterance detection). Simple energy-based VAD: if the audio RMS energy falls below a threshold for &gt;800ms, the utterance is considered complete. Neural VAD (Silero VAD): a small neural model (&lt;1MB) classifies 30ms audio frames as speech or silence, with much better performance in noisy environments. The end-of-utterance is declared when 5 consecutive frames (150ms) are classified as silence. Noise cancellation preprocessing: apply a noise suppression filter (RNNoise, a 100KB neural noise suppressor) to the audio stream before sending to the STT pipeline — this significantly improves STT accuracy in environments with background music, HVAC noise, or crowd noise.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Multi-turn conversation state machine:</strong> Some commands require multiple exchanges: "Book a flight" → "Where to?" → "New York" → "When?" → "Next Friday" → "Confirming: NYC flight next Friday. Confirm or cancel?" The conversation state machine manages this: states are (Idle, Listening, Processing, Speaking, AwaitingSlot). Transitions: Idle → Listening on wake word; Listening → Processing on utterance end; Processing → Speaking when TTS starts; Speaking → AwaitingSlot if the response asks a follow-up question (NLU detects a question in the response); AwaitingSlot → Listening after TTS ends (automatically reopen mic for the follow-up answer). The conversation context is a stack of &#123;intent, filledSlots&#125; — maintained across turns to allow slot accumulation and correction ("No, I said Monday, not Friday").</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Latency budget for sub-500ms response:</strong> The 500ms total latency budget (from end of user utterance to first audio byte of response) is allocated: VAD end detection 150ms + STT final transcription 150ms + intent classification 50ms + action dispatch &amp; response generation 50ms + TTS first chunk 100ms = 500ms total. The critical path: STT is the largest budget item. To minimize STT latency, streaming partial results are shown as visual text on screen during recognition (the user sees their words appear as they speak), so the final result is already partially displayed before the TTS starts playing. The visual transcript also serves as a fallback for users in noisy environments where audio playback isn't useful.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Accessibility for deaf and hard-of-hearing users:</strong> Voice input is designed as an enhancement, not a replacement for touch. Every voice command has an equivalent touch/keyboard path. Visual captions: all spoken responses are simultaneously displayed as text (closed captions). For deaf users, the system operates in "voice input, visual output" mode: they speak commands, read responses — no audio output required. For non-speaking users with motor disabilities, the system supports switch access (scanning through available voice commands shown on screen, selecting with a switch device). The wake word can be replaced with a button tap for users who cannot speak consistently.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The voice pipeline has four stages in the audio processing chain: (1) Wake word detector (always on, on-device): raw audio → 16kHz PCM → compressed CNN model → wake event; (2) STT pipeline (on wake): audio stream → RNNoise noise suppression → VAD framing → WebSocket streaming to Whisper server (or local WebSpeech) → partial + final transcripts; (3) NLU (on final transcript): text → intent classifier + slot extractor → &#123;intent, slots&#125; → action dispatcher; (4) TTS (on action result): response text with SSML → cloud TTS API → streaming audio chunks → AudioContext playback + simultaneous caption display.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The conversation state machine runs client-side (no server state required for single-user conversations). Multi-device conversations (the user starts on phone, continues on laptop) require a server-side session store with the conversation context serialized to Redis (keyed by userId, TTL 5 minutes of inactivity). The action dispatcher is a registered function table: intent names map to handler functions that execute app logic and return a response string. This makes the voice system an overlay on the existing app logic — voice is a new input modality, not a separate code path.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/emerging-future-systems/voice-based-ui-system.svg"
          alt="Voice-based UI system: always-on on-device wake word detection (Porcupine CNN, &lt;5% CPU, no audio sent to server); on-wake: RNNoise noise suppression + Silero VAD + Whisper streaming WebSocket STT (100ms frames, partial results displayed); Whisper final transcript → BERT-tiny intent classifier + NER slot extractor; action dispatcher calls app function; response text + SSML → cloud TTS streaming → AudioContext + closed captions; conversation state machine (Idle→Listening→Processing→Speaking→AwaitingSlot); latency budget: 150ms VAD + 150ms STT + 50ms NLU + 50ms dispatch + 100ms TTS = 500ms total."
          caption="Wake word on-device (Porcupine, &lt;5% CPU), RNNoise + Silero VAD, Whisper streaming STT (100ms frames), BERT-tiny intent + NER slots, SSML TTS streaming (AudioContext), conversation state machine, 500ms total latency budget"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Wake Word Model and Privacy</h3>
        <HighlightBlock as="p" tier="important">The wake word model processes the microphone stream continuously using the AudioWorklet API (runs in a dedicated audio thread, not the main thread, preventing UI jank from audio processing). The AudioWorklet receives 128-sample frames from the Web Audio API (at 44.1kHz default, downsampled to 16kHz for the model). The keyword spotting model runs inference on each 10ms frame using WebAssembly (WASM) — the model is compiled from C/C++ to WASM for near-native performance in the browser. The model output is a confidence score for the wake word; a threshold of 0.85 is used to declare detection, balancing false positive and false negative rates.</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">Privacy assurance: the wake word WASM model and all audio processing before wake word detection run entirely in the browser. The microphone stream bytes never leave the device before wake word detection. After the wake event, the user is clearly informed that audio is being sent to the server (a visual indicator: a pulsing microphone icon with "Listening..." text). The STT session ends on utterance completion — audio is not retained by the server after transcription.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Partial Results and Speculative Execution</h3>
        <HighlightBlock as="p" tier="important">Whisper streaming returns partial transcripts as the user speaks. The system uses partial results for speculative execution: if a partial transcript already unambiguously identifies an intent and has all required slots ("set timer 5"), the system begins intent processing immediately — before the user has finished speaking or the final transcript has arrived. The action execution is gated behind a confidence threshold: if the partial result's intent classification confidence is &gt;0.95, dispatch the action; otherwise wait for the final transcript. Speculative results that turn out to be wrong (the partial was "timer 5" but the final is "timer 5 minutes repeat") are corrected by re-running intent classification on the final transcript and undoing any optimistic UI changes.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Voice Persona and SSML Design</h3>
        <HighlightBlock as="p" tier="crucial">The voice persona is the personality of the voice assistant — its name, speaking style, and response patterns. Response design principles: (1) brevity — voice responses should be &lt;2 sentences for most commands (users don't want to listen to long explanations); (2) confirmation — for irreversible actions (deleting a file, sending a payment), always repeat the key details: "Sending $50 to John. Say confirm or cancel."; (3) progressive disclosure — offer more detail on request: "Timer set. Say more info for details."; (4) error recovery — when intent is unclear, ask for the most important missing slot rather than restarting: "I can set a timer — for how long?". SSML prosody is used to convey urgency (faster rate for errors), warmth (slightly slower, higher pitch for confirmations), and questions (rising intonation for follow-up questions).</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="crucial">On-device STT vs. cloud STT: on-device STT (running Whisper locally via WASM or WebGPU) eliminates the cloud round-trip latency and the privacy concern of sending audio to a server, but requires significant device resources (Whisper small.en is ~500MB, runs at ~10× real-time on a modern laptop but only ~2× on a mobile device — too slow for real-time streaming). The practical split: use on-device STT for privacy-sensitive applications (healthcare, legal) running on laptops; use cloud STT for consumer mobile apps where latency and model size are prohibitive constraints. As on-device ML hardware (Apple Neural Engine, Qualcomm Hexagon) becomes more powerful, the crossover point shifts toward on-device.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Grammar-based vs. neural NLU: for a small, well-defined command set (&lt;50 intents), a grammar-based parser (regex + keyword matching, compiled to a deterministic finite automaton) is more predictable, debuggable, and faster than a neural NLU model. It doesn't hallucinate intents, and the developer has full control over what is and isn't recognized. Neural NLU (BERT, GPT) is necessary for open-ended commands where the vocabulary is unbounded ("Write an email to John saying I'll be late") — but this crosses into AI assistant territory (a different design problem). For a command-based voice UI, start with grammar-based parsing and add neural NLU for the subset of intents that require natural language understanding.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A voice-based UI system requires: (1) wake word detection (on-device WASM model, AudioWorklet audio thread, 16kHz PCM, confidence &gt;0.85, &lt;5% CPU, no audio sent before wake); (2) streaming STT (WebSocket Whisper, 100ms frames, partial results displayed real-time, RNNoise noise suppression, Silero VAD 150ms silence for end-of-utterance); (3) intent classification + slot filling (BERT-tiny intent classifier, NER slot extractor; grammar-based for &lt;50 intents, neural for open-ended commands); (4) speculative execution (dispatch on partial &gt;0.95 confidence, undo on final transcript mismatch); (5) SSML TTS (cloud neural TTS, streaming AudioContext, TTFA target &lt;100ms, simultaneous caption display); (6) conversation state machine (Idle→Listening→Processing→Speaking→AwaitingSlot, context stack for multi-turn slot accumulation); (7) 500ms latency budget (150ms VAD + 150ms STT + 50ms NLU + 50ms dispatch + 100ms TTS); and (8) accessibility (every command has touch equivalent, closed captions for all TTS output, switch access for non-speaking users, wake-word-less mode). The governing principle: voice is an input modality, not a product — every voice command must have a non-voice alternative, and the voice system must degrade gracefully when audio is unavailable or the user is in a quiet environment.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
