"use client";
import { useMemo, useState } from "react";
const rows = Array.from({ length: 24 }, (_, index) => ({ id: index + 1, title: `Article ${index + 1}` }));
export function FeedNavigationClient() {
  const [mode, setMode] = useState<'pagination'|'infinite'>('pagination');
  const [page, setPage] = useState(1);
  const [savedPosition, setSavedPosition] = useState("No saved position");
  const visible = useMemo(() => mode === 'pagination' ? rows.slice((page - 1) * 6, page * 6) : rows.slice(0, page * 6), [mode, page]);
  return <main className="mx-auto min-h-screen max-w-5xl p-8"><section className="rounded-3xl border border-slate-800 bg-slate-950/70 p-6"><p className="text-sm uppercase tracking-[0.25em] text-amber-300">Infinite scroll vs pagination</p><h1 className="mt-2 text-3xl font-semibold">Feed navigation lab</h1><div className="mt-6 flex flex-wrap gap-3"><button className={`rounded-2xl px-4 py-3 ${mode==='pagination'?'bg-amber-400 text-slate-950':'border border-slate-700'}`} onClick={()=>{setMode('pagination');setPage(1);}}>Pagination</button><button className={`rounded-2xl px-4 py-3 ${mode==='infinite'?'bg-amber-400 text-slate-950':'border border-slate-700'}`} onClick={()=>{setMode('infinite');setPage(1);}}>Infinite scroll</button><button className="rounded-2xl border border-slate-700 px-4 py-3" onClick={() => setSavedPosition(`${mode} · page ${page}`)}>Save position</button></div><div className="mt-6 grid gap-4 lg:grid-cols-[1.1fr_0.9fr]"><div className="space-y-3">{visible.map((item)=><article key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4">{item.title}</article>)}<div className="flex gap-3"><button className="rounded-2xl border border-slate-700 px-4 py-3" onClick={()=>setPage((p)=>Math.max(1,p-1))}>Previous</button><button className="rounded-2xl bg-amber-400 px-4 py-3 font-medium text-slate-950" onClick={()=>setPage((p)=>p+1)}>{mode==='pagination'?'Next page':'Load more'}</button></div></div><aside className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><h2 className="text-lg font-medium">UX tradeoff</h2><p className="mt-3 text-sm text-slate-300">{mode === 'pagination' ? 'Easier resumption, clear location, and sharable positions.' : 'Faster grazing, but weaker resumption and footer reachability.'}</p><p className="mt-3 text-sm text-slate-400">Saved position: {savedPosition}</p></aside></div></section></main>;
}
