"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-lld-component-library-system",
  title: "Design a Component Library System",
  description:
    "Production-grade component library with design tokens, theming, semantic versioning, visual regression testing, and governance at scale.",
  category: "low-level-design",
  subcategory: "architecture-system-level-lld",
  slug: "component-library-system",
  wordCount: 5600,
  readingTime: 34,
  lastUpdated: "2026-05-10",
  tags: [
    "lld",
    "component-library",
    "design-tokens",
    "theming",
    "versioning",
  ],
  relatedTopics: [
    "multi-tenant-ui",
    "settings-page-system",
  ],
};

export default function ComponentLibrarySystemArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <p>A component library is the engineering artifact that gives a design system its teeth. A design system is a set of agreements—colors, spacing rules, interaction patterns, accessibility standards—but a component library is the implementation of those agreements in code. Without a shared library, each product team independently implements the same Button, the same Modal, the same Form input, diverging slightly each time. After 18 months and 12 teams, the organization has 12 slightly different button implementations, 12 different color palettes, and no mechanism to ship a cross-product security fix or accessibility improvement without touching all 12 codebases separately.</p>
        <p>The problem is not purely technical—it is organizational. A component library is a shared dependency of many teams, which means its API stability, release cadence, migration burden, and documentation quality directly affect the productivity of every team that consumes it. A library with excellent components but poor documentation will not be adopted. A library with frequent breaking changes will be pinned to old versions across the organization. A library with no governance model will accumulate one-off escape hatches until it becomes inconsistent in the ways it was supposed to prevent.</p>
        <p><strong>Explicit assumptions:</strong> The library targets React applications across a medium-to-large organization (5–50 product teams, hundreds of engineers). The library is distributed as an npm package to an internal registry (not public npm). Multiple product themes (brands, dark mode) must be supported without shipping separate packages per theme—theme switching is a runtime concern handled via CSS custom properties. The library is maintained by a dedicated platform team of 3–6 engineers, with contributions accepted from product teams via a formal RFC and PR process. Semantic versioning is strictly enforced; breaking changes require major version bumps and migration guides.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibuild">Functional Requirements</h3>
        <ul className="space-y-2">
          <li><strong>Design token system:</strong> Centralized color, spacing, typography, shadow, and border-radius tokens, generated as CSS custom properties and as typed JavaScript constants. Tokens are the single source of truth for all visual decisions.</li>
          <li><strong>Component taxonomy:</strong> Primitive components (Button, Input, Text, Icon), Composite components (SearchInput = Input + Icon, Select, DatePicker), Layout components (Grid, Stack, Divider), and Page Templates (AuthLayout, DashboardLayout). Each layer builds on the one below.</li>
          <li><strong>Multi-theme support:</strong> Light theme, dark theme, and per-brand theme overrides applied at runtime via CSS custom property reassignment, without page reload and without shipping a separate CSS bundle per theme.</li>
          <li><strong>Documentation site:</strong> Storybook deployment showing every component in every variant and state, with live controls (Storybook Controls addon), copy-paste usage examples, prop tables auto-generated from TypeScript types, and accessibility annotations.</li>
          <li><strong>Semantic versioning with changelogs:</strong> Automated changelog generation from conventional commit messages. Major versions require a documented migration guide and a codemod where feasible.</li>
          <li><strong>Accessibility compliance:</strong> Every component meets WCAG 2.1 AA. axe-core integration in CI fails the build on accessibility violations. Focus management, keyboard navigation, and ARIA patterns are part of the component contract, not add-ons.</li>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <li><strong>Tree-shakeability:</strong> Consuming applications pay bundle cost only for the components they import. An app importing only Button should not pull in the entire library.</li>
          <li><strong>TypeScript-first:</strong> All components export complete TypeScript types. Consuming TypeScript projects get full IntelliSense, prop validation, and no need for @types packages.</li>
          <li><strong>SSR compatibility:</strong> All components render correctly in server-side rendering and static generation environments (Next.js, Remix). No window or document access in render paths.</li>
          <li><strong>Performance:</strong> Component render performance is benchmarked. No component should contribute more than 1ms to initial render in isolation benchmarks. Bundle size is tracked per release (size-limit in CI).</li>
          <li><strong>Version support window:</strong> The platform team maintains the current major version and the previous major version (N and N-1). Teams on N-2 receive no new fixes.</li>
        </ul>
      </section>

      <section>
        <h2>High-Level Approach</h2>
        <p>The library is organized as a monorepo with separate packages for tokens, core components, icons, and utilities. The tokens package is the foundation: it defines the design vocabulary in a platform-agnostic format (a JSON token file) and uses Style Dictionary to generate CSS custom properties, TypeScript constants, and (optionally) Figma Variables. The core components package imports the tokens package and uses CSS custom properties for all visual styling, making theme switching a matter of reassigning custom properties on a root element.</p>
        <p>Components are built with React and TypeScript, styled using CSS Modules (scoped, no runtime CSS-in-JS dependency), and compiled with tsup to produce both ESM and CJS outputs with tree-shakeable entry points per component. The Storybook documentation site is deployed to an internal CDN on every merge to main, always reflecting the current development state. Releases are cut via the changesets workflow: developers add changeset files describing their changes (patch/minor/major), and the release CI bot assembles a versioned release PR that auto-merges and publishes to the internal npm registry on approval.</p>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/low-level-design/architecture-system-level-lld/component-library-system.svg"
          alt="Component library system architecture showing design token layer (color/spacing/typography tokens with Style Dictionary generating CSS variables and JS constants), component taxonomy (Primitives/Composite/Layout/Templates with TypeScript contracts), versioning and release pipeline (changesets, semantic versioning, codemod generation), testing pipeline (unit/visual regression/accessibility), and governance model (RFC process, contribution guidelines, adoption metrics)"
          caption="Component library architecture: design tokens as the foundation, component taxonomy building on tokens, changesets-driven release pipeline, multi-layer testing, and RFC-based governance"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

	        <h3 className="mt-6 mb-3 text-lg font-semibuild">Design Token Architecture</h3>
	        <p>Design tokens are the lowest level of the system: named values that encode design decisions. They are organized in three tiers. Global tokens are raw values with no semantic meaning: color-blue-500 = #3B82F6, spacing-4 = 16px. Semantic tokens map global tokens to their purpose: color-action-primary = color-blue-500, spacing-component-padding-md = spacing-4. Component tokens map semantic tokens to specific component slots: button-background-primary = color-action-primary, button-padding-horizontal-md = spacing-component-padding-md. This three-tier structure allows the design team to change the primary action color across the entire system by updating one semantic token, without touching any component token or component implementation.</p>
	        <p>Tokens are defined in a platform-agnostic JSON format and processed by Style Dictionary at build time. Style Dictionary generates CSS custom properties (--color-action-primary: #3B82F6) for runtime theming, TypeScript constants (export const COLOR_ACTION_PRIMARY = 'var(--color-action-primary)') for type-safe usage, and JSON exports for Figma Variables synchronization. The separation between definition (JSON) and output (CSS/JS) means new output formats (Android XML, iOS Swift colors) can be added without changing the token definitions.</p>
	        <p>Themes are implemented as CSS custom property overrides scoped to a class or data attribute. The base theme defines custom properties at the root, and a dark theme overrides only the subset of properties that change. Applying a theme at runtime is as simple as setting an attribute on the document root and letting CSS selectors switch which token values are active. Multi-brand themes follow the same pattern: a brand theme overrides semantic tokens such as primary color, font family, and border radius without changing global token values, allowing the same component implementations to serve multiple brands without branching component logic.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Component Taxonomy and API Contracts</h3>
        <p>The component taxonomy divides components into four layers by abstraction level. Primitives are the atoms: Button, Input, Text, Icon, Checkbox, Radio, Switch. They accept a small, focused set of props, render a single HTML element or a tightly coupled group, and have no knowledge of the application domain. Composite components are molecules: SearchInput (Input + Icon), Select (built on combobox patterns), DatePicker, Autocomplete. They compose Primitives and add behavior, but remain domain-agnostic. Layout components handle spatial relationships: Grid, Stack (vertical/horizontal flex container with gap), Divider, Spacer. Page Templates are the highest abstraction: AuthLayout, DashboardLayout, ModalLayout. They define the macro structure of a page or overlay and accept content via children or named slots.</p>
        <p>Every component's prop interface is designed with three principles. First, progressive disclosure: the minimum props required to render are few and obvious; advanced props for customization are secondary. A Button requires only children and onClick; variant, size, loading, leftIcon, rightIcon, and asChild are secondary props that enhance without complicating the common case. Second, escape hatches are explicit: every component accepts a className prop and a ref via React.forwardRef, allowing consumers to add styles or access the DOM node without forking the component. Third, polymorphism via asChild (Radix UI's convention): a Button with asChild renders its children as the root element, enabling Link-styled-as-Button without prop-drilling or wrapper elements. The component renders whatever element the consumer passes as children, while applying all of Button's styles and behavior.</p>
        <p>TypeScript prop types are exported alongside the component. Discriminated unions encode variants correctly: a Button's variant prop is typed as 'primary' | 'secondary' | 'tertiary' | 'destructive', not string, so TypeScript catches typos and IDEs offer autocomplete. Required versus optional props are differentiated by TypeScript optionality, not just documentation. Props with strong conventions (like aria-label being required when no visible text is present) are enforced at the type level using conditional types or overloads rather than runtime warnings alone.</p>

	        <h3 className="mt-6 mb-3 text-lg font-semibuild">Build Pipeline and Tree-Shakeable Distribution</h3>
	        <p>The build pipeline uses tsup (a zero-config esbuild wrapper designed for libraries) to produce three outputs per component package: ESM (for bundlers that understand import and export and can tree-shake), CJS (for environments that require CommonJS), and TypeScript declaration files. The entry point strategy is critical for tree shaking: instead of a single index module that re-exports everything, the package exports map routes each component to its own entry point. This allows bundlers to statically analyze which components are imported and exclude the rest. An application that imports only a single component from the library will not pull in unrelated components like date pickers or selects.</p>
        <p>CSS is handled per-component using CSS Modules, which are processed and injected via tsup's CSS support. Each component's CSS file references CSS custom properties (var(--button-background-primary)) rather than hardcoded values, making theming possible without rebuilding or shipping multiple CSS bundles. The compiled CSS for each component is a small file that can be imported alongside the component's JavaScript. At bundle time, CSS bundlers (like Next.js's built-in CSS handling) deduplicate and merge these small files into a single output, so the consumer does not end up with hundreds of separate CSS files at runtime.</p>
        <p>Size-limit runs in CI on every pull request and reports the gzipped bundle size of each component and the total library. Any PR that increases a component's bundle size beyond a configured threshold requires explicit review and justification. This prevents the gradual "bundle bloat creep" where small additions accumulate into significant size increases without anyone making a deliberate decision to accept the trade-off.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Semantic Versioning with Changesets</h3>
        <p>The changesets workflow (from the @changesets/cli package) enforces the discipline of tracking version bumps alongside the code changes that necessitate them. When an engineer submits a PR, the CI bot checks whether a changeset file has been included. A changeset file describes the change in human-readable terms and declares whether it is a patch, minor, or major change across the affected packages. If no changeset is present and the PR modifies component source or tokens, CI fails with a clear message: "This PR modifies library source but does not include a changeset. Run 'pnpm changeset' to describe your change."</p>
        <p>On merge to main, the changesets GitHub Action opens or updates a "Version Packages" PR that accumulates all pending changeset files into a single proposed release. This PR shows the aggregated changelog (all changeset descriptions combined and grouped by package), the proposed new version numbers, and a diff of the generated CHANGELOG.md files. When the platform team is ready to ship a release, they merge this PR. The GitHub Action then publishes the updated packages to the internal npm registry and creates a Git tag for each release. This approach decouples the decision of when to release from the decision of what changed and how significant each change is—engineers declare significance when they write the code, not at release time.</p>
        <p>Breaking changes require additional steps beyond a major version bump. The PR that introduces a breaking change must include not only a changeset with type:major but also a migration guide document in the library's docs site describing what changed, why it changed, and how consumers should update. Where the migration is mechanical (a prop renamed, an import path changed), the PR must also include a codemod—a jscodeshift transform or an AST-based script—that consumers can run to migrate their codebase automatically. Codemods are tested against realistic sample codebases in the library's test suite. This investment in automated migration is what separates a library teams trust from one they pin at a safe version indefinitely.</p>

	        <h3 className="mt-6 mb-3 text-lg font-semibuild">Testing Strategy</h3>
	        <p>Unit tests verify component behavior: that buttons fire onClick when clicked and not when disabled, that inputs are focusable and emit change events correctly, and that modals trap focus and restore focus on close. Tests focus on behavior from the user's perspective (what a screen reader and keyboard user can do) rather than implementation details (which internal state variables the component uses). The general principle is to query the rendered output using accessible roles and names rather than relying on CSS selectors, which keeps tests aligned with accessibility and makes them more resilient to refactors.</p>
        <p>Visual regression testing (Chromatic) captures screenshots of every Storybook story at every commit and compares them against a baseline. Any pixel-level difference triggers a review step: a team member must explicitly accept the change as intentional or reject it as a regression. Visual regression testing catches an entire class of bugs that unit tests miss: a CSS specificity conflict that changes button padding, a font loading change that shifts text layout, a dark mode token that was updated but one component was missed. Chromatic integrates directly with GitHub, showing visual diffs inline in PR review.</p>
        <p>Accessibility testing runs at two levels. Automated axe-core checks run against every Storybook story in CI, catching WCAG violations like missing label associations, insufficient color contrast, and missing ARIA attributes. Automated testing catches roughly 30–40% of WCAG issues; the remainder require human judgment. For complex interaction patterns (focus traps, live regions, carousel navigation), the library includes written manual test scripts that the platform team executes before each major release. New complex components require a sign-off from an accessibility specialist before merging.</p>
        <p>Integration testing runs the library against realistic consumer app setups: a Next.js app, a Create React App setup, and a Vite-based app. These tests verify that the package installs correctly, imports work as expected, SSR renders without errors, and tree shaking is functioning (bundle size does not regress). This catches distribution issues that unit tests miss: a missing file in the package.json exports map, a CJS/ESM interop problem, or an SSR-incompatible import path.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Documentation and Developer Experience</h3>
        <p>Storybook serves two audiences simultaneously: the component showcase for design review and the API reference for engineers. Each component has a Default story (the simplest usage), Variants stories (one per visual variant), States stories (disabled, loading, error), and a Kitchen Sink story showing all combinations on one page. The Controls addon generates a live prop editor from the component's TypeScript types, so designers can adjust variants and states interactively without writing code. The Docs tab for each component auto-generates a prop table from TypeScript types (via the @storybook/addon-docs autodocs feature) and shows the rendered output alongside the usage code.</p>
        <p>The documentation site is deployed to an internal CDN (accessible to all engineers in the organization) with a domain like design-system.acme.internal. It is automatically updated on every merge to main. The site includes: the Storybook component showcase, the design token reference (all tokens with their values and visual examples), migration guides indexed by version, the contribution guide, and the RFC index. Search is implemented across all of these via a pre-built search index (Algolia or a simpler offline solution using Lunr.js), because engineers will not discover the "right" way to do something if they have to navigate manually to find it.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibuild">Governance and Contribution Model</h3>
        <p>A component library without a governance model inevitably accumulates escape hatches. One team needs a slightly different button variant, so they add a new prop. Another team needs a one-off layout, so they add a new Layout component. After two years, the library has 47 button props, 23 layout components, and no coherent design philosophy. The governance model is the guardrail that prevents this.</p>
        <p>New components and new props on existing components require an RFC (Request for Comments) before implementation. The RFC template asks: what problem does this solve, what alternative solutions were considered, what is the proposed API, and which teams have expressed a need for this? RFCs are opened as GitHub issues labeled "RFC" and have a two-week comment period. The platform team synthesizes feedback and makes a decision: accept, reject, or request modifications. Accepted RFCs enter the backlog; the proposing team is welcomed to implement the component with platform team guidance. This RFC process is not bureaucracy for its own sake—it is the mechanism by which the platform team maintains awareness of all proposed additions, ensures that one team's urgent need doesn't become another team's breaking change, and builds shared ownership of the library's direction.</p>
        <p>Adoption metrics are tracked to inform governance decisions. The platform team monitors (via internal npm registry telemetry) which packages and versions are in active use across the organization, how quickly teams upgrade to new major versions, and which components are most and least used. A component that has zero production consumers after one year is a candidate for deprecation. A major version that 80% of teams have not upgraded to after six months indicates the migration burden is too high and the team should investigate codemods or extended support. These metrics make the governance model data-driven rather than opinion-driven.</p>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <p>CSS-in-JS versus CSS Modules: CSS-in-JS libraries (styled-components, Emotion) offer convenient co-location of styles with component logic, dynamic styling based on props, and automatic class name scoping. The trade-offs are significant for a shared library: a runtime CSS-in-JS library becomes a peer dependency that all consumers must install, creating version conflict risk; runtime style injection is incompatible with some SSR environments and adds to hydration time; and bundle size increases because the CSS-in-JS runtime itself ships to every consumer. CSS Modules with CSS custom properties for theming eliminates all of these trade-offs at the cost of slightly less convenient dynamic styling (runtime prop-driven styles require inline styles or class composition rather than template literals). For a shared library intended to serve many teams and environments, CSS Modules is the more robust choice.</p>
        <p>Headless components versus styled components: a headless component library (like Radix UI or Headless UI) provides behavior and accessibility without visual styling—consumers supply all CSS. This maximizes flexibility and eliminates "fighting the library's styles," but shifts the design system enforcement burden to each consuming team. A styled component library (what this design describes) enforces visual consistency but requires consuming teams to use the provided styles as-is or via the token customization layer. For organizations where visual consistency is a product requirement (multi-brand e-commerce platform, regulated financial products), styled components with a robust token customization layer is appropriate. For organizations where each product has genuinely distinct visual identities with only shared behavior requirements, a headless library may be more appropriate.</p>
        <p>Monorepo versus polyrepo: a monorepo (tokens, core components, icons, utilities, documentation site in one repository with pnpm workspaces) enables atomic commits across packages, simplified cross-package development (import changes take effect immediately without npm link), and a single CI pipeline. The trade-off is repository size and CI duration as the library grows; Turborepo's task caching mitigates this by only running tests and builds for packages that have actually changed. A polyrepo (each package as a separate repository) enables independent versioning and smaller repository size per package, but introduces the cross-repo coordination overhead that monorepos are specifically designed to avoid. For a design system where the tokens, components, and icons packages are tightly coupled (a token change affects component styles), the monorepo is the correct choice.</p>
        <p>RFC-gated contributions versus open contributions: strict RFC requirements reduce low-quality additions and maintain design coherence, but they create friction that discourages contribution from product teams and creates a "throw it over the wall to the platform team" culture. Some organizations use a tiered approach: experimental contributions (new components that only one team uses initially) can be added with light review, while components marked as stable (used by multiple teams) require full RFC process. This allows the library to grow from team-specific experiments to shared infrastructure without a rigid upfront process for every experiment.</p>
      </section>

      <section>
        <h2>Summary</h2>
        <p>A production component library is an organizational infrastructure project as much as a technical one. The technical architecture—three-tier token system (global/semantic/component), CSS custom property theming, CSS Modules for scoped styles, tsup for dual ESM/CJS builds with per-component entry points, changesets for version management, Chromatic for visual regression, axe-core for accessibility, and size-limit for bundle discipline—provides the mechanism for consistency. The governance architecture—RFC process for new additions, two-week comment periods, adoption metric tracking, N-1 support window, mandatory migration guides and codemods for major versions—provides the discipline that keeps the mechanism coherent over time. The documentation architecture—Storybook with auto-generated prop tables and live controls, a searchable internal docs site, indexed migration guides—provides the discoverability that drives adoption. The defining constraint is that a component library only succeeds if teams actually use it, which requires that using it is consistently easier than building one-off components locally. Every technical and governance decision should be evaluated against that constraint.</p>
      </section>
    </ArticleLayout>
  );
}
