"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-alerting-anomaly-detection-dashboard",
  title: "Design an Alerting & Anomaly Detection Dashboard",
  description:
    "Architecture for an alerting and anomaly detection dashboard: multi-condition alert rule builder (threshold, rate-of-change, absence), anomaly detection algorithms (Z-score, seasonal ARIMA, isolation forest), alert lifecycle management (firing, acknowledged, resolved), PagerDuty/Slack notification routing, alert grouping and deduplication, on-call schedule integration, runbook linking, alert replay for historical validation, and noise reduction via alert suppression windows.",
  category: "high-level-design",
  subcategory: "data-heavy-systems",
  slug: "alerting-anomaly-detection-dashboard",
  wordCount: 5000,
  readingTime: 31,
  lastUpdated: "2026-05-11",
  tags: ["hld", "alerting", "anomaly-detection", "pagerduty", "oncall", "z-score", "arima", "alert-fatigue"],
  relatedTopics: ["log-monitoring-ui", "time-series-visualization"],
};

export default function AlertingAnomalyDetectionDashboardArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="crucial">An alerting and anomaly detection dashboard serves the on-call engineer — a person who is potentially woken at 3am by a page and must understand within 60 seconds whether the alert is real, how severe it is, what is causing it, and what action to take. Every design decision must be evaluated against this high-stress, time-critical use case. Alert fatigue — the condition where an on-call engineer receives so many alerts that they begin ignoring them — is the primary failure mode of alerting systems. The dashboard must make real alerts unambiguous and actionable while actively suppressing noise (duplicate alerts, low-severity transient spikes, known maintenance windows).</HighlightBlock>
        <HighlightBlock as="p" tier="important">The anomaly detection challenge is that production metrics are highly seasonal: CPU usage is higher during business hours than at night, e-commerce traffic spikes on Fridays, and batch jobs create predictable load patterns every hour. A simple threshold alert (alert if CPU &gt; 80%) will fire every day during the afternoon peak and never fire during a real anomaly that occurs during low-traffic hours (where 70% CPU would be abnormal). Effective anomaly detection requires seasonal awareness — comparing the current value against what is expected at this time of day/week, not against a fixed absolute threshold. This requires storing and computing a baseline from historical data.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Alert rule builder, anomaly detection algorithms, alert lifecycle management, notification routing, alert grouping, and suppression. Not in scope: log-based alerting (covered in log monitoring article), infrastructure provisioning for the detection compute layer, or the underlying metrics storage system.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Alert rule builder:</strong> Visual rule editor supporting three alert types: (1) Threshold: metric &gt;/&lt;/=/!= value for at least N minutes; (2) Rate-of-change: metric changes by more than X% within Y minutes; (3) Absence: metric has no data for N minutes (service down detection). Rules can be applied to a single metric series or to any series matching a label selector (service=~"auth.*" matches all auth services). Preview mode shows the rule applied to the last 7 days of historical data — how many times would this rule have fired?</HighlightBlock>
          <li><strong>Anomaly detection:</strong> Toggle between threshold alerting and anomaly-based alerting per rule. Anomaly methods: Z-score against rolling 7-day baseline (configurable: window size, number of standard deviations); seasonal decomposition (subtract weekly/daily seasonality, alert on residuals); isolation forest (ML model trained on 30-day history, scores current point). Anomaly alerts include a visualization: the metric value, the expected range (baseline ± N*sigma), and the current deviation magnitude.</li>
          <li><strong>Alert lifecycle:</strong> Alert states: Pending (condition met but not yet for the required duration) → Firing (condition met for required duration) → Acknowledged (on-call has seen it) → Resolved (condition no longer met) → Silenced (suppressed for a time window). Alert timeline shows state transitions with timestamps. MTTR (Mean Time to Resolve) is computed per alert and per service.</li>
          <li><strong>Notification routing:</strong> Route alerts to channels based on severity (Critical → PagerDuty; Warning → Slack; Info → Email) and service (each service team can configure their own routing). On-call schedule integration: automatically routes to the current on-call engineer (via PagerDuty schedule API). Escalation: if no acknowledgment within 15 minutes, escalate to the on-call manager.</li>
          <li><strong>Alert grouping and suppression:</strong> Related alerts that fire simultaneously are grouped into an "alert group" (e.g., all services reporting errors when a database goes down). The group shows a single notification with all affected services listed. Suppression windows: scheduled maintenance events suppress all alerts for the affected service during the window. Inhibition: if "database down" alert fires, inhibit all dependent service alerts (to avoid 50 alerts from one root cause).</li>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <li><strong>Alert firing latency:</strong> Alert fires within 1 minute of the metric violating the threshold (detection cycle: 30-second evaluation interval, alert fires after 2 consecutive violations = 1 minute).</li>
          <HighlightBlock as="li" tier="important"><strong>Notification delivery:</strong> PagerDuty page delivered within 30 seconds of alert firing. Slack notification within 60 seconds.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Dashboard load:</strong> Alert list (active alerts) loads within 500ms. Historical alert timeline loads within 2 seconds for 30-day range.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="crucial">The Alert Engine is a stateful streaming service that evaluates alert rules on a 30-second cycle. It queries the metrics data source (Prometheus, InfluxDB, or the internal time-series store) for each active rule, compares the result against the rule condition, and updates the alert state machine. State is persisted in PostgreSQL (alert_instances table: ruleId, labelSet, state, firedAt, resolvedAt, lastEvaluatedAt). When an alert transitions to Firing state, the Alert Engine publishes an alert_firing event to a Kafka topic (alerts.events). The Notification Router consumes this topic, resolves the routing configuration for the alert's service/severity labels, and dispatches notifications to PagerDuty, Slack, or Email. The Alert API (Node.js REST API) serves the dashboard frontend — listing active alerts, historical alert data, and rule management. The Anomaly Detection Service runs as a separate sidecar that periodically trains and evaluates anomaly models, publishing anomaly_detected events to the same Kafka topic.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/data-heavy-systems/alerting-anomaly-detection-dashboard.svg"
          alt="Alerting and anomaly detection architecture showing alert rule builder (rule types: threshold metric>value for N min; rate-of-change >X% in Y min; absence no-data N min; label selector: service=~'auth.*'; preview: apply rule to last 7d → count historical fires → false-positive rate estimate), alert engine (30s evaluation cycle: query Prometheus/InfluxDB per rule; compare result to condition; state machine: Pending{count violations}→Firing{firedAt}→Acknowledged{ackBy}→Resolved{resolvedAt}|Silenced; persist to PostgreSQL alert_instances; on Firing: publish to Kafka alerts.events {ruleId, labelSet, value, threshold, severity}), anomaly detection (Z-score: rolling_mean=avg last 7d same time-of-day; rolling_std=stddev last 7d; z=(current-rolling_mean)/rolling_std; |z|>3 → anomaly; seasonal ARIMA: decompose weekly/daily seasonality → residual alert; isolation forest: train on 30d history → score current point → score>0.7 → anomaly; viz: metric line + baseline band ±3sigma + deviation callout), notification routing (Kafka alerts.events consumer; route by {severity:Critical→PagerDuty, Warning→Slack, Info→Email} AND service routing config; PagerDuty: POST /incidents {title, body, service_key}; Slack: POST webhook {blocks:[alert-card]}; on-call schedule: GET /oncall → current on-call person → assign; escalation: no ack 15min → POST /escalate to manager), alert grouping (AlertManager-style: group by {service, severity}; simultaneous fires within 30s → single notification group; inhibition rule: database_down inhibits all dependent service alerts; suppression window: POST /silences {matchers, start, end} → suppress matching alerts), alert dashboard (active alerts list: severity-sorted; per-alert timeline: state transitions + timestamps; MTTR per service; runbook link per rule; replay: apply rule to historical range → show historical fires; noise analysis: false-positive rate per rule last 7d)."
          caption="Alert Engine (30s evaluation cycle, Prometheus query, state machine Pending→Firing→Acknowledged→Resolved, PostgreSQL alert_instances), Kafka alert events fan-out, Notification Router (severity+service routing, PagerDuty POST, Slack webhook, on-call schedule API, 15min escalation), anomaly detection (Z-score rolling 7d baseline ±3σ, seasonal ARIMA residuals, isolation forest 30d training), AlertManager-style grouping + inhibition + suppression windows, and dashboard (active list, MTTR, runbook links, rule replay)"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Alert State Machine and Evaluation Loop</h3>
        <HighlightBlock as="p" tier="important">The Alert Engine runs a strict evaluation loop: every 30 seconds, for each active alert rule, it executes the rule's query against the data source (a PromQL instant query for Prometheus, or a parameterized SQL query for time-series databases). The result is a set of time series, each identified by its label set (&#123; service: "auth", method: "POST" &#125;). For each series, the engine checks the condition (e.g., value &gt; 500). If the condition is true, the series transitions to Pending state with a violation_count = 1. On the next evaluation (30 seconds later), if the condition is still true, violation_count = 2. When violation_count × evaluation_interval &gt;= for_duration (the "fire after N minutes" setting), the series transitions to Firing state. This two-cycle requirement prevents transient spikes from creating false positives — a single-sample spike will not fire an alert.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The state machine uses PostgreSQL for persistence, not in-memory state. This means the Alert Engine is restartable without losing alert state — if the evaluation pod crashes, a replacement pod picks up from the last persisted state. The alert_instances table is indexed by (ruleId, labelSetHash) — the labelSetHash is a SHA256 of the sorted JSON representation of the label set, enabling O(1) lookup per series. The evaluation loop uses a work queue (one queue entry per rule) with a single shared thread pool — rules evaluate concurrently, but each rule's evaluation is serialized (no two evaluations of the same rule run simultaneously, preventing state machine races).</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Anomaly Detection Algorithms</h3>
        <HighlightBlock as="p" tier="important">Z-score anomaly detection: for each metric series with anomaly alerting enabled, the Anomaly Detection Service maintains a rolling baseline of the last 7 days of data at the same time of day and day of week (Sunday-to-Sunday hourly seasonality). For each new data point, the z-score is computed: z = (current_value - rolling_mean) / rolling_std. A z-score above 3 (3 standard deviations above the mean) is a high-confidence anomaly. The rolling mean and standard deviation are updated incrementally (using Welford's online algorithm) to avoid recomputing from scratch on each new point. The baseline and z-score are stored alongside each data point, enabling the dashboard to show the expected range at any historical timestamp.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Seasonal decomposition (STL): for metrics with strong weekly seasonality (e.g., web traffic, which is always high on weekdays and low on weekends), simple Z-score against a time-of-day baseline is insufficient — the "normal" value on a Monday morning is different from a Sunday morning. STL (Seasonal-Trend decomposition using LOESS) decomposes the time series into trend, seasonality, and residual components. Anomaly detection runs on the residual component after removing the trend and seasonal patterns. This makes the detection sensitive to genuinely abnormal deviations while immune to expected daily/weekly patterns. STL is computed as a nightly batch job over the last 90 days of data for each monitored metric, producing a seasonality model that is applied in real time.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Alert Grouping and Inhibition</h3>
        <HighlightBlock as="p" tier="important">Alert grouping is modeled after Prometheus Alertmanager's grouping concept. When multiple alerts fire within a 30-second window and share the same group_by labels (e.g., severity and team), they are bundled into a single notification group. Instead of 20 separate Slack messages for 20 services experiencing high error rates after a database failure, the on-call receives one Slack message: "20 alerts firing: high error rate — services: auth, payments, orders, catalog [+16 more]". The notification manager waits a configurable group_wait period (default: 30 seconds) after the first alert fires before sending, to accumulate related alerts that fire in quick succession.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Inhibition rules define "if alert A is firing, suppress alert B". This is the key mechanism for root-cause correlation: if "PostgreSQL down" (severity: critical) is firing, inhibit all alerts where label database="postgres" (the downstream service alerts that are consequences of the database being down). Inhibition rules are configured in the Alert Engine's YAML configuration: &#123; source_matchers: [&#123;severity: "critical"&#125;, &#123;type: "database_down"&#125;], target_matchers: [&#123;database: "postgres"&#125;], equal: ["region", "cluster"] &#125;. The equal field ensures inhibition only applies when source and target alerts share the same region and cluster labels — preventing a database failure in us-west from suppressing alerts in eu-east.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Alert Dashboard: Active Alerts and MTTR</h3>
        <HighlightBlock as="p" tier="important">The alert dashboard's main view is a severity-sorted list of active (Firing + Acknowledged) alerts. Each row shows: severity badge (red=Critical, yellow=Warning, blue=Info), alert name, affected service/labels, current metric value vs threshold, time since firing, and a one-click "Acknowledge" button. The list auto-refreshes every 30 seconds (polling the Alert API) or subscribes to a Server-Sent Events stream for real-time updates. Acknowledged alerts are moved to a separate "Acknowledged" section to de-emphasize them while keeping them visible.</HighlightBlock>
        <HighlightBlock as="p" tier="important">MTTR (Mean Time to Resolve) is computed per service and per alert rule over rolling 30-day windows. MTTR = average(resolvedAt - firedAt) for all resolved alerts in the window. High MTTR for a specific alert indicates either that the alert is for a systemic issue that takes long to fix, or that the alert is noisy and engineers stop responding promptly. The dashboard surfaces MTTR trends (is MTTR increasing or decreasing?) alongside a false-positive rate (what percentage of alert firings were resolved within 5 minutes — a proxy for alerts that were false positives or transient). These noise metrics help alert owners tune their alert conditions to reduce fatigue.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">Threshold alerting versus anomaly-based alerting: threshold alerting (metric &gt; fixed value) is simple, predictable, and easy to explain to stakeholders ("we alert when error rate exceeds 1%"). Anomaly-based alerting is more sensitive to unexpected changes (catching anomalies that would not trigger a fixed threshold) but produces more false positives during unusual-but-legitimate events (a flash sale, a product launch, a new customer segment) that look like anomalies compared to the training data. The practical recommendation: use threshold alerting as the primary mechanism for well-understood, business-critical metrics (error rate, checkout failures), and use anomaly detection as a secondary layer that generates lower-severity "investigation recommended" alerts rather than pages. Anomaly alerts should flow to Slack for review, not to PagerDuty for immediate wakeup.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Alert fatigue and the "crying wolf" problem: when on-call engineers receive too many false-positive alerts, they begin acknowledging alerts without investigating them — training themselves to treat pages as noise. This is the most dangerous operational failure mode: when a real incident occurs, the on-call engineer has been conditioned to dismiss pages. The dashboard should actively surface noise metrics (false-positive rate per rule, MTTR trends, alert-to-incident correlation rate) and prompt alert owners to tune or mute high-noise alerts. Some teams implement an "alert budget" — each team is allowed a maximum number of alerts per week, and rules that consistently exceed their budget must be fixed or removed. This incentivizes alert quality over quantity.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="important">An alerting and anomaly detection dashboard is built around a stateful Alert Engine (30-second evaluation loop, PromQL/SQL queries, two-cycle violation confirmation before Firing, PostgreSQL alert_instances state persistence with SHA256 labelSetHash index) publishing to a Kafka alerts.events topic. The Notification Router consumes this topic and dispatches to PagerDuty (Critical), Slack (Warning), and Email (Info) based on service routing config, with PagerDuty on-call schedule API integration and 15-minute escalation. Anomaly detection runs Z-score (rolling 7-day time-of-day baseline, |z|&gt;3), STL seasonal decomposition (residuals after weekly/daily pattern removal), and isolation forest (30-day training, score &gt;0.7). AlertManager-style grouping accumulates related alerts (group_wait 30s) into single notifications; inhibition rules suppress downstream alerts when root-cause alert fires. The dashboard surfaces MTTR per service and false-positive rate per rule to identify and reduce alert noise. The defining operational principle: an alert that engineers dismiss without investigating has negative value — every noisy alert is a step toward the silent incident that goes undetected.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
