"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-bi-dashboard",
  title: "Design a BI Dashboard (Tableau-like)",
  description:
    "Architecture for a Tableau-like BI dashboard: drag-and-drop chart builder, multi-source data connector (SQL, REST, CSV), column profiling, live and cached query execution, dashboard canvas with responsive grid layout, cross-filter interactions between charts, parameterized filters, scheduled data refresh, PDF/image export, row-level security per viewer, and shared dashboard links with permission-gated access.",
  category: "high-level-design",
  subcategory: "data-heavy-systems",
  slug: "bi-dashboard",
  wordCount: 5000,
  readingTime: 31,
  lastUpdated: "2026-05-11",
  tags: ["hld", "bi", "dashboard", "tableau", "data-visualization", "query-engine", "cross-filter", "row-level-security"],
  relatedTopics: ["large-dataset-exploration-ui", "reporting-analytics-dashboard"],
};

export default function BIDashboardArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <p>A BI dashboard like Tableau serves two distinct user archetypes: the builder (a data analyst who connects to data sources, designs visualizations, and assembles dashboards) and the viewer (a business stakeholder who interacts with published dashboards via filters and drill-downs but cannot modify the underlying queries). The design challenge is that these personas have radically different latency tolerance and interaction patterns. The builder can tolerate a 5–10 second query execution while iterating on a chart; the viewer expects sub-second response when clicking a filter chip that cross-filters three charts simultaneously. A naive implementation that fires full re-queries on every cross-filter click will feel unusable for viewers.</p>
        <p>The data scale challenge is fundamental to BI: a single dashboard may query a fact table with 500 million rows. Returning 500 million rows to the browser is impossible; the query engine must push computation to the data source (GROUP BY, aggregations, LIMIT) and return only the summarized result set needed for the specific visualization. The chart builder must expose this query generation transparently enough that non-technical users can build charts without writing SQL, while still allowing power users to override with raw SQL. This is the core UX tension in every BI tool: abstraction versus power.</p>
        <p><strong>Explicit scope:</strong> Chart builder, dashboard canvas with cross-filter, query execution layer, data source connectors, row-level security, and export. Not in scope: ETL pipeline design, data warehouse architecture, or ML-based insights.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <li><strong>Chart builder:</strong> Drag fields from a schema browser onto X-axis, Y-axis, Color, Size, and Tooltip shelves. Supported chart types: bar, line, area, scatter, pie, heatmap, table, geographic map. Auto-suggest chart type based on field data types (date + measure → line; dimension + measure → bar; two measures → scatter). Column profiling: clicking a field shows distribution histogram, null rate, cardinality, and sample values.</li>
          <li><strong>Data sources:</strong> Connect to PostgreSQL, BigQuery, Snowflake, Redshift, MySQL via JDBC-style credentials. REST API connector (specify URL, auth header, JSON path). CSV upload (parsed in-browser, stored in object storage, queried via DuckDB). Live mode: query executes on every filter change. Extract mode: query result cached as an in-memory columnar store, filters applied client-side with sub-millisecond response.</li>
          <li><strong>Dashboard canvas:</strong> Responsive grid layout (12-column, 1–12 span per widget). Widgets: charts, text blocks, images, filter controls (dropdown, multi-select, date range, slider). Cross-filter: clicking a bar in one chart filters all other charts on the dashboard to the selected dimension value. Parameterized filters: filter controls at the top apply WHERE clause parameters to all charts that reference them.</li>
          <li><strong>Row-level security:</strong> Data source can define RLS rules: &#123;field: "region", operator: "=", valueFrom: "viewer.attribute.region"&#125;. When a viewer opens the dashboard, the RLS rules inject WHERE clauses based on the viewer's identity attributes. Builders see all data; viewers see only their permitted rows. RLS rules are enforced server-side on every query — the viewer cannot bypass them by inspecting network requests.</li>
          <li><strong>Sharing and export:</strong> Dashboard share link with permission levels: View, Filter (can change filters but not layout), Edit. Schedule email delivery (PDF, PNG) at set times. Embed via iframe with signed JWT token. Export current view as PDF (server-side headless Chrome render) or CSV (raw query results).</li>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <li><strong>Query latency (live mode):</strong> Simple aggregation queries (&lt;100M rows) return within 3 seconds. Dashboard load shows all charts within 5 seconds of page open via parallel query execution.</li>
          <li><strong>Cross-filter latency (extract mode):</strong> Cross-filter interactions respond within 100ms using client-side DuckDB-WASM or Arrow columnar store.</li>
          <li><strong>Concurrent viewers:</strong> A popular shared dashboard must support 500 concurrent viewers without hammering the underlying data warehouse — achieved via query result caching with TTL per data source refresh schedule.</li>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <p>The system has three major planes. The Builder Plane is a rich client-side application (Next.js) where analysts compose dashboards. It communicates with a Query Service (Node.js) that translates visual field selections into SQL, executes them against the configured data source via a connector layer, and returns result sets. The Viewer Plane is a read-only dashboard renderer that loads the dashboard definition (JSON schema of widget layouts, chart configs, filter configs) from a Dashboard Service and fires chart queries through the Query Service with the viewer's RLS context injected. The Cache Plane sits between the Query Service and the data sources: a Redis layer keyed by SHA256(query + tenantId + rlsContext) with TTL equal to the data source's refresh interval (configurable: 5 minutes to 24 hours). In extract mode, the Query Service pre-fetches the full query result into an in-memory columnar store (Apache Arrow format) hosted in a Node.js worker; subsequent filter operations are applied by the client-side DuckDB-WASM instance that operates on the same Arrow buffer via shared memory or postMessage transfer.</p>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/data-heavy-systems/bi-dashboard.svg"
          alt="BI dashboard architecture showing chart builder (drag field → shelf: X-axis Y-axis Color Size Tooltip; auto-suggest chart type; generate SQL: SELECT dim, AGG(measure) FROM table WHERE {params} GROUP BY dim ORDER BY dim; schema browser: column profiling histogram null-rate cardinality; column types: dimension string date / measure integer float; chart types: bar line scatter pie heatmap table geo-map), query execution layer (Query Service: receive {datasourceId, sql, rlsContext, viewerId}; inject RLS: append AND region={viewer.region} to WHERE; cache lookup: Redis SHA256(query+tenantId+rlsContext) TTL=refresh_interval; cache miss → JDBC connector → data warehouse: BigQuery/Snowflake/Redshift/Postgres; result set → Arrow format → return; extract mode: prefetch full table → Arrow buffer in worker → DuckDB-WASM client-side sub-queries), dashboard canvas (12-column responsive grid; widget types: chart text-block image filter-control; cross-filter: click bar value → dispatch {field:region value:West} → all charts re-query with additional WHERE region=West; parameterized filters: date-range dropdown slider → inject {params} into all chart SQLs; layout save: PATCH /api/dashboards/{id}/layout), row-level security (viewer login → JWT {userId, org, region:West, role:analyst}; Dashboard Service: load RLS rules [{field:region op:= valueFrom:viewer.region}]; inject into Query Service context; server enforces: viewer cannot inspect raw data without RLS; builder: no RLS applied; RLS rules editor: field + operator + viewer attribute mapping), sharing and export (share link: signed JWT {dashboardId, permission:View|Filter|Edit, expiry}; iframe embed: src=/embed/{token}; PDF export: POST /api/export/pdf → Puppeteer headless Chrome → render dashboard → return PDF binary; CSV export: raw query result → stream CSV; scheduled delivery: cron job → render → email via SES; query result cache: 500 concurrent viewers → single warehouse query per TTL window)."
          caption="Chart builder (field shelves → SQL generation, column profiling), Query Service (RLS injection, Redis cache SHA256 keyed, JDBC connectors), extract mode (Arrow buffer + DuckDB-WASM client-side), dashboard canvas (cross-filter dispatch, parameterized filter injection), row-level security (server-enforced viewer attribute WHERE injection), and sharing/export (signed JWT, Puppeteer PDF, scheduled email delivery)"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Chart Builder and SQL Generation</h3>
        <p>The chart builder exposes a visual shelf metaphor (popularized by Tableau, derived from Leland Wilkinson's Grammar of Graphics). Fields from the data source schema are listed in a sidebar panel, showing the field name, data type icon (string: A, integer: #, date: calendar, boolean: toggle), and an expand arrow to see column profiling stats. Dragging a field to the X-axis shelf, Y-axis shelf, Color shelf, or Tooltip shelf updates a declarative chart specification object: &#123; xField: "region", yField: "revenue", colorField: "category", chartType: "bar", aggregation: "SUM", filters: [] &#125;.</p>
        <p>SQL generation from the chart spec: the Query Builder module translates the spec into SQL — for the example above: SELECT region, category, SUM(revenue) AS revenue FROM sales_table WHERE &#123;params&#125; GROUP BY region, category ORDER BY revenue DESC LIMIT 10000. The generated SQL is shown in a "View SQL" panel below the chart for transparency. Power users can switch to Raw SQL mode, replacing the auto-generated SQL with their own query. In raw SQL mode, the field shelf UI is disabled and the chart binds directly to the named columns returned by the raw query.</p>
        <p>Column profiling: when a field is clicked in the schema browser, a side panel shows a distribution histogram (a lightweight SELECT field, COUNT(*) FROM table GROUP BY field ORDER BY COUNT(*) DESC LIMIT 20 query), null rate (SELECT COUNT(*) WHERE field IS NULL / COUNT(*)), cardinality (SELECT COUNT(DISTINCT field)), and 5 sample values. This query is executed against the live data source with a 30-second timeout and cached for 1 hour in Redis. The histogram helps analysts understand the data before deciding how to use the field.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Live Mode vs Extract Mode</h3>
        <p>Live mode: every chart query fires against the underlying data source in real time. When a filter changes, each chart re-fires its SQL with the updated WHERE clause. This mode is necessary for dashboards that must reflect data as of the last few minutes (e.g., operations dashboards). The Query Service parallelizes chart queries on a dashboard page load — all N chart queries fire concurrently using Promise.all, and charts render as their queries complete (independent loading states per chart). Query results are cached in Redis by SHA256(SQL + tenantId + rlsContext) with a TTL configured per data source (default 5 minutes).</p>
        <p>Extract mode: the Query Service pre-fetches the full query result (without aggregation, up to 10 million rows) from the data source and stores it as an Apache Arrow columnar buffer. This buffer is serialized and sent to the browser once on page load. The browser-side DuckDB-WASM instance loads the Arrow buffer as an in-memory table. All subsequent filter interactions — cross-filters, parameterized filter changes, chart type changes — execute as SQL queries inside DuckDB-WASM in the browser, returning results in under 100ms for datasets up to 1 million rows. Extract mode is ideal for dashboards where the underlying data changes infrequently (daily refreshes) and interaction latency is critical. The extract is refreshed on a configurable schedule (nightly, hourly) and the new Arrow buffer is pushed to the browser via a WebSocket message or detected on next page load.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Cross-Filter Architecture</h3>
        <p>Cross-filtering is the most complex interaction on the dashboard canvas. When a viewer clicks a bar in Chart A (e.g., the bar for "West" in a region breakdown chart), the dashboard state manager adds a cross-filter event: &#123; sourceChartId: "chart-a", field: "region", value: "West" &#125;. All other charts on the dashboard subscribe to the cross-filter state (via Zustand in the React client). Each chart recomputes its effective WHERE clause by merging its own parameterized filters with the active cross-filter events: WHERE region = 'West' AND date &gt;= '2024-01-01'. In live mode, this triggers a re-query against the data source. In extract mode, this re-queries the DuckDB-WASM instance.</p>
        <p>Cross-filter highlight versus filter: clicking a bar can either filter (hide non-selected data from all charts) or highlight (dim non-selected data). The dashboard builder configures the interaction type per chart. Highlight is implemented by returning all data but adding an isHighlighted boolean to each row based on whether it matches the cross-filter — the chart renderer uses opacity 1.0 for highlighted rows and 0.3 for non-highlighted. This is computed entirely client-side without a re-query, making highlight mode instantaneous. Multiple cross-filters from different charts are ANDed together — clicking "West" in Chart A and "Q4" in Chart B filters all other charts to rows where region = 'West' AND quarter = 'Q4'.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Row-Level Security Implementation</h3>
        <p>RLS is defined at the data source level by the dashboard admin: a list of rules, each specifying a field, an operator, and a viewer attribute reference. For example: &#123; field: "customer_id", operator: "IN", valueFrom: "viewer.allowedCustomerIds" &#125;. When a viewer authenticates, their JWT includes their identity attributes (encoded in the token claims). The Query Service extracts these attributes from the JWT and injects them into every SQL WHERE clause before execution. The injection happens server-side in the Query Service — the viewer's browser only sees the filtered result set, never the raw SQL or the full data.</p>
        <p>RLS consistency: because results are cached in Redis, the cache key must include the RLS context. The cache key is SHA256(sql + tenantId + JSON.stringify(sortedRLSClaims)) — two viewers with different RLS contexts will always get separate cache entries. This prevents the scenario where Viewer A's query result (containing only West region data) is served to Viewer B (who should see East region data) because the SQL text happened to match. The dashboard builder has a "Preview as viewer" mode that simulates the RLS context of a selected viewer persona, allowing builders to verify that RLS rules are correctly restricting data before publishing.</p>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Dashboard Canvas and Layout System</h3>
        <p>The dashboard canvas uses a 12-column CSS Grid layout with configurable row heights (per widget). Each widget has a position (col, row, colSpan, rowSpan) stored in the dashboard JSON schema. On mobile (viewport &lt;768px), widgets stack vertically in the order defined in the layout. The builder uses a drag-to-resize and drag-to-reposition interaction implemented with pointer events — a drag handle on the widget's bottom-right corner changes the colSpan/rowSpan; dragging the widget's header changes its col/row position. Layout changes are auto-saved with a debounce of 2 seconds using PATCH /api/dashboards/{`{id}`}/layout.</p>
        <p>Text blocks support a subset of Markdown (bold, italic, headers, links) rendered client-side. Image widgets accept a URL or a file upload stored in object storage. Filter controls (dropdown, multi-select date range, slider) are separate widgets that publish their state to the dashboard's filter context — any chart that references the parameter &#123;date_range&#125; in its SQL will re-query when the date range filter changes. Filter controls can be pinned to the top of the dashboard (sticky on scroll) for dashboards with many charts below the fold.</p>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <p>Live mode versus extract mode is the central trade-off. Live mode always shows current data but is slow for complex dashboards (N charts × query latency) and can overload the data warehouse when 500 viewers open the same dashboard simultaneously. Extract mode is fast and warehouse-friendly but shows stale data — a viewer might see yesterday's numbers while the warehouse already has today's data. The extract mode's stale data problem is compounded for RLS: if Viewer A's allowed customers change (a new customer assignment), the extract won't reflect this until the next scheduled refresh. For dashboards with frequently changing RLS data, live mode is necessary despite the latency cost. Most BI tools solve this with a hybrid: a short TTL Redis cache in live mode (capturing the burst of concurrent viewers at the same moment) while still querying the live data source every 5 minutes.</p>
        <p>Cross-filter performance in live mode with many charts: a dashboard with 10 charts and 500 concurrent viewers clicking cross-filters would generate 5,000 simultaneous queries. The Redis cache absorbs much of this (viewers clicking the same cross-filter within the TTL window share a cached result), but the first click for each unique filter combination hits the warehouse. A query queue with per-datasource concurrency limits (e.g., max 10 concurrent queries to a Snowflake warehouse) prevents overload — subsequent queries wait in the queue rather than failing. Charts show a spinner while their query is queued, which is a reasonable UX for interactive dashboards.</p>
      </section>

      <section>
        <h2>Summary</h2>
        <p>A BI dashboard like Tableau is built around a Grammar of Graphics chart builder (field shelves → SQL generation), a Query Service that injects RLS WHERE clauses from JWT viewer claims (server-enforced, cache-key includes RLS context), and a dual-mode query execution strategy: live mode (Redis-cached queries to the data warehouse, parallel execution across charts) and extract mode (full result set prefetched as Apache Arrow buffer, DuckDB-WASM client-side sub-queries for &lt;100ms cross-filter response). The dashboard canvas is a 12-column CSS Grid with cross-filter state managed via Zustand (AND-merged filter events dispatch re-queries or client-side DuckDB filters). RLS rules inject viewer identity attributes into WHERE clauses server-side; "Preview as viewer" mode lets builders verify restrictions before publishing. The defining performance challenge: 500 concurrent viewers opening the same dashboard must not hammer the data warehouse — solved by the Redis result cache (keyed by SHA256 of SQL + tenantId + RLS context) and a per-datasource query queue with concurrency limits.</p>
      </section>
    </ArticleLayout>
  );
}
