"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-realtime-analytics-10k-datapoints",
  title: "Design Real-Time Analytics with 10k+ Data Points",
  description:
    "Architecture for real-time analytics dashboards handling 10,000+ data points per second: WebSocket streaming ingestion, server-side downsampling (LTTB algorithm), canvas-based rendering with requestAnimationFrame double-buffering, windowed aggregation (1s/5s/1min buckets), backpressure and delta compression, pausable charts with historical rewind, metric cardinality explosion prevention, and adaptive sampling based on viewport pixel density.",
  category: "high-level-design",
  subcategory: "data-heavy-systems",
  slug: "realtime-analytics-10k-datapoints",
  wordCount: 5000,
  readingTime: 31,
  lastUpdated: "2026-05-11",
  tags: ["hld", "real-time", "analytics", "websocket", "canvas", "downsampling", "lttb", "timeseries"],
  relatedTopics: ["time-series-visualization", "log-monitoring-ui"],
};

export default function RealtimeAnalytics10kDatapointsArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <HighlightBlock as="p" tier="important">A real-time analytics dashboard displaying 10,000+ data points per second faces a fundamental browser rendering constraint: a typical monitor refreshes at 60Hz, meaning you have 16.7ms per frame to update the DOM. Rendering 10,000 individual SVG elements — each a circle or a path point — forces the browser's layout engine to process 10,000 style recalculations per frame, making 60fps impossible. The solution is to abandon the DOM for rendering and instead treat the chart as a bitmap drawn directly to an HTML5 Canvas element, using the Canvas 2D API or WebGL. Canvas rendering does not interact with the browser's layout engine and can render 100,000 points at 60fps if the drawing code is optimized.</HighlightBlock>
        <HighlightBlock as="p" tier="important">But rendering is only half the problem. The data delivery challenge is equally critical: if the server pushes 10,000 data points per second over a WebSocket, each point is a JSON object with at minimum a timestamp and a value. 10,000 objects at 100 bytes each = 1MB/second of network traffic per chart. A dashboard with 5 live charts would consume 5MB/second — far exceeding the available bandwidth on a corporate network. The server must downsample the data before sending: instead of every data point, send only the points needed to accurately represent the shape of the time series at the current zoom level and viewport pixel width. This is the LTTB (Largest-Triangle-Three-Buckets) downsampling algorithm, which selects points that preserve the visual shape of the curve with the minimum number of points.</HighlightBlock>
        <p><strong>Explicit scope:</strong> WebSocket ingestion, server-side downsampling, Canvas rendering pipeline, windowed aggregation, backpressure handling, and historical rewind. Not in scope: data ingestion pipeline design, time-series database architecture, or alerting systems (covered separately).</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Live data streaming:</strong> Charts update in real time as data arrives. Dashboard supports 5–20 simultaneous live charts. Each chart can display 1–10 metrics (lines). Data arrives at up to 10,000 points per second per metric. Chart time window: Last 1 minute, 5 minutes, 1 hour, 24 hours (configurable).</HighlightBlock>
          <li><strong>Downsampling and aggregation:</strong> The server downsamples incoming data to match the chart's pixel width (typically 1,200px → 1,200 output points maximum). Aggregation windows: 1-second buckets (show min/max/avg), 5-second buckets, 1-minute buckets. The user can toggle between aggregation levels and raw data (when zoomed in to a short time window).</li>
          <li><strong>Pause and rewind:</strong> A "Pause" button freezes the live view. While paused, the user can drag a time selection window to inspect a historical range. "Resume" snaps back to live data. Historical data is fetched from the time-series database (InfluxDB, TimescaleDB, or Prometheus) for the selected range.</li>
          <li><strong>Multi-metric overlay:</strong> Multiple metrics overlaid on a single chart with independent Y-axes (dual-axis). Color-coded legend. Toggling a metric hides/shows its line without re-fetching data — toggled lines are masked in the rendering pass.</li>
          <li><strong>Adaptive resolution:</strong> When the browser tab is backgrounded (visibility API: document.hidden = true), the server reduces push frequency to 1 update/second to conserve resources. When the tab becomes visible again, the server resumes full-rate streaming.</li>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <li><strong>Rendering frame rate:</strong> Charts maintain 60fps with up to 1,200 visible data points per chart. Canvas 2D with requestAnimationFrame double-buffering achieves this without DOM layout overhead.</li>
          <li><strong>WebSocket message rate:</strong> Maximum 60 messages/second per chart to the browser (one per animation frame). Server-side batching accumulates points arriving faster than 60Hz and sends a batch per frame.</li>
          <li><strong>Historical fetch latency:</strong> Fetching 1 hour of data (downsampled to 1,200 points) from the time-series database returns within 500ms.</li>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="crucial">The streaming pipeline has two paths. The real-time path: a metrics producer (application servers, IoT devices, or Kafka consumers) publishes data points to a Metrics Ingestion Service. The ingestion service writes points to a time-series database (InfluxDB or TimescaleDB) and simultaneously pushes them to a Streaming Gateway — a WebSocket server that maintains connections to all open dashboard tabs. The Streaming Gateway applies server-side downsampling: for each connected client, it tracks the client's current chart viewport (time range, pixel width) and applies the LTTB algorithm to select only the points that matter for that viewport before sending. The historical path: when a user pauses and selects a time range, or when a chart first loads, the Dashboard Service queries the time-series database for the requested range and downsample level, returning the data as a JSON array.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The rendering layer is a React component that wraps an HTML5 Canvas element. The Canvas is sized to the physical pixel dimensions of the container (devicePixelRatio aware). An off-screen canvas (OffscreenCanvas) is used for double-buffering: the new frame is drawn on the off-screen canvas in a Web Worker (using Offscreen Canvas + Worker + requestAnimationFrame), then blit-transferred to the visible canvas via transferToImageBitmap() — this prevents partial frames from appearing during drawing. Data points are stored in a circular buffer (a fixed-size Float64Array) that efficiently drops the oldest point as new ones arrive, avoiding garbage collection pressure.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/data-heavy-systems/realtime-analytics-10k-datapoints.svg"
          alt="Real-time analytics architecture showing data ingestion (metrics producer: app servers IoT Kafka → POST /ingest {metricId, timestamp, value}; Ingestion Service: write to InfluxDB/TimescaleDB AND push to Streaming Gateway; Kafka topic: metrics.raw for fan-out; 10K points/sec per metric), streaming gateway (WebSocket server: one connection per dashboard tab; client subscribe {metricId, timeWindow:5min, pixelWidth:1200}; server-side LTTB downsampling: select 1200 points from incoming stream that maximally preserve curve shape; batch per 16.7ms frame → send JSON {points: [{t,v},...], window_start, window_end}; backpressure: if client queue >100 messages → drop oldest → send gap_marker; adaptive: document.hidden=true → reduce to 1msg/sec), canvas rendering pipeline (React component: canvas ref · devicePixelRatio scaling; OffscreenCanvas in Web Worker; requestAnimationFrame loop: receive postMessage {newPoints} → append to circular buffer Float64Array[N]; draw frame: clear canvas → map timestamps to x-pixels → values to y-pixels → lineTo path → stroke; double-buffer: drawImage to visible canvas via transferToImageBitmap(); 60fps with 1200 points; WebGL fallback for 10K+ visible points), windowed aggregation (1s bucket: {min, max, avg, count} · 5s bucket · 1min bucket; toggle aggregation level; raw data when zoomed <30s window; min-max band: fill between min and max lines; avg line overlay), pause and rewind (Pause button → stop consuming WebSocket messages; time-selection drag → historical range; GET /api/metrics/{id}/history?start={t}&end={t}&resolution=1200 → InfluxDB query → 1200 downsampled points → render historical; Resume → reconnect WebSocket → snap to live tail), multi-metric overlay (N metrics same chart · independent Y-axes dual-axis · color legend; toggle metric → mask line in render pass, no re-fetch; series state: Float64Array per metric · 0-copy render)."
          caption="Metrics ingestion (InfluxDB + Streaming Gateway), server-side LTTB downsampling (1,200 points per viewport pixel width), 16.7ms batch WebSocket push (60fps budget), backpressure gap_marker, Canvas + OffscreenCanvas double-buffering in Web Worker (circular Float64Array buffer), windowed aggregation (1s/5s/1min min-max-avg bands), pause+rewind (historical InfluxDB fetch), adaptive streaming (visibility API tab backgrounding), and WebGL fallback for 10k+ points"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">LTTB Downsampling Algorithm</h3>
        <HighlightBlock as="p" tier="important">LTTB (Largest-Triangle-Three-Buckets) is the standard algorithm for visually lossless time-series downsampling. Given N input points and a target output count of M, it divides the input into M-2 equal-width buckets. The first and last points are always included. For each intermediate bucket, it selects the point that forms the largest triangle with the previously selected point and the average of the next bucket — this maximizes the visual difference preserved, keeping the points that most affect the shape of the curve. The algorithm runs in O(N) time and is implemented server-side in the Streaming Gateway for each connected client's viewport subscription.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Viewport subscription: when a client opens a chart, it sends a subscription message: &#123; metricId: "cpu_usage", timeWindow: "5m", pixelWidth: 1200 &#125;. The Streaming Gateway stores this subscription and uses the pixelWidth (1,200) as the LTTB target output count — never send more points than there are pixels to display them. As the time window advances in real time (new points arrive and old points age out), the Streaming Gateway re-applies LTTB on the sliding window of buffered points and sends only the delta (new points added at the tail, old points expired from the head) in each frame batch. The delta is encoded as &#123; add: [&#123;t,v&#125;], remove_before: timestamp &#125;, which the client applies to its local circular buffer.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Adaptive downsampling on zoom: when the user zooms in on a 10-second window within a 5-minute chart, the effective time resolution increases — 1,200 pixels now represent only 10 seconds, so each pixel represents 8ms of data. The client sends an updated subscription with the new timeWindow, and the Streaming Gateway switches from 1-second bucket aggregation to raw data for that narrow window. Zooming out triggers the reverse: the Gateway switches to coarser aggregation to reduce point count back to the target.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Canvas Rendering Pipeline</h3>
        <HighlightBlock as="p" tier="important">The chart component renders to an HTML Canvas element sized at physicalWidth = containerWidth × devicePixelRatio, physicalHeight = containerHeight × devicePixelRatio. This ensures that on retina displays (devicePixelRatio = 2), the canvas is 2× the CSS pixel dimensions, making lines crisp rather than blurry. The canvas CSS size is set to the container dimensions, and the canvas rendering context is scaled by devicePixelRatio using ctx.scale(dpr, dpr).</HighlightBlock>
        <HighlightBlock as="p" tier="important">The render loop runs via requestAnimationFrame. Each frame: (1) clear the off-screen canvas with ctx.clearRect; (2) for each visible metric, map its Float64Array of &#123;timestamp, value&#125; pairs to &#123;x, y&#125; canvas coordinates using linear transforms (timeToX = (t - windowStart) / windowDuration × canvasWidth; valueToY = (maxValue - v) / range × canvasHeight); (3) draw each metric line as a Path2D beginning with moveTo the first point and lineTo each subsequent point; (4) stroke each path with the metric's assigned color and lineWidth 1.5; (5) call drawImage on the visible canvas using the off-screen canvas's ImageBitmap. The entire draw cycle for 1,200 points per metric takes approximately 3–5ms, well within the 16.7ms frame budget for up to 4 metrics per chart.</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">For dashboards with 10 or more metrics per chart (rare but supported), the system switches to WebGL rendering (via the regl library). WebGL renders data as a vertex buffer — the Float64Array of points is uploaded as a VBO (vertex buffer object) to the GPU, and a GLSL shader draws the polyline. WebGL can render 100,000 points per frame at 60fps because the rendering is fully GPU-parallel. The drawback: WebGL requires a different code path and cannot easily render text labels or legends, which are overlaid as a separate Canvas2D layer on top of the WebGL canvas.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Backpressure and Gap Handling</h3>
        <HighlightBlock as="p" tier="important">The WebSocket connection between the Streaming Gateway and the browser is reliable but the browser's JavaScript processing may fall behind if the tab is heavily loaded (e.g., the user has many other tabs open). The Streaming Gateway monitors the WebSocket send buffer size — if the buffered amount exceeds a threshold (e.g., 100 unacknowledged messages), the Gateway enters backpressure mode for that connection: it stops sending individual point batches and instead sends a gap_marker message: &#123; type: "gap", from: t1, to: t2 &#125;. The client renders this as a dashed segment in the chart at the gap timestamps, indicating data was received but not displayed (not missing data). When the client's buffer drains, it sends a backpressure_clear message and the Gateway resumes normal streaming.</HighlightBlock>
        <HighlightBlock as="p" tier="important">True data gaps (periods where no data was received by the ingestion service, e.g., a sensor went offline) are communicated differently: the time-series database marks these as null values, and the streaming data includes null points. The chart renders null gaps by breaking the line: moveTo the next valid point rather than lineTo, creating a visual discontinuity that distinguishes sensor outages from display backpressure. The null gap is labeled with a tooltip: "No data 14:32:05–14:35:12 (3m 7s)".</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Windowed Aggregation and Min-Max Bands</h3>
        <p>Raw data at high sample rates (e.g., 1,000Hz sensor data) is visually useless in a 5-minute window — every pixel represents 250 raw samples, and drawing them all would produce a solid black band. The solution is windowed aggregation: the server computes min, max, and average within each 1-second bucket and sends three values per bucket instead of 250. The chart renders three lines: the avg line (solid), and a shaded band between min and max (semi-transparent fill, rgba(colorR, colorG, colorB, 0.15)). This gives the viewer information about the variance within each bucket (a wide band indicates high variance; a narrow band indicates stable values) without overwhelming the rendering pipeline.</p>
        <HighlightBlock as="p" tier="important">The user can toggle between aggregation granularities: 1-second buckets (default for 5-minute window), 5-second buckets (for 1-hour window), 1-minute buckets (for 24-hour window). When the user zooms into a narrow time window (&lt;30 seconds), the chart automatically switches to raw data mode, disabling aggregation and rendering each individual sample as a point (using fillRect instead of lineTo for clarity at high zoom). Switching aggregation levels triggers a new subscription message to the Streaming Gateway, which re-queries the time-series database for the new resolution.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">WebSocket versus Server-Sent Events (SSE) for real-time data: SSE is simpler (one-directional, HTTP-native, automatic reconnect) and sufficient for dashboards where the server pushes data without needing to receive viewport subscription updates from the client. WebSocket is bidirectional — necessary here because the client sends subscription updates (zoom changes, pause/resume, viewport resize) that the server needs to adjust its downsampling. The added complexity of WebSocket (multiplexing, ping/pong keep-alive, reconnect logic) is justified by the need for bidirectional communication. Libraries like socket.io add reconnect logic, but add 50KB to the bundle; a raw WebSocket with an exponential backoff reconnect loop is sufficient.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Canvas versus SVG for rendering: SVG is the DOM-based alternative where each data point is an SVG element. SVG is convenient for interactivity (hover tooltips via onMouseOver on elements) and accessibility (screen readers can read chart data from SVG attributes). However, SVG performance degrades sharply above 1,000 elements — each element is in the DOM and participates in layout, style recalculation, and paint. Canvas renders as a single image element with no layout overhead, but requires custom hit-testing for tooltips (the rendering code must manually check which drawn data point is under the cursor position on mousemove). The engineering trade-off: SVG for charts with fewer than 500 points where interactivity is important; Canvas for any real-time chart with 1,000+ points.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="important">A real-time analytics dashboard handling 10,000+ data points per second is built around three key insights: (1) never send more points to the browser than there are pixels to display (server-side LTTB downsampling to pixelWidth target, ~1,200 points); (2) never render via the DOM (Canvas 2D with OffscreenCanvas Web Worker double-buffering, Float64Array circular buffer, requestAnimationFrame at 60fps); and (3) adapt to client capacity (backpressure gap_marker when WebSocket buffer fills, visibility API to reduce to 1 msg/sec when tab is backgrounded, WebGL upgrade for 10k+ points/chart). Data arrives from the Streaming Gateway in 16.7ms batches (one per frame), encoded as delta updates (add/remove_before) applied to the local circular buffer. Windowed aggregation (1s/5s/1min min-max-avg) prevents visual noise at normal zoom levels; raw data renders when zoomed to &lt;30 seconds. Historical rewind pauses WebSocket consumption and fetches from InfluxDB/TimescaleDB, returning 1,200 downsampled points within 500ms. The defining constraint: the browser is a rendering bottleneck, not a network bottleneck — every design decision optimizes for reducing per-frame rendering cost.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
