"use client";

import { ArticleLayout } from "@/components/articles/ArticleLayout";
import { ArticleImage } from "@/components/articles/ArticleImage";
import { HighlightBlock } from "@/components/articles/HighlightBlock";
import type { ArticleMetadata } from "@/types/article";

export const metadata: ArticleMetadata = {
  id: "article-hld-pwa-offline-sync",
  title: "Design a PWA with Offline Sync",
  description:
    "Architecture for a Progressive Web App with offline sync: service worker lifecycle (install, activate, fetch interception), cache strategies (cache-first, network-first, stale-while-revalidate) per resource type, IndexedDB mutation queue for offline writes with Background Sync API replay, conflict resolution for concurrent edits (last-write-wins, server-authoritative merge), push notification delivery via Web Push API, app manifest for installability, and update notification UI for new service worker versions.",
  category: "high-level-design",
  subcategory: "cross-platform-mobile-systems",
  slug: "pwa-offline-sync",
  wordCount: 5000,
  readingTime: 30,
  lastUpdated: "2026-05-14",
  tags: ["hld", "pwa", "service-worker", "offline-sync", "indexeddb", "background-sync", "web-push", "cache-strategies", "conflict-resolution"],
  relatedTopics: ["responsive-cross-device-architecture", "hybrid-app-webview-native-bridge"],
};

export default function PwaOfflineSyncArticle() {
  return (
    <ArticleLayout metadata={metadata}>
      <section>
        <h2>Problem Clarification</h2>
        <p>A Progressive Web App (PWA) with offline sync delivers an app-like experience through the browser — installable on the home screen, functional without a network connection, and capable of receiving push notifications. The offline capability is the defining technical challenge: when the user creates, updates, or deletes data while offline, those mutations must be queued locally and replayed to the server when connectivity is restored, without the user losing work or seeing inconsistent state.</p>
        <HighlightBlock as="p" tier="important">The fundamental tension: the server is the authoritative data source, but the app must function without access to it. Every architectural decision is a tradeoff between consistency (data matches the server) and availability (the app works without the server). A task management PWA should let users add tasks while offline — but what if the server rejects the task because a validation rule changed since the client last synced? What if two users edit the same record while both are offline and both sync later? These conflict scenarios must be handled explicitly — "it'll probably be fine" is not a conflict resolution strategy.</HighlightBlock>
        <p><strong>Explicit scope:</strong> Service worker lifecycle, cache strategies, offline mutation queue, Background Sync API, conflict resolution patterns, Web Push API, and update management. Not in scope: the full offline-first data architecture (CRDTs, operational transforms), app store PWA submission, or Workbox internals.</p>
      </section>

      <section>
        <h2>Requirements</h2>
        <h3 className="mt-6 mb-3 text-lg font-semibold">Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Service worker cache strategies:</strong> Different resources require different caching strategies: (1) App shell (HTML, CSS, JS bundles) — cache-first: serve from cache immediately, update cache in the background (stale-while-revalidate). The app shell loads instantly even on slow networks because it never waits for the network. (2) API data (GET /tasks, GET /projects) — network-first with cache fallback: try the network, fall back to cached data if offline. Cache freshness window: 5 minutes — data older than 5 minutes is stale but still usable offline. (3) Images and fonts — cache-first with long TTL: once cached, never re-fetch until the cache is cleared. (4) Critical path API calls (auth, payments) — network-only: never serve from cache, always require network connectivity. These calls fail gracefully with an offline error message.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Offline mutation queue:</strong> When the user performs a write operation (POST/PUT/DELETE) while offline, the mutation is: (1) applied optimistically to the local IndexedDB store (the UI updates immediately); (2) serialized and added to a mutation queue (also IndexedDB): &#123;id: uuid(), operation: "create_task", payload: &#123;...&#125;, timestamp: Date.now(), retries: 0&#125;. The queue is processed in order (FIFO) when connectivity returns. Processing: each queued mutation is replayed to the server API; on success, the queue entry is removed; on 4xx (validation error), the queue entry is moved to a "failed" state and the user is notified; on 5xx or network error, the entry is retried with exponential backoff (up to 5 retries).</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Background Sync API:</strong> The Background Sync API allows the service worker to register a sync event that fires when the browser has connectivity, even if the user has closed the app tab. Registration: navigator.serviceWorker.ready.then(sw =&gt; sw.sync.register('sync-mutations')). The service worker listens for the sync event: self.addEventListener('sync', event =&gt; &#123; if (event.tag === 'sync-mutations') &#123; event.waitUntil(processMutationQueue()) &#125; &#125;). When Background Sync fires (after the tab is closed and connectivity is restored), the service worker opens the IndexedDB mutation queue, processes all queued mutations, and updates the local store with server responses.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>PWA installability:</strong> The web app manifest (manifest.json) defines the app's installable identity: name, short_name, description, start_url ("/"), display: "standalone" (hides the browser chrome when installed), theme_color, background_color, icons (192px and 512px PNG with maskable variants). The &lt;link rel="manifest" href="/manifest.json"&gt; tag in the HTML head tells the browser the app is installable. The browser shows an install prompt when: the app is served over HTTPS, has a manifest with the required fields, and has a registered service worker. The install prompt is captured (window.beforeinstallprompt event) and shown at an appropriate UX moment (not immediately on page load — show it after the user has demonstrated engagement, e.g., after 3 visits or after completing a meaningful action).</HighlightBlock>
        </ul>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Non-Functional Requirements</h3>
        <ul className="space-y-2">
          <HighlightBlock as="li" tier="important"><strong>Conflict resolution:</strong> When a queued mutation is replayed and the server returns a 409 Conflict (the server's version has changed since the client's mutation was created), the client must decide how to resolve the conflict. Three strategies: (1) Last-write-wins (LWW): the client's mutation overwrites the server's version — simple, but can lose server-side changes made by other users. (2) Server-authoritative: the server's version wins; the client discards its mutation and re-fetches the server state — safe but can lose user work. (3) Three-way merge: compare the common ancestor (the version the client saw when it made the mutation), the client's version (the mutation), and the server's version (current) — merge non-conflicting field changes and present a diff UI for conflicting fields. LWW is appropriate for user-owned records (only one user edits a task); server-authoritative for shared records (a document multiple users edit); three-way merge for collaborative features.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Web Push notifications:</strong> Push notification delivery requires: (1) the user grants notification permission (Notification.requestPermission() — request at a contextually appropriate moment, not on page load); (2) the service worker subscribes to push via registration.pushManager.subscribe(&#123;userVisibleOnly: true, applicationServerKey: VAPID_PUBLIC_KEY&#125;) — the subscription object (endpoint URL + auth keys) is sent to the server; (3) the server uses the subscription to send push messages via the Web Push protocol (VAPID-authenticated POST to the push service URL); (4) the service worker receives the push event and shows a notification: self.addEventListener('push', event =&gt; &#123; event.waitUntil(self.registration.showNotification(title, options)) &#125;); (5) clicking the notification fires the notificationclick event in the service worker, which focuses an open tab or opens a new one at the target URL.</HighlightBlock>
          <HighlightBlock as="li" tier="important"><strong>Service worker update management:</strong> When a new version of the service worker is deployed, the browser downloads it but does not immediately activate it — it waits until all tabs using the old service worker are closed (skipWaiting() can bypass this, but risks serving mixed old/new content). The recommended pattern: the new service worker calls self.skipWaiting() in its install event (immediate activation) and the app subscribes to controller change events: navigator.serviceWorker.addEventListener('controllerchange', () =&gt; window.location.reload()). When the new SW activates, the page reloads to the new version. The app shows an "Update available — click to reload" toast before the reload so users are not surprised.</HighlightBlock>
        </ul>
      </section>

      <section>
        <h2>High-Level Architecture</h2>
        <HighlightBlock as="p" tier="important">The PWA architecture has three layers: (1) the app shell layer (HTML, CSS, JS — always available from cache, provides the UI skeleton); (2) the data layer (IndexedDB — the local database that is the client's source of truth when offline); and (3) the sync layer (service worker — mediates between the app and the network, managing cache strategies and the mutation queue). The mental model: the UI always reads from IndexedDB (never directly from the network API). The service worker keeps IndexedDB in sync with the server when online and queues mutations when offline.</HighlightBlock>
        <HighlightBlock as="p" tier="important">The sync architecture uses a unidirectional data flow: server → service worker cache → IndexedDB → React state → UI. Mutations flow: UI action → IndexedDB update (optimistic) → mutation queue → service worker → server. This means the UI is always reactive to the local IndexedDB state, not to network responses directly. When a server response arrives (confirming or correcting a mutation), the service worker updates IndexedDB, and the React app's Dexie subscription re-renders with the authoritative data.</HighlightBlock>
      </section>

      <section>
        <ArticleImage
          src="/diagrams/system-design-problems/high-level-design/cross-platform-mobile-systems/pwa-offline-sync.svg"
          alt="PWA offline sync architecture: service worker cache strategies (app shell cache-first SWR; API network-first 5min fallback; images cache-first long TTL; auth network-only), offline mutation queue (offline write → optimistic IDB update + queue entry {id,op,payload,retries}; FIFO replay on reconnect; 4xx → failed state + notify; 5xx → exponential backoff retry x5), Background Sync API (sw.sync.register('sync-mutations'); service worker sync event fires when connectivity restored even tab closed; processMutationQueue() opens IDB + replays), conflict resolution (409 from server → LWW for user-owned records; server-authoritative for shared; three-way merge diff UI for collaborative), Web Push (Notification.permission → pushManager.subscribe VAPID; subscription endpoint→server; push event → showNotification; notificationclick → focus tab or open URL; VAPID auth), PWA install (manifest.json standalone display; beforeinstallprompt capture; show after engagement 3 visits; 192+512px maskable icons), SW update (skipWaiting install event; controllerchange → reload; 'Update available' toast before reload)."
          caption="SW cache strategies (app shell cache-first SWR, API network-first 5min fallback, auth network-only), FIFO offline mutation queue (IDB optimistic + queued, 4xx failed state, 5xx exponential backoff), Background Sync API (sync event when offline tab-closed), conflict resolution (LWW/server-auth/three-way merge per record type), VAPID Web Push (pushManager.subscribe → endpoint to server → push event → showNotification), SW update cycle (skipWaiting + controllerchange reload + toast)"
        />
      </section>

      <section>
        <h2>Detailed Design</h2>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Service Worker Fetch Interception</h3>
        <HighlightBlock as="p" tier="crucial">The service worker's fetch handler intercepts every network request from the app. The handler applies the appropriate cache strategy based on the request URL pattern: self.addEventListener('fetch', event =&gt; &#123; const url = new URL(event.request.url); if (isAppShell(url)) &#123; event.respondWith(cacheFirst(event.request)) &#125; else if (isApiRequest(url)) &#123; event.respondWith(networkFirst(event.request, &#123;maxAge: 300000&#125;)) &#125; else if (isStaticAsset(url)) &#123; event.respondWith(cacheFirst(event.request)) &#125; else if (isAuthRequest(url)) &#123; /* passthrough — no caching */ &#125; &#125;). The stale-while-revalidate strategy for the app shell: serve from cache immediately, then fetch the network version and update the cache in the background. The user sees the cached version instantly; the next load will have the updated version.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Cache versioning: each deployment has a cache version string (e.g., "v1.2.3-abc123"). The service worker's install event pre-caches the app shell using this version as the cache name. On activate, it deletes all caches that don't match the current version name. This prevents stale cache entries from accumulating across deployments. The cache name includes the git commit hash so that even minor code changes create a new cache bucket.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">IndexedDB Schema and Dexie Integration</h3>
        <HighlightBlock as="p" tier="important">The local database (IndexedDB via Dexie.js) is the client's source of truth. Schema: tasks table (id, title, status, projectId, updatedAt, syncStatus: 'synced' | 'pending' | 'failed'), mutationQueue table (id, operation, payload, timestamp, retries, error). The syncStatus field on task records drives the UI: pending tasks show a sync indicator icon (⟳), failed tasks show a warning icon (⚠) with a "Retry" button. The task list query: db.tasks.where('projectId').equals(currentProjectId).sortBy('updatedAt') — always reads from IndexedDB, regardless of network state.</HighlightBlock>
        <HighlightBlock as="p" tier="important">Dexie Live Queries (useLiveQuery hook): React components subscribe to Dexie queries that re-run reactively when the underlying table changes. When the service worker updates the tasks table after a successful sync, the Dexie live query fires and the React component re-renders automatically — no polling, no manual cache invalidation, no useEffect with dependencies. This makes the local-first data flow clean: the service worker writes to IndexedDB; React reads from IndexedDB reactively.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Mutation Queue Processing</h3>
        <HighlightBlock as="p" tier="important">Queue processing runs in two scenarios: (1) online transition — the app detects navigator.onLine becoming true (window online event) and immediately starts processing the queue; (2) Background Sync — the service worker fires the sync event when connectivity is restored, even if the app is in a background tab or closed. The processing algorithm: (1) fetch all queue entries with status !== 'failed', ordered by timestamp (FIFO); (2) for each entry, POST/PUT/DELETE to the server; (3) on 2xx: remove from queue + update the record's syncStatus to 'synced' in the tasks table; (4) on 4xx: move to 'failed' status + store the error message for display; (5) on 5xx or network error: increment retries; if retries &gt; 5, move to 'failed'; otherwise, delay retry by 2^retries * 1000ms (exponential backoff, capped at 30 seconds).</HighlightBlock>
        <HighlightBlock as="p" tier="important">Mutation ordering matters: if the user creates a task (mutation A) and then updates it (mutation B) while offline, both mutations must be replayed in order. Replaying B before A would fail (the task doesn't exist yet on the server). The FIFO ordering by timestamp ensures correct replay order. Additionally, if mutation A fails (4xx), the dependent mutation B should also be marked failed — cascading failure handling: when a mutation fails, check all subsequent queue entries with the same record ID and mark them as blocked-on-failure.</HighlightBlock>

        <h3 className="mt-6 mb-3 text-lg font-semibold">Push Notification Permission Strategy</h3>
        <HighlightBlock as="p" tier="important">Notification permission is a high-stakes UX decision: if the browser prompts for permission and the user clicks "Block," there is no way to re-prompt — the user must manually re-enable in browser settings. Therefore: never show the browser permission prompt immediately on page load. Instead: (1) show an in-app permission request UI that explains the value proposition ("Get notified when your tasks are due or when teammates comment on your work"); (2) only call Notification.requestPermission() after the user explicitly clicks "Enable notifications" in this in-app UI; (3) if they dismiss the in-app UI, wait at least 7 days before showing it again (stored in IndexedDB); (4) never show it more than 3 times total. This pattern dramatically improves the permission grant rate compared to prompting on first page load.</HighlightBlock>
      </section>

      <section>
        <h2>Trade-offs and Considerations</h2>
        <HighlightBlock as="p" tier="important">Background Sync API availability: Background Sync is supported in Chrome and Edge but not in Safari/Firefox as of 2026. For unsupported browsers, the fallback is foreground sync — processing the mutation queue when the app is in focus and detects network recovery (window online event). The limitation: if the user closes the tab while offline, queued mutations will only be processed when they next open the app. For most use cases (productivity apps, note-taking), this is acceptable. For critical mutations (payment submissions, healthcare data), the app should warn the user before they close the tab: "You have unsent changes. Please wait for sync to complete." (using the beforeunload event).</HighlightBlock>
        <HighlightBlock as="p" tier="crucial">IndexedDB storage limits: browsers impose storage quotas per origin (typically 60% of available disk space, though the exact limit varies). For PWAs that cache large amounts of data (an email client caching years of email), the app must: (1) request persistent storage via navigator.storage.persist() — persistent storage is not evicted by the browser's automatic cleanup; (2) monitor storage usage via navigator.storage.estimate() and warn the user when approaching the quota; (3) implement an eviction strategy (delete oldest cached data when approaching 80% quota). Apps that don't manage storage will eventually hit the quota and fail silently.</HighlightBlock>
      </section>

      <section>
        <h2>Summary</h2>
        <HighlightBlock as="p" tier="crucial">A PWA with offline sync requires: (1) cache strategy differentiation (app shell cache-first SWR, API network-first 5min fallback, auth network-only, images cache-first long TTL); (2) IndexedDB mutation queue (FIFO ordering, optimistic local apply, syncStatus field per record, 4xx→failed+notify, 5xx→exponential backoff 5 retries); (3) Background Sync API (sw.sync.register on queue write, sync event processes queue when connectivity restores even tab-closed); (4) conflict resolution by record type (LWW for user-owned, server-authoritative for shared, three-way merge diff UI for collaborative); (5) VAPID Web Push (in-app permission request before browser prompt, pushManager.subscribe, subscription endpoint to server, notificationclick→focus or open); (6) installability (manifest.json standalone, beforeinstallprompt captured + shown post-engagement, 192+512 maskable icons); and (7) update management (skipWaiting on install, controllerchange→reload, "Update available" toast). The central design principle: the UI always reads from IndexedDB — the service worker keeps IndexedDB synchronized with the server. Offline is a first-class state, not an error condition.</HighlightBlock>
      </section>
    </ArticleLayout>
  );
}
